### ISSUE TITLE
Allow users to select duplicate multi value options

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1001]
## Description of the bug

_When updating multi value record fields, it’s impossible to select a different record.
The options are selectable, but the change is not reflected._

## Reproduction steps

1.	Create a module with a multi value record field
2.	Create a record and populate some values
3.	Try to update the record

## Expected behavior 

_I should be able to update the record_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228255606-38b3b99d-0925-43e3-a424-03757c0176a5.png)

![Image](https://user-images.githubusercontent.com/53232926/228255639-f5dc4acc-846f-4305-a773-963ee2970e60.png)

![Image](https://user-images.githubusercontent.com/53232926/228255657-50afe02d-b001-4fe6-a422-196bfc568b61.png)

Reference: https://20233-qc.cortezaproject.org/compose/ns/BugReport/admin/modules/330130884785092363/record/330130954008016651/edit

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

===================================================================================

## Description of the bug

_Select and record dropdown won’t let you pick duplicate values when they accept multiple values.
In my opinion they should._

## Reproduction steps

1.	Make multi value record and select field
2.	Try to pick duplicate values

## Expected behavior 

_To be discussed_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228259215-759226bd-d346-44f9-bd6d-b48ea163f59c.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by katrinDY** [comment]
For today: implement the rest of the needed changes and submit a PR

**Comment by katrinDY** [comment]
For today: sync with Joze to discuss send part of the task

**Comment by katrinDY** [comment]
For this ticket:
- the first issue - it will be fixed
- the second issue - duplicates will be allowed only for the multi-value field types `Single input` and `Input for each line` for the module fields User and Record

The option to allow duplicates for multi-value field type `Multiple select` for  User, Record and Select module fields will be added with this ticket https://github.com/cortezaproject/corteza/issues/1057

**Comment by katrinDY** [comment]
This feature will be present only on .3. It will be combined with https://github.com/cortezaproject/corteza/issues/1057

**Comment by katrinDY** [comment]
For today: write down plan and be done with adding this functionality for select field

**Comment by katrinDY** [comment]
Closing this issue since it'll be handled in https://github.com/cortezaproject/corteza/issues/1057
