### ISSUE TITLE
New field configs not taken into account

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1002]
## Description of the bug

_When adding a new field with a different kind and if you don't open its configuration, the configuration is not updated, it is just inherited from the default kind/ from the previous field kind._

## Reproduction steps

1. Create a number field but don't open its config
2. save the field and go in all records
3. add a float number for example 1.21
4. Notice that the number is rounded 
5. Now go in modules again and open the number field config and just open the number tab and don't touch anything just press save 
6. Now go in all records and add the same entry, 1.21, notice that now the number is not rounded.

## Expected behavior 

_When you add a new field, the configurations of that field kind should be automatically applied to the new field._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/228258439-c3a7844f-17ba-4cea-b55d-65e905fe139e.webm

## Version

Branch: 2023.3.0

**Comment by katrinDY** [comment]
For today: continue investigation issue and create a PR

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this looks good.
@katrinDY when you have the time just try to put up a small CL entry. Thanks

**Comment by Bojan-Svirkov** [comment]
Added the following CL entry:

```
{
      "what": [
        "field kind not updating after being selected."
      ],
      "how": [
        "by updating the field kind after it is selected."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1018/commits/53418299193eb6a4b4610527c7b5ecb399efa85e",
        "https://github.com/cortezaproject/corteza/pull/1018/commits/de26f561a7f6b24b79136c49a84971ab55b9dac5"
      ]
    }
