### ISSUE TITLE
Calendar block manual refresh inconsistency

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1004]
## Description of the bug

_The block calendar is not refreshing neither automatically nor manually._

## Reproduction steps

1.	Go to Pages -> Record List for Module -> Page Builder
2.	Edit calendar block
3.	Go to General tab
4.	Set Auto refresh to 10 seconds
5.	Save and close
6.	Save the page
7.	Go to Publick pages
8.	Change a record that is connected to the calendar
9.	Wait the information to be refreshed
10.	Click on the “Refresh block””  icon

## Expected behavior 

_Calendar block should refresh as any other block._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/228260718-de7a9906-64d1-4058-adfc-5430750a9be5.webm

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Mariya (Test Fest)
Browser: Chrome

**Comment by katrinDY** [comment]
For today: investigate issue and make a plan

**Comment by katrinDY** [comment]
For today: discuss this with Jože

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. CL is not needed here since this is a fix for 2023.3 feature.
