### ISSUE TITLE
Access to important DAL parameters is too strictly hidden behind RBAC

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1005]
## Description of the bug

_Access to important DAL parameters is too strictly hidden behind RBAC._

_For some operations, such as configuring modules, you might need to know about what connections are available appart from the primary one._

_Currently, the only way to get that list is by having the search and read connections as well as search and read sens. Levels.
This is only ok for users who are allowed to see that very sensitive information (storage connection params) and should be hidden from “regular” configurators._

## Reproduction steps

1.	Create a user with a non super-admin role
2.	Give the user enough permissions to create modules
3.	Notice error messages and the lack of connections/sens. levels.

## Expected behavior 

_When I’m configuring modules, I should be able to see the most basic info about connections and sensitivity levels so that I can utilize them._

I see two options:
1.	Add masking RBAC rules like we have for users
2.	Add a generic, unprotected endpoint which returns the most basic info about DAL configurations.

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by tjerman** [comment]
We'll change this and opt-in for masking sensitive data instead.
A new RBAC rule will be introduced which controls if some users can unmask sensitive data or not. If yes, the data is presented as is, if not, the data is replaced by something else.

**Comment by tjerman** [comment]
This was already sorted out by Denis; false alarm, apologies (https://github.com/cortezaproject/corteza/blob/2023.3.x/server/system/service/dal_connection.go#L297)

If the `can manage dal config` permission is allowed, the user can both see and modify the whole connection param. The param is outright removed if someone is not allowed to manage it.

**Comment by tjerman** [comment]
Closing issue because nothing changed
