### ISSUE TITLE
Field order on compose admin record editor changes when you interact with the interface

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1007]
## Description of the bug

_The field order on the compose admin record editor changes when you interact with the interface. On the screenshots, look at the attachments – those one stick out like a sore thumb._

## Reproduction steps

Follow below screenshot instructions

## Expected behavior 

_The order should be consistent._

## Screenshot/Video

These are my fields:

![Image](https://user-images.githubusercontent.com/53232926/228265712-06a939bb-5add-4c82-a2f7-4f798c0f2877.png)

The layout when I open a record in the admin > modules > all records:

![Image](https://user-images.githubusercontent.com/53232926/228265768-1ac2b4cf-8a0f-4579-a11e-90e75a879973.png)

The layout when I go edit the record

![Image](https://user-images.githubusercontent.com/53232926/228265826-da055ab5-a0c9-4a9c-bee3-f81c3225cf78.png)

The layout when I save the record:

![Image](https://user-images.githubusercontent.com/53232926/228265881-a3ab4fce-11b5-45eb-92af-254715ca774e.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by Bojan-Svirkov** [comment]
Record configurator should not sort fields in place.

[Ticket 1007.webm](https://user-images.githubusercontent.com/53232926/230124533-f7cd4d17-5cd2-4e37-a0e8-3b3aa8125f72.webm)

**Comment by katrinDY** [comment]
For today: sync with Jože reg. this and make a plan

**Comment by katrinDY** [comment]
For today: write down made plan and start working on it

**Comment by katrinDY** [comment]
For today: write down made plan and continue working on it

**Comment by EmmyMay** [comment]
Plan of action: Find instances where we sort module fields and ensure we are sorting a dereferenced version of the arrays. 

Note: This will no longer be done today as I am focusing on resolving security PRs

**Comment by katrinDY** [comment]
For today: execute the plan of action and submit for code review

**Comment by katrinDY** [comment]
For today: discuss task with Jože and figure out how to proceed with it

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.
