### ISSUE TITLE
Record list top bar not responsive on smaller screens

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1013]
## Description of the bug

_Record list top bar (the search box and such) are not responsive_

## Reproduction steps

1.	Open a page with a record list (and search enabled)
2.	Shrink the screen

## Expected behavior 

_The search input box should probably be expanded_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228484306-48c7a384-aa5d-474a-8bca-7145f722ee25.png)

![Image](https://user-images.githubusercontent.com/53232926/228484375-fc8ac95a-e60a-4e21-afb9-37bad6448b86.png)

![Image](https://user-images.githubusercontent.com/53232926/228484403-4d50d03b-aff0-4dbf-bd9c-c2374c797b6e.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by katrinDY** [comment]
for today: make a plan of action, write it down and start working on it

**Comment by EmmyMay** [comment]
This issue has probably been resolved in some other ticket
