### ISSUE TITLE
Change the N items to N {resource name} in record lists

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1014]
## Description of the bug

_Change the counter in Resource lists at the bottom left corner to say N {resource name} instead of N items_

## Reproduction steps

1. Open the compose admin page
2. See modules and charts

## Expected behavior 

_The counter at the bottom left corner should say N {resource name} instead of N items_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228485514-8b300dbd-3934-4492-af19-3972ee20998a.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by katrinDY** [comment]
for today: make plan, write it and start working on it

**Comment by yonkov** [comment]
The plan: 
- [x] Get familiar with the resource list component
- [x] add method that shows different text output based on the resource list count
- [x] update pagination component in all items that have resource lists: namespaces, modules and charts.

**Comment by katrinDY** [comment]
for today: focus on the remaining tasks and submit task for review

**Comment by katrinDY** [comment]
for today: resolve comments and resubmit for code review

**Comment by katrinDY** [comment]
for today: resolve comments, submit for code review and complete task

**Comment by yonkov** [comment]
After discussion with Joze: Go through the following web apps and update the translation files and configurations for `c-resource-list` accordingly:

- [x] compose
- [x] admin
- [x]  privacy
- [x] reporter
- [x] workflow

**Comment by katrinDY** [comment]
for today: add finishing touches and submit for cod review

**Comment by katrinDY** [comment]
for today: complete the checklist and re-submit for review

**Comment by katrinDY** [comment]
fortoday: ping Jože for review

**Comment by katrinDY** [comment]
Tested and can confirm everything is working as it should
