### ISSUE TITLE
Page label in the top left corner goes away on small screens

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1015]
## Description of the bug

_The page label/identifier in the top left corner goes away on small screens._

## Reproduction steps

1.	Open compose > admin > modules
2.	Shrink the screen

## Expected behavior 

_The page label should probably always be there_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228486033-c376b5d6-b2eb-42d3-b835-4f500ea20674.png)

![Image](https://user-images.githubusercontent.com/53232926/228486053-c1688464-8562-43a5-b9b0-4474df026924.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by yonkov** [comment]
This behavior is exhibited on all mobile headers in Corteza Compose. The reason for this is that on mobile, if the title is a little too big it overflows its container like so:

![Image](https://user-images.githubusercontent.com/26258032/232723458-d158f025-53be-4b81-9409-9f0ccd79fed6.png)

We need to decide:
1.  do we want to show the page titles on all headers or just modules
2. how it should look like on mobile (perhaps the easiest way is to push the right side text down on mobile)

After this is decided, I will go on creating a plan.

**Comment by katrinDY** [comment]
todo: discuss implementation with Jože and add plan of action

**Comment by EmmyMay** [comment]
For today: Sync with @Fajfa and make a plan of action.

**Comment by katrinDY** [comment]
For today: add discussed with Jože plan and start working on it

**Comment by yonkov** [comment]
After our talk with Jože - the profile should go on first line, the title on the second and all the rest should go on a third line by taking into account title width.

**Comment by KinyaElGrande** [comment]
For Today: Start working on this and open PR later.

**Comment by katrinDY** [comment]
for today: address comments on PR

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks as expected. Moving the card to Done.

**Comment by Bojan-Svirkov** [comment]
```
Fixed:

{
      "what": [
        "webapp page titles not shown on small screens."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1175"
      ]
    }
