### ISSUE TITLE
Page icons, namespace logos, and custom app images can become invalidated

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1021]
## Description of the bug

Page icons, namespace logos, and custom app images can become invalidated and therefore broken.

The issue exists due to how the attachment (all of these utilize attachment services) acces flow works. TL;DR:
•	You request a list of attachments (or a single attachment).
•	The back-end authorizes your request, grabs a list of attachments you can see, and appends a signature to the URL (along with some other bits).
•	You get that signed URL which you can use to fetch the file.

The problem is enabled since our app logos, page icons, … save the entire URL along with the hash (see the highlighted bit on the right – this is a local instance so no harm in leaking my signature).

![Image](https://user-images.githubusercontent.com/53232926/228782846-76c36637-bd18-40b8-b683-ea5dc79db513.png)

This means that whenever the underlying signer’s algo/secret changes, all these links become invalid and the images appear missing/broken.

## Reproduction steps

1.	Go edit a page which has an icon (if none, make one)
2.	In your env, set AUTH_JWT_SECRET=gytif7g8o9 (or any other value for the secret – this is the easiest way to change the signature)
3.	Restart the server (if in docker compose, run docker-compose up -d)
4.	Refresh the page and see the icon is no longer accessible.

## Expected behavior 

_Icons, logos, and other similar assets should not be affected by such system changes._

## How to fix

This isn’t an issue in how our attachment service works and authenticates file access – that’s good and should stay the way it is.

Possible solutions:
•	Instead of saving the entire URL, save just the attachment ID and store some metadata that indicates it’s an attachment. Then, when accessing the icon, logo; go through the correct flow of signing requests.
•	Create a separate attachment system which isn’t protected and can serve arbitrary assets. This service’s unprotected access should be read only.

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228783068-54689b34-3b3a-4749-b000-1df1b559b313.png)

![Image](https://user-images.githubusercontent.com/53232926/228783102-a1b72628-136c-432b-aa34-66d680a7df9e.png)

![Image](https://user-images.githubusercontent.com/53232926/228783141-b115386c-dbd0-4b21-9052-4e84a41b76c9.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by vicpatel** [comment]
To fix this, added exception for the Namespace, Icons, Page attachments(Which are basically public assets).

**Comment by vicpatel** [comment]
### Fixed:

#### What:
- Fixes compose broken public icon url for Page, Namespace, and Custom app icons after changing the Auth JWT secret.

#### How:
- By adding exception for the Namespace Icons, Page/Icon attachments Which are public assets, no need to validate those.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.

Added CL:

```
Fixed:

{
      "what": [
        "{APP_NAME_COMPOSE} broken public icon url for page, namespace, and custom app icons after changing the Auth JWT secret."
      ],
      "how": [
        "by adding exception for the namespace icons, and page/icon attachments."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1219"
      ]
    }
