### ISSUE TITLE
Namespace cloning incorrectly clones progress bar page blocks

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1022]
## Description of the bug

_Namespace cloning incorrectly clones progres bar page blocks.
After a namespace with a progres bar page block is cloned, the following error is thrown: module does not exist._

_The issue appears to be caused by Envoy not correctly re-referencing the nested moduleID parameter:_

![Image](https://user-images.githubusercontent.com/53232926/228784163-4d6cfd5f-1ec7-4db7-94c1-a5bc2524a472.png)

_Where the cloned module ID is:_

![Image](https://user-images.githubusercontent.com/53232926/228784235-a6e4d478-991c-4330-8709-acee483aa95f.png)

## Reproduction steps

1.	Create a simple namespace where you have a module and a page with a progres page block
2.	Clone the namespace
3.	Enter the cloned namespace

## Expected behavior 

_The progres page block should be re-referenced to point to the cloned namespace._

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by tjerman** [comment]
Already addressed

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. No need for CL here.
