### ISSUE TITLE
CRM namespace cloning takes a while and then fails

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1023]
## Description of the bug

_CRM namespace cloning takes a while and then fails spectacularly._

_failed to encode nested resources: failed to set dependency references for corteza::compose:page [RecordPageForModuleQuote 329393723458912261]: parent reference {corteza::automation:workflow {[329393718979330053] map[329393718979330053:true]} {corteza::compose:namespace {[crm_copy2] map[crm_copy2:true]}} false} not found_
## Reproduction steps

1.	Navigate to your namespace list
2.	Try to clone the default CRM namespace

## Expected behavior 

•	Namespace cloning should not take that long
•	There should be no error

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228786271-14e32e83-0c7d-4392-9c21-cb01e84d801d.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by tjerman** [comment]
This was already addressed last week

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. CL entry is not needed here
