### ISSUE TITLE
When configuring a calendar page block no views are marked as enabled

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1025]
## Description of the bug

_When configuring a calendar page block, no views are marked as enabled.
By default, just the month view is enabled but that is not reflected under the configurations._

## Reproduction steps

1.	Add a calendar page block
2.	Inspect the calendar tab and see there are no enabled views selected

## Expected behavior 

_Month should be selected by default._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228787975-51bd9ed4-bf3a-40bb-b7e8-122168b8b509.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Tomaz (Test Fest)
Browser: Firexox

**Comment by yonkov** [comment]
For today: I will take closer look to the calendar block, trace down how the data flows in it and will update the code so that the enabled views have "Month" selected by deafult.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that the default enabled view now is `Month`. So everything works as expected and there is no need for CL entry since this falls under the general improvements of our product.
