### ISSUE TITLE
Available/selected fields not scrollable in safari

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1028]
## Description of the bug

_In Safari browser, in Record List, you can't see all available fields in General Settings of the block, including System Fields. They seemed to be not scrollable._

## Reproduction steps

1.	Go to Pages -> Record List for Module -> Page Builder
2. 	Edit Existing Block
3.	Go to Record list tab
4.	Check available fields and/or selected fields
5.	Try to scroll down to view the whole list of fields
6.	You won't be able to scroll all the way down the list, you won't be able to select all desired fields

## Expected behavior 

_To see/scroll through the whole list of available system fields and manually created fields. The ability to select any desired fields._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228835220-c98b5476-3c06-4505-b17b-7f95f62b3347.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporer: Iveta (Test Fest)
Browser: Safari

**Comment by katrinDY** [comment]
for today: investigate cause of issue

**Comment by katrinDY** [comment]
The cause of the issue is overflow works differently on iOS and OS X compared to other operating systems

**Comment by katrinDY** [comment]
for today: find a solution to the issue

**Comment by katrinDY** [comment]
for day: implement solution and submit for review

**Comment by katrinDY** [comment]
for today: time-box issue to 2. If no solution, ask for help

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that now everything works as expected.

Added CL:
```
Fixed:
 {
      "what": [
        "available and selected fields not scrollable in safari due to set max height in the item picker component."
      ],
      "how": [
        "by setting a height instead of max height"
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1221"
      ]
    }
