### ISSUE TITLE
Apply new color variables to webapps

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1029]
The old variables should be replaced with the new ones.

![Image](https://user-images.githubusercontent.com/15791641/229165228-4c469514-a446-4978-86a5-73edcbefa8eb.png)

Important!!, also replace all hardcoded values that don't use the variables themselves!

**Comment by katrinDY** [comment]
Webapps:
- [x] compose
- [x] admin
- [x] wf
- [x] reporter
- [x] privacy
- [x] discovery
- [x] one

**Comment by katrinDY** [comment]
@tjerman, I've applied the same colors to the docs - https://github.com/cortezaproject/corteza-docs/pull/374

**Comment by Bojan-Svirkov** [comment]
Tested and confirming the changes. There is no need for Cl entry here. Moving the card to Done.
