### ISSUE TITLE
Add getOptionKey property to all vue-selects

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1030]
## Description
vue-select uses the `id` property by default to determine the key of items. Since we often use it with objects that don't have the id property it serializes the object itself which causes performance issues. The getOptionKey property needs to be added to all places where vue-select uses objects that don't have the `id` property as for items.

## Webapps
- [x] admin
- [x] compose
- [x] privacy
- [x] wfs
- [x] reporter
- [x] finishing touches

**Comment by katrinDY** [comment]
For today: add the rest of the code and submit task for code review

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

**Comment by Bojan-Svirkov** [comment]
No need for CL here since this falls under general improvements part.
