### ISSUE TITLE
After a geometry record is saved, it appears as two identical geo entries

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1031]
## Description of the bug

_When adding one geometry record, after saving the record it appears as two identical geometry records saved._

## Reproduction steps

1.	View Record for Module
2.	Hit Edit
3.	Go to Geometry field and add a new record
4.	Save and view

## Expected behavior 

_After saving only one geometry record, I expect only to see one record for geometry (one for longitude and one for latitude)_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/228857095-bf966bc7-5630-4a2b-a5db-7448519b7e23.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Iveta (Test Fest)
Browser: Safari

**Comment by kelanik8** [comment]
I'm not able to reproduce this error

**Comment by Bojan-Svirkov** [comment]
I can't reproduce this either. So I am moving this card to done.
