### ISSUE TITLE
Can use Case managment and Low code apps when they're disabled

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1034]
## Reproduction steps
1. Click on admin area
2. Go to applications
3. Press on Case Management
4. Uncheck the “unable” checkmark
5. In webapp One click on Case Management

## Expected behaviour
Both apps shouldn't be accessible when disabled

## Tested on
Microsoft Edge
Version 111.0.1661.51 (Version officielle) (64 bits)

**Comment by yonkov** [comment]
For today: The plan is to investigate where and how the apps are enabled and how are they displayed in web app one, then filter through them to enable the links only on the ones that are enabled.

**Comment by yonkov** [comment]
Update: after testing the issue in Firefox and Edge browsers, I did not see that the issue persists anymore. Sending it for qa.

**Comment by Bojan-Svirkov** [comment]
I also retested in on `Edge` and everything looks normal and works as expected. Since this is no longer an issue I am moving the card to done and also closing it.
