### ISSUE TITLE
Delay when clicking on page magnification button

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1036]
## Description of the bug

_When I click on the page magnification button on my record list (both the modal and full screen variants), there is a bit of a delay before the modal opens up.
I’m not sure why that is, but my guess is that we’re loading the content before we open the modal. If that’s the case, this might throw people off (especially on slower connections)._

## Reproduction steps

1.	Make a record list magnifyable (as a modal)
2.	Magnify the record list

## Expected behavior 

_The modal should open immediately, or there should be some indication that it’s processing._

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Tomaz (Test fest)
Browser: Firefox

## Note:

This needs to be investigated

**Comment by Bojan-Svirkov** [comment]
@tjerman I retested this and I don't think that I am able to reproduce this. Magnifying a record list or any other block works pretty fast for me. Can you confirm if we can close this ticket?

[379285a8-99e8-494c-9ffc-5586924ec768.webm](https://github.com/cortezaproject/corteza/assets/53232926/41668a84-0cd7-441b-93f6-21212f3da053)

**Comment by tjerman** [comment]
Can you test on something with more data in it? Perhaps try rate limiting your network to a slower connection (can do this in the dev tools)

**Comment by Bojan-Svirkov** [comment]
[8a28bb2d-cf2f-4933-a7a6-5f49a909a82f.webm](https://github.com/cortezaproject/corteza/assets/53232926/d3cf271c-e446-4adb-9ed8-505f035e7c01)
[bfc6507a-0577-4c01-a490-e8ae34b35dbc.webm](https://github.com/cortezaproject/corteza/assets/53232926/f2d2388b-bd40-43b1-a569-a459c5d8fab5)

On fast internet even if I have more data everything opens as it should, and on slow network while the content is loading I see a loading spinner indicating that something is loading up, so I think we are good with this one.

What do you think @tjerman ?

**Comment by Fajfa** [comment]
@tjerman Ping

**Comment by katrinDY** [comment]
The issue has already been resolved
