### ISSUE TITLE
View not properly updated after 'Confirm email address' is clicked in Admin

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1038]
## Reproduction steps
1. Create new user via Signup
2. Sign in as an admin user and open the user
3. Click on confirm email

## Expected behavior
Redirected back to the same user record page

## Screenshots/Video
_Before update_
![Image](https://user-images.githubusercontent.com/85161724/229107447-06ad456f-d68f-49f1-a7ba-11aad0dd55db.png)

_After update_
![Image](https://user-images.githubusercontent.com/85161724/229107521-3af7d3fe-94aa-4b3a-a083-48746fe29104.png)

## Tested on
Edge on MacOS 13.0.1
## Version
2023.3.0-dev.5

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. I also added the following CL entry:

```
{
      "what": [
        "admin user view not properly updated after 'Confirm email address' was clicked in Admin."
      ],
      "how": [
        "by refetching the user on admin user patch."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/commit/e76fb09707239b8e8c7b430e1f829e4adb975894"
      ]
    }
