### ISSUE TITLE
Cannot add DSN connection via a correct DSN string

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1039]
## Description
The error cannot open connection: only DSN connections supported is thrown

## Reproduction steps
1. Click on Connections
2. Insert metadata for connection
3. Go to “Data access layer configuration and connection parameters”
4. Insert
postgres://corteza:corteza@localhost:5432/d1?sslmode=disable
Or
postgres://corteza:*********@corteza_db:5432/testfest?sslmode=disable

## Expected behavior
There should be a different error string if the database is unreachable OR the connections should be successfully added.

## Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/229108503-d1ad38ee-6241-4ee7-8a8e-4952919bf0ff.png)

## Tested on
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0

## Version
2023.3.0-dev.5

**Comment by katrinDY** [comment]
for today: update ticket with plan and start executing it

**Comment by katrinDY** [comment]
for today: update ticket with plan and start executing it

**Comment by petergrlica** [comment]
This was confirmed by @KinyaElGrande as a non-bug as the bug report itself was invalid, closing.
