### ISSUE TITLE
Sorting list of automation workflow sessions does not work

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1041]
## Reproduction steps
1. Go to admin
2. Click on AUTOMATION -> Sessions in the sidebar
3. The list of sessions should include different statuses, event types and created at dates
4. Clicking on any of the columns does not sort data correctly, uses only frontend sorting of the displated data.

## Expected behavior
Session should be sortable

## Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/229114780-4f2f0af9-9144-4484-aab3-2f9bf2f38bdc.png)

## Tested on
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0

## Version
2023.3.0-dev.5

**Comment by Bojan-Svirkov** [comment]
The sorting now works good but I noticed one small issue. When I sort by status and then I want to go to the next page, I am receiving an error (`Failed to load resource list: could not query AutomationSession: store error: pq: invalid input syntax for type integer: "failed"`)and the list is not displayed. 

![image](https://user-images.githubusercontent.com/53232926/232724499-f12c30c0-b5ae-419b-8271-bd714ca09061.png)

**Comment by Fajfa** [comment]
BE Issues:
- Failed sessions return empty list (its working on QC)
- If using sort and having multiple pages, the "last" page still gives page cursor

**Comment by vicpatel** [comment]
Problem: When we have string func for the columns and we encode pagingCursor according but while decoding it(pagingCursor), It takes string value of column instead of struct(interface value) which fails the query. IE. Here `status` column and It's underlying values are `started (0), prompted (1), suspended (2), failed (3) and completed (4)` and while sorting this column and going to the next page it will fail due to pageCursor decode column value as string but It should decode interface value.

**Comment by vicpatel** [comment]
For now updated PR with solution, Updationg paginag cursor if there is status in filter.

**Comment by tjerman** [comment]
@Fajfa the MySQL issue (where you can't sort over failed) is caused by an `1038 Out of sort memory, consider increasing sort buffer size` error which might be caused by a [MySQL bug](https://stackoverflow.com/a/67266529).
So... on your end, consider increasing the sort memory.

**Comment by Bojan-Svirkov** [comment]
There is still an issue when sorting sessions by status and you go to the next page.
Note: I am using postgres.

![image](https://github.com/cortezaproject/corteza/assets/53232926/51427ea9-d2c3-4b35-b378-e0ade3f50c46)

**Comment by Fajfa** [comment]
@tjerman Please do look at this

**Comment by katrinDY** [comment]
for today: Tomaž  to take a look at issue

**Comment by katrinDY** [comment]
Added CL:

```
{
      "what": [
        "automation sessions list sorting in {APP_NAME_ADMIN}."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1141"
      ]
    }
```
