### ISSUE TITLE
Description of edited role shown when creating a new role

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1043]
## Reproduction steps
1 . Create a role with a description
2. Click on ‘New’ button
3.  See the previous role’s description is shown

## Expected behavior
The description from the prev role shouldn't be present when creating a new one

## Video
![1](https://user-images.githubusercontent.com/85161724/229484044-22c6a14c-25fa-4063-977f-58d3029cb692.gif)

## Tested on
Safari on  MacOS Ventura 13.2.1

## Version
2023.3.0-dev.5

**Comment by katrinDY** [comment]
For today: address the comment left in the PR

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is fixed. No need for CL here since this is a small fix and does not require an entry.
