### ISSUE TITLE
Multi line comments not respected in Privacy

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1045]
## Description
Adding a new export request comment, the comment text should be displayed as a multiline text, currently the newlines are stripped.

This is a problem on Deletion request as well

## Reproduction steps
1. Go to privacy app
2. Click on Request data export
3. Choose checkboxes and click Export Selected Data
4. Insert comment with multiple lines and see the display

## Expected behavior
The request for export comment should be multiline

## Screenshots/Videos
_Export request_
![Image](https://user-images.githubusercontent.com/85161724/229118020-c3647eb3-0c26-4a48-977d-3cf1396d29dc.png)
![Image](https://user-images.githubusercontent.com/85161724/229118021-97768b35-94d4-4057-9e7b-2e05d3b7c7fe.png)

_Delete request_
![Image](https://user-images.githubusercontent.com/85161724/229118086-dd71ae08-97ab-4751-acb8-040f445f5683.png)

## Tested on
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0

## Version
2023.3.0-dev.5

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now displayed as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Fixed:

 {
      "what": [
        "multiline privacy request comments displaying as inline comments."
      ],
      "how": [
        "by adding support for multiline comments in privacy requests."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1214"
      ]
    }
