### ISSUE TITLE
Reporter list improvements

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1046]
## Issues:
I. Search bar only searches for handles and not names
II. Sort doesn’t work for names

---

### Description
When I search for a report by name where the handle is different than the name, no search results appear. Search results only appear when I search for reports by handle

### Expected behavior
I should be able to search by name

### Tested by
Emmy

### Version
2023.3.0-dev.5

---

### Description
When I soft reports by name, I get an Error and all reports disappear:

### Expected behavior
I should be able to sort by Last Change

### Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/229124445-5b33acbc-8f02-4022-b457-3c049b372737.png)

### Tested by
Emmy

### Version
2023.3.0-dev.5

**Comment by tjerman** [comment]
You currently can't sort/filter using names because they are under `meta` and we haven't (yet) implemented filters to use nested JSON properties.
Workflow list uses handle instead of name, do the same here.

**Comment by vicpatel** [comment]
We disabled name filter from workflow and reporter list for now.

**Comment by Bojan-Svirkov** [comment]
Tested the needed points and it looks good, the sort works fine and the search is only applicable to handles, which also works as expected. Moving the card to done.
