### ISSUE TITLE
Workflow triggers continue loading after execution fails

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1047]
## Reproduction steps
1. In the subwf add a ‘Prompt’ step. Set its type to ‘Redirect user to an outside URL’. 
2. Provide a url in the arguments section.
3. Add a ‘Termination’ step. Make sure all steps are connected 
4. Create a normal wf with the trigger resource set to ‘System’ and event set to ‘onManual’
5. From the side navigation of wf tools, add ’Execute Workflow’. Configure the wf id of this step to equal the id of the subwf you added
6. Execute the wf by clicking the play button
7. Since it is a prompt, ensure you are not in any of the webapps so that it can timeout

## Expected behavior
After server timeout, loading spinner should stop

## Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/229126027-74c38d0b-e72a-4c3f-bb17-fbf347239d59.png)

## Tested by
Emmy

## Version
2023.3.0-dev.5

**Comment by tjerman** [comment]
You currently can't sort/filter using names because they are under `meta` and we haven't (yet) implemented filters to use nested JSON properties.
Workflow list uses handle instead of name, do the same here.

**Comment by vicpatel** [comment]
We need to have try catch here so if BE req timeout than loader stops.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. 

Added CL:

```
Fixed:

{
      "what": [
        "workflow dry run process not stopping on server timeout/error."
      ],
      "how": [
        "by resetting the state and refreshing the trigger label so the spinner disappears."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1195/commits/ca64d3b6f0b8d160156581f75eea59575b94df97"
      ]
    }
