### ISSUE TITLE
Replace selects with vue-select

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1049]
Make a wrapper component around the vue-select component. This component will replace every instance of vue-select in the code base. 

The First Phase

- [x]  Find the simplest implementation or thereabout of vue-select in compose and begin there.
- [x] Create a wrapper component that accepts the props of vue-select and more. 
- [x] Make v-modeling work for this wrapper component.
- [x] Make respective slots available
- [x] Implement other custom props such as debounce timer, etc.
- [x] Implement search functionality
- [x] Update vue-select version

The Second Phase
This entails replacing vue-select with the new component wherever it is used.

###  Reporter Web App

- [x] Remove Vue-select from package.json
- [x] Column Selector (used in Chart, Metric, Link, and Join)
- [x] Prefilter
- [x] Scenario (Pick Scenario select) in Builder and Viewer

### Compose Web App

- [x] Remove vue-select package
- [x] Admin/Pages
- [x] Admin/Charts
- [x] Public/Record/Exporter
- [x] Public/Record/BulkEdit
- [x] Nylas Configurator
- [x] Navigation/ComposePages
- [x] Metric Configurator
- [x] Tabs Configurator
- [x] Recordlist Configurator
- [x] Record Configurator
- [x] Progress Configurator
- [x] Chart Configurator
- [x] Namespaces/Reminder
- [x] Namespace Sidebar
- [x] User Editor Module Fields
- [x] RecordList Filter
- [x] Page/Builder Selector
- [x] UniqueValues
- [x] Dal Settings

### Admin Web App

- [x] CRoleEditor
- [x] CFilterParams
- [x] CSelectUser
- [x] CPermissionClone
- [x] CPermissionList
- [x] CRoleEditorMembers
- [x] Remove Vue-Select

### Workflow Web App

- [x] Remove Vue-Select
- [x] Replace all Vue-Select

### Privacy Web App
- [x] Remove Vue-Select
- [x] Replace all Vue-Select

### Vue Library
- [x] Remove Vue-Select
- [x] Replace all Vue-Select

The Third Phase
This entails replacing Bootstrap's select with the new component wherever it is used.

- [x] Compose Web App
- [x] Admin Web App
- [x] Reporter Web App
- [x] Workflows Web App
- [x] Privacy Web App
- [x] Lib/Vue

**Comment by katrinDY** [comment]
For today: discuss task with Jože and start working on it

**Comment by katrinDY** [comment]
This is a bigger task since a reusable component has to be added with classes. Adding to 2023.x milestone

**Comment by EmmyMay** [comment]
Skipping replacing Multi mode for Select fields when the user chooses to have the multiple option which is basically using `<b-form-select multiple />` until @Fajfa gives input. Reason being that the component is way different in appearance to `BFormSelect`, and there is also a prop type issue that would impact our new wrapper component for vue-select if the multiple prop is used.
