### ISSUE TITLE
Discard snoozed flag when reminded at is changed in reminders

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1054]
## Description of the bug

_When changing the reminders remind at, the snoozed flag should go away.
Currently the snoozed indicator persists even though the reminder’s due date was changed._

## Reproduction steps

Have a reminder prompt the message and snooze it for any time

![Image](https://user-images.githubusercontent.com/53232926/229134509-b58cde6b-d998-458d-9a2a-1ca75b50abfa.png)

See the snoozed indicator (the left most icon)

![Image](https://user-images.githubusercontent.com/53232926/229134544-a6f6b72a-3c68-40bf-bd56-fca1ff5cb164.png)

Edit the reminder to be at a later date (the old one for me was a few days before today):

![Image](https://user-images.githubusercontent.com/53232926/229134597-84ff2f03-7697-417f-b3c4-5b0c0e639ccd.png)

See the snoozed indicator is still there

![Image](https://user-images.githubusercontent.com/53232926/229134649-77b05d37-de4e-4a1b-ad6f-a0aebfbaeedc.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Tomaz (Test fest)
Browser: Firefox

**Comment by tjerman** [comment]
2023.3.x monorepo commit `308f997c9`
