### ISSUE TITLE
Email address under the “send feedback” points to info@crust.tech

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1055]
## Description of the bug

_The email address under the “send feedback” in the top question mark icon points to info@crust.tech._

_Now. I know there are some restrictions on how Corteza references Crust (ie. we can’t really give preferential treatment since Corteza is a sepparate thing from Crust) but I’m not sure on the exact details._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/229135477-a35fe07a-8953-4f89-a129-6fa3b1883c96.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Tomaz (Test fest)
Browser: Firefox

**Comment by tjerman** [comment]
```
# Changed

## What

the feedback email domain from `crust.tech` to `cortezaproject.org`

## Refs

monorepo `2023.3.x` commit `0072a4bf4`
```
