### ISSUE TITLE
Reminders improvement

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1056]
## Description of the bug

UI/UX improvement, mostly not a bug I don’t find reminders intuitive.

1.	Should the + add a new reminder button become something cleaner (do we need it to be so verbose?

![Image](https://user-images.githubusercontent.com/53232926/229136094-400a7762-aff8-488a-b9f5-8a19f0384c8d.png)

Btn-outline-primary -> btn-primary
Text-center -> no alignment

Consistent with records and other add something lists like records

![Image](https://user-images.githubusercontent.com/53232926/229136151-120558be-28a8-4ff4-b068-01f7995f94ef.png)

2.	Should the toggle become a checkbox? A toggle tells me that something can be ON or OFF; so here enable/disable the reminder, not dismiss it – I think a checkbox would fit better (or a button that writes “dismiss”

![Image](https://user-images.githubusercontent.com/53232926/229136197-330f7395-df05-4c61-8750-8288549d9291.png)

3.	Can we show more content or make the content accessible with less work? Z, for example, has a description. Can we show (a truncated) description under the label? Alternatively, making the reminder clickable to expand/collapse with details would (in my opinion) work also.

4. I don’t find the left two icons (that the reminder is snoozed and for what time it’s set) intuitive. Do we need to hide information behind icons/tooltip instead of just showing it? In addition, the left (that it’s snoozed) and the right one show the same data (bug?):

![Image](https://user-images.githubusercontent.com/53232926/229136350-fbe0ee13-0543-44f1-8e72-b933ea6b9813.png)

![Image](https://user-images.githubusercontent.com/53232926/229136371-f4cdcc8c-13a4-4e12-9dda-28ec097ffe71.png)

5.	When editing a reminder, should the save button be moved next to the back button (same setup as elsewhere)?

![Image](https://user-images.githubusercontent.com/53232926/229136430-dd46cd18-f719-43d1-8bb5-4da55a6beb24.png)

6.	Should the fact the reminder was snoozed displayed on the reminder edit page, like it is on the view page?

![Image](https://user-images.githubusercontent.com/53232926/229136472-b978cee3-6d39-4083-9166-bceff5820ad3.png)

![Image](https://user-images.githubusercontent.com/53232926/229136488-e7782dde-4cda-435c-a7e1-225b69077dae.png)

7. Should the reminders panel change to feel the same as the navigation panel? When expanded (on large screens) should it push the content instead of rendering over the content?
Notes:
I really like how Apple’s reminders are displayed; can we utilize what they have going on?

![Image](https://user-images.githubusercontent.com/53232926/229136575-88103367-a02f-4683-8be4-1917d4d2cf1e.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Tomaz (Test fest)
Browser: Firefox

**Comment by katrinDY** [comment]
for today: discuss plan of action with Jože and write it down

**Comment by katrinDY** [comment]
for today: discuss plan of action with Jože and write it down

**Comment by yonkov** [comment]
Plan of action:

Reminders list page:
- [x] Change button text "Add a new reminder" to "Add a reminder" and put it down to the bottom of the reminders list
- [x]  Change toggle buttons to checkboxes (check bootstrap documentation for available options)
- [x]  Remove the clock icon and add a date under the reminder title
- [x] If there is a reminder description, show truncated description under the reminder's title
- [x]  Change reminder styles and add necessary bootstrap classes accordingly (margins paddings, font sizes, etc.). The reminders need to look good, even when they show more info. 

Reminders single page:
- [x] Make the back and save buttons appear on same line. Make the buttons consistent with other back and save buttons across Corteza.

**Comment by katrinDY** [comment]
for today: complete first two checkboxes

**Comment by katrinDY** [comment]
for today: complete remaining checkboxes and submit for code review
