### ISSUE TITLE
Fix hash and query URL trim on field

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1062]
## Description of the bug

_When I enable “Only allow SSL (https) Url”, the software doesn't trim the part of the link after the “?” (but before it, which totally change the link and leads to another page)._

## Reproduction steps

1.	Go to Modules
2.	Go to Module 2
3.	Click on the Field settings button for “URLinputTF”
4.	Click “URL input”
5.	Enable “Trim '?' from the Url”
6.	Click “Save”
7.	Go to “All records” button
8.	Click on a random record
9.	In the field “URL input TF” insert the link[ https://www.planetcrust.com/why-using-a-low-code-crm-is-a-game-changer-for-nonprofit-organizations?utm_campaign=blog](https://www.planetcrust.com/why-using-a-low-code-crm-is-a-game-changer-for-nonprofit-organizations?utm_campaign=blog)

## Expected behavior 

_I think this feature should remove the part after the “?” and at the end in the field to be visible:[ https://www.planetcrust.com/why-using-a-low-code-crm-is-a-game-changer-for-nonprofit-organizations](https://www.planetcrust.com/why-using-a-low-code-crm-is-a-game-changer-for-nonprofit-organizations)” . But the software places[ https://www.planetcrust.com/?utm_campaign=blog](https://www.planetcrust.com/?utm_campaign=blog) instead, which is leading to another page._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/229200543-3c304922-563e-49a2-ada0-fedd638666d5.png)

![Image](https://user-images.githubusercontent.com/53232926/229200571-d8384c5a-cc81-4e45-992a-80a80803e711.png)

## Description of the bug

_When I enable “Trim '#' from the Url”, and I placed a link in the filed containing “#”, the software didn’t trim anything from the link._

## Reproduction steps

1.	Go to Modules
2.	Go to Module 2
3.	Click on the Field settings button for “URLinputTF”
4.	Click “URL input”
5.	Enable “Trim '#' from the Url”
6.	Click “Save”
7.	Go to “All records” button
8.	Click on a random record
9.	In the field “URL input TF” insert the link https://stackoverflow.com/questions/75831150/nested-array-or-objects#answer-75831216

## Expected behavior 

_I think this feature should remove the part after the “#” and in the field to be visible: “https://stackoverflow.com/questions/75831150/nested-array-or-objects”. But the software didn’t trim anything from the link._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/229200730-2e181f55-5f67-45af-9d20-95c70f3b8b32.png)

![Image](https://user-images.githubusercontent.com/53232926/229200762-d57d97ca-552a-4ca5-9e64-130312cb5cfd.png)

## Description of the bug

_When I enable “Trim '#' from the Url”, and “Trim '?' from the Url” and I placed a link in the field”, the software trimmed the text before the “#” from a link containing both “#” and “?”. In this particular link the “#” is before the “?”._

## Reproduction steps

1.	Go to Modules
2.	Go to Module 2
3.	Click on the Field settings button for “URLinputTF”
4.	Click “URL input”
5.	Enable “Trim '#' from the Url” and “Trim '?' from the Url”
6.	Click “Save”
7.	Go to “All records” button
8.	Click on a random record
9.	In the field “URL input TF” insert the link https://stackoverflow.com/questions/75831150/nested-array-or-objects#answer-75831216?123

## Expected behavior 

_I think this feature should remove the part in the link after the “#” or “?”, not before._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/229200928-77b4b3d5-f3cc-4b8d-a9ac-032d5295c92e.png)

![Image](https://user-images.githubusercontent.com/53232926/229200949-63aa867d-69f4-4d6a-97b1-63066efb3e19.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Mariya (Test fest)
Browser: Chrome

**Comment by tjerman** [comment]
Will hop onto this one after #469

**Comment by katrinDY** [comment]
For today: add plan of action

**Comment by KinyaElGrande** [comment]
### Plan of Action

1. Reproduce the bug
2. Identify the root cause of the issue.
3. Develop a hypothesis and test it to validate or invalidate it.
4. Fix the bug and verify that everything is working as expected

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

Also added a Fix CL:

```
{
      "what": [
        "hash and query URL trim on URL input record field trimming the part before the hash and query instead of after it."
      ],
      "how": [
        "by changing the order of trimming methods to match their corresponding labels."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1173/commits/4b73eb782e679b7bc82518f4ceddbe9663fa358b"
      ]
    }
