### ISSUE TITLE
Tabs titles getting erased when you save the page

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1073]
## Description of the bug

_When you add a tabs block for the first time and you add couple tabs there and you give those tabs a title, and you press save and close, you can notice that the titles are present and as soon as you press save on the page builder you can see that the tab titles are erased and the blocks titles are there and just the first title is still present. (You can clearly see this behaviour from the video below)_

## Reproduction steps

1. Create a new NS
2. Create a new module
3. Create a record page
4. Go on your public page and add a tabs block
5. Add couple tabs and write titles for each tab
6. Press save and close on tabs block
7. Notice that the titles are there
8. Now press save on the page builder
9. Notice that the titles are erased except for the first tab

## Expected behavior 

_The tabs titles should not be erased on a page save._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/229772584-bf51e526-c73f-492a-9c45-973aa3fdeacf.webm

## Version

Branch: 2023.3.x

**Comment by EmmyMay** [comment]
The problem appears only when you have not saved a block before tabbing it then give it a title. If you save the blocks before tabbing them and giving them a title it does not occur.

**Comment by katrinDY** [comment]
For today: investigate issue and see what's causing this behaviour

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. No need for CL here since this is a fix for an unreleased new feature.
