### ISSUE TITLE
When setting Module record permission there is a missing delete label

### ISSUE THREAD

**Issue by andre-badenhorst-crust-tech** [cortezaproject/corteza#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3

### Current Behavior

Missing resource for deleting record module permissions

![image](https://user-images.githubusercontent.com/116157602/230115492-c6869936-76df-4dd6-8fa1-a0200a332bdf.png)

### Expected Behavior

Delete label

### Steps To Reproduce

Navigate to the NS admin panel
Click on a module
Click the permission icon and select record

### Environment and versions

```markdown
{"response":{"buildTime":"2023-04-01T14:26:41Z","version":"2023.3.0-dev.5.1"}}
```

**Comment by Fajfa** [comment]
Fixed: ef017a3cb
