### ISSUE TITLE
Cleanup of all automatically created dependabot PRs

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1085]
We need to cleanup all the dependabot PRs that are automatically created.
`Dependabot is a bot that searches old libs in a repo and automatically bumps it up, but it needs to be merged.`

Here is the list:
https://github.com/cortezaproject/corteza/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

**Comment by katrinDY** [comment]
The next step for completing this task will be to be QC-ed. If everything's fine, move to done, else address issues

**Comment by Bojan-Svirkov** [comment]
Tested this and also ran the cypress tests so everything looks normal so I am moving the card to **Done**.

**Comment by EmmyMay** [comment]
A little setback on this, I missed the list above and will now go through them and any other ones

**Comment by Bojan-Svirkov** [comment]
2023.3.x-security-review-dependabots

**Comment by Bojan-Svirkov** [comment]
Looking good. Moving the card to Done.
