### ISSUE TITLE
Tabs block titles get erased once you add a new block

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1128]
## Description of the bug

_When you first write a title for your tabs block and after that you add a new block the title that you have written gets erased. (This doesn't happen if you already have a block and you just select one, it only happens when you add new blocks)_

## Reproduction steps

1. Add a tabs block
2. Go in tabs configuration and press on add to add a new tab
3. Write a title (before adding or selecting block)
4. Now press on add new block button and select any block
5. Once you add the block notice that the title gets erased.

## Expected behavior 

_If you write up a title, the title doesn't need to get erased after you add a block._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/231448278-62922148-b85b-48c3-8ac5-91f12a65e394.webm

## Version

Branch: 2023.3.x

**Comment by EmmyMay** [comment]
For today: Take a look at this and timebox to 1h.

**Comment by katrinDY** [comment]
For today: open PR and submit for review

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected.

Also Fixed CL was added:

```
{
      "what": [
        "tabs block titles getting erased once you add a new block to the list."
      ],
      "how": [
        "by not updating the title when creating a block."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1170/commits/3ee9fd5cddabdb39ca7eafd90086c12a96c427f9"
      ]
    }
