### ISSUE TITLE
Calendar agenda event mouse pointer not using 'pointer'

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1130]
## Description of the bug

_When you have configured an event source to your calendar and you select the record to open up in a modal for example, when you go to the agenda view of your calendar, the record is clickable and it opens in a modal, but when you hover over the record the mouse is not using `pointer` it is using the ` text selector cursor`_

## Reproduction steps

1. Create a calendar block which has a configured record source and configure it to open in a modal
2. Enable the agenda view of your calendar
3. Go to the agenda view and hover over your record
4. Notice that the mouse is not pointer but a selector
5. IF you click on the record it opens just fine, so just the pointer is the issue.

## Expected behavior 

_The calendar agenda event mouse should be pointer instead of text selector._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/231479884-093e23bd-c4ba-4386-bf26-f235609c21fa.webm

## Version

Branch: 2023.3.x

**Comment by yonkov** [comment]
For today I will make a plan and start working on it.

**Comment by yonkov** [comment]
- [ ] Determine the correct partial for displaying data in calendar agendas
- [ ] Add a check if event source is a reminder or record
- [ ] if event source is record, set the cursor to pointer

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Fixed:

{
      "what": [
        "hovering on record event on calendar agenda not showing the cursor as pointer."
      ],
      "how": [
        "by changing the cursor from text selector to pointer."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1179/commits/2ec5bb3bbe5c9e4436a828dffed09a4611c6fd0c"
      ]
    }
