### ISSUE TITLE
Admin dashboard saying 0 active users even tho you have users

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1133]
## Description of the bug

_If you are on a new DB that doesn't have still any users created, go to the user sign up, and just write the email, without a handle or full name and press save. Notice that the handle will be auto generated and once you log in, see that the admin dashboard is saying `0 active users` even tho you have created a user._

## Reproduction steps

1. Be on a fresh DB
2. Create a user with just writing up the email, leave the handle and the names empty
3. Press save and once you are logged in see the dashboard, it is saying `0 active users`

## Expected behavior 

_If I have a user, the dashboard should be counting the correct number of users and not to be showing zero even if I have an user_

## Screenshot/Video

![image](https://user-images.githubusercontent.com/53232926/231787951-e16f3aea-4005-43e4-81c4-f157101194c2.png)

https://user-images.githubusercontent.com/53232926/231784764-005f6c9e-2ef2-41d3-8f24-aaf84a5971ad.webm

## Version

Branch: 2023.3.x

**Comment by tjerman** [comment]
Can't reproduce. I did get the same error a few weeks back but I can't get it to not work anymore.
@katrinDY @Bojan-Svirkov do share some configs in case you have some extra knobs enabled

**Comment by Bojan-Svirkov** [comment]
This is no longer an issue. I am moving the ticket to Done.
