### ISSUE TITLE
When running up a corteza on a fresh DB, no application is present

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1134]
## Description of the bug

_Once I ran corteza on a fresh DB I don't have any apps present on admin thus they are not present on One too._

## Reproduction steps

1. Create a new DB
2. Ran ONE or Admin webapp
3. notice that ONE list is empty since there are no apps
4. Also notice that Applications tab in admin is also empty and there are no apps present.

## Expected behavior 

_Once i spin up the server I expect the basic webapps (reporter, WF, CRM, case management, low code, admin ...) to be present and enabled._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/231785355-59f86c12-0625-4f03-8146-9ef00ddc56d2.png)

## Version

Branch: 2023.3.x

**Comment by tjerman** [comment]
Resolved with b6c24588a
Provision files used `applications` but yaml decoder only used `application` and `app` aliases.

![image](https://user-images.githubusercontent.com/12545711/231966616-4e8f01ab-ab43-4148-a75c-d6cb2cf2c6de.png)
