### ISSUE TITLE
CRM and Case management tabs block are shrank on a fresh DB

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1135]
## Description of the bug

_When you open CRM or Case management on a newly created DB the page block are really small. This was discussed before in a Bugs channel, and it looks like they are now x4 smaller than they used to be before._

_Note: We will have to go through the provision files and update xywh; they changed to be 4x larger._

## Reproduction steps

1. Create a new DB
2. Log in to Compose
3. Open either CRM or Case management
4. Notice that the page blocks are really small

## Expected behavior 

_The tabs block should be the same size as they were before. (I guess 4x bigger since that was the discussion from before)_

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/231786778-18266e34-96c2-460d-b601-51bb33cf6018.png)

## Version

Branch: 2023.3.x

**Comment by tjerman** [comment]
Resolved with b6c24588a
Provision files used `applications` but yaml decoder only used `application` and `app` aliases.

![image](https://user-images.githubusercontent.com/12545711/231966616-4e8f01ab-ab43-4148-a75c-d6cb2cf2c6de.png)

**Comment by tjerman** [comment]
Wrong issue...

**Comment by Fajfa** [comment]
Fixed on base

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that now the page blocks look as they should.
