### ISSUE TITLE
Reduce probability of horizontal scrolling on resource lists

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1146]
## Description
Currenlty, in all resource lists except RL, we have a couple of buttons on the right side of a list item that allow us to edit/view/... an item. These icons make it more probable that a resource list would have to be horizontally scrolled. In cases described below, extract some icons into a 'more menu' 3-dot icon and in places where we have an edit icon only, ensure the rows of data can instead be clickable. 

## Current behaviour

![Image](https://user-images.githubusercontent.com/85161724/232781602-b69a5548-a613-4902-a970-09a79af0f883.png)

## Expected behaviour

![Image](https://user-images.githubusercontent.com/85161724/232780752-d1cf8d36-e38e-4ee0-896d-59859ffdd1c2.png)

## Implementation list

<details>

<summary>Compose</summary>

- [x] Charts
- [x] Add Delete to Charts
- [x] Modules
- [x] Add Delete to Modules
- [x] Namespace
- [x] Add Delete to Namespace
- [x] Update Namespace Edit to stop using $store.dispatch

</details>

<details>

<summary>Admin</summary>

***For the Admin webapp the task would be to make sure the resource lists used no longer have an edit button. Each row should be clickable***

![Image](https://user-images.githubusercontent.com/31524469/234591450-614d7958-69e2-4862-a86d-eec4e14ab032.png)

- [x] APIGW
- [x] Connections
- [x] Federated Nodes *pending locale*
- [x] Sessions
- [x] Workflow
- [x] Application
- [x] AuthClient ([Address Inability to delete authclients](https://github.com/cortezaproject/corteza/issues/1216))
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template
- [x] Users

</details>

<details>

<summary>Reporter</summary>

- [x] List of Reports

</details>

<details>

<summary>Workflow</summary>

- [x] Workflow List

</details>

**Comment by KinyaElGrande** [comment]
For Today: Speak to Jože and make a plan.

**Comment by yonkov** [comment]
For today: Write the plan and start working on it.

**Comment by EmmyMay** [comment]
Plan of Action

1. Find all instance of the resource list that needs updating and update this issue
2. Add the 3 dots menu to each

**Comment by katrinDY** [comment]
for today: take a look at the three dots issue in admin. Time-box to 2h

**Comment by EmmyMay** [comment]
I would say the admin's three dots is done. But I will need additional guidance from @Fajfa on how we want it to look like.

**Comment by katrinDY** [comment]
for today: sync with Jože for additional guidance

**Comment by katrinDY** [comment]
for today: add finishing touches and open PR

**Comment by katrinDY** [comment]
for today: addresses comments

**Comment by katrinDY** [comment]
for today: continue working on this and complete admin and compose part

**Comment by katrinDY** [comment]
for today: start working on admin

**Comment by katrinDY** [comment]
for today: get familiar with code for deleting api gtw and try to resolve blocker. If not possible ping Jože. Then continue with admin implementation

**Comment by EmmyMay** [comment]
APIGW has been implemented but has a styling blocker for now. The dropdown shifts the resource-list layout and specifying a boundary does not fix it.

**Comment by EmmyMay** [comment]
For federated nodes: 
We would either have to make it possible to see deleted federated nodes, or make it impossible to undelete federated nodes from the list view

**Comment by katrinDY** [comment]
for today: complete AuthClient, Queue, Role, Users

**Comment by katrinDY** [comment]
for today: complete admin part of the task

**Comment by EmmyMay** [comment]
For federated nodes: I will need some help here. It does not appear that the weight of the deleted flag changes when sorting. This did not have status filters before, so maybe I am the one who does not know how to correctly implement it.

**Comment by KinyaElGrande** [comment]
For today: refactor admin and finish workflow and reporter.

**Comment by katrinDY** [comment]
for today: sync with Jože to discuss necessary changes

**Comment by katrinDY** [comment]
for today: address comments on PR

**Comment by katrinDY** [comment]
for today: continue addressing comments, refactoring code and submit for code review

**Comment by katrinDY** [comment]
for today: complete task

**Comment by katrinDY** [comment]
fro today: address last review comments

**Comment by EmmyMay** [comment]
Testing Notes:

1. Items in a resource list should be able to be deleted or undeleted in the 3-dots menu.
2. If permssions like canGrant and canDelete are not set, the three dots menu should not appear

**Comment by katrinDY** [comment]
for today: address last comment from QC and complete task

**Comment by katrinDY** [comment]
for today: sync with Katrin on review comments, address thems and submit for review.

**Comment by EmmyMay** [comment]
# Changelog

## Added

### What

**3 dots menu (kebab menu) to resource lists**

### Why

**This makes it easy for user to perform certain operations on resources from the list view.**
