### ISSUE TITLE
service.auth-notification auth notification "could not send email"}

### ISSUE THREAD

**Issue by ghost** [cortezaproject/corteza#1149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2022.9.9

### Current Behavior

While deploying a fresh corteza project with proper SMTP settings, the value SMTP_FROM is not set in the auth-notification.

It is exactly(!) the same behavior as described in #372. Is there a quick fix? Yaren-IT has already asked this question in #372. There may be an answer by now.

**Comment by gerickt** [comment]
same problem here

**Comment by ghost** [comment]
Hello gerickt,

Pascal described me a solution to this problem in the penultimate post:

https://forum.cortezaproject.org/t/is-there-such-a-thing-as-a-demo-user-or-account/1336

Despite this, the behavior is sad. Especially with such a complex and well-made product.

Greetings,
Roman

**Comment by etranger7** [comment]
I encountered the same problem.
For some reason the variables set in the .env file don't get passed down to the system container settings that are located in
corteza/provision/001_settings/auth.yml
That file still contains the info@example.ltd address.
Manually editing that file gets me around this specific issue and I no longer get the "could not send email" error.

However, I'm still not getting an email. Could be directly related to this or not.

Regardless, it would be great if this issue could be fixed.

Version: 2023.3

**Comment by ghost** [comment]
Pascal described the solution. This works perfectly.

https://forum.cortezaproject.org/t/corteza-email-sending-failed/305/3

It's really a shame that it is the way it is. Especially because this project was funded with EU funds. I myself chose odoo as the platform for my project.

**Comment by etranger7** [comment]
Thank you for the tip.
