### ISSUE TITLE
Funnel chart labels get hidden when you hover on them

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1153]
## Description of the bug

_When you configure a funnel chart and you let's say configure the `Show relative value` & `Always show labels` to be enabled, once you add the chart to a public page, the values are getting hidden when you hover on it. This doesn't happen on doughnut chart for example._

## Reproduction steps

1. Create a funnel chart
2. Enable the `Show relative value` & `Always show labels`
3. Save the chart
4. Add it to a public page
5. Hover on it and notice that the values are hidden

## Expected behavior 

_When you hover over the chart the values should be still shown as in any other chart._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/233315216-dc4f8aba-0142-4b64-b247-59e60ba6d004.webm

## Version

Branch: 2023.3.x

**Comment by katrinDY** [comment]
for today: make plan and start working on it

**Comment by yonkov** [comment]
The plan:

- [x] Read documentation on funnel charts
- [ ] Examine the different options in corteza-js  between the generic chart and funnel chart 
- [ ] Fix the issue

**Comment by katrinDY** [comment]
for today: get familiar with chart code and open PR by EOD

**Comment by katrinDY** [comment]
for today: resolve issue and resubmit for review

**Comment by katrinDY** [comment]
Tested and can confirm the labels appear on hover with the correct configuration.

**Comment by katrinDY** [comment]
```
Fixed:

{
      "what": [
        "funnel chart labels are hidden when you hover on them."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1222"
      ]
    }
```
