### ISSUE TITLE
Cannot cancel two requests in Privacy (one after the other)

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1159]
## Version
_2023.3.0-dev.5.1_

## Description
After I cancel a request, I cannot cancel another one 

## Reproduction steps
1. Create a request
2. Cancel it through the cancel btn in the request list
3. Try to cancel another request in the same way
4. You aren’t able because the cancel btn in disabled

## Expected behavior
I should be able to cancel more than one requests

## Tested on
Safari on MacOS Ventura 13.2.1

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works flawlessly. 

Added CL:

```
Fixed:
{
      "what": [
        "not being able to cancel more than one privacy request consecutively in {APP_NAME_PRIVACY}."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/commit/a559569053a4cbb9f56cfd3e37a7110827a528c8"
      ]
    }
