### ISSUE TITLE
Improve Admin UI for mobile

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1162]
## Version for all issues
_2023.3.0-dev.5.1_

## Issues
1. Page scroll if off in user list
2. The buttons are not correctly positioned on a small enough viewport in Role editor
3. Endpoint label field appears below its input. Same happens on create

 ---

### Description
The page is scrollable outside of viewport, while the content (list table) is the correct size of the viewing area.

### Reproduction steps
Go to user list and scroll right (first the list, then the page)

### Expected behavior
The view should be fixed without scrollbars.
This was tested only on a desktop machine via developer tools.

### Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/233405551-b20ee76d-87ca-4ed4-b790-b5e8a6b65cc4.gif)

### Tested on
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
Samsung Galaxy S8+

---

## 2. The header buttons are not correctly positioned on a small enough viewport in all editor info
- [x] APIGW
- [x] Connections
- [x] Federated Nodes *pending locale*
- [x] Sessions
- [x] Workflow
- [x] Application
- [x] AuthClient
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template
- [x] Users

### Reproduction steps
Edit an existing role on a mobile device

### Expected behavior
The New button should be vertically positioned on top

### Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/233406408-2c6d3e37-1986-4140-b504-b3dbc6b82929.PNG)

### Tested on
Iphone 13 Pro Max 
Safari

---

### Reproduction steps
1. Integration gateway
2. Edit a gateway

### Expected behavior
Elements shouldn't be overlapping

### Screenshots/Videos
![Image](https://user-images.githubusercontent.com/85161724/233407196-8968a881-c99f-419a-a9e8-67fcb52f3ddd.PNG)

### Tested on
Iphone 13 Pro Max 
Safari

## 4. Editor Info Responsiveness for editor info buttons
- [x] APIGW
- [x] Connections
- [x] Federated Nodes
- [x] Sessions
- [x] Workflow
- [x] Application
- [x] AuthClient
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template
- [x] Users

 ### 5. Remove column for actions on resource lists for admin
- [ ] APIGW
- [ ] Connections
- [ ] Federated Nodes *pending locale*
- [ ] Sessions
- [ ] Workflow
- [ ] Application
- [ ] AuthClient
- [ ] Queue
- [ ] Role
- [ ] Senstivity Level
- [ ] Template
- [ ] Users

### 6. Make forms responsive for all *resource editor components*
- [x] APIGW
- [x] Connections
- [x] Federated Nodes
- [x] Sessions
- [x] Workflow
- [x] Application
- [x] AuthClient
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template
- [x] Users

### 7. Consider using Labelled Switch Component for switches in editor infos for all resource lists
- [x] APIGW
- [x] Connections
- [x] Workflow
- [x] Application
- [x] AuthClient
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template

### 8. Refactor Delete and Undelete Actions
- [x] APIGW
- [x] Connections
- [x] Workflow
- [x] Application
- [x] AuthClient
- [x] Queue
- [x] Role
- [x] Senstivity Level
- [x] Template
- [x] Users

**Comment by katrinDY** [comment]
for today: get familiar with task and start fixing issues

**Comment by katrinDY** [comment]
prioritizing https://github.com/cortezaproject/corteza/issues/1181 over this task since its for .3

**Comment by katrinDY** [comment]
for today: continue working on task and solving the issues

**Comment by katrinDY** [comment]
for today: sync with Jože to discuss task

**Comment by katrinDY** [comment]
for today: sync with Jože to discuss task and start imeplementing code

**Comment by katrinDY** [comment]
for today: sync with Jože to discuss task

**Comment by EmmyMay** [comment]
The first issue seems to no longer be a problem.

**Comment by katrinDY** [comment]
for today: complete the header buttons part of the task

**Comment by katrinDY** [comment]
for today: work on the 6th bullet point `Make forms responsive for all editor infos`

**Comment by katrinDY** [comment]
for today: continue with form responsivenes , delete and undelete btns for each resources

**Comment by katrinDY** [comment]
for today: continue with responsiveness delete and undelete btns of msg queues and auth clients

**Comment by katrinDY** [comment]
for today: continue with msg queues and intg gtw

**Comment by katrinDY** [comment]
for today: finish federation and session for issues 6,7,8

**Comment by katrinDY** [comment]
for today: find a way to fix the issue in the 5th bulletpoint

**Comment by katrinDY** [comment]
for today: sync with Jože to resolve blocker

**Comment by katrinDY** [comment]
for today: discuss with Jože the fifth point of the task and decide how to proceed with the task

**Comment by EmmyMay** [comment]
The forms I did not manage to fix for are CProfilerHitInfo (could not locate where it is used), ExternalOIDC, ExternalSAML, ExternalSecurity, ExternalStd. The latter are imported but unused.

**Comment by EmmyMay** [comment]
I need to have a call with @KinyaElGrande  regarding a backend issue I found with this.
