### ISSUE TITLE
Make sidebar body scroll only on items

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1164]
Query and button to public/admin should always be at the top
Same on reporter and workflow search, all three should look and behave the same.

**Comment by EmmyMay** [comment]
For today: Sync with @Fajfa for clarification on this.

**Comment by katrinDY** [comment]
for  today: take a look at what was discussed with Jože and start implementing the code

**Comment by EmmyMay** [comment]
Workflow is mentioned here, but I cannot reproduce this on there.

**Comment by katrinDY** [comment]
for today: address comments on PR and re-submit for review

**Comment by katrinDY** [comment]
for today: reverse changes and submit for code review

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected.

Added CL:
```
Changed:
{
      "what": [
        "the sidebar of {APP_NAME_COMPOSE} and {APP_NAME_REPORTER} to be scrollable just on items and the search bar and public/admin page button to be always on top."
      ],
      "why": [
        "to improve the accessibility of the the search bar and the buttons for public and admin page."        
      ],
      "how": [
        "by making the sidebar components stick to top."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1189"
      ]
    }
