### ISSUE TITLE
Add select all items in record list (includes records on all pages)

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1167]
Add the capability to select all records in the record list from all pages, and allow bulk editing/deleting/exporting/automation and other things you can do with selected records.

**Comment by katrinDY** [comment]
for today: get familiar with  the task and make a plan

**Comment by katrinDY** [comment]
for today: add plan

**Comment by KinyaElGrande** [comment]
#### Plan

- [x] Implement a  button with an option to select all records in the record list from all pages.
- [x] Modify editing selected records rest API.
- [x] Create a new service for editing selected records.
- [x] Modify deleting selected records rest API.
- [x] Create a new service for deleting selected records.
- [x] Modify undeleting selected records rest API.
- [x] Create a new service for undeleting selected records.
- [x] Implement `excluded records` while exporting all records
- [x] Implement automation selected records

**Comment by EmmyMay** [comment]
For today: begin executing the plan of action.

**Comment by katrinDY** [comment]
for today: implement REST API for button for selecting all record for all pages

**Comment by katrinDY** [comment]
for today: sync with Tomaž to discuss plan of action and continue working on the task

**Comment by katrinDY** [comment]
for today: sync with Tomaž and Katrin to discuss blockers and continue working on the task

**Comment by katrinDY** [comment]
for today: discuss plan of action with Tomaž and continue working on the task

**Comment by katrinDY** [comment]
for today: finish with select service for editing implementation and start working on the service for deleting

**Comment by katrinDY** [comment]
for today: timebox to an hour to try and resolve blocker on editing. If can't resolve blocker, ping Tomaž. After resolving the blocker, focus on deleting

**Comment by katrinDY** [comment]
for today: discuss blocker with Tomaž and finish with delete and complete functionality

**Comment by katrinDY** [comment]
for today: finish with delete and undelete functionality and start working on the exporting for all records

**Comment by katrinDY** [comment]
for today: add remaining code to BE and submit for review

**Comment by katrinDY** [comment]
for today: open PR for BE part

**Comment by KinyaElGrande** [comment]
For today: strat implementing the FE part.

**Comment by katrinDY** [comment]
for today: continue working on FE part

**Comment by katrinDY** [comment]
for today: add finishing touches to FE and submit code for review in 4h max

**Comment by katrinDY** [comment]
for today: discuss blocker with Tomaž and update issue

**Comment by katrinDY** [comment]
for today: address what's remaining of the blocker and submit for review by EOD

**Comment by katrinDY** [comment]
for today: sync with Tomaž and Jože to discuss review comments and start addressing them

**Comment by katrinDY** [comment]
for today: address comments and send for code review

**Comment by katrinDY** [comment]
for today: address  comments and submit for review

**Comment by KinyaElGrande** [comment]
### Changelog
 ```json
 {
   "what": [
      "Support for selecting all records and performing edit, delete and undelete bulk operations"
   ],
   "why": [
      "to give the user the ability to select all records in the recordlist and perform edit, delete and undelete bulk operations"
   ],
   "refs": [
        "https://github.com/cortezaproject/corteza/pull/1223/commits/f2e1e9f86204e7b29f5b4bdd25bf9f9b0d1cdb3b",
        "https://github.com/cortezaproject/corteza/pull/1263/commits/a4314134aeac95516f5ead09950687832c1165e6"
   ]
 }
 ```

**Comment by katrinDY** [comment]
for today: address issue and submit to QC
