### ISSUE TITLE
Replace admin role/user picker with vue select (like permissions modal)

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1169]
## Description
To keep consistent. Use multiselect vue-select.
Look where old pickers are used and replace them.

## Make change in:
- [x] role picker in user edit
- [x] role member in role edit
- [x] auth settings -> permitted/prohibited/forced roles
- [x] auth client -> permitted/prohibited/forced roles

**Comment by katrinDY** [comment]
for today: add vue-select to user edit

**Comment by katrinDY** [comment]
for today: continue implementing code for vue-select to user edit

**Comment by katrinDY** [comment]
for today: add remaining changes and submit for review

**Comment by katrinDY** [comment]
for today: add finishing touches and submit for review

**Comment by katrinDY** [comment]
for today: sync with Jože and address comments

**Comment by katrinDY** [comment]
for today: address comments and submit for review

**Comment by katrinDY** [comment]
for today: address comments and submit for review

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected.

Added CL:

```
Changed:
{
      "what": [
        "{APP_NAME_ADMIN} role and user picker with vue-select."
      ],
      "why": [
        "to be consistent with the rest of the pickers used in {PRODUCT_NAME}."
      ],
      "how": [
        "by adding vue-select to role and member picker components."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1194"
      ]
    }
