### ISSUE TITLE
Login page double spacing

### ISSUE THREAD

**Issue by mangss52** [cortezaproject/corteza#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.0

### Current Behavior

Tiny UI fix

Double spacing at the bottom of the login page 

"Access source code on
[GitHub](https://github.com/cortezaproject/)"
![WhatsApp Image 2023-04-25 at 12 34 58](https://user-images.githubusercontent.com/18050774/234269393-ff1e12a7-2820-4a67-a6e2-f94fae0b4a3b.jpg)

### Steps To Reproduce

Navigate to {base_url}/auth/login

**Comment by Fajfa** [comment]
Fixed by #1653
