### ISSUE TITLE
Document page block duplication

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1180]
Page block duplication enables you to reuse existing page blocks to simplify dashboard creation and reusability.

The documentation should [go here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/index.html)

- [x] Document how to enable the feature (if any) and how to use it.
- [x] Provide a step-by-step example of using it.
- [x] Provide some use cases

Original issue https://github.com/cortezaproject/corteza/issues/447

**Comment by EmmyMay** [comment]
For today: make a plan and begin working on this.

**Comment by katrinDY** [comment]
for today: add finishing touches and submit for review

**Comment by katrinDY** [comment]
for today: address comments and submit for review

**Comment by katrinDY** [comment]
for today: Tomaž to review

**Comment by katrinDY** [comment]
for today: sync with Tomaž on review comments and address them

**Comment by tjerman** [comment]
lgtm; merge it
