### ISSUE TITLE
Document conditional fields on pages

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1181]
Conditional fields enable configurators to show specific fields only under a condition.

The documentation should [go here](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/compose-configuration/index.html)

- [x] Document how to enable and use the feature
- [ ] Document the used expression language
- [x] Provide config. examples

Original issue https://github.com/cortezaproject/corteza/issues/478

**Comment by katrinDY** [comment]
for today: start writing the documentation

**Comment by katrinDY** [comment]
todo: sync with Tolu for docs fix

**Comment by katrinDY** [comment]
for today: continue working on task

**Comment by katrinDY** [comment]
for today: continue working on task

**Comment by EmmyMay** [comment]
I don't think the language should be documented @tjerman because we have an example link to the language in the feature

**Comment by tjerman** [comment]
That's fine then

**Comment by EmmyMay** [comment]
closes https://github.com/cortezaproject/corteza-docs/pull/423
