### ISSUE TITLE
WF error step text expander not working

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1199]
The Workflow error step text expander does not work, and when you have more text it overlaps with the scroll bar.
See photos for more context:

![Image](https://user-images.githubusercontent.com/53232926/238615901-78e04ff7-86f7-4a99-8adf-06ac65143e9f.png)

![Image](https://user-images.githubusercontent.com/53232926/238615918-0b44aabc-4439-4513-bc5c-83cf310c9493.png)

**Comment by katrinDY** [comment]
for today: investigate issue and get familiar with it

**Comment by katrinDY** [comment]
After review: the text expander and modal look and behave as they should. However, I noticed a couple of things
1. When we have a multiline expression, the UI behaves a bit awkwardly and the text of the err step is concatenated.

![Image](https://github.com/cortezaproject/corteza/assets/85161724/3212bd6e-82d2-4c0e-89a9-5304944ad336)

2. When we have a multiline expression, the arrow connecting looks a bit off (only on multiline)

![Image](https://github.com/cortezaproject/corteza/assets/85161724/7b7ec123-a001-4185-a754-3523b8e3c78a)

**Comment by katrinDY** [comment]
Added CL:

```
Fixed:
{
      "what": [
        "text expander functionality in {APP_NAME_PRIVACY} error step."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/commit/84215c0edf87b52b0bcb07fe632107b48e48d582"
      ]
    }
```

**Comment by katrinDY** [comment]
[Issue](https://github.com/cortezaproject/corteza/issues/1233) for the above findings
