### ISSUE TITLE
Improve DAL Schema Management

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#1200]
Since the introduction of DAL, modules can be *bound* to their own database tables.
We don't, however, have a system in place which would help us support alterations on these *stand-alone* tables.
The current implementation is too strict to just error out on almost any change we make to *physical columns*.

The goal of this issue is to produce an MVP of a system to facilitate schema alterations in both a manual and an automated manner.

## Flow outline

* When a module is updated, we prepare a new DAL model definition based on it.
* Using the old model (when available) we calculate the diff between them.
* Analyzing the diff, we can see if we need to perform any DDL operations on the underlying schema.
  * We'll probably need to also utilize the connection's schema definitions here.
* If no, we don't do anything additional.
* If yes, we define a new schema alteration with all of the operations we'll need to perform.
* We set a model issue since a schema mismatch poses an issue.
* When we respond to the module update request, the front end determines if it needs to display a modal to interact with this alteration (using model issues).
* The front end prompts a modal window with all of the operations the schema alteration needs to perform.
* The user has two options here: do it on their own or let the system do it automatically.
* If the user does it on their own, the user does so then they prompt Corteza to re-validate the model (to see if it's compatible with what the user has done).
* If we do it automatically, the user selects what they want to do and Corteza handles what they've selected.

## Important notes

* We need to decide if we want to put the entire alteration into a transaction or just its operations.
It might be impossible to transact the entire alteration since it doesn't have to happen in one go... or does it...
* Decide if we want to utilize the actionlog or do we want to have something custom.
* In case the user updates the module multiple times, all ongoing alterations must be squashed into a single one (since modules and models are detached, the model/schema may not have all of the alterations applied from the previous module update).
* It might not be so trivial to mix and match automatically and manually done alteration operations -- if the order is important, how do we indicate the manual one has already been done?
Consider allowing just one or the other.
* It could be a nice addition to make DAL output base commands on what it's going to run so the users would have an easier time doing things manually.

## Tasks

* https://github.com/cortezaproject/corteza/issues/1201
* https://github.com/cortezaproject/corteza/issues/1202
* https://github.com/cortezaproject/corteza/issues/1203
* https://github.com/cortezaproject/corteza/issues/1204
* https://github.com/cortezaproject/corteza/issues/1205

**Comment by katrinDY** [comment]
for today: start resolving on of the tasks

**Comment by katrinDY** [comment]
Have a working version by Tuesday/Wednesday

**Comment by katrinDY** [comment]
for today: continue with testing and tweaking

**Comment by katrinDY** [comment]
for today: address temporal value handling

**Comment by katrinDY** [comment]
for today: look into db transaction table locking race condition

**Comment by katrinDY** [comment]
for today: continue refactoring and testing

**Comment by katrinDY** [comment]
for today: continue with unit tests

**Comment by katrinDY** [comment]
for today: continue addressing db inconsistency

**Comment by katrinDY** [comment]
for today: continue testing

**Comment by katrinDY** [comment]
found issues after QC:
- https://github.com/cortezaproject/corteza/issues/1287
- https://github.com/cortezaproject/corteza/issues/1288
