### ISSUE TITLE
Define schema alteration management

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#1201]
Under the system component, define a `DalSchemaAlteration` service with all of the corresponding codegen definitions (store, types, ...); consider omitting envoy at this stage.

In addition to the service, we should add rest logic also.

The service provides the standard CRUD operations over alterations.
We can add additional functions the `pkg/dal` package could utilize (I'm quite sure we can get away with just CRUD).

## Core-type fields

These fields must be present; you may add others if you see fit (such as timestamps).

* **AlterationID uint64**: the field denotes the entire alteration and the same value is shared by all operations in the same alteration.
* **OperationID uint64**: the field denotes a single operation inside the entire alteration and is always unique
* **Operation string**: the field denotes what this bit of the alteration performs.
Optimally, this would be some enum field.
* **Params JSON**: cookie-cutter field for all parameters the system would need to perform an alteration

**Comment by katrinDY** [comment]
for today: start working and complete it

**Comment by tjerman** [comment]
Base prepared; to add along the way:

* extra functions when needed
* RBAC (might need some extra brains on this)
* consider event buss

**Comment by tjerman** [comment]
Skipping QA because it'll be tested all in one go (this is a single bit of the whole picture)
