### ISSUE TITLE
Extend UI to support these new additions

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#1204]
On the module update response, check if there is a specific issue.

**Important** see the consideration regarding mix and matching manual and automatic alterations -- we might omit this bit for now.

* If there is, fetch the referenced alterations (should they already be provided with the issue?)
* Show a modal window listing all of these alterations.
* Each alteration can be toggled (see the important note).
* At the bottom you'd have an option to apply these alterations or to skip them and do it manually.

We can also have a button next to each alteration operation to do them one by one, which would theoretically make the whole mix-and-match manual and automatic alterations possible and trivial.

The alterations modal should also know how to show related logs.

**Comment by tjerman** [comment]
This is what the UX would look like (for now):

* modal window with all alterations 
* two buttons at the bottom; one to do it manually and one to do it automatically (we might not need the manual button; just show dismiss always)
* if you press the manual option, you get a dismiss button next to each alteration
* if you do it automatically, non-resolved alterations get resolved one by one
* if an alteration is dependent on a different one, they're visually grouped and logically can't be resolved in an incorrect order. Until the first alteration is resolved, the dismiss button is hidden/disabled on the second one.
* If all alterations are dependant in the _same branch_, no visual grouping is needed (perhaps)

If you close the modal, you can re-open it under the issues.
We could consider moving this thing (or adding a copy of it) under some/new tab in addition to/instead of a modal.

**Comment by katrinDY** [comment]
for today: complete task

**Comment by tjerman** [comment]
_Completed_ with the exception of Jože wanting to make it look nice; the base logic is prepared (mocked until the rest of the API (other issues) are in place).

**Comment by katrinDY** [comment]
for today: Tomaž to connect it to the api and add nicer param encoding

**Comment by katrinDY** [comment]
for today: connect api to FE and finalize FE

**Comment by katrinDY** [comment]
for today: finish task

**Comment by katrinDY** [comment]
for today: discuss finishing touches with Tomaž

**Comment by Fajfa** [comment]
Closing this, since it was implemented. The "parent" issue is this https://github.com/cortezaproject/corteza/issues/1200
