### ISSUE TITLE
Record organizer overflowing long texts

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1209]
![Image](https://user-images.githubusercontent.com/53232926/238983591-88e9d51f-c9fb-44ca-9a8e-6b6799dce864.png)

**Comment by katrinDY** [comment]
for today: add finishing touches and submit for code review in an hour

**Comment by katrinDY** [comment]
The issue is present in the fields:
- record
- email
- url

**Comment by katrinDY** [comment]
for today: resolve comments and resubmit for code review

**Comment by katrinDY** [comment]
for today: continue implementing a solution and submit code for review
