### ISSUE TITLE
Discovery upgrade issue with 2022.9.4 <-> 2022.9.6 or later

### ISSUE THREAD

**Issue by vicpatel** [cortezaproject/corteza#1210]
Go from 2022.9.1 to 2022.9.9

**Comment by vicpatel** [comment]
Adding some debug logs and refactoration.

**Comment by petergrlica** [comment]
Check w/ a project that is known to fail @petergrlica

**Comment by katrinDY** [comment]
for today: Peter to sync with Vivek

**Comment by petergrlica** [comment]
Synced w/ Vivek, will test the provisioning on an existing db with an old enough Corteza version.

**Comment by katrinDY** [comment]
for today: continue testing

**Comment by petergrlica** [comment]
Todo - test with 2nd project
