### ISSUE TITLE
Improvement of Corteza signup flow

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1213]
_It’s not clear how a user enters Corteza after signing up, resulting in users not knowing how to get started in Corteza, especially in the public instance that our leads access, though all users would appreciate clearer onboarding._

##  The Problem:

- When a user goes to sign up for Corteza, they first go to this screen:

![Image](https://user-images.githubusercontent.com/53232926/239265856-2c4786bd-fb03-4b44-84ec-f57efa008653.png)

- After clicking submit, they land here, which is a UX nightmare (see my comments):

![Image](https://user-images.githubusercontent.com/53232926/239266075-c590e243-6690-4842-ad94-9dff4c2a9cbb.png)

### Could we change the onboarding process to make the onboarding experience better and clearer?

Below are three options for solutions, starting with the preferred:

## 1. Best UX Option:

After signing up, the user is taken directly to Corteza One – no second screen.

## 2. Second-best UX Option:

_If the second screen is necessary, is it possible to remove the profile info so it looks/functions like this:_

![Image](https://user-images.githubusercontent.com/53232926/239266972-3fbd3e29-9627-4fb6-bd80-68420c3c3bee.png)

## 3. Third-best UX Option:

_If neither option 1 nor 2 is possible, could we redesign the second page so it looks/functions like this:_

![Image](https://user-images.githubusercontent.com/53232926/239267177-3f7691f1-9c31-40af-8ae1-b49dc04c9453.png)

**Comment by katrinDY** [comment]
for today: discuss which approach to take with Joze and start implementinig it

**Comment by katrinDY** [comment]
for today: add finishing touches on BE and open PR

**Comment by katrinDY** [comment]
for today: add finishing touches

**Comment by katrinDY** [comment]
for today: team up with Tomaž ad complete task

**Comment by katrinDY** [comment]
for today: discuss fix with Tomaž and Jože

**Comment by katrinDY** [comment]
for today: investigate issue found by QC and start working on it

**Comment by katrinDY** [comment]
for today: fix bug and continue working on issue

**Comment by katrinDY** [comment]
for today: sync with Katrin to reproduce issue found by QC

**Comment by katrinDY** [comment]
CL added
