### ISSUE TITLE
Inability to delete or undelete authclient resources

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#1216]
When you try to delete or undelete an authclient, it errors out.

## Reproduction steps
1. In the admin web app, go to Authclients,
2. Open or create a new one
3. Click on delete

## Expected behavior
The resource should delete and reveal an undelete button and both should delete and undelete an authclient resource

### Note
 Attempt to refactor the logic for deleting so that it can be similar to other resources.

![Image](https://github.com/cortezaproject/corteza/assets/31524469/30be5682-78a3-493c-bcba-16f5a91d2c05)

**Comment by EmmyMay** [comment]
I believe this is an FE issue and will be addressing this as part of #1146

**Comment by EmmyMay** [comment]
Here is the [commit](https://github.com/cortezaproject/corteza/pull/1178/commits/c8158d8d8132f3e43802469ad4c80add09295b51) that addresses this as part of #1146  @Fajfa

**Comment by EmmyMay** [comment]
Here is the updated [commit](https://github.com/cortezaproject/corteza/pull/1178/commits/2fafe314823dd14faebe94d72218daeaec3fd48f) addressing this as part of #1146  @Fajfa

**Comment by Fajfa** [comment]
Fixed with 46f5455bd0ae67b9de2159f9d04b054a711832e1
