### ISSUE TITLE
Add an option to remove an icon once it has been added

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1217]
## Description of the bug

_Once you add an icon to your compose page, there is no way of actually removing the added icon from the list._

## Reproduction steps

1. Go in one of your namespaces
2. Open any page
3. Under Page Icon, press on the configure page icon button
4. Add an icon
5. After adding the icon, deselect it and see that you don't have an option to completely remove the icon from the list.

## Expected behavior 

_We should be able to have an option to remove an icon from our list once it has been added to the list._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/239936310-0e75ccc3-f6c2-4cf6-8099-3b13501ba5dc.png)

## Version

Branch: 2023.3.x

**Comment by katrinDY** [comment]
for today: continue working on task

**Comment by katrinDY** [comment]
lgtm; leaving this here if you wanna test it @Fajfa
