### ISSUE TITLE
Navigation compose page not clickable if sub-page is not enabled

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1218]
## Description of the bug

_When you configure a compose page in your navigational page block, if you disable your `display sub-pages` option, the compose page won't be clickable._

## Reproduction steps

1. Add a navigational page block in your NS
2. Add a compose page
3. Disable the display sub-pages option
4. Save the page
5. Try clicking on the compose page
6. Notice that nothing happens if the option is disabled
7. If you enable the option, the subpage from the dropdown will open your actual compose page.

## Expected behavior 

_Even if display sub-pages is disabled, you should be still able to click and open your compose page._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/239938393-4ea30043-cc45-4b22-a0a8-53527de2bc0c.png)

https://drive.google.com/file/d/1ndOoMkg0ATpX-KbJGjJVh9tG2Kca8t6z/view?usp=share_link

## Version

Branch: 2023.3.x

**Comment by Fajfa** [comment]
Whole nav item should be clickable and not just the text
