### ISSUE TITLE
Saving a layout as a copy doesn't work

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#1228]
## Description of the bug

_When you want to make a copy of your existing record page, you are not able to and you are receiving the error message: `Failed to clone layout: handle not unique`_

## Reproduction steps

1. Open a namespace that has an existing page
2. Open the page builder of your page from your admin panel
3. Press on Save as copy
4. Notice that the copy doesn't work and you are receiving an error

## Expected behavior 

_Since the future is there, I should be able to copy a page and have an exact copy of my layout/page._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/240863334-a5717bcd-6a4c-4429-99de-bc50e8b7a83d.png)

## Version

Branch: 2023.3.x

**Comment by katrinDY** [comment]
for today: make plan and discuss it with Jože

**Comment by katrinDY** [comment]
Layout is copied successfully but:
- the new layout isn't selected like the success message says
- after creating a copy of a layout, the title of the new and previous copy are changed

![Image](https://github.com/cortezaproject/corteza/assets/85161724/9895dbba-5826-4cab-84fa-210725df4d64)

**Comment by katrinDY** [comment]
Added CL:

```
{
      "what": [
        "copy of page layout in {APP_NAME_COMPOSE}."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1230"
      ]
    }
```
