### ISSUE TITLE
Fix styles of x button in webapp one searchbar

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1241]
## Version
_2023.3.2_

## Description
Notice how the x btn appears on the left side of the mag. glass and then the mag. glass is hidden and the x appears in its place
![Image](https://user-images.githubusercontent.com/85161724/244681661-20aba14e-5b2c-4f49-9aee-0b56ed05ebad.gif)

## Expected behaviour
Either show one of the btns or place the x btn right next to the mag. glass (remove the gap between the two btn).
Discuss with Jože

**Comment by Fajfa** [comment]
Fixed: dcc541d953d61172797117cddc929d327023fa0a
