### ISSUE TITLE
File page block custom styles break css of component

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1244]
## Version
_2023.3.2_

## Reproduction steps
Set max height and width to component and notice how the second file appears on top of the previous file's name

![Image](https://user-images.githubusercontent.com/85161724/244688480-b88131a1-2ff4-44e0-89d3-d96c91f669e7.gif)

## Expected behaviour
Custom styles shouldn't break component styles. To be discussed

Second Issue: 

Images cover the name of other uploaded images.

**Comment by EmmyMay** [comment]
Plan of Action

Get familiar with the components involved
Reformat where needed
Isolate why the second issue occurs
