### ISSUE TITLE
Corteza studio

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1267]
1. UI/UX for styling (Studio)
2. Clean up UI to allow easier styling
3. Create a simple way to switch to dark mode.
4. Move themes to a central point on the root of repository
5. Add prop (showValue), to color picker. Which will show the color value in text next to the input

**Comment by KinyaElGrande** [comment]
## Installing Dart Sass Documentation

### Development Environment:
To use Corteza, you must install Dart Sass in your development environment. Follow the instructions below based on your operating system:

**Linux**
```shell
# Using Homebrew
brew install sass/sass/sass

# Using Snap
sudo snap install dart-sass

```

**macOS**
```shell
brew install sass/sass/sass
```

**WIndows**
```shell
# Using Chocolatey
choco install sass

# Using Scoop
scoop install sass

```
Alternatively, you can download Dart Sass binaries directly from https://github.com/sass/dart-sass/releases. 

_When using prebuilt binaries, make sure to add Dart Sass to your system's PATH._

### Production Environment
In a production environment, especially when deploying with CI/CD pipelines or Docker, you can ensure that Dart Sass is available using the following methods:

1. **CI/CD Deployment on GitHub Pages**

To install Dart Sass for CI/CD deployment on GitHub Pages, include the following step in your workflow file:

```yaml
- name: Install Dart Sass
  run: sudo snap install dart-sass

```

2. **Docker Deployment on Ubuntu 20.04 with Dart Sass V1.67.0**

If you're using Docker and deploying on Ubuntu 20.04, you can include the following Dockerfile to ensure Dart Sass(V1.67.0) is available:

```Dockerfile
FROM ubuntu:20.04

RUN apt-get -y update \
 && apt-get -y install \
    ca-certificates \
    curl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local

ARG SASS_URL="https://github.com/sass/dart-sass/releases/download/1.67.0/dart-sass-1.67.0-linux-x64.tar.gz"

RUN curl -OL $SASS_URL

# Extract the release (if it's an archive)
RUN tar -xzf dart-sass-1.67.0-linux-x64.tar.gz

# Clean up downloaded files (optional)
RUN rm -rf dart-sass-1.67.0-linux-x64.tar.gz

ENV PATH=$PATH:/usr/local/dart-sass

```

**Comment by petergrlica** [comment]
Please check https://github.com/cortezaproject/corteza/pull/1479 on the `custom.css` override @Fajfa @KinyaElGrande
