### ISSUE TITLE
Nylass improvements

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1270]
Prefilll information for certain components

Email(Composer):
- Prefill data from record values.
https://developer.nylas.com/docs/user-experience/components/composer-component/#custom-callbacks

Mailbox:
- Prefilter data based on record values
https://developer.nylas.com/docs/user-experience/components/mailbox-component/#mailbox-properties

**Comment by katrinDY** [comment]
for today: sync with Jože and stat working on task

**Comment by Fajfa** [comment]
This will wait until Monday

**Comment by katrinDY** [comment]
for today: complete task
