### ISSUE TITLE
Add option to display "Select" fields as Radio group/checkbox group for select fields

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1272]
Add visual options for select field, that shows the options in a different view.

Form checkbox(if multi value), radio buttons(if single value)

- [x] Configurator
- [x] Template cleanup for the Select field where needed
- [x] Radiogroup for Single value
- [x] Checkbox group for Multi value

**Comment by katrinDY** [comment]
for today: sync with Jože before starting to work on this task

**Comment by katrinDY** [comment]
for today: work on the configurator part and edit the issue to add checkboxes with that needs to be done

**Comment by katrinDY** [comment]
for today: complete the 2nd and 3rd checkboxes

**Comment by EmmyMay** [comment]
QC Notes

With this issue we wan to be able to display Select options as either Radio buttons (in the case of non-multi select fields) or as Checkbox groups (in the case of multi Select field)

This has been done by adding an option called Radio group/ Checkbox Group to the Configuration of Select fields.

For Single Types, there is the default option and this new radio group option. The multi type has more options. 

Depending on the option chosen, there is an additional Checkbox provided to address duplicates.  

To test this out, you'll need to ensure the radio groups or checkbox render correctly when editing a record that has a select field with a bunch of options. 

Also to ensure the duplicate checkbox appears when certain select field types are chosen.

**Comment by katrinDY** [comment]
CL added
