### ISSUE TITLE
Radar chart issue with preset filter for last year/quarter/month

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1275]
## Version
_2023.3.2_

## Error
![Image](https://github.com/cortezaproject/corteza/assets/85161724/200e9e72-2e08-46f5-981f-bfe088e4e04b)

## Steps to reproduce
![Image](https://github.com/cortezaproject/corteza/assets/85161724/07d32164-00bf-4502-948e-08116fd30c70)

**Comment by Fajfa** [comment]
Echarts internal issue, no data to display means it throws that error.
Since there is no data to render the chart stays empty
