### ISSUE TITLE
Error in console when trying to add an unconfigured unique value constraint in a module

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1276]
## Version
_2023.3.2_

## Error
![Image](https://user-images.githubusercontent.com/85161724/248808544-1df95a62-2736-4d1f-9f97-b04d7b668f25.png)

## Reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/248808022-ede72b8a-bfba-4113-8b82-1b46ed8c04f0.gif)

**Comment by Fajfa** [comment]
Disable the button if you cannot add it or resolve the error gracefully

**Comment by katrinDY** [comment]
CL added
