### ISSUE TITLE
Unsaved changes error triggered after namespace save

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1283]
## Version
_2023.3.3-rc.1_

## Reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/249164333-7d49cafe-2641-437c-92e4-ad5031a0dec0.gif)

**Comment by Fajfa** [comment]
Fixed: [aa7cdf2](https://github.com/cortezaproject/corteza/commit/aa7cdf28e24263c858ad891b1cf0912596e278da)

**Comment by katrinDY** [comment]
LGTM
