### ISSUE TITLE
DAL: pq: syntax error at or near "MODIFY"

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1287]
## Conclusion
This can also happen if you click on resolve after adding one/multiple fields

## Reproduction steps

![Image](https://user-images.githubusercontent.com/85161724/250584316-30f56320-2a30-4468-9fbb-cad7f5e1d8dd.gif)

**Comment by tjerman** [comment]
Resolved.
@katrinDY do note that the way you've configured it doesn't really make sense so it'll probably cause issues down the line.

You've used `values` for the generic values JSON (the first field uses it), then you've made the second field use that `values` column as an integer -- that won't fly
