### ISSUE TITLE
Fix record list filter operator priority edge case

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1294]
When not equal was being used in combination with multiple conditions, possible wrong operator priority happened.

Example filter: 
![Image](https://github.com/cortezaproject/corteza/assets/15791641/8995ac5c-3a0a-44cf-bae4-795018636ee6)

Produced this query: `(Rating != '☆☆☆☆☆' OR Rating IS NULL AND Rating != '★☆☆☆☆' OR Rating IS NULL)`
Which in turn only returned results that don't have '☆☆☆☆☆' as their value, since there is no () around the two conditions,

The fix turns the query for that filter to: `((Rating != '☆☆☆☆☆' OR Rating IS NULL) AND (Rating != '★☆☆☆☆' OR Rating IS NULL))`

**Comment by katrinDY** [comment]
CL added
