### ISSUE TITLE
Module field label appears underneath the delete button in bulk edit modal

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1306]
## Reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/251476872-84b03a8e-50dd-4e47-9499-6335f4ea6c7d.png)

## Solution
To be discussed

**Comment by kelanik8** [comment]
https://github.com/cortezaproject/corteza/pull/1339/commits/6f6df66d6f8dd28b29d581cbbf5443c4864294d4
