### ISSUE TITLE
Unique value modifiers not visible and persisted after save

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1352]
## Reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/254576809-e1108d79-de42-4b85-ad26-2c3116685392.gif)

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/295defc9a9eadbe2b150d0c9e0c93cf799fd5dd9
