### ISSUE TITLE
Add a reusable processing button component and apply it to appropriate places

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1361]
## Description
Check if one already exists in corteza/vue

Use them in places where the buttons are disabled on click because there is processing.

## Plan of action
Add CButtonSubmit in:
- [x] compose
- [x] admin
- [x] wf
- [x] reporter
- [x] privacy
- [x] fix styles in all webapps

----

Extend CInputConfirm by adding processing after clicking on confirm btn in:
- [x] compose
- [x] admin
- [x] wf
- [x] reporter
- [x] privacy
- [x] fix styles in all webapps

**Comment by katrinDY** [comment]
Tested everywhere and it lgtm. @Fajfa up to you if when this ticket is gonna go to `Docs and CL` column
