### ISSUE TITLE
Investigate compose page memory leak

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1363]

**Comment by kelanik8** [comment]
All states causing memory leaks

- pageLayout
- namespace
- module
- page
- blocks
- undestroyed events
- grid component / page block
- vue-composition-api
- bv-modal
- bv-toast
- echarts
- Record filter
- vuex state
- States with canCreateOwnedRecord, canDeleteModule, canUpdateModule, canCreateRecord, namespaceID, updatedAt, canGrant
