### ISSUE TITLE
Large Module not showing any results in UI list

### ISSUE THREAD

**Issue by nabl13** [cortezaproject/corteza#1364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.4

### Current Behavior

In one of my modules (messages) are more then 40K records (counted in DB), If i try to display a list anywhere in the UI it wont show any results.
If i query the module via API it wors perfectly fine with or without any query.

However if i set a filter in a record list in the UI to filter only messages linked to the specific record of another module whose record page is shown it displays the messages correctly. For example the list of messages which is shown inside employe records filtered only for this employe.
A similar filter (createdBy = ${userID}) does again not show any results. 
the response via UI captured in chrome dev tools looks perfectly fine, except for the fact that it returns empty:
`{
    "response": {
        "filter": {
            "moduleID": "***",
            "namespaceID": "***",
            "query": "(createdBy = ***)",
            "deleted": 0
        },
        "set": []
    }
}`

This behavior was the same in the preceding versions. and via API there is no problem querying records in this module.
I use MySQL as the DB Backend

### Expected Behavior

Records should be shown like queried or the first n records without any filter.

### Steps To Reproduce

1. have a module with many records
2. try to display records in the UI

**Comment by Fajfa** [comment]
Related: https://github.com/cortezaproject/corteza/issues/1368
