### ISSUE TITLE
Invalid username and password combination on signup

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1369]
### Description
Users that want to create an account some times receive the error `invalid username and password combination” “failed to authenticate with password`

Get rid of the handle input on sign up (it is generated automatically). We have duplicated checks on emails as well, we will just make sure that the auto-generated handle will not be duplicated (or at least it will not trigger an error).

**Comment by petergrlica** [comment]
@KinyaElGrande Can you please check the PR?
