### ISSUE TITLE
Add UI/UX hints to performance impacting features

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1381]
Features/configurations that impact performance a lot should have a "performance impact" hint next to them.

- [x] 1. Gather features that impact performance (focus on compose, mainly page blocks and fields)
- [x] 2. Implement reusable component
- [x] 3. Add to relevant places and describe why/how/when it impacts performance.
- [x] 4. Ask Lenny if there any other places to add the ? to
- [ ] 5. Finishing tuches

**Comment by katrinDY** [comment]
Functionality that impacts performance:

- automation buttons
- calendar record source events
- chart pb and drill down option
- iframe url
- field condition for record
- filtering and full page navigation in RL
- report
- twitter feed url
