### ISSUE TITLE
Cannot save report if load datasource namespace is changed

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1384]
## Reproduction steps

![Image](https://user-images.githubusercontent.com/85161724/262390623-a4e308b6-4d60-4e66-826a-9f666dda33ba.gif)

**Comment by Fajfa** [comment]
Fixed: [773beaf](https://github.com/cortezaproject/corteza/commit/773beaf4105deb57f3bfb9204d9013c329a36eed)
