### ISSUE TITLE
Properly handle all navigation (record/page) inside modal flows

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1389]
Some record/page navigation in modals doesn't open the new view in the modal itself:
- Record viewers
- Calendar block click on event
- Geometry block click on event
- Others to be found

We need to keep the modal flow inside the modal itself

**Comment by kelanik8** [comment]
Fixed
- Calender
- Geometry
- Chart -> open record -> add new -> create page doesn't show, only on page resize
- Organizer
- Record
- Record list

**Comment by kelanik8** [comment]
@katrinDY there was no code changes

**Comment by katrinDY** [comment]
Found this:
![5](https://github.com/cortezaproject/corteza/assets/85161724/76b82320-f042-4f20-8826-65c3e5b4551d)
