### ISSUE TITLE
Allow admin to enable end user to add/remove available columns from record lists to create an individual view

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#1402]
Add the possibility to the record list editor to be able to show/hide columns. The end user will have a button with a modal to choose the columns

**Comment by Fajfa** [comment]
0,1. Fix current configure columns saving whole fields instead of just ID's

1. Prevent saving whole field to backend (module.meta.ui.admin.fields) it should only save fieldID
2. Ensure saving to local storage (when not in all records/admin)
3. Show fields from localstorage
