### ISSUE TITLE
Record import ability to resolve record types

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#1409]
Enable mapping of all field types when importing. When a user imports records, they can't map values in the 'record type' or 'user' fields. The user should be able to import a list of records with related data (records or users) when they have the ID's of the records and users they want to link to

**Comment by tjerman** [comment]
At least check it

**Comment by tjerman** [comment]
It already worked; enabled on front-end

![Image](https://github.com/cortezaproject/corteza/assets/12545711/9a148ba7-0ecb-4ad7-810b-2880d889c9c8)

`ref` is some related record, `uu` is some user.

@katrinDY 

```
## Added

### What

support for User and Record fields to be exported/imported on the record list page block.

### Refs

2023.9.x; `https://github.com/cortezaproject/corteza/commit/7fc4ca921`

**Comment by katrinDY** [comment]
All's good. Closing
