### ISSUE TITLE
Filter error for setting in progress bar page blocks

### ISSUE THREAD

**Issue by leenchou** [cortezaproject/corteza#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.4

### Current Behavior

if the filter contains ${recordID} in progress bar block, the ${recordID} will be changed to 0 when it is stored in database. for example set filter like rel_record = ${recordID}, it will be changed to rel_record=0 when it is stored to database. so that I can't Filter out the correct data.

**Comment by Fajfa** [comment]
Thanks for reporting this, fix will be released with 2023.3.6
