### ISSUE TITLE
Error trying to export namespace: module does not exist

### ISSUE THREAD

**Issue by martkaczmarek** [cortezaproject/corteza#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.5

### Current Behavior

When trying to export a namespace (Manage namespaces -> Pick from list -> Export namespace), I'm encountering the following response:

```
{
   "error":{
      "message":"invalid module reference {corteza::compose:module {[347533651178741763] map[347533651178741763:true]} {corteza::compose:namespace {[344241087105269762] map[344241087105269762:true]}} false}: module does not exist"
   }
}
```

344241087105269762 is a valid namespace ID - it's the built-in CRM namespace that I modified over time. No module exists with the id of 347533651178741763, at least not now. I guess it was created and then deleted. However, when I go into modules list in this namespace and hit "Export", the modules list exports without problem. Module with ID 347533651178741763 was not in that list. 

### Expected Behavior

Export tool should ignore non-existing modules during export or have some sort of clean-up after deleting module. 

### Anything else?

When I created a blank test namespace with two modules and deleted one of them, the export succeeded, so that wasn't the case here. There's something wrong with this one particular namespace.

**Comment by martkaczmarek** [comment]
Update: after restoring yesterday's backup of the database, the error message has changed:
```
{
   "error":{
      "message":"parent reference {corteza::compose:page {[347533949125320707] map[347533949125320707:true]} {corteza::compose:namespace {[344241087105269762] map[344241087105269762:true]}} false} not found"
   }
}
```
This error appeared exactly once. After that, every error looks like before (referrencing module, not page)
Note that nothing really should have changed in the database contents since yesterday, we don't yet use the application in production. 

---
After a few tries, the error seems to be pointing at random pages, which are vaguely related to the problematic deleted module.

**Comment by Fajfa** [comment]
Ref: https://forum.cortezaproject.org/t/namespace-export-error/1570/2

**Comment by tjerman** [comment]
I have a fix prepared, will merge after release

**Comment by tjerman** [comment]
```
# Fixed

## What

namespace export erroring out with an invalid reference error whenever we're referring to deleted resources.

## How

by ignoring missing references and exporting/importing regardless of missing references.
This should be expanded and improved upon in a future release.
```

**Comment by katrinDY** [comment]
Thank you for adding the CL

**Comment by martkaczmarek** [comment]
Issue still exists in 2023.9.0: 
`{"error":{"message":"parent reference {corteza::compose:page {[347533966607179779] map[347533966607179779:true]} {corteza::compose:namespace {[344241087105269762] map[344241087105269762:true]}} false} not found"}}`

**Comment by tjerman** [comment]
Hm.. can you try to figure out what resource causes this error? My guess would be a page.
I can take another look if I missed something

**Comment by martkaczmarek** [comment]
I guess it could be some already non-exiatent page or one that got replaced by new one... but shouldn't the application now just ignore this error and export anyway?

**Comment by Anth0rx** [comment]
I took a look at my PostgreSQL database and identified the affected page(s) in `compose_page`:
```sql
SELECT title FROM compose_page WHERE id = {{corteza::compose:page}};
```
I had to delete the respective entries in both `compose_page` and `compose_page_layout` to successfully export the namespace:
```sql
DELETE FROM compose_page WHERE id = {{corteza::compose:page}};
```
Unfortunately, this does not solve the issue when importing the data. I get the following error when navigating to the imported namespace:
```
Could not load record list: cannot search data entry: model 363XXXXXXXXX691 does not exist
```

**Comment by martkaczmarek** [comment]
@tjerman since it still doesn't work, should I create a new issue or will this one be reopened?

**Comment by martkaczmarek** [comment]
Issue still present in 2023.9.1:
`{"error":{"message":"parent reference {corteza::compose:page {[347533966607179779] map[347533966607179779:true]} {corteza::compose:namespace {[344241087105269762] map[344241087105269762:true]}} false} not found"}}`

**Comment by tjerman** [comment]
Ah.. so it turns out the problem is caused by page layouts regarding the deleted page. If you delete those does the problem go away?

**Comment by tjerman** [comment]
All right, fingers crossed the next one does it for good :see_no_evil: `1d5402678` ignores cases for resource translations

**Comment by Anth0rx** [comment]
Unfortunately, the issue still persists for `2023.9.2-rc.1`.

**Comment by tjerman** [comment]
Well then I'll need some help from you. Could you provide a DB dump for me?

**Comment by martkaczmarek** [comment]
> Well then I'll need some help from you. Could you provide a DB dump for me?

I can send you the DB backup from my env by email, if that's okay

**Comment by martkaczmarek** [comment]
`2023.9.2-rc.1` finally works in my case. However, if I try to export namespace, delete it in Corteza and then import it again, it complains with error: _Namespace failed to import: not unique_. The problem exists even if I give it a different name when importing, change the id line in the exported yaml or even hard delete the namespace from database. There should be an option to force importing the namespace as new, with new IDs generated for namespace, modules, pages etc for test environments and such.

**Comment by pesogrone** [comment]
Hi there,
Is this issue still being looked into? I’ve recently encountered the same problem — it occurs during both export and namespace copy operations.

Here’s the error message I’m seeing:

`{"error":{"message":"parent reference {corteza::compose:page {[437026476915687426] map[437026476915687426:true]} {corteza::compose:namespace {[437020422219759618] map[437020422219759618:true]}} false} not found"}}`

I’ve been trying to manually delete the related entries in the database, but the issue keeps coming back. Is there any known workaround in the meantime?

Thanks in advance!
