### ISSUE TITLE
Make compose sidebar respect the current page you're on

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1431]
Currently on admin we always navigate to a specific page. In reality if you're editing a page and click on another, you shouldn't be taken to the builder but you should stay on the edit and open the clicked page instead.

**Comment by kelanik8** [comment]
Cases
- When on the page edit and redirect to a separate page the route should redirect to the edit page of the new page
- When on the page builder and redirect to a separate page the route should redirect to the page builder of the new page
- When on the module view all records page and redirect to a separate page the route should redirect to the new page all records page of the new page
- When on the module edit page and redirect to a separate page the route should redirect to the new page module edit page of the new page

**Comment by katrinDY** [comment]
Issues:

- `When on the module view all records page and redirect to a separate page the route should redirect to the new page all records page of the new page` this doesn't work for me. Can you recheck it, please? *no longer an issue*
- create a page -> I'm redirected to the edit view of the page -> select a page from the sidebar -> I'm redirected to the page builder of the selected page *no longer an issue*
