### ISSUE TITLE
Improve loading UI when importing a namespace

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1442]
## Current behaviour

![Image](https://user-images.githubusercontent.com/85161724/268626509-e55ec14f-e231-4738-a2f3-18d123d42f84.gif)

## Expected behaviour

Perhaps hiding the inputs when the spinner is shown? To be discussed

**Comment by Fajfa** [comment]
Updated: https://github.com/cortezaproject/corteza/commit/c997655b961965ee607907c54fd68ba10686fcbd
