### ISSUE TITLE
Add indication block is used in other layouts when editing it/in block toolbox

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1445]
- [x]  Understand what is meant by "Block Toolbox"
- [x] Understand how the page layout is structured
- [x] Decide if to sync /  sync with @Fajfa 
- [x] Include "ref" property in JS for blocks (meta)
- [x] "ref" meta should be set as soon as a block is used
- [x] decide when to indicate

**Comment by EmmyMay** [comment]
I observed tthat blocks cannot be copied between layouts.
