### ISSUE TITLE
When I try to set up smtp.office365.com email setting, it show 504.5.7.4 unrecognized authentication type.

### ISSUE THREAD

**Issue by eldenjone** [cortezaproject/corteza#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.x

### Current Behavior

![image](https://github.com/cortezaproject/corteza/assets/6011016/e6f95253-5404-4c36-a0ae-ac70d6508b63)

### Expected Behavior

successful config email 

### Steps To Reproduce

config smtp.office365.com

**Comment by eldenjone** [comment]
Any feedback about this issue？ So far I haven't successfully sent an email.

**Comment by eldenjone** [comment]
Hello, is this not support office 365?

**Comment by eldenjone** [comment]
@petergrlica is this issue valid?

**Comment by petergrlica** [comment]
@eldenjone any success with this smtp?
We are using mailgun without any issues.

What are you settings like? Please omit any sensitive info
Do you have `SMTP_TLS_INSECURE` and `SMTP_TLS_SERVER_NAME` set?

**Comment by eldenjone** [comment]
@petergrlica  I used smtp.office365.com and 25 port, and by using a mailbox account and password, this account we can sent mail  successfully in our system, but not work in corteza. it shows 504.5.7.4 unrecognized authentication type when click test button.
