### ISSUE TITLE
Cannot import records

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1471]
*Note: caused by https://github.com/cortezaproject/corteza/commit/399f9a7cc490dc8849ae285568a1e86d9c78703d*
## Reproduction steps

Export a record from Accounts RL -> change the name of the account -> import the record -> UI says importing was successful but the record wasn't imported

**Comment by tjerman** [comment]
Fixed with `532e1ac46`

```
# Fixed

## What

record import not importing anything with no reported errors.

## How

by fixing the file management to correctly report rows and counts.
The issue was caused because the state wasn't reset correctly after performing a _preflight_ to analyse and count records.

## Refs

Monorepo; 2023.3.x -- `532e1ac46`
```
