### ISSUE TITLE
When I try to use the recordID in a contextual security role expression, I do not see the record with the corresponding recordID

### ISSUE THREAD

**Issue by dcharpen** [cortezaproject/corteza#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.7

### Current Behavior

There seems to be some relatively new issue with contextual security roles. This is a new issue and this previously worked fine.

Cannot utilize the recordID field in contextual expressions for security roles

Expressions that do not work:
Anything that involves reading the value of either the recordID or any field under values, like resource.values.SomeField == xyz

Version: 2023.3.7
Seems to be broken on 2023.3.6 as well.

### Steps To Reproduce

1. Create a new security role and select the ‘Contextual role’ option
2. Populate the expression with → has(resource, “recordID”)
3. Verify with a logged in user, non-admin, they can see all records
4. Update the newly created security role with the expression → resource.recordID == 213
— This example uses a recordID of 213 but choose a recordID that exists for some module in your Corteza instance.
5. As a non-admin user, Navigate to whatever module has a record with that particular recordID and verify it is not visible.

### Anything else?

https://forum.cortezaproject.org/t/contextual-security-roles-seemingly-broken/1631

**Comment by tjerman** [comment]
Closing as can't reproduce
