### ISSUE TITLE
Option to select from brand colors for Metrics and Navigation buttons

### ISSUE THREAD

**Issue by bfleming212** [cortezaproject/corteza#1501]
Currently, when setting the color for Metrics or Navigation buttons you have to put in the hex codes, whereas for Progress Bars and Automation buttons you can choose from what we now call the “brand colors” (white, black, primary, secondary, etc.).

It would be faster to allow this same option, i.e. selecting from brand colors, for Metrics and Navigation buttons.

![Screen Shot 2023-11-06 at 2 24 29 PM](https://github.com/cortezaproject/corteza/assets/123066216/65785ad8-e152-444e-b728-daae05fd0dbb)

![Screen Shot 2023-11-06 at 3 58 41 PM](https://github.com/cortezaproject/corteza/assets/123066216/c76eb491-2bbb-4f9a-b99b-bcc227f0c5d2)

**Comment by Fajfa** [comment]
@KinyaElGrande This will be resolved same as #1502
Closing this one, the other one will be used to keep track
