### ISSUE TITLE
Option to select from brand colors in color picker

### ISSUE THREAD

**Issue by bfleming212** [cortezaproject/corteza#1502]
Currently, when setting the color for a custom color scheme for charts you have to put in the hex codes. It would be faster to allow the user to create color schemes by selecting from their brand colors.

![Screen Shot 2023-11-06 at 2 24 07 PM](https://github.com/cortezaproject/corteza/assets/123066216/2b572dd7-35fe-4846-9380-72063ba9000c)

**Comment by Fajfa** [comment]
@KinyaElGrande This will be resolved in the same way as #1501
