### ISSUE TITLE
Workflow prompt not displaying unless page is refreshed

### ISSUE THREAD

**Issue by dcharpen** [cortezaproject/corteza#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.8

### Current Behavior

The prompt, from a workflow, will not display unless the screen/tab is refreshed.

### Expected Behavior

Prompt, from workflow, should be displayed on-screen without a page refresh.

### Steps To Reproduce

1. Create a two step workflow that has an 'On manual' trigger and then immediately has a prompt
2. Put an automation page block on a page layout to test. Connect the automation block to the new workflow from step 1.
3. View the page and click the button. Verify nothing happens.
4. Refresh the page. Verify the prompt is displayed.

<img width="715" alt="user_prompt" src="https://github.com/cortezaproject/corteza/assets/148785313/254144f3-007e-4839-8440-c15788bf0c10">

<img width="741" alt="user_prompt_block" src="https://github.com/cortezaproject/corteza/assets/148785313/5d8f25bf-d7e0-4f95-a422-c57ecd6559e3">

**Comment by Fajfa** [comment]
Hello @dcharpen 
I could not replicate this with the steps provided. Which browser are you using, can you try another one just in case?

**Comment by dcharpen** [comment]
I tried in both Chrome and Edge before submitting. Other users are experiencing the same thing on their computers and browsers.

It didn't happen to you when testing on 2023.3.8? The prompt displayed immediately without a page refresh? Are there any settings or .env variables that would impact this?

**Comment by dcharpen** [comment]
I have confirmed the issue was with Nginx and websocket support not being enabled. There is no issue. Thank you for your quick response. This ticket can be closed.
