### ISSUE TITLE
Schema alterations: wrong ALTER query in MSSQL

### ISSUE THREAD

**Issue by martkaczmarek** [cortezaproject/corteza#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.0

### Current Behavior

In the automatically opened window, Corteza warns about the incompatible attribute type in MSSQL based module table:
![image](https://github.com/cortezaproject/corteza/assets/31852710/bd32f6f7-8fe5-4ac2-8289-e472e5f6ff3e)

Whether I click "Resolve" or "Resolve automatically", the new error appears from the SQL side, but success message is displayed in Corteza: 
![image](https://github.com/cortezaproject/corteza/assets/31852710/7fae1db8-1a8d-497b-8918-70a9decb4e09)

In SQL I can see it's trying to use the following query
`ALTER TABLE "compose_record_Campaigns" MODIFY COLUMN "revision" DECIMAL`

Which is wrong, the query in MSSQL thould read:
`ALTER TABLE "compose_record_Campaigns" ALTER COLUMN "revision" DECIMAL`

Also, after running the proper query and setting column type to DECIMAL, Corteza still asks to change it. 

### Expected Behavior

1. Corteza should use proper ALTER TABLE 'xxx' **ALTER** COLUMN... query
2. Corteza should parse SQL query error response before displaying the green Success-type dialog
3. Corteza should be better at checking whether column already has proper data type

### Environment and versions

```markdown
MSSQL 2019
Corteza 2023.9.0 Docker install
```

**Comment by tjerman** [comment]
The query fixed in `58ea38233`

**Comment by martkaczmarek** [comment]
Resolved in 2023.9.1
