### ISSUE TITLE
Schema alterations: MSSQL columns aren't created after field mapping changed to Column

### ISSUE THREAD

**Issue by martkaczmarek** [cortezaproject/corteza#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.0

### Current Behavior

After changing field mapping from the default JSON to Column:
![image](https://github.com/cortezaproject/corteza/assets/31852710/b7a20135-52cb-40ab-b5f8-9ea1c9546670)
columns aren't automatically created, but from now on Corteza expects them to be there:
![image](https://github.com/cortezaproject/corteza/assets/31852710/2123d358-1b7c-497e-80ce-1ed14924e6d9)

I don't see any ALTRER TABLE query sent to SQL Server. 

### Expected Behavior

Columns should be automatically created in database 

### Environment and versions

```markdown
MSSQL 2019
Corteza 2023.9.0 Docker install
```

**Comment by martkaczmarek** [comment]
Issue still exists in 2023.9.1.
Everything works well if we create a new field and assign it a _Column_ type at the same time:
![image](https://github.com/cortezaproject/corteza/assets/31852710/8aa4351a-1221-4bc8-9a1f-91f290d943f8)
but the schema alterations console doesn't trigger when we change the type from _JSON_ to _Column_ later.

**Comment by tjerman** [comment]
You get a little issues tab in the toolbar; if you click on that do you get anything?

![Image](https://github.com/cortezaproject/corteza/assets/12545711/5d006b5a-b6d0-4173-b3e6-61b4f8e88409)

**Comment by martkaczmarek** [comment]
> You get a little issues tab in the toolbar; if you click on that do you get anything?

If I change the module's field from JSON to Column and click Save, nothing happens and there is a success message:
![image](https://github.com/cortezaproject/corteza/assets/31852710/2ae82e5b-ff9d-4650-b3a5-326054cb5406)
At this point there are no Issues displayed, even if I go back to main menu and come back to Module configuration. 
When I try to insert some test, non-null data into columns I get error message simillar to the one from the original post:

> Could not load record list: mssql: Invalid column name 'Sample3'.

The application doesn't know the columns aren't there right until it tries to read or save data. 
The Issues tab doesn't appear at all, like the schema check isn't triggering.

**Comment by tjerman** [comment]
Should be resolved in the next patch... I forgot to add code to cover codec change alterations... my bad.

```md
# Fixed

## What

changing module field store encoding type breaking the module from storing or presenting any data.

## Refs

2023.9.x monorepo `4520742ad`
```
