### ISSUE TITLE
Can't copy-paste Tabs block

### ISSUE THREAD

**Issue by bfleming212** [cortezaproject/corteza#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

I can copy a Tabs Block ("Block has been successfully copied) but can't paste it ("Not a valid page block")

### Expected Behavior

Copy a Tabs Block and then paste it on any other page.

### Steps To Reproduce

Copy Tabs block using copy block feature.
Paste Tabs Block using ⌘-v

**Comment by Fajfa** [comment]
Closing, couldn't reproduce.
