### ISSUE TITLE
Research Toolbar Issue on iPhones

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#1520]
- [x] Make it possible for other devices to access the web app from the server (not relevant anymore)

- [x] The toolbar on compose is covered by Safari's browser toolbar.

**Comment by katrinDY** [comment]
Using Xcode simulator for iPhone 15Pro Max
- table bottom not visible
- not able to scroll horizontally and vertically (click and hold + scroll with one finger)
- have to double click to open a chart (this is how the emulator works)
![Image](https://github.com/cortezaproject/corteza/assets/85161724/fd2eef7c-5c4d-4cfd-8d38-0cfea6731b48)
