### ISSUE TITLE
Adding new module with record revisions enabled results in unusable module 

### ISSUE THREAD

**Issue by jem-Solytica** [cortezaproject/corteza#1522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

Creating a new module within a Compose namespace results in an infinite loop of the Alterations modal (there's also a network call or two occurring at the same time, with each refresh of the modal) if record revisions are enabled while creating the module. Creating the module with record revisions disabled and enabling later does not result in the revisions table being created in the database or revisions being stored.

### Expected Behavior

Alteration modal appears once and alterations apply successfully to create base module table and record revisions table.

### Steps To Reproduce

1. Create a Namespace "Test001" with handle "test001"
2. Create a module and configure as follows  with handle "kv"
3. Configure the module as follows:
    1. Name: "Test001 KV"
    2. Handle: "kv"
    3. Fields:
        1. "key" / string / required
        2. "value" / string
    4. Data Store - Use primary DB connection
        1. Collection or table name: "compose_{{namespace}}_{{module}}"
        2. Map fields as columns
    5. Unique Values
        1. Add one constraint on field key, ignore case
    6. Record Revisions
        1. Enable and use "compose_{{namespace}}_{{module}}_revisions" as the table name
4. Click Save

### Environment and versions

```markdown
Fresh install of Corteza, fresh database and empty storage

Corteza instance - 2023.9 via docker with the ENVIRONMENT variable set to "dev"
Database - PostgreSQL 15, dsn set via ENV variable
OS - Ubuntu 22.04
Network - Proxied via Cloudflare (tried with Cloudflare dev mode enabled to bypass Cloudflare caching)
Browser - Microsoft Edge (also tested in Chrome and Firefox, caches cleared, normal/private modes, etc.)
```

### Anything else?

First observed when upgrading from 2023.3 (latest) to 2023.9 and then got an error that my module had a pending alteration and was unusable.

Omitting the "Record Revisions" step causes the module to create successfully, but revision functionality is unavailable.

Variants tested:
- Tried static table names (both main table and revisions)
- Tried leaving field mapping as default of JSON
- Tried omitting required value
- Tried omitting unique key constraint
- Tried saving the module with revisions disabled and then enabling later, did not create the expected revisions table

**Comment by jem-Solytica** [comment]
Additional detail--I tried creating a module with all defaults and enabled record revisions. Appeared to work, but the module becomes unusable because of some pending alteration that can never apply successfully.

**Comment by Fajfa** [comment]
Thank you very much for a detailed report, we'll try to address this ASAP

**Comment by tjerman** [comment]
@Fajfa should be fixed from my end (https://github.com/cortezaproject/corteza/commit/7d3c88f0b2f1525407d8cc229649a287ed9b27b3)

**Comment by katrinDY** [comment]
Found this issue:

After you save the module -> resolve the issue in the alteration tab -> try to create a record -> you get the error

![Image](https://github.com/cortezaproject/corteza/assets/85161724/1b0c3c5b-d4f8-404a-be67-d2d3896d154a)

but the record is saved. No issues are present on the module.

**Comment by tjerman** [comment]
Ah.. another problem is that the custom revision model also requires alterations which we (I) didn't take into account. Not entirely sure how we'll show/handle that one though...

**Comment by tjerman** [comment]
```
# Fixed
## What

record revisions not saving after resolving DAL schema alterations involving the corresponding record revision schema.

## How

by properly presenting, processing, and reloading all relevant models

## Refs

2023.9.x monorepo `33821ddd9`
```
