### ISSUE TITLE
Standardize list inputs

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1631]
Create a standardized component that makes it easier to style list inputs, especially the ones with the +Add button.

- [x] Create the reusable component in Vue/Lib

Places with list inputs that need reassessing.

## COMPOSE WEB APP
- [x] Field Conditions in Record Configurator
- [x] Tabs Page Block Configurator
- [x] Modules Edit
- [x] Modules Edit Unique values tab (probable)
- [x] Recordlist Page Block  Filter Presets
- [x] Recordlist Page Block Presort

## Reporter Web App

- [x] Prefilter
- [x] GroupBy
- [x] Aggregate

## Admin Web App

- [x] Auth Client redirect URI
- [x] Settings Custom links

### Those that need to be reworked

- [ ] Number configurator (Threshold for progress bar)
- [ ] Progress Bar (Threshold)

**Comment by EmmyMay** [comment]
I and @Fajfa discussed about extracting the "needs to be reworked" ones to a separate issue

**Comment by EmmyMay** [comment]
Could not find any other places where the wrapper is needed @Fajfa
