### ISSUE TITLE
When I export records I don't get Record Selector values

### ISSUE THREAD

**Issue by lennyhorstink2** [cortezaproject/corteza#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

When I export a list of record in Corteza I get all values except the IDs of Record Selector fields. This limits what I can do with a record export.

When I export, for example, Note records in the CRM I want to be able to see the IDs of the records the notes are linked to. A Note can be linked to modules like a Lead, Account or Opportunity. But in the export I can only see the title, description and system fields for a Note record. I cannot see to which record the link.

### Expected Behavior

I expect a record export to have all the field values of records.

### Steps To Reproduce

1. Go to any record list that shows records of a module with related records.
2. Create an export
3. Now you'll see all fields except the fields of the type "Record Selector".

**Comment by Fajfa** [comment]
Related: https://github.com/cortezaproject/corteza/issues/551

**Comment by Fajfa** [comment]
Enabled in this commit: https://github.com/cortezaproject/corteza/commit/3ed3b1ebb828b78f4ac834acdf7e6a100729dc80
