### ISSUE TITLE
Allow display of blocks based on roles/conditions

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1658]
In several situations, we can be obliged to create several layout just to show/hide a single bloc from a layout to another based on : user role or on a value (contextual role).

To avoid creating several layouts with only small differences, visibility condition or roles management (like in layouts) would help a lot.

**Comment by martkaczmarek** [comment]
I second this. A good way to do this and much more would be to allow any yes/no button in page configuration to be replaced with an expression (maybe in some 'expert mode'?). It's done this way in Power Automate - every switch in object's properties can be dynamically expressed with variables.
