### ISSUE TITLE
Compose : Add new record in a modal

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1659]
In compose, it can be very useful to be able to add new record in a modal just like it's possible to add in modal.

**Comment by Fajfa** [comment]
Can you give more explanation on the desired behavior?
Does this mean the add button would open the record create screen in the modal?

Also note that this can be achieved by clicking on a record and clicking on "Add new"

**Comment by KoamSK** [comment]
Right now (2023.9.2), it is possible to open record in _the same tab_, _a new tab_ or _in a modal._
On the other hand, when clicking on "+ Add" in a record list, the is no options and it always continues _in the same tab_ with a empty record page.
The desired behavior is to be able to show the empty record page _in a modal_, when clicking on "+ Add".
