### ISSUE TITLE
Compose : open record in edit mode

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1660]
It can be interesting to make a record open directly in edit mode. It would make navigation much quicker !

**Comment by Fajfa** [comment]
Can you give more explanation on the desired behavior?
Does this mean when you click on the record it opens in a modal in edit mode?
Would this be configurable in the block configurator(default on click mode view/edit) or would it happen each time you clicked a record and you would choose then?

**Comment by KoamSK** [comment]
Yes when clicking on a record, the record page opens in edit mode directly instead of a view mode (doesn't have to be a modal).
This might be configurable in the block configuration (default on click mode view/edit).

This is very useful because a lot of records are accessed just to be modified (which enhances user experience).
