### ISSUE TITLE
 Set a date back to an empty value in a workflow (bug after update to 2023.9.1)

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1673]
There is a hack that allows emptying a datefield : 
https://forum.cortezaproject.org/t/set-a-date-back-to-an-empty-value-in-a-workflow/1310/8
-In a workflow, define variable called "empty" (type: any) = (an empty field) 
-Set fieldname.value (type:any) = empty
And the fieldname will be empty again.

But since the update to version 2023.9.1, the trick doesn't work anymore and the field "fieldname" is set to a weird date "

Before:
![before (1)](https://github.com/cortezaproject/corteza/assets/105485183/f86b4399-682c-4501-90f5-c3e5a3801d5f)

After the workflow execution :
![after (1)](https://github.com/cortezaproject/corteza/assets/105485183/44349c48-452d-4714-8225-779c8318d8ad)

Any ideas on how to empty a date correctly ?

Please find the module and the workflow here attached
[empty date 2023.9 (1).zip](https://github.com/cortezaproject/corteza/files/14184589/empty.date.2023.9.1.zip)

**Comment by martkaczmarek** [comment]
That is one of many bugs related to handling null values, we need a proper null handling system in Corteza - numbers also can't be set to empty.

**Comment by KoamSK** [comment]
Changing type of empty from "any" to "array" resolved the problem.

**Comment by Fajfa** [comment]
Fixed with: https://github.com/cortezaproject/corteza/issues/1679
