### ISSUE TITLE
Record list does not update after edit

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1678]
Let's consider : 
Parent module with one field : "filterField" (string)
Child module with one field :  "name" (string)

The record of parent module has two blocks : 
- one record block with just filterField 
- one record list block for child module records with a filter : name = '${record.values.filterField}'

Expected behavior : 
When changing and saving filterField --> the record list filter will change

Actual behavior : 
Nothing changes, until the page is reloaded (F5).

![2024-02-09 19-19-00 (online-video-cutter com)](https://github.com/cortezaproject/corteza/assets/105485183/db747377-bafb-49c0-b771-68338e4d6f6e)

The correction of this issue [1672](https://github.com/cortezaproject/corteza/issues/1672) might correct this one as well

**Comment by Fajfa** [comment]
Yup as you pointed out, the #1672 issue is for this exact thing. Closing this one so we can keep it all in one
