### ISSUE TITLE
Empty a date when "Inline value editing" is enabled gives a wrong date

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1679]
When you try to empty a date in a record list with "Inline value editing" enabled it gives a weird date : 01/01/1901 00:53.
When you try to empty a date in edit record page, it works as expected.

https://github.com/cortezaproject/corteza/assets/105485183/074185cb-ceb8-414b-bc3e-345fa1baaf2b

This is probably related to this issue [1673](https://github.com/cortezaproject/corteza/issues/1673)

**Comment by Fajfa** [comment]
Fixed with: https://github.com/cortezaproject/corteza/commit/6fe0b8ae83121d5e4d93ddb6a5b7b1778b8730d9
