### ISSUE TITLE
Close button on WF Prompts

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#1710]
Close button is required on certain wf prompts (record selectors, option selections, confirmations, ...) where users can use to terminate a workflow if no longer needed. 

Reason: Users may accidentally execute certain workflows or will decide not to proceed when prompted for some input. Currently they have to proceed with an input which may/may not execute the rest of the workflow which is not ideal for the user experience.

**Comment by Fajfa** [comment]
Added: https://github.com/cortezaproject/corteza/commit/3708ca9f3285a5aae81b534d40fc71c8647501ea
