### ISSUE TITLE
User selector doesn't allow searching or navigating the list of options

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1714]

**Comment by Fajfa** [comment]
FE issue fixed with: https://github.com/cortezaproject/corteza/commit/01bd594118f306d959ec3493428f80c709f9c9df

**Comment by tjerman** [comment]
Temporary fix with https://github.com/cortezaproject/corteza/commit/566ff41b6b802c60b0bd6dd79d6c4f0f00f1c8d1
We'll need to handle this elsewhere but for now it's ok since it's urgent.
