### ISSUE TITLE
Dropdown menu hidden behind select compose record prompt

### ISSUE THREAD

**Issue by rm5170** [cortezaproject/corteza#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.4

### Current Behavior

Drop down menu is hidden behind the prompt window and is effectively unusable.

![Select record dropdown issue](https://github.com/cortezaproject/corteza/assets/161966486/ff9cf04b-31b6-4065-a12b-419f8beb88e2)

### Expected Behavior

Drop down menu is shown on top of prompt so all data is visible.

### Environment and versions

```markdown
Tested on latest Firefox and Chrome on Windows
```

**Comment by Fajfa** [comment]
Thanks for reporting this, 2023.9.4 will be updated with this fix today https://github.com/cortezaproject/corteza/commit/27e142c1a64aab374c04ae8e26c6a49326c656fd
