### ISSUE TITLE
Cannot add record in duplicate CRM ns

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1716]
## Issue on 2023.9.x and 2024.3.x

![Image](https://github.com/cortezaproject/corteza/assets/85161724/5aaffcbe-d4e2-4000-98c5-344657453ad8)

**Comment by Fajfa** [comment]
Issue is with exporting namespaces, some blocks are included on the layout and not on the page.blocks
FE fallback also wasn't there (except for builder), adding that

**Comment by Fajfa** [comment]
Todo, remove required slug from clone and import endpoint
