### ISSUE TITLE
Processing in save btn stuck when user tries to clone a ns

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1718]
## Issue on 2023.9.x

![Image](https://github.com/cortezaproject/corteza/assets/85161724/c41cccf3-0406-4158-9c9c-4c37b4c87c89)

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/55a827a2cbd908f5d5bb573a85d145dfba7fa7f1

**Comment by katrinDY** [comment]
Should there be a success message after ns is cloned?
