### ISSUE TITLE
When I prompt for a record in workflows, it no longer returns the entire record (Missing record values)

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.4

### Current Behavior

In workflows prompts for a compose record, the value returns does not return the entire record where I can access field values.

ie: record.values.XXXX is no longer available. 

ex return:
```
{
  "record": "{\"recordID\":\"379550856904835073\",\"moduleID\":\"0\",\"namespaceID\":\"0\",\"ownedBy\":\"0\",\"createdAt\":\"0001-01-01T00:00:00Z\",\"createdBy\":\"0\"}"
}
```

Notice that the values are missing here. This breaks subsequent steps that expects values from this selected record.

### Environment and versions

```markdown
Observed on 2023.9.4.
```

**Comment by tjerman** [comment]
Should be resolved with `772d03e91`

@katrinDY 

```
## Fixed

### What

prompt submissions always being treated as `Untyped` by running a type resolution step before applying to the scope.

### Refs

2023.9 `772d03e91`

**Comment by tjerman** [comment]
https://github.com/cortezaproject/corteza/commit/772d03e91

**Comment by katrinDY** [comment]
All's good. Closing
