### ISSUE TITLE
Compose - Add support for tables in rich text editor

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1753]
It would very helpful to add support for tables in rich text editor in corteza compose

Action List (By EmmyMay)

- [x] Update toolbar with table option

**Comment by Fajfa** [comment]
@KoamSK 
Could you elaborate, as much details as possible is always helpful.

What do you expect from this, how would you configure it, who can use it and so on

**Comment by KoamSK** [comment]
Sure.

The use cases of tables in a rich text are virtually unlimited, but here are the main two:
- Data representation and comparison
- Layout and text alignment

Practical exemple : 
- a conclusion text field where a user need to represent his data in a text field.

I noticed the project uses tiptap for rich text input, so I think the most straightforward implementation is the one used in the official exemples : https://v1.tiptap.dev/tables
- Vue file of the example: https://github.com/ueberdosis/tiptap/blob/v1/examples/Components/Routes/Tables/index.vue
- Documentation: https://tiptap.dev/docs/editor/api/nodes/table

Please don't hesitate if you need more details on anything. I'm here to help !
