### ISSUE TITLE
Smtp Password is no longer in the Admin Setting Gui

### ISSUE THREAD

**Issue by sebastian-fahrenkrog** [cortezaproject/corteza#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.1

### Current Behavior

The email admin gui under /admin/system/email does no longer show the password field. 

I think this commit removed the password field from the vue viewscript: 
https://github.com/cortezaproject/corteza/commit/5f88e4cb8802d3748214d834dc30ecfdc2b9c36e

All other fields are shown. 

<img width="1184" alt="Bildschirmfoto 2024-04-14 um 19 44 59" src="https://github.com/cortezaproject/corteza/assets/50595160/8b82e3ab-ca3c-4aa4-82a2-61ac7cede2e7">

### Expected Behavior

Password field should be shown / included. 

### Environment and versions

```markdown
2023.9.1
```

**Comment by Fajfa** [comment]
Cant believe we haven't noticed this.. thanks. Will address asap.
I believe SMTP password is still accessible through the .env

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/96a7fd61d4296aca9ade1a1a3dc62acd17b57c17
