### ISSUE TITLE
When I try opening charts drill down records in a page record list block, UserIDs are not used for filtering

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#1767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.5

### Current Behavior

When chart drill down is configured to use a page block instead of a model, the records aren't filtered based on the chart filter if the chart filter uses userIDs/recordIDs (such as `${userID}` , `${ownerID}`).

But this works perfectly when viewing chart drill down records in a modal.

See the following example when using page block:
![chrome-capture-2024-3-17](https://github.com/cortezaproject/corteza/assets/70228240/f7bea77c-380f-4423-bcd4-062b994a25f8)

When inspected the api request, it shows that the userID is used in its literal format in the payload.
<img width="995" alt="Screenshot 2024-04-17 at 11 49 41" src="https://github.com/cortezaproject/corteza/assets/70228240/cc1ca74b-cb60-4b23-a2fc-ddbcde4fd635">

This works perfectly when viewed in a model OR if the chart filter doesn't include IDs as variables
![chrome-capture-2024-3-17 (1)](https://github.com/cortezaproject/corteza/assets/70228240/92227bf0-fc63-449b-a2fa-0beddcc81cfe)

And here's the request payloa
<img width="978" alt="Screenshot 2024-04-17 at 11 50 33" src="https://github.com/cortezaproject/corteza/assets/70228240/b557624f-8f3c-40f5-ad03-f7c613d940b5">
d:

### Steps To Reproduce

1 Create a chart that uses a filter having a ID variable. Ex: `createdBy = '${userID}'`

**Comment by Fajfa** [comment]
Fixed: 8d2ccea51ea74c56e5187f1aa4a0a944407a32ff
