### ISSUE TITLE
Unable to Add Data to Corteza Platform

### ISSUE THREAD

**Issue by joelket23** [cortezaproject/corteza#1771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3

### Current Behavior

I'm unsure why the 'Add' button isn't appearing here to enable data addition into the CRM. only export button available
<img width="500" alt="image" src="https://github.com/cortezaproject/corteza/assets/82398173/f9ac1a82-fbe3-4f8f-83ef-6825075638f9">

### Expected Behavior

There should be an 'Add Data' button available, as indicated by the tutorials

### Steps To Reproduce

1. Install as per your YouTube view
2. System Mac arm M1

### Environment and versions

```markdown
########################################################################################################################
# docker-compose supports environment variable interpolation/substitution in compose configuration file
# (more info: https://docs.docker.com/compose/environment-variables)

########################################################################################################################
# General settings
DOMAIN=localhost:18080
VERSION=2023.3
LOG_DEBUG=true
LOG_LEVEL=debug

########################################################################################################################
# Database connection
DB_DSN=postgres://corteza:corteza@db:5432/corteza?sslmode=disable

########################################################################################################################
# Server settings

# Running all-in-one and serving web applications directly from server container
HTTP_WEBAPP_ENABLED=true

# Disabled, we do not need detailed persistent logging of actions in local env
ACTIONLOG_ENABLED=false

########################################################################################################################
# SMTP (mail sending) settings

# Point this to your local or external SMTP server if you want to send emails.
# In most cases, Corteza can detect that SMTP is disabled and skips over sending emails without an error
#SMTP_HOST=smtp-server.example.tld:587
#SMTP_USER=postmaster@smtp-server.example.tld
#SMTP_PASS=this-is-your-smtp-password
#SMTP_FROM='"Demo" <info@your-demo.example.tld>'
```

**Comment by Fajfa** [comment]
You either dont have the permissions to add the record or no record page exists.
I suggest the [forum ](https://forum.cortezaproject.org/)for such configuration questions.

**Comment by joelket23** [comment]
I have created a new local setup for exploring Corteza, so I don't anticipate any permission issues since the first signup is considered an admin. @Fajfa

**Comment by Fajfa** [comment]
Closing in favor of the forum since this seems to be a configuration issue
