### ISSUE TITLE
When I try to use a workflow function to lookup the first created record in a module, it looks up the last created, and vice versa.

### ISSUE THREAD

**Issue by svailsa** [cortezaproject/corteza#1789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.4

### Current Behavior

When I try to use a workflow function to lookup the first created record in a module, it looks up the last created. When I try to use a workflow function to lookup the last created record in a module, it looks up the first created.

### Expected Behavior

When I use a workflow function to look up the first created record in a module, it should look up the first created record. When I use a workflow function to look up the last created record in a module, it should look up the last created record. 

### Steps To Reproduce

1. In 2023.9.4
2. Create a workflow with a beforeCreate or beforeUpdate trigger, then try and find the first created or the last created record in another module (using a workflow function) 
3. It returns the opposite of what you expect

**Comment by Fajfa** [comment]
Fix: https://github.com/cortezaproject/corteza/commit/7b29b80163fa523c677fc29de3c523f47bcaadcd
