### ISSUE TITLE
Quick way to add records from record selector fields

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1795]
https://forum.cortezaproject.org/t/add-shortcut-to-add-record-on-record-selector-field-type/2068/4

**Comment by jacmatias** [comment]
Is it a good idea for it to be a simple 'plus' icon on the field?

Something like the picture :)

I've thought about it, and maybe it would be cool if we could choose the event "on-click" - open the Record Creation page in a Modal form, or in a new page/same page;

<img width="437" alt="Screenshot 2024-05-23 at 02 03 09" src="https://github.com/cortezaproject/corteza/assets/30475536/df45562b-0282-4620-b330-5c93e880f068">
