### ISSUE TITLE
When I try to open a filter list on a record list having only the filter enabled, the list gets hidden behind the left navigation menu

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#1799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.6

### Current Behavior

<img width="1178" alt="Screenshot 2024-05-22 at 11 36 43" src="https://github.com/cortezaproject/corteza/assets/70228240/47c9fb49-35e9-41a8-860b-96f4f8abaf56">

### Steps To Reproduce

Create a new record list with a filter,
remove add record, import, export buttons so the filter comes to the leftmost section of the record list block

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/719b4215de27bc830857dff16e61911148a28d64
