### ISSUE TITLE
Default language is always en

### ISSUE THREAD

**Issue by Tobias-08** [cortezaproject/corteza#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7

### Current Behavior

Even if there is only one configured language (that is not `en`, e. g. `LOCALE_LANGUAGES: "de"`) the default language for a user is always `en`. This is the case for all UI parts (one, compose, admin, ...). Only auth/profile picks `de` correctly.
On startup in the profile "German" is correctly selected as preferred language, but `i18next`-cookie is `en` on startup. If the profile is saved again with "German" selected (even it was selected before) then `i18next`-cookie gets correct `de` value and language works as expected in the other UI parts.

### Expected Behavior

Language is set correctly from the beginning (without saving the profile again).

### Environment and versions

```markdown
Edge 126
```

**Comment by davidkornel** [comment]
I experience the same issue on Chrome Version 127.0.6533.88.
