### ISSUE TITLE
Custom OIDC providers not available on login

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1851]
Check if custom OIDC providers work properly.

**Comment by Fajfa** [comment]
Fix: https://github.com/cortezaproject/corteza/commit/1b4b349385a0e648aeacc685b53544fcdb2c5bad

**Comment by katrinDY** [comment]
I'm not able to see my custom OIDC provider on the login page. Maybe it's because it might filter out improperly configured ones. Someone from BE should check it out

**Comment by KinyaElGrande** [comment]
I have checked and retested a couple of times  with  version `2023.9.8-rc.1` and my custom OIDC provider `OIDC-Customy` is available on the Login page.
However, when configuring a custom OIDC provider,  please make sure that the following values are present and valid : `OIDC Issuer URL`, `Client Key`, and `Secret`.

#### Login screen screenshot with Customy OIDC provider 
<img width="801" alt="Screenshot 2024-08-26 at 13 15 06" src="https://github.com/user-attachments/assets/5de5e48f-a40e-4837-bdfc-2a62aa066486">
