### ISSUE TITLE
You need to Close the transpiler when done

### ISSUE THREAD

**Issue by bep** [cortezaproject/corteza#1856]
https://github.com/cortezaproject/corteza/blob/7c177080ab7ffb0f390adb720ad7df2fb81f1043/server/pkg/sass/processor.go#L181

Maybe I'm overlooking something, but open an issue just in case.

Creating a new transpiler spins up a new Dart VM, so not very light weight. The transpiler is thread safe, so ideally you want to start one instance on application startup, use that for everything, then close it on application shutdown.

**Comment by KinyaElGrande** [comment]
Thank you @bep for pointing this out and for providing an explanation on the why.

I've assigned this issue to myself, and we will be working on fixing it.

**Comment by bep** [comment]
> one instance on application startup, use that for everything, then close it on application shutdown.

Note that the `Close` becomes less of an issue if you have _one instance_, as the child process will die when the main application exits.
