### ISSUE TITLE
Map Block don't Work

### ISSUE THREAD

**Issue by alrikvidal** [cortezaproject/corteza#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7

### Current Behavior

Hello,

When I add a "Map" block, the "Markers" do not appear. If I switch to version 2023.9.6, I don't have any issues as long as I only have one "Marker".
Otherwise, the Map disappears.

### Steps To Reproduce

Docker Compose

**Comment by Fajfa** [comment]
Hey thanks for reporting, a typo caused this, will patch 2023.9.7 with it.

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/2a5f7e94eca852b846846f9330452ef5a5e1be51

**Comment by alrikvidal** [comment]
I do docker compose down, docker system prune -a and pull but the problem is the same :)

![map](https://github.com/user-attachments/assets/1f0c7f58-23a3-4c0a-a4b3-f21769476e20)
![image](https://github.com/user-attachments/assets/0ff97eaf-d46d-4f93-9529-df296b9e4328)

**Comment by Fajfa** [comment]
Well it wasn't released yet so thats the reason.
You need to keep an eye on here to see when the image tag was updated https://hub.docker.com/r/cortezaproject/corteza/tags
