### ISSUE TITLE
When I try to filter a record list on a number field, there is no place in the filter dialog to enter the desired number.

### ISSUE THREAD

**Issue by cmrusna97** [cortezaproject/corteza#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7

### Current Behavior

I am attempting to filter a Record List on a number field, but the filter dialog for that column does not have a place to enter the number.  See image below.

![image](https://github.com/user-attachments/assets/5cb853aa-c67c-401e-a072-d104e2a8496a)

### Expected Behavior

A field for entering the number to be filtered on should appear in the dialog box along with the field and comparison selection boxes.

### Steps To Reproduce

1.  In Corteza version 2023.9.7
2. Create a module with one or more number fields
3. Create a record list for the module including at least one of  the number fields.
4. Attempt to filter the list using the filter icon in the column header.
![image](https://github.com/user-attachments/assets/bcb2fa5d-c59b-4063-b5ca-e0d4fe51528d)

### Environment and versions

```markdown
OS - Ubuntu LTS 22.04
Browser - Google Chrome 126.0.6478.185 (Official Build) (64-bit)
```

**Comment by Fajfa** [comment]
Hey thanks for reporting this, not sure when this broke but it has been fixed: https://github.com/cortezaproject/corteza/commit/d619a4273e513548f31db23bad895ef8c6eb7725

2023.9.7 version has been updated with the fix so you can pull your container to update it.
