### ISSUE TITLE
Multiple values are ignored in charts. Only the first value is counted.

### ISSUE THREAD

**Issue by lennyhorstink2** [cortezaproject/corteza#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7

### Current Behavior

This is an issue a customer reported and it's a regression because it was working correctly in at least 2022.3.1.

When I have records with multi-values and want to show those values in a chart, only the first value is added to the "count".

![image](https://github.com/user-attachments/assets/c9221a4e-a1fc-4361-ba7d-8357a5858707)

![image](https://github.com/user-attachments/assets/c51b9747-9a82-4fa0-84f3-91d68cfe486f)

### Expected Behavior

It should count each value. So, in the screenshot above "energy" should be 2 and "electronics" should be 2 as well.

![image](https://github.com/user-attachments/assets/97b67d92-4f5b-4ff4-930a-9f52a5d72ac2)

![image](https://github.com/user-attachments/assets/91e88f22-2020-435d-8a43-edbc47f9ad8d)

These are screenshot of 2022.3.1, where the counting is done correctly.

### Steps To Reproduce

1. Go to QC. You can see the account demo data in compose/ns/crm/pages/361869359460057090
2. Go to the chart: compose/ns/crm/admin/charts/400987354007797761/edit and there you can see the wrong counting of the values in the industry field.

**Comment by tjerman** [comment]
@katrinDY branch is `2023.9.x-fix-chart-mv-keys`
Should be fine; I've tested with all _officially supported_ databases
