### ISSUE TITLE
"Default field value" does not appear for new "text input" and "number imput" fields

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1884]
The "Default field value" input does not appear when the "Default value" checkbox is checked for "text input" and "number input". However, it displays as expected for "Datetime", "checkbox", and "record selector" fields.

If a "Default field value" was defined in previous versions, the input displays correctly.

![image](https://github.com/user-attachments/assets/3f910b95-cab0-4158-9f1b-dc4e1065e41d)

Version : 2023.9.7

**Comment by Fajfa** [comment]
On the latest version, I can see it normally for both number and text input.
Try updating the version again, there were some fixes added to the 2023.9.7 version after the initial release.

**Comment by KoamSK** [comment]
I can confirm that the problem was resolved by pulling the images again.
