### ISSUE TITLE
Empty fields disabled in edit mode - record list block with Inline record editor

### ISSUE THREAD

**Issue by KoamSK** [cortezaproject/corteza#1885]
In edit mode, the record list block (with "Inline record editor" set to YES) allows editing of fields with non-empty values (e.g., name1), but fields with empty values cannot be edited and are disabled.

However, when accessing the record page of the field module, editing the field is possible.

![Inline edit null](https://github.com/user-attachments/assets/5a31a70d-b5f1-4bbd-b5c7-5d9ae3756009)

version : 2023.9.7

**Comment by Fajfa** [comment]
Cant seem to replicate this, double check you have the latest 2023.9.7 version, please.
Otherwise could be due to permissions but I'm not sure.

**Comment by KoamSK** [comment]
I can confirm that the problem was resolved by pulling the 2023.9.7  image again.
**Old :** 
![old](https://github.com/user-attachments/assets/3de43e85-6234-4bff-a036-3e57ce1780b3)

**New:** 
![new](https://github.com/user-attachments/assets/8c58071a-2c63-4b17-bc78-82e16ccb1e33)
