### ISSUE TITLE
 Authentication failed and white screen after login 

### ISSUE THREAD

**Issue by aj2215singh** [cortezaproject/corteza#1897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.1

### Current Behavior

Hi everyone,

I’m facing an issue where I get a white screen after logging into Corteza
I’m using the Dockerfile from the Corteza GitHub repository for version 2023.9.1 ([corteza/Dockerfile at 2023.9.x · cortezaproject/corteza · GitHub](https://github.com/cortezaproject/corteza/blob/2023.9.x/Dockerfile))).

The same setup works perfectly on localhost. However, when I deploy it with the domain, I encounter a white screen after logging in. Sometimes, it also redirects back to the login page.

also try with docker-compose getting same issue when i deploy with domain

I'm deploying Corteza on a custom domain (https://corteza-staging.remedoapp.com/), but I'm unable to log in. Upon further debugging, I found that the /default-client API is being called over HTTP, which causes the browser to block the request as the domain is on HTTPS. Can you help me understand why this is happening and how to resolve it?

Domain: https://corteza-staging.remedoapp.com/
curl of API failing
curl 'http://corteza-staging.remedoapp.com/auth/oauth2/default-client' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer;' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-raw 'code=YJGYOWEZZJATNZMXMY0ZNZI5LTLINZGTZTY4ZJE2NTNKMZLM&scope=profile+api&redirect_uri=https%3A%2F%2Fcorteza-staging.remedoapp.com%2Fauth%2Fcallback'

### Environment and versions

```markdown
Here are the environment variables I’ve configured:

VERSION → 2023.9.1
ENV STORAGE_PATH “/data”
ENV CORREDOR_ADDR “corredor:80”
ENV HTTP_ADDR “0.0.0.0:80”
ENV HTTP_WEBAPP_ENABLED “true”
ENV HTTP_WEBAPP_BASE_DIR “/corteza/webapp”
ENV PATH “/opt/dart-sass:/corteza/bin:${PATH}”
ENV DB_DSN “postgres://cortezxxxxa:Cortezaxxx@si-db-sxxtg.cozyzzzbi2ia9gb.ap-south-1.rds.amazonaws.com:5432/corteza?sslmode=disable”
ENV DOMAIN corteza-staging.remedoapp.com
```

### Anything else?

https://forum.cortezaproject.org/t/white-screen-after-login/2302

![image](https://github.com/user-attachments/assets/3a9ada02-36f2-4120-b1d5-084542c129ca)

**Comment by Lx** [comment]
It's happening because if you don't set `HTTP_SSL_TERMINATED=true`, Corteza assumes it should be served over HTTP.

Adding `HTTP_SSL_TERMINATED=true` to your environment is likely to resolve your issue.
