### ISSUE TITLE
The filters do not appear on the blocks

### ISSUE THREAD

**Issue by alrikvidal** [cortezaproject/corteza#1899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7

### Current Behavior

Hello,

On the blocks with records, when I enable the filtering option for my users, no option to filter the records appears

![image](https://github.com/user-attachments/assets/6c43e59d-267b-468c-990c-e8732d7411b4)
![image](https://github.com/user-attachments/assets/5c1e5e68-8193-49e6-a7e7-1606c4c10982)

**Comment by Fajfa** [comment]
Im guessing its due to some of your configuration changes. If you have customCSS or any other custom settings, i suggest you look at that. 

Tested this and it is fine on both versions.

**Comment by alrikvidal** [comment]
i don't have custom CSS ...
:( 

![image](https://github.com/user-attachments/assets/b8a3bebf-8e77-40d2-9c5c-fd02588601c7)

**Comment by Fajfa** [comment]
It looks to me like the header of the table is a different color so something must have changed. Maybe just the variables?
The filter is located next to the sort button, try clicking there.

![image](https://github.com/user-attachments/assets/67b493d2-d9a1-4933-9d19-b3081bc676ec)
