### ISSUE TITLE
When I add a second metric in the Chart Builder, the builder stops working.

### ISSUE THREAD

**Issue by lennyhorstink2** [cortezaproject/corteza#1912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.7 and 2023.9.8

### Current Behavior

When I try to add a second metric to the chart the builder stops working.

![image](https://github.com/user-attachments/assets/1209b805-7578-436e-87af-ab12650ca9f5)

### Expected Behavior

I must be able to add multiple metrics to create a chart like in the screenshot below. It is working in 2023.9.6 (checked this), but it stopped working in 2023.9.7 and it's also failing in 2023.9.8.

![image](https://github.com/user-attachments/assets/35156258-c953-48ee-a620-57d9cfb78c9f)

### Steps To Reproduce

1. Create a new generic chart in any namespace
2. Select a module
3. Add the dimension
4. Add the data for the first metric. The preview of chart will show on the right.
5. Click on "+ Add metric" and it stops working. The second metric block is not added.

### Anything else?

This is a regression and we have a customer who needs this working

**Comment by Fajfa** [comment]
https://github.com/cortezaproject/corteza/commit/cd6bf89e26b38e2b6dfa37975cf246062fe5cc11
