### ISSUE TITLE
Record lists in record pages cannot have filters on multiple record list fields

### ISSUE THREAD

**Issue by lennyhorstink2** [cortezaproject/corteza#1913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.8

### Current Behavior

When you create a record list on a record page the filter for the "parent field" is automatically added, even if the "parent field" select is empty. It's this field:

![image](https://github.com/user-attachments/assets/91965208-ada3-4990-b23c-eccdd677b6f9)

You can see that the pre-filter is also added in the traditional way, with "AccountId = ${recordID}".

Now, when you look at the request in the network tab you can see that the pre-filter is as followed:

![image](https://github.com/user-attachments/assets/43b32dbc-a9dd-42d4-9cc5-40bebb71827b)

The query has 2 times the AcccountId filter. 1 time because of the prefilter (added at the start of the query) and the other time because of the selected parent field: "query=(AccountId = 362746800681058306) AND (AccountId = 362746800681058306)".

While the filter above will function, we have a customer that needs a filter that queries to 2 parent fields with an OR. Let's say we have AccountId and ParentAccountId and the pre-filter is: "AccountId = ${recordID} OR ParentAccountId = ${recordID}". In this case the query in the GET is "query=(AccountId = 362746800681058306 OR ParentAccountId = 362746800681058306) AND (AccountId = 362746800681058306)". Because the last bit, the "AND (AccountId = 362746800681058306)", is added automatically, the result of the query will only be records where the AccountId = 362746800681058306. Records were only the ParentAccount = 362746800681058306 will not be returned.who

### Expected Behavior

If the "parent field" selector is empty (like in the screenshot below) the automatic filter should not be added. It should, in that case, only add to the query what is written in the pre-filter text area. Like this we can make more complex filters like explained above.

![image](https://github.com/user-attachments/assets/80ff7c5c-a85c-4919-9372-9380aca9db6b)

### Steps To Reproduce

1. Go to qc
2. Enter the route compose/ns/crm/pages/361869359459991554/record/362746800681058306
3. Open the network tab
4. Reorder the record list by clicking on an arrow next to any column name. This will load a new "GET" request.
5. Now you can see the filter. Because the "parent field" select is empty, the query should be just "query=(AccountId = 362746800681058306)", but it is "query=(AccountId = 362746800681058306) AND (AccountId = 362746800681058306)".

**Comment by Fajfa** [comment]
https://github.com/cortezaproject/corteza/commit/d6aa8ef93584d1de522cff20301d7c8c1916cd8b
