### ISSUE TITLE
Rename Precision to Scale to correctly describe what it does.

### ISSUE THREAD

**Issue by alrikvidal** [cortezaproject/corteza#2001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.8

### Current Behavior

Hello

In a module, when creating a "Numeric" type record and selecting the "Precision," the field created in the database will be limited in the number of characters to the value of the precision.

Example: If I set the "Precision" to 3, the field create in the database will be "Numeric(3)," whereas "Precision" is supposed to represent the number of digits after the decimal point.

**Comment by Fajfa** [comment]
I just tested this and cannot replicate it. What is your DB?

**Comment by alrikvidal** [comment]
Postgresql 15

Cordialement,


***@***.***<https://www.pceservices.com/>
Alrik VIDAL
Directeur des systèmes d’information
Å 07 62 00 43 05
PCE Services – PCE Mobile – Qonexio
175 rue de la Maladière - 42120 PARIGNY
www.pceservices.com<http://www.pceservices.com/> – 04 81 17 10 00









De : Jože Fortun ***@***.***>
Envoyé : jeudi 3 octobre 2024 14:26
À : cortezaproject/corteza ***@***.***>
Cc : Alrik VIDAL ***@***.***>; Author ***@***.***>
Objet : [EXTERNE] Re: [cortezaproject/corteza] Creation of 'Numeric' fields. (Issue #2001)

ATTENTION: Cet e-mail provient d'une personne externe à votre organisation. Ne cliquez pas sur les liens ou n'ouvrez pas sur les pièces jointes si vous ne connaissez pas l'expéditeur et que vous n'êtes pas sûr que le contenu est sûr.

I just tested this and cannot replicate it. What is your DB?

**Comment by Fajfa** [comment]
Im using MySQL so it might be a Postgres thing. Related https://github.com/cortezaproject/corteza/issues/595

**Comment by Fajfa** [comment]
I will rename it to scale since that's what it does, (explanation will be in tooltip)
9f7f2b8b6c6329f5d76a3bd54d5e8a2ec615e4d4
