### ISSUE TITLE
The id of the namespace is declared twice in the html

### ISSUE THREAD

**Issue by lennyhorstink2** [cortezaproject/corteza#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2024.9.0

### Current Behavior

Namespaces have an ID, which is similar to the short name of the namespace. This ID is used in the CSS to target elements in a single namespace. It allows us to, for example, set a different background.

But, the same ID appears twice in a single namespace's HTML. This is not valid HTML (there can only be 1 ID) and it causes the background to be placed twice (one partly over the other one).

![image](https://github.com/user-attachments/assets/b229e7fa-bd4a-495b-a868-e47e98430538)

![image](https://github.com/user-attachments/assets/352f4d36-4eea-4e7c-9301-bdb4259c3a15)

### Expected Behavior

The second ```id = "clean_water_3c5z5"```should be removed.

### Steps To Reproduce

Inspect the HTML and you'll find 2 ID's in a single namespace.

**Comment by Fajfa** [comment]
https://github.com/cortezaproject/corteza/commit/26270f215f02622a167deea8c4d0b2af18192757
