### ISSUE TITLE
Correct one of the identical sub-expressions on both sides of operator "||"

### ISSUE THREAD

**Issue by McLaynV** [cortezaproject/corteza#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2024.9.x branch

### Current Behavior

In [`client/web/compose/src/components/PageBlocks/GeometryConfigurator/Configurator.vue` line 205](https://github.com/cortezaproject/corteza/blob/2024.9.x/client%2Fweb%2Fcompose%2Fsrc%2Fcomponents%2FPageBlocks%2FGeometryConfigurator%2FConfigurator.vue#L205) there is 
```js
const bounds = this.bounds || this.bounds
```
It seems not intentional. 

@kelanik8 

### Expected Behavior

Correct one of the identical sub-expressions on both sides of operator "||"

**Comment by Fajfa** [comment]
Thanks, fixed https://github.com/cortezaproject/corteza/commit/07cfb1552b680f7fb929a30ce29f3ce199596272
