### ISSUE TITLE
Duplicate definition of saveColor in CInputColorPicker

### ISSUE THREAD

**Issue by McLaynV** [cortezaproject/corteza#2029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2024.9.x branch

### Current Behavior

In `lib/vue/src/components/input/CInputColorPicker.vue` the function `saveColor` is defined twice: 
```js
    saveColor () {
      this.$emit('input', this.currentColor)
      this.closeMenu()
    },

    toggleMenu () {
...
    },

    saveColor () {
      this.$emit('input', this.currentColor || this.value)
      this.closeMenu()
    },
```

### Expected Behavior

Only one definition of the function

### Anything else?

@KinyaElGrande @Fajfa

**Comment by KinyaElGrande** [comment]
@McLaynV  That's a great catch!
Thank you for reporting this, I'm gonna add a fix for this.

**Comment by Fajfa** [comment]
Fixed https://github.com/cortezaproject/corteza/commit/a07fd70d0b86a09ddb55decfd6323d246834d75f
