### ISSUE TITLE
Search doesn't work on Record Selector Prompts

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#2032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.9-rc.4

### Current Behavior

Search doesn't filter the list of available selections (records) from the list.

![chrome-capture-2024-11-20](https://github.com/user-attachments/assets/2e76e0a7-b2df-4782-8b06-945124665196)

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/2f3358e6ea2c59c8cda40a9ad2d0e3673421e1fc
