### ISSUE TITLE
Workflow gateway default path names are not properly shown

### ISSUE THREAD

**Issue by chandimaj1** [cortezaproject/corteza#2034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1995" alt="Screenshot 2024-11-20 at 15 17 23" src="https://github.com/user-attachments/assets/c2b7f916-761f-43a0-938b-182108decd06">

**Comment by Fajfa** [comment]
Fixed: https://github.com/cortezaproject/corteza/commit/233aa9e5af7d66d4e595b501448c66083b606d7c
