### ISSUE TITLE
Prefilter events in map element not working properly 

### ISSUE THREAD

**Issue by kindiann** [cortezaproject/corteza#2036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

When setting Prefilter events on a map element, (in this case parentmapobject='${recordID}'), after saving the content is replaced with a funny value ('0') and the prefilter doesn't work: (parentmapobject='0').
As a test, setting the Map block Title to ${recordID}, the Title is shown with an ID, as expected. However, when setting this in the Prefilter events, the ${recordID} gets replaced with an '0'.

### Expected Behavior

The expected behaviour would be to keep the content in the prefilter events (parentmapobject='${recordID}') and not to be replaced with an "parentmapobject='0'".
![Xnip2024-11-27_07-17-20](https://github.com/user-attachments/assets/0e0fa0e7-6dec-4e92-9fe4-6a0be7594b26)
![Xnip2024-11-27_07-17-45](https://github.com/user-attachments/assets/6b78854b-db52-488b-b438-062a9344e4fa)
![Xnip2024-11-27_07-18-18](https://github.com/user-attachments/assets/59d3e692-405c-4c74-a064-7c550e323898)
![Xnip2024-11-27_07-18-46](https://github.com/user-attachments/assets/9cb5f24e-00f6-4d86-8201-5b2c963b3f75)

### Steps To Reproduce

Add a map block.
Set the prefilter events to filter based on the current opened record. In this case is parentmapobject='${recordID}'.
Save the map block.
Open the map block and check the content of the prefilter events, which will be already messed up with the content being: parentmapobject='0'.

**Comment by Fajfa** [comment]
Thanks for reporting it, will fix it. https://github.com/cortezaproject/corteza/commit/03ec8d39303ebf403662df4a7f2a08a7bfbf9bb6
