### ISSUE TITLE
Allow blocking changing preset filters

### ISSUE THREAD

**Issue by rsyrnicki** [cortezaproject/corteza#2038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.8

### Current Behavior

In a Record List Block, if "Users will be able to export records" is checked, and even if "Users will be able to filter the list" is unchecked, the user can change or delete all filters, even the preset ones, before exporting. So if I set a preset filter that only allows a user to see his own records, he can export the entire table by just deleting the filter. I wasn't able to find a solution, so I assume, it's a bug.

![cort_record_1](https://github.com/user-attachments/assets/d7c55f27-a208-47f8-81e8-9c0df6daf7ee)
![cort_filter_1](https://github.com/user-attachments/assets/22a40bb2-eac2-4ae0-9499-d236fda160e9)
![cort_exp_1](https://github.com/user-attachments/assets/8d28844c-dc5a-4cb4-b571-f12329e8fec1)
![cort_exp_2](https://github.com/user-attachments/assets/cb8b7009-1160-474b-a6ec-b4b61e203ee9)

### Expected Behavior

I expected only the filters set by a user to be changable before export. The preset filters should be appended to the user filters with an "and" operator. Preset filters should not be changed by users.

### Steps To Reproduce

1. Run Corteza 2023.9.8 in Docker
2. Create a module with data
3. Create a page with a record list block that points to the created module
4. Add any preset filter
5. In the block, enable user export (see screenshots)
6. Create a user (group authenticated)
7. Log in as the new user
8. Open the page and press export
9. Now a user can delete a preset filter and export all data from the module

**Comment by Fajfa** [comment]
This was actually intended, so if you can export records it was assumed the users might want to change the filter before exporting.

That being said, I do get your point and it probably makes sense to have that export filter controlled by the, "Users will be able to filter the list" option.

**Comment by rsyrnicki** [comment]
If it was intended, then is there another way to filter what a user can export from a module? For example with permissions? I feel like I'm missing something.

**Comment by Fajfa** [comment]
Yes, you can have record permissions that will prevent users from reading the record (and also exporting them)

**Comment by rsyrnicki** [comment]
> Yes, you can have record permissions that will prevent users from reading the record (and also exporting them)

It seems there is no way to set record permissions to a user, only to a group. Is there a solution for that, other than creating a group for every user?

**Comment by Fajfa** [comment]
Users have roles, and roles have permissions. So there is no way around setting permissions only on roles.
But you can have contextual roles, that are based on context. Check out the documentation for that.

**Comment by rsyrnicki** [comment]
> you can have contextual roles, that are based on context. Check out the documentation for that.

That sounds promising. I'll check it out and close the issue if I managed to  do it.

**Comment by rsyrnicki** [comment]
I see now that filters should not be used to filter content, a user is not supposed to see. I'll use contextual roles for that. Thank you.
