### ISSUE TITLE
Fix Contextual Roles with Record List Block

### ISSUE THREAD

**Issue by rsyrnicki** [cortezaproject/corteza#2040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9.9

### Current Behavior

I created a contextual role for copose:record with a following expression: `resource.values.userMandant == userID`, where userMandant is a multi field. 
I changed the permissions of a module as in the screenshot (for other roles I set Read records to 'Deny')
![image](https://github.com/user-attachments/assets/40be3275-d274-4554-9258-c53b313c3408)

When I try to list this module in a record list block in frontend, there are holes in the list. 
![image](https://github.com/user-attachments/assets/9f480502-6548-4bb7-b182-c191527f80b2)
Note that the record counter says 1 - 20 when there are only 3 records visible on this page. Following pages look similar, with two or three rows and a lot of empty space. 

I'm not sure if its connected, but when a user tries to export the data, no records are available. 
![image](https://github.com/user-attachments/assets/6b9ec72d-b123-4683-8498-5b2565bf72bd)

### Expected Behavior

I expected the list in the record list block to be uninterrupted and for the visible records to be exportable. 

### Steps To Reproduce

1. Run Corteza 2023.9.9 as Docker
2. Create a module and fill it with data
3. Create a contextual role, that allows a user to see only a subset of the records in the module
4. Display the module in a record list block
5. Create a user that meets the requirements for the contextual role
6. See holes in the list and see that export is impossible

**Comment by Fajfa** [comment]
@rsyrnicki Based on your forum posts, is this still relevant?

**Comment by rsyrnicki** [comment]
The issue dissapeard after I configured the filters and contextual roles correctly. Still no idea what caused the holes or not being able to export, but I'm no longer able to replicate the issue. Closing.
