### ISSUE TITLE
Error establishing a database connection  when access the website: https://cortezaproject.org/

### ISSUE THREAD

**Issue by xuanlongvts** [cortezaproject/corteza#2042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

three days ago, when i access the website:  https://cortezaproject.org/  It's has an errror Error establishing a database connection  when access the website: 

![Screenshot from 2024-12-09 10-56-30](https://github.com/user-attachments/assets/328b3a02-4e9a-45c3-97ff-6de1c1b622cb)

**Comment by Fajfa** [comment]
Should be good now.
