### ISSUE TITLE
Deploy a Server Discovery Demo

### ISSUE THREAD

**Issue by francescobianco** [cortezaproject/corteza#349]
We are looking for deploying a single docker-compose.yml file with both the 'corteza-server' and 'corteza-server-discovery'.
Not easy at all, can we provide an ready-to-use solution like this one:

- https://docs.cortezaproject.org/corteza-docs/2022.3/devops-guide/examples/deploy-offline/index.html

but with 'corteza-server-discovery', obviously also elasticsearch or any other search service.

cc @simonetravaglini

**Comment by darh** [comment]
@vicpatel can you share our setup here please

**Comment by petergrlica** [comment]
@francescobianco hi, sorry for the delay, hope you figured out how to set it up on production.

We've added an example on how we use discovery, hope it still serves some purpose to you.
It is still not added to the official documentation, but you can still check the PR: https://github.com/cortezaproject/corteza-docs/pull/282/files
