### ISSUE TITLE
config.js is served as content-type: text/plain

### ISSUE THREAD

**Issue by gandalfb** [cortezaproject/corteza#358]
**Describe the bug**
Running the docker-compose example from documentation with traefik adding the "nosniff" option `contentTypeNosniff: true` leads to a non-usable webapp, due to the browser (Chrome 101.0.4951.54 (Official Build) (64-bit)) saying the mime-type restriction is blocking script execution.

**To Reproduce**
Adjust reverse proxy to apply "X-Content-Type-Options=nosniff"

Deploy docker-compose as of document of `2022.3.1`

Open the url and see an error within browser console. The Website stays blank

Disabling the nosniff option makes the app usable and it loads.

**Expected behavior**
The config.js is send with a proper content-type in order the mime-type is delivered correctly and nosniff is usable.

Furthermore the app.*.js files are delivered as `content-type: text/javascript;`

I am not sure if this really is an issue but it somehow interfers with the "nosniff" header, wanting to be a header providing further security?

Thank you, and I hope this is an issue and not wasting your time.

Kind regards

**Comment by darh** [comment]
Hi @gandalfb thank you for reporting this.
We need to investigate this a bit.

**Comment by darh** [comment]
This was fixed in branches `2022.3.x` (will be part of 2022.3.4 release sometime next week) and `2022.9.x` (f41b7872f, 1bdf2b59a)
