### ISSUE TITLE
CREATE INDEX access ON auth_oa2tokens failed with "Specified key was too long; max key length is 3072 bytes"

### ISSUE THREAD

**Issue by siddontang** [cortezaproject/corteza#362]
Thanks for helping us to improve Corteza! We welcome all bug reports. Once we've verified and fixed your issue, we'll ping you in the comments to see if you can verify the fix.
We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with
the `status/to-test` label. You can pick any of these up for verification. ***You can delete this message portion of the bug report.***

**Describe the bug**

I ran `make test.store` to test corteza with TiDB , failed to create the index `access` on table `auth_oa2tokens`

The error is "Specified key was too long; max key length is 3072 bytes"

I found the `access` type is varchar(2048), which can't be created as an index directly both in TiDB and MySQL.  BTW, I ran this through MySQL command directly for MySQL. 

**To Reproduce**

Run `CREATE INDEX access ON auth_oa2tokens` directly through MySQL console. 

**Expected behavior**

Index created successfully. 

**Screenshots**

**Additional context**

I think we can use less length for `access`, or create the prefix index like `create index access on auth_oa2tokens (access(512))`

**Comment by darh** [comment]
@siddontang could be. We recommend that you run Corteza on Percona (https://docs.cortezaproject.org/corteza-docs/2022.3/devops-guide/system-requirements.html#_database) for now. Version 2022.9.x is getting some upgrades of the store layer so we might broaden the supported databases soon.

Can you share the versions of the TiDB and MySQL that you are using?

**Comment by darh** [comment]
Also, not denying that indexes, columns etc in the oa2tokens table could not be altered as you describe...

**Comment by siddontang** [comment]
Sorry I made a mistake, I just ran the DDL query through MySQL command line for MySQL 8.0. But `make test.store` can run well for MySQL 8.0, but not TiDB 6.0.

I checked the schema after testing and found an interesting thing in MySQL 8.0 and Percona Server 8.0:

```
CREATE TABLE `auth_oa2tokens` (
  `id` bigint unsigned NOT NULL,
  `code` varchar(48) NOT NULL,
  `access` varchar(2048) NOT NULL,
  `refresh` varchar(48) NOT NULL,
  `data` json NOT NULL,
  `remote_addr` varchar(64) NOT NULL,
  `user_agent` text NOT NULL,
  `rel_client` bigint unsigned NOT NULL,
  `rel_user` bigint unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `expires_at` (`expires_at`),
  KEY `code` (`code`),
  KEY `access` (`access`(1024)),
  KEY `refresh` (`refresh`),
  KEY `client` (`rel_client`),
  KEY `user` (`rel_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3
```

As you can see, `KEY `access` (`access`(1024)),` is just a prefix index, I don't know where you create a prefix here. I just logged the DDL here https://github.com/cortezaproject/corteza-server/blob/2022.9.x/store/adapters/rdbms/ddl/generators.go#L65, the log is just like `CREATE INDEX "access" ON "auth_oa2tokens" (access)`.

I will find where you use the pefix index, and it is honored that you can tell me directly :-)

**Comment by siddontang** [comment]
another thing is that I found we use `utf8mb3` for the table charset, do we need to use `utf8mb4` here?

**Comment by siddontang** [comment]
I use Wireshark to capture all the queries, and found that here you set `set session sql_mode='ANSI'`, which can let the creating table successful but with some warnings. See a simple example in the command line:

```
mysql> create table t (id int, name varchar(2048), index(name)) charset=utf8;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes


mysql> set names utf8mb4;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t (id int, name varchar(2048), index(name)) charset=utf8;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes

mysql> set session sql_mode = 'ansi';
Query OK, 0 rows affected (0.00 sec)

mysql> create table t (id int, name varchar(2048), index(name)) charset=utf8;
Query OK, 0 rows affected, 2 warnings (0.06 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                     |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 3719 | 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous. |
| Warning | 1071 | Specified key was too long; max key length is 3072 bytes                                                                                                                    |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```


But I think here you just want utf8mb4, in fact?
