### ISSUE TITLE
Insert table `compose_record` warning `'values' doesn't have a default value`

### ISSUE THREAD

**Issue by siddontang** [cortezaproject/corteza#364]
Hi, I tried to run corteza server based on TiDB, and meet a warning with `'values' doesn't have a default value`

The SQL is below:

```
INSERT INTO compose_record (created_at,created_by,deleted_at,deleted_by,id,module_id,owned_by,rel_namespace,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?) [arguments: (\"2022-05-25 22:00:00\", 285596350924455938, NULL, 0, 285694512854990850, 285595792411000834, 285596350924455938, 285595790146011138, NULL, 0)
```

 Corteza doesn't assign a value to the `values` field, but as we can see from the table, the `values` must be NOT NULL.   

```
CREATE TABLE `compose_record` (
  `id` bigint(20) unsigned NOT NULL,
  `rel_namespace` bigint(20) unsigned NOT NULL,
  `module_id` bigint(20) unsigned NOT NULL,
  `values` json NOT NULL,
  `owned_by` bigint(20) unsigned NOT NULL,
  ......
)
```

I know that Corteza uses `ASNI` SQL mode, which can treat this as a warning, but it is may better to insert a default value or just create the table without `NOT NULL`.

**Comment by tjerman** [comment]
What version are you using?
Before `2022.9` (not released yet) there is no `values` column in the `compose_record` table.

If you're running `2022.9` I'd suggest you (until `2022.9` is more stable) switch to some `2022.3` version.

**Comment by siddontang** [comment]
I used 2022.9, I will use the stable version later.
