### ISSUE TITLE
service.auth-notification auth notification "could not send email"}

### ISSUE THREAD

**Issue by Yaren-IT** [cortezaproject/corteza#372]
While deploying a fresh corteza project with proper SMTP settings, the value SMTP_FROM is not set in the auth-notification.

`corteza              | 10:36:02.000     ERROR   service.auth-notification       auth notification send failed   {"requestID": "<redacted>", "name": "auth_email_confirm", "email": "<redacted>", "error": "could not send email: gomail: could not send email 1: 450 4.1.8 <info@example.tld>: Sender address rejected: Domain not found"}`

After visiting the settings via the webfront, you can manually set the correct sender address.
Since I am a newbie in the corteza ecosphere, it was very time consuming to fix this and start a server.

This issue seems related to #7 and #288 
The reproducing steps are the same.

Is there any chance to get this working with the .env file?

![grafik](https://user-images.githubusercontent.com/105632602/174586171-a2950c0a-16b0-4c18-81f9-09d233d4d768.png)

**Comment by Yaren-IT** [comment]
1. On a fresh deployment
  - `corteza-server settings list --prefix "auth.mail.from-address"` gives `auth.mail.from-address  "info@example.tld"`
  - `corteza-server settings list --prefix "smtp.servers"`gives `smtp.servers                                            [{"from": "redacted@domain.tld", "host": "redacted.domain.tld", "pass": "redactedpassword", "port": "465", "user": "redacted", "tlsInsecure": false, "tlsServerName": ""}]`
  - `# corteza-server auth test-notifications some@mail` gives ```11:57:58.646    ERROR   service.auth-notification       auth notification send failed   {"name": "auth_email_password_reset", "email": "some@mail", "error": "unable to find configured and working SMTP dialer"}```
  `could not send email, contact your administrator`
3.  After correcting `auth.mail.from-address` with `corteza-server auth test-notifications changed@example.tld` it's still the same: `corteza              | 12:05:53.258     ERROR   service.auth-notification       auth notification send failed   {"requestID": "redacted", "name": "auth_email_confirm", "email": "redacted", "error": "could not send email: gomail: could not send email 1: 450 4.1.8 <info@example.tld>: Sender address rejected: Domain not found"}`
But `corteza-server settings list --prefix "auth.mail.from-address"` is showing up the right address: `auth.mail.from-address  "changed@example.tld"` 

Test-notifcations is still not finding any configured and working SMTP dialer.

(I used a valid an working email instead of changed@example.tld)

**Comment by darh** [comment]
Thank you. Someone will take a look in a couple of days and update this issue.

**Comment by vicpatel** [comment]
This is fixed with [07a8fdb](https://github.com/cortezaproject/corteza-server/commit/07a8fdbbd54588f1b5c21f96d3a4c518e3bb6509).

**Comment by vicpatel** [comment]
It is released with `2022.3.4`
