### ISSUE TITLE
pkg/objstore/minio GetObject causes lots of unclosed goroutines

### ISSUE THREAD

**Issue by junfengye** [cortezaproject/corteza#410]
call minioClient.GetObject returns minio.Object, It implements Reader, ReaderAt, Seeker, Closer for a HTTP stream.
It will start a goroutine wait for Close() functoin is called.
But corteza use it as a ReadSeeker, so it is not closed.

see the goroutines with pprof /debug/pprof/goroutine?debug=2

**To Reproduce**
call attachment related api

**Expected behavior**
no minio related goroutines

**Screenshots**
![image](https://user-images.githubusercontent.com/2325550/190967850-05b5648a-c857-46b2-869c-c6e960603bf0.png)

**Additional context**
attachment related automation function pass Reader in workflow scope, simply change **ReadSeeker** to **ReadSeekCloser** and close the **Closer** will cause the workflow related testcase failed

**Comment by darh** [comment]
Thank you for this and the proposed solution. Someone from our team will address this shortly!

**Comment by darh** [comment]
Fixed on 2022.9.x. Will back-port for 2022.3.6 (2022.3.5 is about to be released)
