### ISSUE TITLE
Workflow "runtime error. invalid memory address or nil pointer dereference” for corredor script.

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#413]
**Describe the bug**
Server panics when attempting to access nil Var expression.

**To Reproduce**
Set up a workflow that executes a corredor script. Don't fill out the args section. Run the script

**Expected behavior**
A clear error saying you must put something in the args section, or coerce empty args to an empty expression.

**Additional context**
See this forum post for information including the stack trace

https://forum.cortezaproject.org/t/simple-corredor-script-results-in-runtime-error-invalid-memory-address-or-nil-pointer-dereference/1038/7

**Comment by vicpatel** [comment]
Hey, Thank you for reporting this.
This is fixed and merged to `2022.9` and `2022.3`.

[2022.9 commit](https://github.com/cortezaproject/corteza-server/commit/422f870f40412576c3899917c15bed58332dab6e), [2022.3 commit](https://github.com/cortezaproject/corteza-server/commit/9ad5b36caf36002a06d08cce1ce603578683afda)
