### ISSUE TITLE
REST API Documentation Versions Incorrect

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#417]
**Describe the bug**
The documentation versions do not reflect the version of the branch they are commited in

https://github.com/cortezaproject/corteza-server/blob/57721291b270d4ed9b9e625d7a17fca2cc6c27eb/docs/system.yaml#L5

https://github.com/cortezaproject/corteza-server/blob/57721291b270d4ed9b9e625d7a17fca2cc6c27eb/docs/federation.yaml#L5

**Expected behavior**
Version matches the branch name

**Additional context**
Am I misundertanding the version? Is the version of the API supposed to reflect the "last changed" version?

**Comment by darh** [comment]
Fixed in `17dd946c5`
