### ISSUE TITLE
Automatic migration from 2022.3.5 to 2022.9.0 failing?

### ISSUE THREAD

**Issue by Grisgruis** [cortezaproject/corteza#424]
I was testing the upgrade to 2022.9.0 and found something weird.

When setting up a clean setup in 2022.3.5, and adding some leads:
![image](https://user-images.githubusercontent.com/1905778/195192723-20bd78fd-7cb0-4ada-a8a8-20febf1c5971.png)

Doing nothing else then changing the version to 2022.9.0 and stopping / starting docker-compose this results in only 1 type of lead and the company info removed..

![image](https://user-images.githubusercontent.com/1905778/195192960-73c8558d-7d96-4ae4-af32-58e9c1f29946.png)

Is this known / expected behaviour? I see no upgrade steps yet in the PR for the docs https://github.com/cortezaproject/corteza-docs/pull/292/files

Might warn some users of loosing data?

**Comment by darh** [comment]
Hi & thank you for reporting this. There should be no data loss. 

I'll assume that this is a test db without any real data? Can you maybe share data-dump from the db?
There might be something specific on your config that we missed.

**Comment by surturas** [comment]
had this happen to me to on my private prod system (for some odd reason i done a backup before upgrade so no harm) the data on the DB is broken
![image](https://user-images.githubusercontent.com/115612556/195264645-f938029c-b18d-438b-b28a-e7594ee287e3.png)
it happened to all custom namespaces and all modules within. i posted on the forum too https://forum.cortezaproject.org/t/migration-from-2022-3-5-to-2022-9-0-failing-for-custom-low-code-apps/1077

**Comment by Grisgruis** [comment]
Yeah i see the same as @surturas alle entries have the same json data

**Comment by Yangruipis** [comment]
hi @Grisgruis and @surturas, i met the same issue before, just upgrade to the latest commit, this was fixed by https://github.com/cortezaproject/corteza-server/commit/7e4e4d3b5abb22d4535d548828cf0d2116284cd3 (2022-10-04)

**Comment by Grisgruis** [comment]
this was resolved in update
