### ISSUE TITLE
Postgres DB Error Upon Module Creation

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#425]
**Describe the bug**
I'm getting the error:

```
pq: zero-length delimited identifier at or near """"
```

The full log error from the DB is

```
corteza_db_1        | 2022-10-13 07:59:35.860 UTC [52654] ERROR:  zero-length delimited identifier at or near """" at character 28
corteza_db_1        | 2022-10-13 07:59:35.860 UTC [52654] STATEMENT:  CREATE TABLE IF NOT EXISTS "" (
corteza_db_1        |     "Phone" TEXT NOT NULL
corteza_db_1        |   , "LastOutreachAttemptStatus" TEXT NOT NULL
corteza_db_1        |   , "BusinessName" TEXT NOT NULL
corteza_db_1        |   , "id" BIGINT NOT NULL
corteza_db_1        |   , "rel_module" BIGINT NOT NULL
corteza_db_1        |   , "deleted_by" BIGINT     NULL
corteza_db_1        |   , "rel_namespace" BIGINT NOT NULL
corteza_db_1        |   , "revision" BIGINT NOT NULL
corteza_db_1        |   , "meta" JSONB NOT NULL
corteza_db_1        |   , "owned_by" BIGINT NOT NULL
corteza_db_1        |   , "created_at" TIMESTAMP(0) NOT NULL
corteza_db_1        |   , "created_by" BIGINT NOT NULL
corteza_db_1        |   , "updated_at" TIMESTAMP(0)     NULL
corteza_db_1        |   , "updated_by" BIGINT     NULL
corteza_db_1        |   , "deleted_at" TIMESTAMP(0)     NULL
corteza_db_1        |   )
```

**To Reproduce**
Leave handle as an empty value

**Expected behavior**
Client side exception. Currently I have to go into the DB and do module cleanup in order to fix.

**Comment by darh** [comment]
@skamensky can you maybe address this while solving the whole schema management thing?

**Comment by skamensky** [comment]
@darh ,

Sure. I'll add a fix for this. It looks like this is using the handle as the DB table name (I didn't verify by digging into the code). 

We have two options:

1. Require a handle for a physical table
2. Use the ID as the table name

If it comes down between a choice of those two things, which do you prefer?

**Comment by skamensky** [comment]
@darh ,


I can no longer reproduce this. It seems to have gotten fixed somewhere along the way.
I think this can be closed.
