### ISSUE TITLE
Required Field Attribute On Module Not Respected For Physical Tables

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#427]
**Describe the bug**
When setting a field to "not required", it still received a `not null` constraint in postgres

**To Reproduce**
1. Create a field that's not required
2. Try to create a record without populating the 'not required' field
3. Get DB error

**Expected behavior**
`not required` translated to no `not null` constraint being applied to the column

**Screenshots**
Definition of the module (I also tried checking and unchecking before the initial saving of the module, to no effect)
![image](https://user-images.githubusercontent.com/19151369/195666274-62303fac-7ef8-40c1-b1f5-de2bd5303d5f.png)

**Additional context**
Generated definition (retreived from goland IDE)
```
-- auto-generated definition
create table "Parent"
(
    "Name"        text         not null,
    id            bigint       not null,
    rel_module    bigint       not null,
    deleted_by    bigint,
    rel_namespace bigint       not null,
    revision      bigint       not null,
    meta          jsonb        not null,
    owned_by      bigint       not null,
    created_at    timestamp(0) not null,
    created_by    bigint       not null,
    updated_at    timestamp(0),
    updated_by    bigint,
    deleted_at    timestamp(0)
);```

**Comment by skamensky** [comment]
I created a fix for this here

https://github.com/cortezaproject/corteza-server/pull/431

@darh , can you please take a look?

**Comment by skamensky** [comment]
Solved with https://github.com/cortezaproject/corteza-server/pull/431

**Comment by darh** [comment]
I'll keep this one open for now. We'll close it when we merge the #443

**Comment by darh** [comment]
Nevermind 🙈
