### ISSUE TITLE
Record Selection Not Working For Physical Tables

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#429]
**Describe the bug**
When trying to save a record after having selected a related record, the server returns an error that the record is not found.

**To Reproduce**
1. Set up two modules (both physical), A and B
2. Make a record selector field on B point to A
3. Create an A record
4. Try creating a B record point to A

**Expected behavior**
Record saves normally.

**Additional context**
This [forum post](https://forum.cortezaproject.org/t/record-selection-not-working/1084?u=shmuel) has more information

**Comment by skamensky** [comment]
This seems to have been resolved in `2022.9.1`

**Comment by darh** [comment]
I doubt it :)

I've [fixed](https://github.com/cortezaproject/corteza-server/commit/a8d2fef3c) it yesterday, after .1 patch.

Closing this.

**Comment by skamensky** [comment]
Yup, whoops, I was running bleeding edge github code instead of the released code. 

Thanks for the fix!
