### ISSUE TITLE
info@example.tld

### ISSUE THREAD

**Issue by Yaren-IT** [cortezaproject/corteza#430]
**Describe the bug**
After deploying a fresh corteza server, resetting passwords does not work correctly.

**To Reproduce**

1. Deploy a fresh corteza Docker instance, configure accordingly.
2. Execute an interactive bash terminal inner corteza-server
3. Set valid email-from with `corteza-server settings set auth.mail.from-address VALID@EMAIL.TLD`
4. Test Email Settings with `corteza-server auth test-notifications VALID-TEST-EMAIL-RECIPIENT@EMAIL.TLD`
5. Info: Email works just fine and arrives.
6. Set user with `corteza-server users add VALID-USER@EMAIL.TLD --make-password-link`

**Expected behavior**
Expected is an Email with Password Reset link.
This does not arrive, although it did with test-notifications.
It does even not work over the WebApp, with manually clicking on the reset button. The WebApp tells about an internal Error, and Logs on serverside tell:
`ERROR   service.auth-notification       auth notification send failed   {"requestID": "...", "name": "auth_email_password_reset", "email": "...", "error": "could not send email: gomail: could not send email 1: 450 4.1.8 <info@example.tld>: Sender address rejected: Domain not found"}`

**Comment by darh** [comment]
Thank you @Yaren-IT for a very thorough bug report. Will look into it.
Does restarting the server help by any chance?

Also -- can you share the version you're using please.

**Comment by Yaren-IT** [comment]
Indeed, it helped.
After simply restarting my instance with `docker compose down && docker compose up -d` , resetting the password worked.
EDIT:
Version is 2022.9.1 
> Thank you @Yaren-IT for a very thorough bug report. Will look into it. Does restarting the server help by any chance?
> 
> Also -- can you share the version you're using please.

**Comment by darh** [comment]
I think your expectations about email sending on users-add command were wrong.

The `--make-password-link` flag only gives you a link, it does not send an email.
I've created two new issues. One to actually implement this behaviour (with different flags) and the 2nd one to warn the user that server needs to be restarted when SMTP settings are changed from the CLI.

Closing this.
