### ISSUE TITLE
Support Compose page duplication [PlanID: 2023.3/35/3]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#451]
On the Compose page builder
 - [x] Add page clone button in the bottom toolbar
 - [x] On record pages, keep the button, disable it and add a hint on mouse-over that record pages can not be duplicated
 - [x] Page cloning happens in-browser (make a copy of the page, remove page ID from the payload and send a create-page request). 
   - [x] Prefix the title with `"Copy of "`
   - [x] Remove handle

![Image](https://user-images.githubusercontent.com/1500447/198876001-4a566c51-1aee-4600-97b9-748ccdbc51fb.png)

**Comment by katrinDY** [comment]
Code: [8076874](https://github.com/cortezaproject/corteza/commit/80768746674a5ac8b5841fb58ae3b696f897dca7)


Demos:
![Image](https://user-images.githubusercontent.com/85161724/200312028-e80434ef-5844-4a9e-9c55-0ec8ad294a4a.gif)
![Image](https://user-images.githubusercontent.com/85161724/200312029-199ace1b-c9ff-46b0-997f-7a10b9a3a851.gif)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. Moving the card to Done.

**Comment by katrinDY** [comment]
Changelog:

Added

what: Added support for page duplication. A page can be duplicated when in edit mode or when in the page builder view.

why: This easily allows users to copy/share content from one page to another.

**Comment by Bojan-Svirkov** [comment]
@katrinDY I just have one more question: When a page is duplicated/copied, and you delete a record on the copied page, should that record be also deleted on the original/main page?

**Comment by katrinDY** [comment]
@Bojan-Svirkov, the same change shouldn't be applied to the original

**Comment by katrinDY** [comment]
@Bojan-Svirkov, sorry, by bad, this is intensional because both of the records point to the same module.
