### ISSUE TITLE
Add support for Compose page block tabs [PlanID:2023.3/8/2.6]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#452]
Integrators can configure **Tabs** block on Compose page.  This is accomplished by linking existing record page blocks of any other type. Each linked block represents one tab in the tab block.

The implementation is based on [Bootstrap's tabs](https://bootstrap-vue.org/docs/components/tabs).

 - [x] Prepare mockups that demonstrate this feature @darh 

----

 - [x] Page can have multiple tab blocks
 - [x] For now, nested tabs are not allowed (block tab with a block tab)
 - [x] Tabs are configured right of the "General" tab in the block configuration
 - [x] Integrator can use pre-existing blocks (show warning where there are no blocks available)
 - [x] New blocks can be added via tab block
 - [x] Integrator can change the order of tabs by reordering linked blocks
 - [x] Page block rendering logic must be corrected to omit linked blocks when rendering a page
 - [x] [When tab block is deleted, page blocks should render those blocks again.
 - [x] Blocks can be duplicated via tab block's configurator
    - [x]  Checkboxes are shown
    - [x] Duplicate button should not be disabled once a box is checked
    - [x] Tab should be duplicated and block should be duplicated for all checked boxes
 - [x] Implement bootstrap's properties for `<b-tabs>`: align, fill, justified, small, pulls, vertical
 - [x] By default, 1st tab is active
 - [x] When changed, the active tab must be preserved after refresh (store it in URL)
 - [x] Linked's block title is used as a tab title

### Phase 2 Requirements

- [x] Each block should have a temp ID and tabbed option in their meta and Switch to using blockID once blocks have been saved
- [x] Making a tab is broken, this should be fixed.
- [x] Tabs should be rendered visually in tabBase
- [x] Edit is broken. This should be fixed.
- [x] Add new block feature is broken, this should be fixed.
- [x] Each Block should have a 'General' toggle switch for tabbing blocks
- [x] When a Tab Block is deleted, tabbed blocks should be deleted and should appear on page
- [x] Actual blocks should not be saved in each tab
- [x] Until a Tab block is added to the page, the add button should be disabled
- [x] Deleting a tabbed block out of a tab should not alter the page-rendering logic only when you delete a tab block itself
- [x] Tabbing a block should flip its tabbed switch automatically
- [x] remove tab tracking
- [x] Blocks should not be saved in options
- [x] Change tab interface structure
- [x] remove tabbed options from all blocks
- [x]  Remove blockIndex from Tabs block
- [x] Truncate via css alone
- [x] Remove tabbed option from all blocks and use just meta
- [x] Cancelling should undo changes in configurator including adding a block or making a tab or tabbing blocks
- [x] When adding a block in a tab, the tabs option should be disabled in the block selector
- [x] Cross-check method names
- [x] Fix Apply issues in libjs
- [x] Add delete to each block's configurator except tabs
- [x] Deleting a tabbed block should remove it from any Tabs block
- [x] Update from TempIDs when the page is saved
- [x] Eliminate the tabs mixins
- [x] Refactor the UpdateBlocks method
- [x] Take care of Tabs duplication edge-case
- [x] TempID setting logic should be on the class level
- [x] Refactor Selection disabling logic
- [x] Add a comment to block deleting logic.
- [x] Manually untabbing blocks should remove it from everywhere it is tabbed
- [x] PageBlock Class should have a method to reset tabs for copying and cloning

**Comment by EmmyMay** [comment]
Tab blocks have their dimensions pre-determined just as other blocks xywh
You link existing blocks to the tabs via a dropdown (try drag and drop later)
data structure should stay as is for page
Number of blocks determine number of tabs
Block title determines tab name

**Comment by EmmyMay** [comment]
UI preview

![image](https://user-images.githubusercontent.com/31524469/205916407-e4294756-b76e-4f3c-a88d-c22028edcf7d.png)

**Comment by EmmyMay** [comment]
> UI preview for Tab configurator
> 
> ![image](https://user-images.githubusercontent.com/31524469/205916407-e4294756-b76e-4f3c-a88d-c22028edcf7d.png)

**Comment by EmmyMay** [comment]
Note: Block duplication, for now, will not be allowed for tabbed blocks. We can discuss more on why this is.

**Comment by EmmyMay** [comment]
TabBase UI Preview

![image](https://user-images.githubusercontent.com/31524469/205984826-b969df29-bfbe-48aa-b651-f79c02cb3b91.png)

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/206006155-191ed517-fb20-4f15-819e-51657f6324fe.png)

**Comment by EmmyMay** [comment]
UI Update 



![Image](https://user-images.githubusercontent.com/31524469/207654677-44a42b26-b797-4a40-b546-6fc5e991cb4c.png)



![Image](https://user-images.githubusercontent.com/31524469/207654880-c4c0bf1f-4b4c-4554-a3e7-7277928a0698.png)




![Image](https://user-images.githubusercontent.com/31524469/207654902-17b6efde-3b73-455d-bb61-16ba9b592dfa.png)

**Comment by EmmyMay** [comment]
This may not be ready for this milestone as it is still pending fixes from me based on review updates.

**Comment by EmmyMay** [comment]
Editing this issue to have a phase 2 which would include logic refactoring and some flow changes. The changes would help to simplify the approach currently used to better circumvent structural and architectural restrictions in compose's builder component. This phase 2 update will also bring about some UX flow changes in the way this feature was originally intended to work. The issue shall be updated with new requirements for this to be considered DONE.

**Comment by EmmyMay** [comment]
![Image](https://user-images.githubusercontent.com/31524469/219081427-f3330a0e-a14e-4e16-96b2-55374a3a3398.png)



![Image](https://user-images.githubusercontent.com/31524469/219081607-e558ba6d-4783-46bd-bc30-cf72485cc86f.png)

**Comment by katrinDY** [comment]
For today: take care of two more things discussed with Jože and then, if time today, address the comments in the PR.

**Comment by katrinDY** [comment]
For today: resolve remaining comments in PR and a couple of minor things found along the way. To be ready for code review by 1pm latest.

**Comment by katrinDY** [comment]
For today: address the remaining comments on PR. Time-box blocker for two hours and if can't resolve, sync with Jože.

**Comment by tjerman** [comment]
Should all be finished by dev release tuesday

**Comment by Bojan-Svirkov** [comment]
This was tested and confirming that it works as intended. The only thing left now is the CL entry @EmmyMay

**Comment by EmmyMay** [comment]
# Changelog Entry

## Added

### What was added?
Added support for the Tabs PageBlock

### Why was it added
To make pageblock organizing much easier for users.

**Comment by Bojan-Svirkov** [comment]
Added CL
