### ISSUE TITLE
Allow users to use IN/NOT IN operator in Reporter's filter UI

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#457]
Integrator must be able to select IN or NOT IN operators.

When IN/NOT IN operator is selected left/right sides are flipped - `value IN field`!

![Image](https://user-images.githubusercontent.com/1500447/200590130-6ecf3dce-048a-4397-b70c-3cd35a153564.png)

Bonus points:

 - [x] Enable IN/NOT IN operators only for multi-value fields
 - [x] Disable all other operators for multi-value fields

**Comment by darh** [comment]
Assigning to SNE to keep it close to #456. Feel free to change that.

**Comment by kelanik8** [comment]
![Image](https://user-images.githubusercontent.com/23015247/203418775-e2d171c7-f2a6-4813-b77f-d57324c74689.png)

**Comment by kelanik8** [comment]
https://github.com/cortezaproject/corteza/pull/560

**Comment by kelanik8** [comment]
![Image](https://user-images.githubusercontent.com/23015247/203444096-30ed51f0-fb44-444c-a2cf-674b1f258a39.png)

**Comment by kelanik8** [comment]
Changelog

What changed
- New filter operators(IN/NOT IN) added to the prefilter in the reporter UI

Why did it change
- Users can now use IN/NOT IN operator in Reporter's filter 

How did it change
- Updated the prefilter component with the two new operators
- Added the locale properties for the filter text
- Add the logic to configure switch value and fields input when a multi field value is selected

**Comment by kelanik8** [comment]
Steps to recreate: 

- open reporter
- select a report
- toggle the report builder
- add a block with a table element
- under the prefilter section
- select a field the a multi value type
- and save the see the reflected changes

**Comment by Bojan-Svirkov** [comment]
The functionality works as expected for now and I added the CL entry, will just leave the ticket in qc since it might be also possible the other issues to be fixed today in regards to the `in operator in joins/links` and multivalue fields displayed as one whole name.

**Comment by Bojan-Svirkov** [comment]
Tomaz addressed the other issues so I am moving the card to `Done`.
