### ISSUE TITLE
Add support for listing and viewing of deleted record and ability to undelete them

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#459]
## Backend changes

 - [x] define new `restore` RBAC operation 
 - [x] add RBAC checks in the service code
 - [x] implement `POST /record/{id}/restore`

Notes on new API endpoint. I'm fully aware of the "unrestfulness" of the proposed solution. Right now even DELETE is abused for soft delete (should be hard).

### Record list block
 - [x] a configuration option to enable delete-record listing
 - [x] swap delete button with restore, same behaviour (with confirmation)
 - [x] colour changes (warning bg) when viewing a list of deleted records

### All records 
 - [x] should implement the same changes for viewing individual records
 - [x] exclusive/inclusive/excluded should be part of the filter

![Image](https://user-images.githubusercontent.com/1500447/200867186-2072e06a-6e36-47a7-b11e-5f995d77ccc1.png)
![Image](https://user-images.githubusercontent.com/1500447/200867188-ebfb9cf6-a90c-4b17-8080-061c8627f67b.png)
![Image](https://user-images.githubusercontent.com/1500447/200867185-1bf707cc-6ad9-4dfa-a504-e31e09c1f0d4.png)
![Image](https://user-images.githubusercontent.com/1500447/200867187-3539451f-2a9f-4922-b402-beff155e3879.png)

**Comment by KinyaElGrande** [comment]
Moving this to  **sprint backlog**  in order to focus on https://github.com/cortezaproject/corteza/issues/527.

**Comment by KinyaElGrande** [comment]
Currently, there is a blocker on version 23.3 when returning only deleted records.
Both `Exclude (0, default)` and `(2) deleted`  deleted filters return the same list of records where `"compose_record"."deleted_at" IS NULL `.

This only happens with record resource, I have tested the user resource and everything works fine.

**Comment by Bojan-Svirkov** [comment]
This still needs some work since it looks like the records are not saving.

[d710082f-97a1-4009-97a1-a80bc97f8480.webm](https://user-images.githubusercontent.com/53232926/212339869-a3c9ceaa-ca39-424e-a5e1-c91a4188b409.webm)

**Comment by KinyaElGrande** [comment]
I have fixed the issue in my latest update [Modify bulkUndelete endpoint name and http verb](https://github.com/cortezaproject/corteza/pull/740/commits/2830639ab95a755272f40708cd6a81048accdf86).

**Comment by Bojan-Svirkov** [comment]
Retested this again and I can confirm that now this looks and works good. The only thing now left is the CL entry.

**Comment by KinyaElGrande** [comment]
# Change Log

## What was added

- A configuration option to enable delete-record listing.
- Support for viewing a deleted record.
- Support for undeleting a deleted record.
- Support for undeleting multiple deleted records.

## Why was it added
To allow users to view and restore deleted record(s).
