### ISSUE TITLE
Support for Nylas page block

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#462]
Email and calendar integration enables users to access their inboxes and calendars, compose and send emails and list contacts. This is not a generic integration - only Nylas is supported to save time on front-end implementation.

All Nylas components (Agenda, Composer, Contact List, Conversation, Email and Mailbox) are supported.

# Authorisation and configuration

Corteza allows both types of supported authorisation - for single and for all accounts. The user configures components inside Nylas dashboard and copies component ID to Compose block configuration.

Corteza enables end-users to authorise themselves through OAuth2 mechanisms and store auth provider's (Nylas) credentials. These credentials can be later accessed by the user for the purpose of fulfilling Nylas components configuration.

 - [x] Allow users to use Nylas Auth API to retrieve access-token

❗[Todo: show configuration and authorisation flows]

Access tokens are stored as credentials-type resources with a well-known credentials kind. Only one Nylas access token per Corteza user is allowed for now (a soft limit needs to be implemented). The token is then used by all Nylas blocks

❗[Todo: mockup: how users are prompted with authentication flow to gain access tokens]

# Page block for integrators

Corteza introduces a single page block type (`IntegrationNylas`) that serves as a container for all supported types of Nylas components. Because Nylas offers the HTML tag as a whole to copy, we need to support seamless processing and extraction of relevant values.

 - [ ] Introduce one new block type that can handle all 6 different types of Nylass components

![Image](https://user-images.githubusercontent.com/1500447/198829598-0f1df16e-297b-4fe2-8e67-536b24a98b4f.png)

(Nylas dashboard: showing example HTML with generated ID and access token placeholder)

❗ [Todo: mockup where the new block type should be]

❗ [Todo: mockup of how the block configuration should look like]

❗ [Todo: mockup of how the block preview, when placed on the grid, should look like]

Nylas dashboard can preconfigure certain properties and use those settings as a default. Corteza allows to explicitly override these settings.

❗ [Todo: table with all available settings for Nylas components available in Corteza]

# Page block for end-users

Nylas page block can be rendered in one of four states:

 - [x] fully configured and working, outputting appropriate content (calendar, email, ...
 - [x] configured but missing access token, user can click and link it
 - [x] unconfigured but known component type

❗ [Todo: mockups for all four types]

**Comment by tjerman** [comment]
I'm working on figuring out how it should be integrated with the existing (auth) services.
Will try to have it sorted and ready to go by Monday.

**Comment by tjerman** [comment]
The back-end now supports users to authenticate Nylas to get their access tokens; https://github.com/cortezaproject/corteza/commit/0e9bb432ce23ba3d9a262442c3e2c393224c9281 https://github.com/cortezaproject/corteza/commit/9d52427d977faedc1cdf118b4ec10360b3e2ec20

* OAuth is done through the standard auth component.
* A new external provider was added with an additional `usage` field which identifies what all the providers should be used for
  * `identity` - for authentication (default if none specified)
  * `api` - for API integrations
* Access tokens are stored in the credentials table identified by the `access-{provider}` handle
* Access tokens can be obtained via the `GET /system/users/{userID}/credentials` endpoint

Changes to the external authentication flow

when the external provider authenticates the user
* if the provider is used for identity, it is used to login/signup the user (login in case they already exist)
* if the provider is used for API access, the access credentials are stored in the `credentials` table for later use.

Other important changes
* changed credentials access control to allow users to manage their own credentials

To enable Nylas for usage

1. find your Nylas authentication params in the dashboard (the key and the secret)
2. go to the admin webapp > system settings; scroll to the bottom and click on the config button for Nylas
3. punch in the key/secret, tick the use for API checkbox
4. confirm/save it all

Invoke Nylas authentication via the `GET /auth/external/nylas` endpoint (for example `localhost:1024/auth/external/nylas`).

**Comment by Bojan-Svirkov** [comment]
I just tested this and I am happy with the results. @tjerman & @Fajfa  now only the changelog part and we are done.

**Comment by Fajfa** [comment]
Added:

What was added:
A new page block on compose called Nylas, that can display Nylas components defined in the Nylas dashboard.
The Nylas external provider was also added to the list in the Admin panel under System setting.
If the external provider is configured the blocks will be usable in Compose.
The configurator requires the Nylas component kind you wish to display and its component ID
The user can then be authenticated/connected with Nylas by clicking the button on any of the Nylas components.

Why was it added:
To enable the integration with Nylas and support the use of its components inside Compose
