### ISSUE TITLE
Chart labels overlapping

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#464]
As seen on the attached example, the left-side label on all chart is covering the axis values

![Image](https://user-images.githubusercontent.com/1500447/201093737-ecb4cd88-8baa-493b-89a5-08451c3d95e7.png)

**Comment by Fajfa** [comment]
This would be my proposed solution, 

![Image](https://user-images.githubusercontent.com/15791641/203110819-b0f71e6a-44b6-4ab5-905d-0844c0d941c4.png)

**Comment by darh** [comment]
Much better. 

Please sync with @katrinDY she is also working on some element repositioning, rotation and hiding features.

**Comment by darh** [comment]
This is `_Axis.nameLocation`, correct?

How about if we let the user decide between `center`, 'end', `start`, and an additional `hide` that hides the name?

**Comment by Fajfa** [comment]
Correct, we can do that, i wouldn't do hide but instead if there is no value we can just not show it. Otherwise a dropdown for the position.

**Comment by Fajfa** [comment]
The Y Axis now has an option for the label position on both compose and reporter charts

**Comment by Bojan-Svirkov** [comment]
@Fajfa This looks good. When you have the time just add the entry for the CL. 🍻

**Comment by Fajfa** [comment]
What was added?

For charts with y-axis, a new label position option was added. It enables you to position the label at the bottom, middle or top of the y-axis.

How was added?

By using the nameLocation property of Apache Echarts y-axis, which enables this. A select dropdown was also added in the y-axis section in Compose and Reporter chart configurations.

ref: [18248a2](https://github.com/cortezaproject/corteza/commit/18248a2376ec4400ac562faae32be3ec129acca1)

**Comment by Bojan-Svirkov** [comment]
Added to CL.
