### ISSUE TITLE
SQL/scan issue while building report

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#465]
HTTP request
```
/api/compose/namespace/238940487652933635/module/238940488189870083/record/report
?metrics=SUM(Amount)+AS+sum_amount,SUM(Amount)+AS+sum_amount
&dimensions=DATE_FORMAT(CloseDate,+%27%25Y-%25m-01%27)
&filter=StageName+%3D+%27Closed+Won%27+and+Amount+IS+NOT+NULL' 
```

Error:
```
sql: expected 4 destination arguments in Scan, not 3"
```

----

This can be repeated if you construct a chart with 2 metrics using the same field and function.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1500447/201380115-2448d063-e38d-43cd-aa96-f44be71f3db5.png">

**Comment by darh** [comment]
All fixed now.

**Comment by Bojan-Svirkov** [comment]
Looking good. Just tested it and moving it to Done.

**Comment by darh** [comment]
Changelog text can be picked out the 88bafc2.
