### ISSUE TITLE
Update de-duplication UI on module and fields configuration pages

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#467]
Follow the mockups. @vicpatel will provide details and payload examples.

![Image](https://user-images.githubusercontent.com/1500447/201123414-466b3797-9cdd-4c9d-ae14-07379f5aecab.png)

![Image](https://user-images.githubusercontent.com/1500447/201123372-d337b3b4-b35f-4458-be12-fd6d0f0745cc.png)

**Comment by kelanik8** [comment]
![image](https://user-images.githubusercontent.com/23015247/205591068-5a55f732-95bf-43bb-bc7a-be75f4b57532.png)

**Comment by kelanik8** [comment]
![Image](https://user-images.githubusercontent.com/23015247/206464197-fa0ac839-c932-4a28-a125-701f89d8a1c6.png)

**Comment by kelanik8** [comment]
@Fajfa https://github.com/cortezaproject/corteza/pull/617

**Comment by Bojan-Svirkov** [comment]
couple more things need to be addressed, already discussed with Tolu.
So when you have soft validation, an error is popping up saying that you cannot create the record and to check the form, but there is no message on the form and the record is actually created. So this needs to be looked into.

**Comment by Bojan-Svirkov** [comment]
I retested this again, and when I go into an existing namespace with a module this is what I am seeing in the module under the `unique values` tab. The constraints are empty but it looks like they are added. Check the screenshot for more details:
![image](https://user-images.githubusercontent.com/53232926/214057591-193c8b2e-acde-4033-9b69-26ddea114fc7.png)

Also I tested all of the value modifiers and I don't receive the expected behavior for the `Ignore case` modifier. The others seems to be working fine. Please look into this again.

**Comment by Bojan-Svirkov** [comment]
We should not be able to configure the same field to be added in both of the constraints
![image](https://user-images.githubusercontent.com/53232926/214341838-386f02e4-b46b-4e1e-8f18-6ffbb0ce4358.png)

And also the trash delete cans needs to be aligned a bit more so they will be centered

![image](https://user-images.githubusercontent.com/53232926/214342205-68d27088-ee0f-4911-91ba-cb52cc36a695.png)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. The only thing now left is the CL entry.

**Comment by vicpatel** [comment]
changed:

• What changed
-- Updated module validation rules for unique value constraints previously used as validation for record duplication detection.

• Why did it change
-- To extend support for record duplicate detection with multiple fields in single rule with various detection algorithm and muli-value matching criteria.

• How did it change
--  Extended record duplicate detection configuration to support multi value matching criteria and value checking algorithms.

**Comment by kelanik8** [comment]
Changelog

**What changed**
- Revamped the de-duplication UI with a new tab called unique value
- Added Unique validation constraints options on Field validation configuration


**How did it change**
- Added a new tab Unique value with option to add and remove constraints
- Added a checkbox for each constraint for soft duplication
- Field can be searched and added to a constraint
- Each field in a constraint can configure the value modifier type and for Mutli-value if the field happens to be a multi-field value type

**Comment by Bojan-Svirkov** [comment]
Added CL
