### ISSUE TITLE
Sorting resource by "last-change" does not work as expected

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#468]
As reported by @Bojan-Svirkov 

> I just came a cross this case, so when you are for example in the namespace list in compose and you sort them by last change, the order is mixed up and the namespaces are not sorted in the correct order. Same thing for workflows, when I sort them by `Updated at` you can see from the video that the order is mixed up, we have entries one by one September, October and then August which cannot be, they need to be in the correct order one by one. Currently I just noticed this on Compose and Workflows but it is possible to be present also on other places. I see that some of the formats where changed from `11/09/2022`, to `Wednesday, November 9, 2022 at 7:01 AM`, so this could be also the mix up. Also from the screenshot you can see that the order is mixed up.

![Image](https://user-images.githubusercontent.com/1500447/201127300-46368efb-df75-433c-9df4-ecdf3d44de60.png)

---

@Fajfa 

> we sort by updatedAt but show either updatedAt || createdAt
> 
> If we want a proper solution we need to discuss it a bit, so next sprint.

----

- [x] NS list
- [x] Module list
- [x] Charts
- [x] WF list
- [x] Other places?

**Comment by Bojan-Svirkov** [comment]
There are still some issues on this. Waiting on Vivek to address them.

**Comment by Bojan-Svirkov** [comment]
When you sort by last change, the view is kinda broken, meaning always the same results are shown even if you press next page. The total record count is also surpassing the total records we have if we continuously press next. @vicpatel please check this.


https://user-images.githubusercontent.com/53232926/204781639-74e6be1e-360a-497e-92b6-6eec581af252.webm

**Comment by Bojan-Svirkov** [comment]
@vicpatel Now everything looks good and the only part left is the Changelog entry. Please include it. Thanks.

**Comment by Fajfa** [comment]
What was fixed:
- The namespace, module, page, workflow, and reporter lists now properly sort the last change column.
Previously the sorting was done on the updatedAt value and the value was shown as updatedAt or createdAt if the resource wasn't updated yet.

How was it fixed:
- The webbapps can now use the `coalesce(deletedAt, updatedAt, createdAt)` to sort based on all three columns, so that the value displayed matches the value that is being used to sort

**Comment by vicpatel** [comment]
Added#

What was added:
- Added support for `coalesce` sorting on all supported store driver.

Why was it added:
- To allow sorting of first non-NULL value among given columns into one column.

**Comment by Bojan-Svirkov** [comment]
Added CL entry. @Fajfa & @vicpatel you can close this issue.
