### ISSUE TITLE
Optionally send invitation email when a new user is created by an administrator

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#469]
- [x] Add template that will be used for sending (similar to one we have for password-reset)
- [x] Extend `users add` CLI command with `--send-email` flag
- [x] Extend the user-create endpoint and add prop to request to trigger email sending when new user is created
- [x] Checkbox for admin console that should be checked for email to be sent

 Ref: #430

**Comment by katrinDY** [comment]
For today: add finishing touches to functionality for 3rd checkbox and start working on 4th checkbox

**Comment by KinyaElGrande** [comment]
Moving this back to sprint backlog and focus on https://github.com/cortezaproject/corteza/issues/995

**Comment by katrinDY** [comment]
For today: continue working on the last two checkboxes

**Comment by tjerman** [comment]
Get a PR going by monday morning

**Comment by tjerman** [comment]
Will have a PR ready for me in a bit

**Comment by katrinDY** [comment]
@KinyaElGrande write down the progress of the two edge cases and what issues there are

**Comment by KinyaElGrande** [comment]
### Edge case:
1. when the email service (Outlook SMTP) clicks on every link in the email, causing every token to expire on delivery.

### Consideration:

1. use the password reset flow in implementing send invite token to the user.

**Comment by KinyaElGrande** [comment]
**Update**: I think using the password reset flow to implement sending an invite token to a user may not be appropriate, as the two features have different purposes and may require different validation, for example, password reset link requires the password reset setting to be enabled.

**Comment by katrinDY** [comment]
for today: ping Tomaž to discuss blocker after language task is finished

**Comment by EmmyMay** [comment]
For Today: Take a look at the edge case.

**Comment by KinyaElGrande** [comment]
**Update**: I have tested a couple of times using (Outlook SMTP) and can confirm that the token remains valid even when the email is opened in an Outlook mail server.

**Comment by katrinDY** [comment]
for today: Tomaž to check task and decide if it's ready for QC

**Comment by KinyaElGrande** [comment]
For today: Address the comments on the PR.

**Comment by yonkov** [comment]
For today: Finish addressing the comments on the PR.

**Comment by katrinDY** [comment]
for today: address comments on PR and merge task
