### ISSUE TITLE
Support for conditional fields [PlanID:2023.3/48/2.6]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#478]
This is a basic implementation of conditional fields for the **record page block**. It provides a way for users to control fields that should be hidden or shown by checking the current context and values of the current record.

Examples:
 - when the selected age is 18 or more, show the field for gender
 - when the occupation is developer, show text input for a favourite IDE

The condition expression is written in JavaScript and executed inside a browser using **eval**. There might be other expression languages and execution environments provided in the future. 

Configuration for conditional fields is stored under record block options and not on the field!

- [x] extend `lib/js/src/compose/types/page-block/record.ts` to support field conditions
- [x] make sure implementation is future-proof (eg, allow extension to other languages for conditions)
- [x] configurator must warn/prevent users when adding a conditional view to required fields

**Comment by tjerman** [comment]
- discuss required fields
- consider limiting the allowed operation set (what functions, operators, ...) are allowed so it will be easier to extend/improve/move to gval (consistency) in the future

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/214353706-98846aef-f4d9-4273-8a60-f168871dd724.png)

**Comment by Bojan-Svirkov** [comment]
I just tested this and there is small issue. When you have a condition, and you try to add a record, the condition is being evaluated even before a values are added and it this case we receive an error (picture below). So I guess the condition should first wait for values to be entered and then to do it's evaluation.

![image](https://user-images.githubusercontent.com/53232926/219647489-d5d8c04e-1c00-443a-81d3-d887856fa17f.png)

**Comment by EmmyMay** [comment]
We need to take a look at checkboxes. Users have to save before its value get evaluated.

**Comment by katrinDY** [comment]
Discuss this with Jože

**Comment by EmmyMay** [comment]
# Changelog Entry

## Added

### What was added?

**Fields in records can now be displayed based on evaluated expressions.**

### Why was it added?

**To give users more control on how records are displayed**

**Comment by Bojan-Svirkov** [comment]
Tested this and I can confirm that this works as expected. Added CL entry as well. Moving the card to **Done**.
