### ISSUE TITLE
Allow users to navigate to previous and next page [PlanID:2023.3/15/1]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#480]
## About

Expand navigation when inside a record page to allow you to go to the next/prev record.

This could be achieved by extending what the record read endpoint returns by including the next/prev page cursors.
If we do decide to use paging cursors we need to be careful how to handle update like operations since they could break the order and not work as expected.

## Important

if you're editing records it might not be stable to rely on page cursors since they are applied as filters.
In some cases, the next page cursor could mean the exact same record.

## User stories

As a user I can use prev/next buttons on record page when coming from a record-list because  I want to be able to access next/prev page

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. The only thing left now is the CL entry.

**Comment by kelanik8** [comment]
Changelog

**What changed**
  - Added support to allow users to navigate to previous and next record page
  - Added a checkbox to enable the record page pagination on the configurator record list
  - Added pagination of modal and same tab view of the record
  
  
**Why did it change**
  - To allow users to navigate to previous and next record page
  
**How did it change**
  - Added previous and next buttons on the record page
  - Added logic to support pagination on modal view and same tab view

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL entry
