### ISSUE TITLE
Inline editing in record lists [PlanID:2023.3/1/1]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#481]
## About

Provide inline editing for record lists outside of record pages (on regular pages).
The feature should feel similar to how the current inline editing feels like.

## User stories

As an administrator, I can select an option in the block configuartion to enable inline editing of top level record lists in the same manner as I now can for record lists embedded on a record page.

As a user, I can edit the data in certain pre-selected columns (by administrator) directly in the top level record list without having to enter the record.

## UX suggestion from Lenny

1. Hover over the cell in a "record list" page block, or a field in a "record" page block and the edit button shows.
2. Click the edit button to edit the field (and just that single field).
3. A modal pops up with that single field. This could be the same model like in point 2 (the record modal window), but showing just 1 single field in editing mode (nothing more), and a cancel + save button.
4. When cancel is hit, the modal closes. When save is hit, the record is saved with this new value, and the page is refreshed if all is ok (because there might be formula fields or workflows linked to the field.

**Comment by Bojan-Svirkov** [comment]
Everything works as expected. Moving the card ahead.

**Comment by Bojan-Svirkov** [comment]
Added the changelog:

```
{
      "what": [
        "support for inline editing in record lists."
      ],
      "why": [
        "to allow user to easily edit a record by just hovering on the field and pressing on the edit button."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/956/commits/363afde876a22b454dc324b870902c5a9f70bb84"
      ]
}
