### ISSUE TITLE
Allow users to manage their profile photo [PlanID: 2023.3/27/1.5]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#483]
Administrators can enable (default) or disable if users can set their own profile photo in the auth/profile pages. The profile photo is either an uploaded photo or custom initials (1-3 ASCII characters) with a custom background and text colour. Administrators can also upload and set the initials with colours for any user via the admin panel.

The profile photo is then used on the top navigation on the right side.

-----

 - [x] for image - we accept JPEG and PNG formats, max size (propose)MB, resize to (propose)x(propose)px dimensions.
 - [x] admin can enable/disable photo upload (enabled by default)
 - [x] admin can enable/disable "the initials" feature (enabled by default)
 - [x] create a special endpoint to serve profile photos for users, accepts user-id and dimensions (resized on-demand)
 - [ ] in-browser resizing and cropping is a bonus.

**Comment by KinyaElGrande** [comment]
Moving this issue to the backlog and focus on https://github.com/cortezaproject/corteza/issues/682.

**Comment by katrinDY** [comment]
For today: address FE and BE comments and re-submit for a review.

**Comment by katrinDY** [comment]
For today: ping Jože to review FE code

**Comment by KinyaElGrande** [comment]
Additional functionality has been added to the avatarInitials image generation when creating a new user:


1.  If the user's first name is available, the initials will be the first two letters of the name (e.g., `John => JO`).
2. If the user's full name is available, the initials will be the first character of the first and last names (e.g., `John Doe => JD`).
3. If the user has three or more names, the first three characters of the first, second, and third names are taken to form the initials (e.g., `John Doe Test => JDT`, `John Doe User Test => JDU`).
4. If the user's handle exists and their name doesn't, the initials will be the first letter of the handle (e.g., `john => J`). If the handle contains delimiters such as `., _, or -`, the handle name is split using those delimiters, and the first letter from the first and second parts is used as the initials (e.g., `john.doe => JD`, `john-doe.me => JD`, `john_doe.me-you => JD`).
5. If both the name and handle don't exist, the initials will be the first letter of the email (e.g., `john.doe@tld.dev => J`). If the email name contains delimiters before the @ symbol, the email name is split using those delimiters, and the first letter from the first and second parts is used as the initials (e.g., `john.doe@tld.dev => JD`, `john-doe.me@tld.dev => JD`, `john_doe.me-you@tld.dev => JD`).

**Comment by katrinDY** [comment]
BE and FE changes are required. Will need a day and a half to add them

**Comment by katrinDY** [comment]
For today: add FE changes discussed with Jože and submit a PR in 3 hours

**Comment by KinyaElGrande** [comment]
For today: Finalize on the changes discussed with Jože, address Peter's comments, and Move the issue to QC before EOD.

**Comment by katrinDY** [comment]
For today: add BE tests and submit for review. Jože to take care of the remaining FE changes on admin

**Comment by katrinDY** [comment]
For today: apply fix discussed with Peter and submit BE for review in 1h

**Comment by katrinDY** [comment]
For today: sync with Tomaž reg. issue and discuss with Jože what will be done afterwards

**Comment by Bojan-Svirkov** [comment]
Added CL entry:
```
{
      "what": [
        "support for managing and generating user's profile picture."
      ],
      "why": [
        "to provide users with greater flexibility and customization options for their profile avatars, while also allowing admins to manage avatars on behalf of users."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/887/commits/e24b391e5b1dc539855122534a4394a6868c4afd"
      ]
    }
```
