### ISSUE TITLE
Support richer links to pages on sidebar, allow use of icons [PlanID: 2023.3/16/1.7]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#484]
- [x] Allow integrators to upload an icon for the sidebar
 - [x] Allow integrators to select one of the previously uploaded icons for the sidebar
 - [ ] Allow integrators to select icons from the library of the sidebar
 - [x] Allow integrators to explicitly select pages that expand

**Comment by katrinDY** [comment]
What's accomplished on the FE so far:
- added a button that opens a modal. In the modal, there will be two sections. One for uploading an icon and another for listing the previously set page icons. The two sections will be split with an `<hr>`
-  added a checkbox for toggling whether to show subpages of a page or not

![Image](https://user-images.githubusercontent.com/85161724/215539905-26fe63b1-05bb-4225-94f1-f7e5aa6169df.png)
![Image](https://user-images.githubusercontent.com/85161724/215539904-20bb1708-d2d7-4130-9197-50eb9d827b67.png)

**Comment by vicpatel** [comment]
As we discussed, We will use existing `/namespace/{namespaceID}/page/{pageID}/attachment` endpoint to upload page icons and meta info will be saved on `page.config.navItem.icon` struct.

```
PageConfigIcon struct {
	// "attachment"
	// Reference (ID) to an existing attachment in local Corteza instance is expected
	// This type and reference must be validated by the backend.

	Type string `json:"type,omitempty"`
	Src  string `json:"src"`

	// Any custom styling that should be applied to the icon
	Style map[string]string `json:"style,omitempty"`
}
```

**Comment by tjerman** [comment]
* Define an icon gallery on some administration page where you can upload icons that can be used within Compose pages (you can use the Compose attachments for that)

On page configuration

* Define a section to upload an SVG as an icon (store it directly in the page meta)
* Define a search to select an icon from the galery
* Define a search to select a FA icon.

**Comment by katrinDY** [comment]
We won't be adding a search to select a FA icon (discussed with Jože). The rest will be added

**Comment by katrinDY** [comment]
Added mx size and file type whitelist in admin's compose settings

![Image](https://user-images.githubusercontent.com/85161724/220391482-27126f82-fe45-4aca-b5e8-25c0541879bc.png)

**Comment by katrinDY** [comment]
Added functionality for setting link as page icon

![Image](https://user-images.githubusercontent.com/85161724/220986495-08ce4ce2-3de2-4b07-a844-26a164fca6db.png)

**Comment by katrinDY** [comment]
For today: finish up with styles for select and download btn. Take a look at UI to see if anything more needs to be added

**Comment by katrinDY** [comment]
Preview of the gallery items and their icon buttons. This demo is in FileBase because BE endpoint for retrieving a list of icons doesn't work as expected. The same view will be present on page edit.

![Image](https://user-images.githubusercontent.com/85161724/221849253-dc4276de-a97e-43b6-bcbf-6d7f11d00ebf.gif)

**Comment by katrinDY** [comment]
Demo of view, select/unselect and download buttons

![Image](https://user-images.githubusercontent.com/85161724/221930253-d61c8d8e-a24c-4a01-b54e-4bdbd05ecfb1.gif)

**Comment by katrinDY** [comment]
What's left to be done:

- upload attachment and fetch list of icons endpoint need to be fixed
- preview link as icon
- expand list of pages in sidebar
- show page icon next to page title

**Comment by katrinDY** [comment]
For today: if the remaining BE changes are added, continue working on this. Else, work on record list filter task

**Comment by katrinDY** [comment]
Preview for link added

![Image](https://user-images.githubusercontent.com/85161724/223181798-a3b9837f-5a5c-433f-b31b-13b4c3455fd3.gif)

**Comment by katrinDY** [comment]
Page expand functionality added:

![Image](https://user-images.githubusercontent.com/85161724/223181937-70cfd75f-ed05-4ee7-9939-c5fa7b1ae987.gif)

**Comment by katrinDY** [comment]
For today: research on how to display page icon in sidebar and implement the functionality

**Comment by katrinDY** [comment]
Show page icon in the sidebar (link set as icon):

![Image](https://user-images.githubusercontent.com/85161724/223503003-cfcc7ce0-6df0-4e30-a2f0-99a9223920b5.gif)

**Comment by katrinDY** [comment]
For today: style list of page icons and choose what styles to use when selecting a page icon

**Comment by katrinDY** [comment]
New way/style of selecting an icon:

![Image](https://user-images.githubusercontent.com/85161724/224091622-f65141f1-16f8-4116-99a7-82fe041c65b1.gif)

**Comment by katrinDY** [comment]
For today: sync with Vivek reg list page icon and upload attachment endpoints. Figure out why they aren't working as expected and apply the needed fixes

**Comment by katrinDY** [comment]
For today: take a look at upload type being sent when uploading an attachment. Afterwards see and discuss what more needs to be done

**Comment by katrinDY** [comment]
Fetching of page icons and attachment upload are now working.

Todo:
- make sure an attachment can be selected and set as an icon
- either select an attachment as a page icon or upload a link
- change the page icon a couple of times to confirm this works
- refactor code

**Comment by katrinDY** [comment]
For today: complete the remaining things to be done and submit the task for code review

**Comment by katrinDY** [comment]
svg files will be supported in a future version. A lot of changes need to be done which will delay the feature

**Comment by katrinDY** [comment]
Todo:
- [x] fix broken icon link in sidebar for attachments
- [x] in admin set 10 as default max size
- [x] when uploading an attachment show the right message if an attachment file is whitelisted
- [x] mark selected page icon on icon list fetch
- [x] refactor code if needed

For today: complete todo list and if everything is ready submit code for review. If not, apply fixes and  submit code for review tomorrow at the latest

**Comment by katrinDY** [comment]
For today: focus on this task. Address any comments and make sure task moves forward to "Done"

**Comment by katrinDY** [comment]
For today: address the rest of the comment from PR and submit to QC

**Comment by Bojan-Svirkov** [comment]
Found a small issue where when you add an icon and after saving the icon if you do any change on the page visibility toggle or the expand toggle the icon is getting erased after saving the changes. Providing also a video of this case:

[bf336c10-400a-42ea-a48a-81d6ac07d268.webm](https://user-images.githubusercontent.com/53232926/227032848-88466c48-ba15-46b4-9c22-87e4140f9b7c.webm)

**Comment by katrinDY** [comment]
Added fix for the reported bug. Moving to QC

**Comment by Bojan-Svirkov** [comment]
Retested and confirming that now everything works as expected.

**Comment by katrinDY** [comment]
CL:

What: Added support for page icon and  the option to expand subpages in the sidebar

Why: The page icon was added to allow the user to further customize a page. The expand sub-page option was added to improve access to subpages. When the option is enabled, the user can always see sub-pages without having to constantly expand the parent page.

Commit for 23.3: 72d44713f26cd4d6cfc10a0b4a35abf00ea9394e

**Comment by Bojan-Svirkov** [comment]
Added CL. Moving the card to Done.
