### ISSUE TITLE
Add support for record list filters [PlanID: 2023.3/5/1]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#485]
## About

We want to enable administrators to define a set of record list filters which users can quickly apply to their record list(s).

### How

When configuring a record list, an administrator can define a set of record list filters grouped by role.
When a user is viewing a page with some record list, they can see that list of stored filters at the top of the record list depending on their roles.

### Extra

Users can also define their own _personal_ record list filters which are shown in addition to the admin-defined ones.

**Comment by katrinDY** [comment]
Note to self: Discuss plan with Peter and Jože

**Comment by katrinDY** [comment]
For today: get familiar with the task and make a plan

**Comment by katrinDY** [comment]
For today: take a look at the ticket, make a plan and sync with Peter to discuss it

**Comment by katrinDY** [comment]
Update: a couple of things popped up reg. https://github.com/cortezaproject/corteza/issues/484. Will take a look at this task tomorrow

**Comment by katrinDY** [comment]
For today: ping Jože to confirm if I'm on the right track with my plan. Ping Peter to discuss implementation and start adding the code

**Comment by Bojan-Svirkov** [comment]
The first part of this ticket works and looks good. Moving it back to sprint backlog so that the fix for limiting the filter to one role can be further implemented.

**Comment by petergrlica** [comment]
BE commit: https://github.com/cortezaproject/corteza/commit/9759e84a0415dd005e22edd2965a39d04e0d128d @Fajfa

**Comment by Bojan-Svirkov** [comment]
Retested and confirming that this works as expected. The only missing part now is the CL entry.

**Comment by kelanik8** [comment]
**Changelog**

**What changed**
- Record list fitlers can configured on the record list configurator
- Record list filters in the configurator can be grouped by roles
- The record list filter configured can then be applies quickly from the filters dropdown


**Why did it change**
- So users can quickly apply filter to the record list

**How did it change**
- Updated record list configurator with the logic to add and group record list filter based on roles
- Updated the record list base with a filter dropdown of the list of the configured record list in the configurator

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added Cl.
