### ISSUE TITLE
Support for Bulk record updates [PlanID: 2023.3/6/0.5]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#488]
As an administrator, I can select an option to allow bulk updates of specific columns in a record list.

As a user, I can select the records I wish to update in a record list, then select the column, then add the value to which I wish to change all selected records.

As a user I'm informed about skipped locked-for-editing records after bulk update because I want to be informed about skipped records.

DevNote: backend must gracefully skip locked records and inform

**Comment by katrinDY** [comment]
For today: add endpoint for bulk record update

**Comment by Bojan-Svirkov** [comment]
I just tested this and I can confirm that this works as intended. The only thing left out now is the CL entry.

**Comment by kelanik8** [comment]
**Changelog**:

**What changed**
- Added the option to enable the bulk update in the record list configurator
- Added support for bulk record updates, by selecting records on the record list and then click on the edit button at the top right of the record list table,  which toggles the bulk update modal
- Added option to select and update multiple fields on the bulk update modal

**Why did it change**
- Users can update multiple records in a record list

**How did it change**
- Updated the record list configurator with a new option to enable the bulk update functionality
- Updated the record list base with bulk edit modal

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL. Moving the ticket to **Done**.
