### ISSUE TITLE
Resolve references on record import [PlanID: 2023.3/37/0.6]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#489]
Investigate when the issue in regards to resolving references such as other records and users occurred and address it as this feature should have been implemented a long time ago with the initial importer versions.

**Comment by tjerman** [comment]
It's still working, we just have it disabled on Compose's interface. When I removed the code that prevents users from using those values, it works fine:

![Image](https://user-images.githubusercontent.com/12545711/225557336-72d82874-18a3-414c-b4c7-ed3479d152dd.png)

At this point I can't recall why we disabled it, I just know we made a sane decision to do so. @Fajfa can you recall? Should we re-enable record and user fields?

**Comment by tjerman** [comment]
## Changed

## What

record import modal to allow users to map values to record and user fields

## Refs

2022.9.x monorepo commit `0cf81dc45`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL was also added so moving the card to Done.
