### ISSUE TITLE
Statistics for Store and DAL operations

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#492]
Provide a document which notes performance for various operations under the reworked record storage (DAL).

The original sheet with numbers and operations can be found here https://docs.google.com/spreadsheets/d/127Bot4ExWkc3fwb0BL15Uv8QMse1pAbHROfa62Yz0s4/edit#gid=1553278367

The majority of the heavy lifting is already done in the sheet itself where the goal here is to nicely present findings and flex the numbers a little bit.
Additional measurements can also be captured but consult @tjerman in regards to that as he (I -- I'm editing this comment :) has some scripts that automated the process.

- [x] figure out what sort of data we want to show and what metrics we want to focus on
- [x] document and express the findings

**To consider**

Perhaps it would be best to simply offload this work onto those benchmark scripts since this sheet (except for charts) was generated by it.

- [x] Check if there is any web service/asciidoc plugin that can render charts (consider this https://quickchart.io/)

**Comment by tjerman** [comment]
Will be available with the next patch release
