### ISSUE TITLE
Change the color of approving a request checkmark in privacy (for consistency)

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#494]
Currently let's say when rejecting a privacy request, the button is red and when you click on it the checkmark for confirming is also red, but when we press on approve, the approve button is blue but it's checkmark for confirming the action is again red, so let's try to change the approve checkmark on the approve request button to be also blue.

![Image](https://user-images.githubusercontent.com/53232926/201366159-a1f0c606-a291-4bdf-a7bf-ac8bf5975c73.png)

![Image](https://user-images.githubusercontent.com/53232926/201366185-8ef5d4ee-bc1f-4efb-960b-9b764bbd166c.png)

![Image](https://user-images.githubusercontent.com/53232926/201366209-a13984de-155a-4408-a978-8b442253e14b.png)

**Comment by Bojan-Svirkov** [comment]
Denis: This must be rethought a bit (not only the colours part, the whole ux). I'll prepare and schedule for the next sprint.


Just set variant-ok="primary" (or whatever it needs to match the approve's button colour) on the approve-request button.

**Comment by katrinDY** [comment]
branch name for:
- 23.3 2023.3.x-feature-improve-btn-consistency-in-privacy
- 22.9 2022.9.x-feature-improve-btn-consistency-in-privacy

**Comment by Bojan-Svirkov** [comment]
Just tested this and I can confirm that this is now looking good. 

@katrinDY Can you just include the entry for the ChangeLog here on the ticket?

**Comment by katrinDY** [comment]
@Bojan-Svirkov

Changelog:

Changed:

What: The color of the button for confirming the action to accept a privacy request was changed.

Why: This was done to match the same color pattern as the colors when confirming/denying the action to reject a privacy request. This also improves consistency and UX.

How: The color was changed to dark blue.

- 2022.9.x: [d4ed9ff](https://github.com/cortezaproject/corteza/commit/d4ed9ff53965b85f97a66d15214f526461392210)
- 2023.3.x: [8379518](https://github.com/cortezaproject/corteza/commit/83795183f21a36afb1dbcc317458cbc48c46b6c4)

**Comment by Bojan-Svirkov** [comment]
Added to the CL.
