### ISSUE TITLE
SMTP send an email button

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#497]
It will be really beneficial if we have a test button in SMTP server setting in admin that will automatically trigger an email to be sent by clicking on it. This will come in handy when testing SMTP server settings, MailHog and other features.

**Comment by KinyaElGrande** [comment]
This is a new feature that has 2 sections : 

1. Test configuration (connect and ping `HELO`  to the server)
2. Send an actual hello from Corteza to custom email address (pre-filled with mail of the current user)

V1 should validate the following bits

-  host & port -- are the params correct and can we ping the server
-  username & password -- are the params correct and can we authenticate
-  connectivity -- can we connect to the server

**Comment by KinyaElGrande** [comment]
**What was added**
`Test SMTP server` button

**Why was it added**
When the button is clicked, it tests SMTP configuration settings and sends a test email to  the `sender address `.

If the SMTP configuration settings is **OK** a success toast message  `SMTP configuration check passed` is displayed.
<img width="1064" alt="Screenshot 2022-11-28 at 12 26 53" src="https://user-images.githubusercontent.com/32476094/204242716-0ac00560-d9ad-49d3-9f05-9caee98b05b9.png">

If SMTP configuration settings is **NOT OK** , warning toast message(s) regarding configuration inputs are displayed.
<img width="1068" alt="Screenshot 2022-11-28 at 12 27 08" src="https://user-images.githubusercontent.com/32476094/204257558-cc642a9d-bafb-41c6-b95f-8d6832461b5e.png">

**Comment by Bojan-Svirkov** [comment]
Configuration checker is getting stuck on `Pending`. Same thing also happening for Mumbi so moving back this to In progress.

**Comment by Bojan-Svirkov** [comment]
Finally I am happy with how this works. This is now working as expected so I just also added the CL entry so I am moving the card to **Done**.
