### ISSUE TITLE
Issues on mobile devices; portions of the screen "cut off"

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#500]
ref: [https://forum.cortezaproject.org/t/save-button-in-mobile-browser-not-visible/924/4](https://forum.cortezaproject.org/t/save-button-in-mobile-browser-not-visible/924/4 "smartCard-inline")

Samsung S20 (the normal sized one)

On 1) I can’t see the record page’s toolbar because the browser’s toolbar is hiding it. My suspicion is that the body of the web application is not scrollable (but some div inside of the body as the main content div) the browser won’t detect that you’re scrolling and hide it.

On 2) the last application on Corteza One is cut off half way through

On 3), the auth pages, I can’t see the top part with the button to all apps, log out, …

![Image](https://user-images.githubusercontent.com/53232926/201655992-2306ed34-b44d-4268-9667-4aee7f088bdc.png)

![Image](https://user-images.githubusercontent.com/53232926/201656038-b14164f2-f92b-400d-9da0-50f7fd11abb3.png)

![Image](https://user-images.githubusercontent.com/53232926/201656064-5a9c0243-9206-42b2-a457-b4dfaff5d3c1.png)

Comment from Mia: As expected, this is not as trivial due to mobile browser bar behaviour. Need more time and probably Jože's input.‌

**Comment by Fajfa** [comment]
Fixed the auth screen on mobile views,
Fixed topbar not being fully visible on smaller screens (Avatar was disappearing)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is looking good. Now the only thing left is the CL.

**Comment by Fajfa** [comment]
### What was fixed
Only on mobile views:
Fixed login form covering up the topbar on auth screens. 
Fixed not being able to click the avatar button in topbar on certain views

### How was it fixed
By adjusting the styling of the auth screens and the Corteza topbar

**Comment by Bojan-Svirkov** [comment]
Added the entry to the CL.
