### ISSUE TITLE
Using roles inside RBAC: Allow operation on resource to a role fails to determine the role ID

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#504]
When you use the RBAC: Allow operation on resource to a role workflow function and you pass in an already fetched role like so:

![Image](https://user-images.githubusercontent.com/12545711/201958671-5875e27c-0eb9-449d-b804-3402f42fc215.png)

The role ID is incorrectly determined and the RBAC rule is saved like so:

![Image](https://user-images.githubusercontent.com/12545711/201959006-a4c5a79f-b7e4-4b4a-ab95-e7820ece32bc.png)

Notice how the ID is 0.

If you change the function arguments like so:

![Image](https://user-images.githubusercontent.com/12545711/201959640-d1a1c997-d031-426f-bebb-c73f1f947930.png)

The output is correct:

![Image](https://user-images.githubusercontent.com/12545711/201959458-d615b1cc-8e8f-4670-80ff-cc38eb5d8b40.png)

**Comment by tjerman** [comment]
Prereq: https://github.com/cortezaproject/corteza/issues/602

**Comment by tjerman** [comment]
Resolved https://github.com/cortezaproject/corteza/commit/6a14808af

## Fixed

### What

RBAC rules not applying when assigning them via workflows when providing the role via the `Role` type.
The workflow didn't raise any errors, but the saved RBAC rule was invalid (the `roleID` was set to `0` -- invalid).

### How

By updating the automation handler code to check all of the supported types and not just the `roleID`.
The handler logic was only using the `roleID` parameter and omitting the others.

**Comment by tjerman** [comment]
To check this

1. make a new workflow with some onManual trigger (any trigger would do, but manuals make it easy to test)
2. add a template lookup function and point it to some template
3. add a role lookup function and point it to some role
4. add a RBAC: Allow operation... function
5. open the admin panel, go to the template you entered in the template lookup function, open the RBAC rule modal
6. run the workflow
7. re-open the RBAC role modal and see the change applied

**Comment by Bojan-Svirkov** [comment]
Just finished testing this and I can confirm that now the ID is present and this works as expected.

![image](https://user-images.githubusercontent.com/53232926/207293130-999903e9-58c0-4e89-9e91-df04c037d00e.png)

The CL was also added.
Moving the card to **Done**.
