### ISSUE TITLE
Compose page duplication name improvement

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#509]
When you create couple copies of a page they are named as:

Page
copy of page
copy of a copy of a page

![Image](https://user-images.githubusercontent.com/53232926/202168448-2b690441-ce3f-444d-95ed-5c3d26aac417.png)

and so on respectively, so if we create 3-4 or more the naming kinda gets confusing and long, so let's try to improve the naming for example if we have test page, instead of saying copy of a test page, and after that copy of a copy of a test page, let's do this like:

Test
Copy of Test
Copy of Test (1)
Copy of Test (2) 

and so on.

**Comment by yonkov** [comment]
## Changlelog

### What was changed

When you go to admin => pages and edit a specific page, you have an option to clone existing page by clicking on "Save as Copy" button. (Another way to clone the page by going to the page builder of the specific page). When you click on "Save as Copy" button, a new page is generated and its title recomputed. If no other copies of the old page exist, the title of the new page is constructed by adding a prefix "copy of" to the page title. If other copies exist, a number is added as a sufix to the page's name. To give an example, if you copy a page, called "Test", the new page will become "Copy of Test". If you copy "Copy of Test", it will become "Copy of Test (2)" and so on:  

Test
Copy of Test
Copy of Test (2)
Copy of Test (3)

In previous versions of Corteza, the copied page was always prefixed with 'copy of'. If we continue with the same example as above, the page dublication process  used to look like that:

Test
Copy of Test
Copy of Copy of Test
Copy of Copy of Test
Copy of Copy of Copy of Test

### How was changed

In Compose, two files have been adjusted, `views/Admin/Pages/Edit.vue` and `views/Admin/Pages/Builder.vue`. The namespace's pages have been programatically filtered to find how many times a certain page with same name already exists by excluding 'copy of' prefix and number sufix. Depending on the number of pages that match the same name, a counter is adjusted. 

### Why was changed

If we copy a page 3-4 or more times, the naming gets confusing and too long. Reshaping this aims to improve user interaction across Corteza.

**Comment by Bojan-Svirkov** [comment]
Tested and Cl added. Moving the card to **Done**.
