### ISSUE TITLE
Record selection count improvement

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#510]
Currently if we have let's say 20 records and they are divided into two pages, and if I select for example 1 record from the second page the title is saying `1 of 5 records selected` (because we have 5 records on that page), so I guess we will need to change the logic here so when we select a record to be taken out/counted from the total of all records so the record to say `1 of 20 records selected`

![Image](https://user-images.githubusercontent.com/53232926/202169829-11684303-5361-446e-a911-5343d83028fc.png)

**Comment by darh** [comment]
This could be a bit misleading if we do not have "select all on all pages".

This is a separate functionality. Deprioritizing this for now.

**Comment by Bojan-Svirkov** [comment]
This is now obsolete since we are working on another feature that will allow us to select all the records from all pages so we can either edit or delete them so that interconnects with this functionality. Closing this ticket since we no longer need it.
