### ISSUE TITLE
When NS is without a handle the sidebar misbehaves

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#511]
When you create a NS without a handle, The sidebar details are not displayed (pages, modules, charts, you can see this more clearly in the vide below), and when you add a handle to the same NS, the sidebar is fully shown. 

Also, once a handle is added if you erase the handle again and try to save the NS, you are receiving error saying `Could not save namespace application: field name is empty` (and the field name is actually not empty) and also in the same time getting success message `Namespace saved`, so this is not good we will need to improve this. So the NS gets saved even though we are receiving that error message. So let's see what we can do here.

![Image](https://user-images.githubusercontent.com/53232926/202187872-f2d0dceb-c5a6-4ed0-b615-2fd58c92879a.png)

https://user-images.githubusercontent.com/53232926/202187880-f14aefce-a5a9-439e-8a6d-01cd9a02828e.webm

**Comment by Fajfa** [comment]
Since this has been fixed before release, no changelog is needed
https://github.com/cortezaproject/corteza/commit/65ea8f0087b17ca9cbbcaa654a0ac15c8a050e8a

**Comment by Bojan-Svirkov** [comment]
Everything now works as expected and since no CL is needed I am moving the card to `Done`.
