### ISSUE TITLE
Unable to import a namespace without a handle

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#512]
Two issues here:
- when trying to import a namespace without it having a handle, I get ![Image](https://user-images.githubusercontent.com/85161724/202189038-1a83d827-495c-426b-971b-35fdc5196670.png)
- if I try to import a namespace with a handle => no issues with this part => the options to add a full and short name are presented (![Image](https://user-images.githubusercontent.com/85161724/202190272-d6a95f3f-5dae-42af-9d08-7ad03231d2d9.png)) => here I don't add a handle and get ![Image](https://user-images.githubusercontent.com/85161724/202189518-6fed82e2-59b6-40fa-a293-66af640775b9.png)

**Comment by tjerman** [comment]
I can take a crack at this one

**Comment by katrinDY** [comment]
This has been resolved. Closing issue.
