### ISSUE TITLE
Integration gateway filter list consistency

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#518]
Currently the filter list is inconsistent with the other Corteza entity lists, this should be fixed to match the global UX.

![Image](https://user-images.githubusercontent.com/4668490/202222316-bae45fc0-28d5-4802-81ab-475fb7dd1938.png)

**Comment by Fajfa** [comment]
Closing this issue since it will wait for the general UX improvements on API GW anyway
