### ISSUE TITLE
Integration gateway filter sorting

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#519]
The profile prefilter comes in handy when taking a closer look on the input of the requests into Corteza.
Sometimes you want to profile the routes after authentication, so it would be useful to be able to move profiler after any filters that should occur before (as opposed to removing all before).

Use the weight meta on filter in request:
```
{
    "routeID": "310841959059030019",
    "weight": "0",
    "kind": "prefilter",
    "ref": "header",
    "enabled": true,
    "params": {
        "expr": "Foo = \"foo1\""
    }
}
```

**Comment by Fajfa** [comment]
Since drag and drop is already enabled, I'll close this issue and include the UX changes in the UI cleanup issue #522
