### ISSUE TITLE
Review, update or remove tools used by the server

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#530]
In `server/Makefile.inc`, we reference a list of tools varying from static code analysis to code
generators. 

Review what we use and what is obsolete.

**Comment by katrinDY** [comment]
for today: make changes to make file and open PR by end of the day

**Comment by katrinDY** [comment]
for today: sync with Tomaž to discuss issue

**Comment by katrinDY** [comment]
for today: complete issue by EOD
