### ISSUE TITLE
Display field label instead of name in metric field selectors

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#540]
When you use metric page block and you need to configure the field, instead the field taking the field label of the record, it is taking the name which is wrong. 

Note: This was discussed with Joze so if there are any questions you can reach out to him.

**Comment by EmmyMay** [comment]
https://github.com/cortezaproject/corteza/pull/586

**Comment by EmmyMay** [comment]
Changelog Doc

## Changed

### What Changed
Labels instead of names are being displayed in Metric pageblock fields.

### Why did it change
We were incorrectly displaying the field names instead of its labels.

### How did it change
Metric pageblock fields now show labels instead of names.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now okay, also the entry was added to the CL. Moving the card to **Done**. @EmmyMay once you merge everything feel free to close this issue.

**Comment by EmmyMay** [comment]
Cherrypicked to 2023.3.x
