### ISSUE TITLE
Adding/deleting/editing a record on a duplicated page also reflected on the main page

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#542]
- When you create a copy of a page in compose and you add a record on the copied page, the record is also added on the main page. The same goes when you delete or edit a record, the changes are reflected on the copied and on the main page.

https://user-images.githubusercontent.com/53232926/203040092-46d912bb-0f26-4a4f-9e41-96893f3173ee.webm

**Comment by katrinDY** [comment]
this is expected. The records point to the same module. Closing this.
