### ISSUE TITLE
Federation handshake fails due to invalid generated URL

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#545]
The generated URL seems to always point to local.cortezaproject.org; potentially a lapsus in the code.

- [x] Investigate to find out what's wrong
- [x] Review the [documentation](https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/federation/index.html) and update as needed
- [x] Post an update on the forum https://forum.cortezaproject.org/t/federation-node/1137/3

**Comment by petergrlica** [comment]
Referred the forum user to a part of the docs

**Comment by petergrlica** [comment]
Added https://github.com/cortezaproject/corteza/issues/690, closing this one
