### ISSUE TITLE
Page builder does not remember navigation state

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#552]
**Describe the bug**
When pressing save and close in page builder it always brings you to the admin panel

**To Reproduce**
Edit page, press save and close.

**Expected behavior**
Should navigate you to where you came from (e.g. page detail page)

**Screenshots**

https://user-images.githubusercontent.com/19151369/193866281-a054c04d-2ac0-402b-aaaf-712eef2d8040.mp4

**Comment by Fajfa** [comment]
Hey, thank you for raising this issue. We have general navigation improvements in the pipeline (for 2023.3), which includes this problem you're experiencing.

**Comment by kelanik8** [comment]
- related pages
- tree
- namespace sidebar
- admin edit page
- public page
