### ISSUE TITLE
Refresh values only instead of fields on page value refresh

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#553]
**Is your feature request related to a problem? Please describe.**
When using the workflow prompt step of refresh field values it hampers user experience to see the whole page flash. 

**Describe the solution you'd like**
Instead of redoing the entire field value layout, you can refresh the values only and create a smoother user experience.

**Additional context**
See GIF for what I mean
![Record page for module _Account_ _ CRM _ Low Code](https://user-images.githubusercontent.com/19151369/193867591-87dd5ad7-16cf-4a61-81f8-95fbc0a77287.gif)

**Comment by Fajfa** [comment]
We had this implemented the way you suggested, not sure what happened. Should be fixed/improved so it works like you described.

**Comment by skamensky** [comment]
Are you unable to reproduce this on the latest release?

**Comment by Fajfa** [comment]
I can and will try to squeeze it into the 2022.9.1 release, that will be released sometime next week.

**Comment by skamensky** [comment]
Glad you could reproduce it. No rush. Let me know if there's something I can do to help.
