### ISSUE TITLE
Date-only field crashes the app

### ISSUE THREAD

**Issue by pszuster** [cortezaproject/corteza#559]
**Describe the bug**
When you define a field as Date-only in a module and then select a date as a user, the browser's tab crashes (chrome and Firefox)

**To Reproduce**
1. Go to Low Code -> Module -> add "Date and Time" field.
2. Go to the field config and select "Date Only".
3. Save the module.
4. Create a record using the module and pick a date from the calendar.

**Expected behavior**
Users should be able to pick a date without crashing the browser

**Screenshots**
<img width="417" alt="image" src="https://user-images.githubusercontent.com/10658194/162849113-52545c51-72c3-48e8-990c-68a5d12361ac.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome v100.0.4896.75 , Firefox v98.0.1

**Comment by tjerman** [comment]
I can't seem to reproduce this issue; would you be able to make a screen recording demonstrating this?

* Are you able to get the same behaviour on a completely fresh namespace?
* are you able to get the same behaviour on a completely fresh Corteza instance?
* do you have any workflows/automation scripts defined?
* what is the browser crash message; does it just close or does it show some message?

**Comment by pszuster** [comment]
![corteza_date_bug](https://user-images.githubusercontent.com/10658194/162964220-5d351d5a-0027-49b7-8efd-562fd712c8a8.gif)

- Are you able to get the same behaviour on a completely fresh namespace?
Yes
- are you able to get the same behaviour on a completely fresh Corteza instance?
yes (2022.3)
- do you have any workflows/automation scripts defined?
no
-what is the browser crash message; does it just close or does it show some message?
No message, just freezes

**Comment by tjerman** [comment]
That's strange...
Thanks for reporting; we'll take a look

**Comment by tjerman** [comment]
For a workaround, disable date-only from the date field.
We are looking into addressing this, but we are unable to reproduce the issue.

**Comment by brunoccr** [comment]
The same problem for me, both 2022.3.2 and 2022.3.3.rc1

**Comment by Fajfa** [comment]
This was fixed 2023.3
