### ISSUE TITLE
code cleanup: console.log

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#564]
Unexpected console statement

 - [ ] client/web/one/src/app.js#L94
 - [ ] client/web/workflow/src/components/WorkflowEditor.vue#L771
 - [ ] client/web/admin/src/app.js#L146
 - [x] client/web/compose/src/components/Namespaces/Importer/index.vue#L97
 - [x] client/web/compose/src/components/Namespaces/Importer/index.vue#L101
 - [ ] client/web/compose/src/components/PageBlocks/CommentBase.vue#L243
 - [ ] client/web/compose/src/components/PageBlocks/RecordListBase.vue#L1347
 - [ ] client/web/compose/src/components/PageBlocks/RecordListBase.vue#L1355
 - [ ] client/web/compose/src/components/PageBlocks/RecordListBase.vue#L1370
 - [ ] client/web/compose/src/components/PageBlocks/RecordOrganizerBase.vue#L244
 - [ ] client/web/compose/src/components/PageBlocks/Shared/AutomationTab.vue#L292
 - [ ] client/web/compose/src/components/PageBlocks/Shared/AutomationTab.vue#L306
 - [ ] client/web/compose/src/components/PageBlocks/Shared/AutomationTab.vue#L332
 - [ ] (look around ...)

Check webapps:
- [x] compose
- [x] admin
- [x] reporter
- [x] privacy
- [x] one
- [x] workflows
- [x] discovery

**Comment by katrinDY** [comment]
## All redundant console.log/error/debugger removed

## Code:
- 2023.3.x  https://github.com/cortezaproject/corteza/commit/ee24191c708a20d9463ebbfe043fcd2b494918e3
- 2022.9.x https://github.com/cortezaproject/corteza/commit/6ab15de8d270932829afd9d9655ca5b9ff0659b6
