### ISSUE TITLE
Alignment of chart customize filter

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#571]
The `customize filter` needs to be aligned a bit since now it is really close to the box above, so it needs to be centered abit (shifted abit down) to match the other checkboxes below which are fine.

![Image](https://user-images.githubusercontent.com/53232926/203985296-4c05b0ef-781d-470e-99c1-6e6a9b17aec9.png)

**Comment by katrinDY** [comment]
### End result:

![Image](https://user-images.githubusercontent.com/85161724/204850748-397b926d-b4fa-4a69-89ec-30cd0f433ffc.png)
