### ISSUE TITLE
Reporter tables pagination issue

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#574]
1. When I add a limit to a reporter table, the next page is not usable and you cannot go to the second page, same goes for the compose report table. (You can see this from the video in more details)

2. When I try to remove the limit, either erase it or just write `0` I am receiving the error `Failed to run report: json. cannot unmarshal string into Go struct field Paging.Frames.paging.limit of type uint`

Video:

https://user-images.githubusercontent.com/53232926/204000460-b41ae52f-1849-46f1-9bbf-7ff47f8d9751.webm

**Comment by vicpatel** [comment]
This will resolve this https://github.com/cortezaproject/corteza/pull/588

**Comment by Bojan-Svirkov** [comment]
@vicpatel This happens to be working okay in the reporter but when you try to use a reporter table in compose, you can only click next page and after that you cannot go back. Please double check this again. 

[29638ce6-8ddf-4c4b-962d-04d2abc0e5dd.webm](https://user-images.githubusercontent.com/53232926/205253569-48b49453-2d8e-426a-8435-ee966a860af8.webm)

**Comment by Bojan-Svirkov** [comment]
Retested and confirming that this now looks good. @Fajfa & @vicpatel now I will only need the CL part.

**Comment by vicpatel** [comment]
Fixed:
What was fixed
- Fixed next page paging cursor for reports

How was it fixed
- By updating the page cursor only if it exists while creating a report paging filter to preserve the valid cursor for the next page

**Comment by Bojan-Svirkov** [comment]
Added to CL. So moving the card to **Done**.
