### ISSUE TITLE
Issue when saving a newly added display element

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#575]
### Gif of the issue:
![Image](https://user-images.githubusercontent.com/85161724/204006500-086b0db2-0214-46de-b448-298e384c1cc8.gif)

**Comment by Fajfa** [comment]
Interesting, this only happens when you switch a type of chart before first saving it. Fixing

**Comment by Fajfa** [comment]
Fixed 

1.  What
- Reporter chart display element configuration was not properly saved on creation if the chart type was changed

2. How
- Properly updated the chart display element options when the chart type changed

**Comment by Bojan-Svirkov** [comment]
Tested and added the Cl entry. Since everything is already merged I will by straightly closing this issue.
