### ISSUE TITLE
Compose record filter improvements

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#578]
#### - Currently all the operators are shown in compose filters for example for a single value text type field. So let's try to hide the operators if they are not supported. For example the `Contains` and `Not contains`, if a field is a single value one, let's hide the operators and just shown them if a field is a multi value one.

- [x] Hide the `Greater than` & `Less than` for not supported field types (ex: strings)

- [x] Try to implement a new operator called `Between` or `Range` which will be only used for displaying a number values in a given range.  - server

- [x] Try to implement a new operator called `Between` or `Range` which will be only used for displaying a number values in a given range.  - UI

- [x] Try to implement a new operator called `Between` or `Range` which will be only used for displaying a date values in a given range(?maybe)  - server [It will be supported by server alongside]

- [x] Try to implement a new operator called `Between` or `Range` which will be only used for displaying a date values in a given range(?maybe)  - UI

- [x] Improve the error message when something is not supported. For example currently `In` operator is not supported on a single value and the error message is just saying `Could not load record list: unsupported IN operator`, so let's improve this so it would be saying `Could not load record list: unsupported IN operator on a single value field.`

- [x]  Hide Contains and Not contains if a field is a single value one, show them if a field is a multi value one.

**Comment by skamensky** [comment]
Thanks, I was bitten by this

**Comment by kelanik8** [comment]
@Fajfa https://github.com/cortezaproject/corteza/pull/713

**Comment by Bojan-Svirkov** [comment]
Tested 1st, 6th and the 7th point and confirming that everything looks good. Now the only part left is the points related to the Between and range, so moving this card back to in progress.

**Comment by kelanik8** [comment]
Changelog

What changed
- `Greater than` & `Less than` filter operators are hidden for field type with string, emails and URLs
- `Contains` and `Not contains` filter operators are hidden for fields with single value
- Contains and Not contains filter operators appear on fields with multi-value configured

Why did it change
- To prevent users from using filter operators that are not supported for certain field types

How did it change
- Updated the operators list configuration in the record list filter component with `Greater than` & `Less than` filter operators hidden from string types.
-  Updated the operators list configuration in the record list filter component with `Contains` and `Not contains` hidden for field types with non multi value

**Comment by Bojan-Svirkov** [comment]
Added CL

**Comment by vicpatel** [comment]
Server changes branch ref: `2023.3.x-ql-between-comparision`(Updated branch name)

**Comment by vicpatel** [comment]
BE still has some issues, working on it.

**Comment by vicpatel** [comment]
Fixed server, and pushed to branch!

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is finally working in the way it is supposed to. Now the only thing left is the CL entry.

**Comment by vicpatel** [comment]
Added:

• What was added
-- Added `BETWEEN` and `NOT BETWEEN` operator support for single value fields(number and date-time record fields)

• Why was it added
-- To extend record filtering support for range filtering of numeric and date-time for single value field.

**Comment by Bojan-Svirkov** [comment]
Added CL
