### ISSUE TITLE
Make sure compose record report data is provided in order

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#579]
Previous versions (2022.3 here) ordered the output using the dimensions (https://github.com/cortezaproject/corteza/blob/2022.3.x/server/store/rdbms/compose_record_report_builder.go#L210); now, we don't do that.

Add sorting to the DAL pipeline builder [here](https://github.com/cortezaproject/corteza/blob/299ffd36181a8ce4759aa67800811f5844121b6f/server/compose/service/record.go#L1778)

**Comment by tjerman** [comment]
2022.9.x

https://github.com/cortezaproject/corteza/commit/956e30e2b21649749a98273c3a5ccf32cb80da92

**Comment by tjerman** [comment]
```
## Fixed

### What

Fixed invalid data ordering on compose charts caused by improperly ordered data on the record report endpoint.

### How

Adding an explicit sorting by the specified dimension field

```

**Comment by tjerman** [comment]
Moved to current sprint because trivial and fairly important

**Comment by tjerman** [comment]
On compose > charts, the data from the record report endpoint should now be returned in order (dates for example); before in 2022.9 whey were not.

What you can do to reproduce is:

* make a new module with a date-time field
* create a couple of records with random dates
* create a new chart and use that date-time field for dimension
* press that load data button and inspect the HTTP response -- the data should have dimensions returned in ascending order.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now shown as it should. Also the CL entry has been added so @tjerman if everything is merged feel free to close this issue.
