### ISSUE TITLE
Auth pages (authorized clients) do not show empty-list text properly

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#580]
Empty list:

![Screenshot 2022-11-29 at 14 42 29](https://user-images.githubusercontent.com/1500447/204544753-eeecc9f7-6d74-4d08-9f7e-decd870cfa71.png)

List of auth clients

![Screenshot 2022-11-29 at 14 42 10](https://user-images.githubusercontent.com/1500447/204544756-65b5532e-27e9-483c-acfe-d67d6317d66b.png)

See the "no authorized clients found". That text should show on the empty list but not on the full one. It works in reverse right now.

Make sure it is fixed on `2022.9.x` and on `2023.3.x`.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now looking good both on 2022.9.x and 2023.3.x. Moving the card to **Done**.
