### ISSUE TITLE
Reporter text block paragraph option not working as expected

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#598]
When you add a text block in reporter and you want to use the paragraph setting, the paragraph option is not applied when the block is saved.

![Image](https://user-images.githubusercontent.com/53232926/205645225-cb484ea1-e29e-4d45-bb0c-f7ac54197b5b.png)

**Comment by katrinDY** [comment]
this may be caused by the tiptap library

**Comment by Bojan-Svirkov** [comment]
I just tested this and can confirm that this is now fixed. I will be moving the card to **Done** since this is trivial thing and there is no need for changelog entry. @EmmyMay once you merge everything feel free to close this issue.
