### ISSUE TITLE
Broken compose checkbox filtering

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#599]
When you try to filter records by checkbox, the filter is broken and you are receiving the error `Could not load record list: pq: syntax error at or near "$3"`

![Image](https://user-images.githubusercontent.com/53232926/205677438-f5ad8200-a968-45f4-aa61-27bfbb7004cc.png)

- [x] also fixes (https://github.com/cortezaproject/corteza/issues/583)

**Comment by skamensky** [comment]
Related to previous bug report:

https://github.com/cortezaproject/corteza/issues/583

**Comment by vicpatel** [comment]
Ref branch for this fix# `2022.9.x-fix-checkbox-filtering`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. @vicpatel the only thing left now is the CL entry.

**Comment by vicpatel** [comment]
### Fixed

#### What was fixed
- Fixed filtering for bool type for equal and not equal operator.

#### How was it fixed
- By adding custom val hanlder for bool type to convert it properly while parsing the query according to supported drivers.

**Comment by vicpatel** [comment]
Merged!

**Comment by Bojan-Svirkov** [comment]
CL added, moving the card to Done.
