### ISSUE TITLE
Broken compose sorting by date

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#600]
When you want to sort your records by date, the date sorting is broken and you are receiving the error: `Could not load record list: pq: invalid input syntax for type timestamp with time zone: ""` 

![Image](https://user-images.githubusercontent.com/53232926/205678040-8be33e61-e7b5-473b-8351-3a0816ef3356.png)

**Comment by vicpatel** [comment]
As per the error message tested with Postgres DB.
It is working as expected, Could be fixed by latest fix for sorting in recent patch.

**Comment by Bojan-Svirkov** [comment]
@vicpatel On my old DB the issue is there but I just tested it with a fresh db and there is no issue. So I guess this was a DB related issue, so should we consider this ticket as done?

**Comment by vicpatel** [comment]
Yeah, Looks like issue with module, other existing module with date filter works.
we can move this to Done.
