### ISSUE TITLE
Remove handle requirement on role create

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#606]
## Description
This shouldn't be a requirement. Handle requirement was removed from user, template, namespace, etc. The same has to be done here.

## TODO
- [x] remove requirement from BE
- [x] generate api-calls on FE
- [x] test functionality

**Comment by tjerman** [comment]
@Bojan-Svirkov the changelog text would be along the same lines as the previous handle req. removals.

2022.9.x monorepo commit `fd55cce9b`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed.

The CL entry has been also added.
