### ISSUE TITLE
Admin panel/page tree: incorrect state of pages on loading

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#623]
## Description
While the pages are being fetched instead of showing the loading text and spinner, `No pages` is shown

## Current behaviour
![Image](https://user-images.githubusercontent.com/85161724/206723330-16784505-3534-4f06-883a-1a95061bf03c.png)

## TODO
- [x] show spinner on loading

## PR
https://github.com/cortezaproject/corteza/pull/671

**Comment by katrinDY** [comment]
CL:

Fixed

What: The state of the page list while its content is being fetched.

How: A spinner with "Loading" text was added. After the content is fetched, the spinner is hidden.

**Comment by Bojan-Svirkov** [comment]
CL has been added and this has been tested, but there is just a little thing that needs to be fixed:

![image](https://user-images.githubusercontent.com/53232926/208444210-8274c773-f283-4284-bb9d-e0a254a2840a.png)

**Comment by katrinDY** [comment]
Issues addressed. Code for
[22.9](https://github.com/cortezaproject/corteza/commit/508b63869fa257c5380a0e20faee85ce6dafddce)
[23.3](https://github.com/cortezaproject/corteza/commit/ec5232699ea94952c30772c4c59d758a560bcda2)
