### ISSUE TITLE
Record list/module field picker: can't reorder fields if I'm filtering fields

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#624]
## Steps to reproduce
- Open up a record list configurator, go to where you select what module fields you wish to show, select a few, then search for some field
- Try to reorder the selected fields -- the reorder is discarded when you rearrange the field

## Screenshot
![Image](https://user-images.githubusercontent.com/85161724/206724775-8ca24266-7148-4541-a3e8-4e735964734a.png)

**Comment by Fajfa** [comment]
A comment here, i dont think we should enable drag&drop if you're searching. Only adding by click

**Comment by katrinDY** [comment]
@Bojan-Svirkov

Where to test:

Compose:
- funnel chart
- all records -> configure fields
- record list config
- record config
- export record -> config
- edit module -> discovery settings, validation

Reporter:
- table config
- chart config

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. Only thing left is the CL.

**Comment by katrinDY** [comment]
CL 

Changed

What: Dragging and reordering is disabled while searching for a field when configuring module, chart and page fields.

Why: It doesn’t make sense to search for a field and reorder the already selected fields 

How: A computed property was added that tracks if a query parameter is added and  if dragging is disabled

Refs
[22.9](https://github.com/cortezaproject/corteza/commit/a0a70315893e3ece0043b1551c24877a908dcd36)
[23.3](https://github.com/cortezaproject/corteza/commit/c56d19ee948440b38cee6d529f5945046ace213d)

**Comment by Bojan-Svirkov** [comment]
Added CL.
