### ISSUE TITLE
Filtering not available in block magnification

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#635]
When you configure a block (filter list) to be magnified the filter is present but it is not working, it is not clickable. It looks like the problem is with the z-index and the popoverTarget being the same as the record list not in modal.

Steps to reproduce:
1. Add a block and configure it the magnification to be enabled
2. Click on magnify icon 
3. Once the list opens in modal for example try clicking on the filter

**Comment by kelanik8** [comment]
@Fajfa https://github.com/cortezaproject/corteza/pull/709

**Comment by katrinDY** [comment]
Tested this and can confirm it's working as expected.

**Comment by Bojan-Svirkov** [comment]
@kelanik8 can you please add a changelog entry here?

**Comment by kelanik8** [comment]
Changelog

What changed
- The record list filter component updated with a unique id, which is previously the block id
- The record list filter component updated with a style of `position: initial` to prevent the record filter pop over z index issues

Why did it change
- To fix the issue of filtering not working on modal or fullscreen magnification

How did it change
- The filter component uses a unique id for the target value of the filter pop over

**Comment by Bojan-Svirkov** [comment]
Added CL. @kelanik8 I guess this can be merged, and once merged feel free to close this issue.
