### ISSUE TITLE
Record revisions not showing on 2023.3

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#638]
When I am testing this on .9 it works fine, but on 2023.3 the record revision block is empty and I am receiving this error in console on the picture below:

![Image](https://user-images.githubusercontent.com/53232926/207363213-a9b78fe6-e91c-45c7-8245-3bb687458d31.png)

https://user-images.githubusercontent.com/53232926/207367736-f818e2e1-cbd1-450e-9108-30ec386ae966.webm

**Comment by tjerman** [comment]
Resolved https://github.com/cortezaproject/corteza/commit/d8caa79ca7adb4514cce4ee21bbca2796878056c
No need to changelog this one

**Comment by Bojan-Svirkov** [comment]
Record revisions are now showing as they should. Moving the card to **Done**.
