### ISSUE TITLE
Calendar block misbehaving on 2022.9 and 2023.3

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#639]
## Description of the bug

_When I try to use the `Calendar` block in compose, the block misbehaves. Either I am only seeing the dates in page builder view or sometimes they are not shown in the builder but on the page itself, or they are shown in the page but when I magnify the block the calendar is not shown. So this is pretty random. You can see this behavior more in details below in the screenshots and the video provided._

## Reproduction steps

1. Add a calendar block on a public page
2. Try also adding an event source to the block
3. While in page builder, observe if the dates are shown
4. save the page and see if the dates are shown on the public page
5. Enable the block to be magnified in a modal view
6. once everything saved, try to magnify the block and see if the dates are shown.

## Expected behavior 

_The calendar block should work as expected and the dates should be always shown whether in page builder mode, on public page or when magnified._

## Screenshots & Videos

https://user-images.githubusercontent.com/53232926/207365227-a43abf6d-93ec-43bc-8165-bfa5b89eb886.webm

https://user-images.githubusercontent.com/53232926/207365226-0296d984-f882-416d-915f-d8e9a93a1038.webm

## Versions

Branch: 2023.3.x

**Comment by kelanik8** [comment]
@Bojan-Svirkov I'm can't seem to recreate the error on my end.

**Comment by katrinDY** [comment]
I was able to reproduce the issue. Cause of the issue `show` is being set to false which prevents the calendar's content from being displayed. If the calendar PB is moved or the screen is resized, the content is shown. Gonna fix it on Monday.

**Comment by katrinDY** [comment]
The issue is also present on 22.9

**Comment by katrinDY** [comment]
A couple of notes after debugging:

The problem occurs:
- if we have one calendar with events set and another without events set
- when toggling between page builder and view page

If we create multiple calendar page blocks all with/without events, the calendar will load normally
If throttle is substituted with debounce, the calendar's body isn’t loaded for page blocks that have events added

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. @katrinDY when you have the time just try to add the CL entry.

**Comment by katrinDY** [comment]
CL

Fixed

What: Hiding of calendar in calendar block when switching from page builder to view page and vice versa

How: Throttle was replaced with async/await in the CalendarBase component

Ref:
- 22.9 [4124f8f](https://github.com/cortezaproject/corteza/commit/4124f8fee4db4e546f836ff2ab9b2222cbb5c666)
 - 23.3 [b72ce11](https://github.com/cortezaproject/corteza/commit/b72ce116c07b0eaeacbf6524ec1a5e9b9a4303f7)

**Comment by Bojan-Svirkov** [comment]
Added CL
