### ISSUE TITLE
Permissions not followed in admin

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#640]
## Ref
https://forum.cortezaproject.org/t/template-permissions-in-9-5/696

## Description
For the templates, we used return this.can('system/', 'queue.create') instead of (from the top of my head) return this.can('system/', 'temlate.create').

Doing a quick look, I think we don't apply some other RBAC rules (users and auth clients)

## TODO
- [ ] go through the code to validate everything is as it should be
- [ ] make any changes if necessary

**Comment by katrinDY** [comment]
Reference to RBAC rules https://docs.cortezaproject.org/corteza-docs/2022.9/integrator-guide/security-model/references/operations.html

**Comment by katrinDY** [comment]
Check and if needed fix broken permission. No need to check if the other permissions work as expected. This will be tested later on.

**Comment by yonkov** [comment]
I tested template permissions and can confirm they are working as expected on both 2022.9 and 2023.3. 

Steps to reproduce in case needed:
1. create a new user, create a new role and then link the role to the user
2. add the following permissions to the role:

![Image](https://user-images.githubusercontent.com/26258032/222099194-c0642951-51d7-4fe2-8dc4-32fc4303d5c5.png)

![Image](https://user-images.githubusercontent.com/26258032/222099326-c8101432-ed1d-4b3f-9fc0-3b3d165b1dc8.png)

3. Cheer up : )

**Comment by Bojan-Svirkov** [comment]
Everything works as expected, moving the card to **Done**.
