### ISSUE TITLE
Geometry multi value map inconsistency

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#641]
## Current behaviour
When you click on any geometry field, the default map location is shown. If I have a location set in USA, I have to scroll to the place instead of the map taking me there.

## Expected
Show the correct map location when opening a specific geometry location

## Proposals 
- when we click on specific entry the pin can be enlarged 
- set a different color for the currently selected pin

## Steps to reproduce
1. Add geo location field in a module
2. Enable multiple location entries
3. In a record add a couple of geo location entries
4. Click on any of the locations and see that the map doesn't take you to the selected location

## Vide with reproduction steps
https://user-images.githubusercontent.com/85161724/207381945-30cab3dd-c1ae-444a-b4b9-2923d0169d86.webm

**Comment by katrinDY** [comment]
For today: take a look at task, make plan and start working on it

**Comment by yonkov** [comment]
Update from today, 10 p.m. CET - I am researching the leaflet map library for potential settings that might resolve this and after that will start implementing the solution.

**Comment by yonkov** [comment]
Update from today, 10 p.m. CET - I tackled the issue with geometry link not opening the map on the designated location, what is left to do is to map the link to the corresponding pin. Estimated time - 1 -2 hours to make a PR

**Comment by yonkov** [comment]
Daily update: The task passed code review but on qa we agreed that if there are a few pins in a close distance, it would be better to zoom-in the map because currently is too far of and in this way only the clicked marker would be visible. Additionally, Joze requested that the clicked marker should change its color. Working on it.

**Comment by katrinDY** [comment]
For today: timebox to 1h to figure out how to handle the color change for the pin.

**Comment by yonkov** [comment]
Update: delivered the requested changes and resubmitted for code review.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL entry was also added.
