### ISSUE TITLE
Whitespaces trimmed on key -> val dropdowns

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#643]
## Description
Currently, the key values setting for dropdown lists allows for whitespaces. This can be difficult to detect and debug when it occurs because it: 
- prevents record manipulation
- the exact field is not logged in the error log

## Screenshot of issue
![Image](https://user-images.githubusercontent.com/85161724/207385914-8cba56d0-78d9-478f-8943-b426f3016f13.png)

## TODO:
- [ ] remove the whitespace after the values

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as it should. No need for CL since it is trivial thing. Moving the card to **Done**.
