### ISSUE TITLE
Add notification message on successful namespace delete

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#645]
## Description
Whenever we create/update/delete a module/record/chart a toast notification tells us that we have successfully done that. After deleting a namespace, no notification appears.

## TODO
- [ ] add notification for successful namespace deletion

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. Moving the card to **Done**.

**Comment by yonkov** [comment]
## Changlelog

### What was changed

After deleting a namespace, a notification appears to confirm to users that a namespace has been saved.

### How was changed
A toast notification message was added in `vies/Namespace/Edit`

### Why was changed
Whenever we create/update/delete a module/record/chart a toast notification tells us that we have successfully done that. We need to have consistence across Corteza, that is why we want to add notification message when we delete a namespace.
