### ISSUE TITLE
Close import modal after successfully importing a workflow

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#647]
## Locations of the issue
- workflow configurator
- workflow list

## Import modal
![Image](https://user-images.githubusercontent.com/85161724/207551456-ecdc40d6-8bc9-45dd-a6f0-8a4ed834ae6c.png)

**Comment by katrinDY** [comment]
Both components that use the import modal have been tested and are working as expected

**Comment by katrinDY** [comment]
CL

Changed

What: The closing of the import modal

Why: To give the user a better UX

How: An id was added to the import modal through which the modal is closed after a successful import

**Comment by katrinDY** [comment]
@Bojan-Svirkov, can you, please, retest it just in case I missed something?

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL
