### ISSUE TITLE
Persist application position in application list

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#648]
## Steps to reproduce
1. Create an application in admin
2. List the application so it's visible in webapp one
3. In webapp one see that the application appears at the start of the applications list
4. Move the application to the bottom on the list
5. In admin enable the application
6. In webapp one see that the application has been moved to the start of the application list

## Notes
The reordering also happens if you add/remove a url to the app

## Video with reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/207568950-832eae39-d4b1-474d-87a3-c8ee8df2dc06.gif)

**Comment by EmmyMay** [comment]
Closed because this is an edge-case we do not need to cater to. In the future, maybe with websockets.
