### ISSUE TITLE
Error when trying to delete a sensitivity level added to a connection

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#651]
## Error
![Image](https://user-images.githubusercontent.com/85161724/207598019-b6fab729-cc0d-4b5b-aa04-a62e88f78f77.png)

## Steps to reproduce
1. Create a sensitivity level
2. Create a connection and add the newly created sensitivity level
3. Try to delete the sensitivity level used in the newly created connection and see the error pop up

**Comment by tjerman** [comment]
Deleting in use sensitivity levels should be an invalid operation so it's ok it failed.
It _failed on accident_ so the error message looks a bit scary so we should add an explicit check with a nicer message.

**Comment by tjerman** [comment]
Added extra validation and a nicer error

![image](https://user-images.githubusercontent.com/12545711/210548608-e7633bb6-5375-4c34-b116-bc60eb207f96.png)

**Comment by katrinDY** [comment]
Tested and can confirm this works as expected. Moving to CL & Docs column.

@tjerman, after adding the CL, don't move the task to done. Leave it where it is.

**Comment by Bojan-Svirkov** [comment]
Added CL.
