### ISSUE TITLE
Wrong title of module view shown while loading module

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#653]
## Steps to reproduce
1. In compose click on admin panel button
2. Go to Modules and click on any module
3. See the title is `Create namespace` while the module is being loaded

## Video with reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/207601516-2cb0885c-eddd-47f6-a96e-496b353e0837.gif)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this looks good. Moving the card to **Done**.
