### ISSUE TITLE
Can create a resource without entering any data

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#656]
## Resources
- templates
- workflows
- connection

## Steps to reproduce
1. Select any of the listed resources above from the sidebar
2. Click on `add` to create a new resource
3. See that you're able to submit an empty form

## Expected behavoir
This shouldn't be possible. We should require name/short name in order to create any of the resources

## Notes
Please, speak to Jože before starting

**Comment by tjerman** [comment]
@katrinDY is this really unexpected? Since we don't require handles nor names I don't really see a reason why submitting empty forms would not be permitted.
The server does (or should at least) filter out/ignore invalid/empty things when performing operations over them (such as workflows)

**Comment by katrinDY** [comment]
@tjerman I'm not entirely sure if this should be expected or unexpected. It makes sense that we don't require handle and/or name for these resources but it also doesn't make sense that we can create such resources without entering handle and/or name. You can close this issue, if you think it's expected

**Comment by tjerman** [comment]
I'll let @Fajfa make the final call; for me, this is more of a UX issue

**Comment by Fajfa** [comment]
I do agree we need to require the resource name, like we do on modules to keep it consistent

**Comment by tjerman** [comment]
Monorepo 2023.3 commit `d431b90a9`

**Comment by katrinDY** [comment]
@Bojan-Svirkov, test code on 
- 2023.3.x-bugfix-make-name-required-for-resources
- 2022.9.x-bugfix-make-name-required-for-resourcess

**Comment by katrinDY** [comment]
Two more resources to cover:
- sensitivity levels
- auth clients

**Comment by Bojan-Svirkov** [comment]
Retested and confirming that this now works as expected. The only thing left now is the CL entry.

**Comment by katrinDY** [comment]
CL:

Changes:

What: Make name property required when creating templates, dal connections, workflows, auth clients and sensitivity levels
Why: Before adding this requirement, the listed resources could be created without entering any data into their fields. It doesn't make sense to be able to create a resource without entering any data.
How: Validations were added to prevent creating one of the listed resources without adding a name

Refs:
- 22.9 38a02d5b9
- 23.3 4ccafb19

**Comment by Bojan-Svirkov** [comment]
Added CL
