### ISSUE TITLE
Remove * from workflow handle

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#657]
## Notes
How to determine if a handle is required or not? If you can create a resource without a handle - it's not required

## Location of issue

![Image](https://user-images.githubusercontent.com/85161724/208451768-cb340b32-74b2-44fb-b926-c048618ae2b4.png)

## TODO
- [x] remove the * from the translation (this field is no longer required)
- [x] check for other * that weren't removed

**Comment by Bojan-Svirkov** [comment]
Looks good, moving the card to **Done** and no need for CL entry for this since it is really a minor thing.
