### ISSUE TITLE
Using has() function on Record Selector(multivalue) fields return incorrect results

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#663]
## Example scenario

ModuleA has a multi value record selector field: module_b_records which selects records from Module B.

The workflow uses a record select compose records prompt for the user to pick one of the records from module B.

Another step uses the `has` function to see if the multi value field in record A includes the record selected by the user.
`ex: has(ModuleA_record.module_b_records, ModuleB_record.recordID)?"record found!":"record not found!"`

This evaluates incorrectly and results as `false` even when it should be `true`.

## Issue TL;DR

The record passed to the resume prompt gets treated as `Vars` instead of `ComposeRecord` which then breaks how the values are treated and so the has gets broken.

More investigation to be done

Also worth considering if this should change even (we potentially break some BW operations)

## Notes

For now the workaround is casting the ID (`int(group.recordID)`) in the expression `has(record.values.group, int(group.recordID))`

**Comment by tjerman** [comment]
I can no longer reproduce this issue and I do remember there were some type system changes a while ago so it looks like we `accidentally` fixed this as well.
From the logs the types and values seem fine (`{ ... "ndl": {...}, "ndlType": "ComposeRecord", ...}`

**Comment by tjerman** [comment]
@Bojan-Svirkov could you do some testing on your end as well?

wf: https://gist.github.com/tjerman/7b9d1c3a0484baf7ede56d8e81496cdd
namespace: [testko.zip](https://github.com/cortezaproject/corteza/files/10344785/testko.zip)

**Comment by Bojan-Svirkov** [comment]
I wasn't able to reproduce this issue too, so I will be moving this card to done since it looks like it is no longer a problem.
