### ISSUE TITLE
Exporting namespaces with dots in name breaks it

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#665]
## Discussion in forum
https://forum.cortezaproject.org/t/namespace-with-dots-404/830

## TODO
- [ ] create a namespace with a dot in the name
- [ ] export the namespace and see if an error occurs

**Comment by KinyaElGrande** [comment]
Could not reproduce the bug.
Exporting a namespace with a dot in the name works as expected.
Closing the issue.
