### ISSUE TITLE
Submit buttons in the template editor don't change state on click

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#669]
## Description
Both of the submit buttons in the two sections (cards) don't change state after being clicked. A spinner should appear in the button substituting the `Submit` text

## Screenshot
![Image](https://user-images.githubusercontent.com/85161724/207872309-4d7bf07e-453a-4c97-86b9-c7e397a3aa78.png)

## TODO
- [x] add spinner after submitting the form to match UI consistency

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. The only thing left now is a CL entry.

**Comment by EmmyMay** [comment]
### Changelog Documentation

# Added

## What was added?
A spinner to indicate when an action in template editor is submitted.

## Why was it added?
There was a UI inconsistency in the way it was and worked, making it difficult to tell when your changes were being submitted.
