### ISSUE TITLE
Default  record list column order changes when admin/all records are accessed

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#673]
**Tested on HT staging**

## Steps to reproduce
1. I opened up a record page with a record list without any fields selected (I left it to use whatever columns it wanted by default) (img 1)
2. I went to admin/modules/all records for that module (img 2)
3. Navigated back and order changed (img 3)

## Img 1
![Image](https://user-images.githubusercontent.com/85161724/207934548-19a87021-c25b-4a13-9779-e694d5af54fe.png)

## Img 2
![Image](https://user-images.githubusercontent.com/85161724/207934569-f536f21d-21b5-46f4-8c26-8fcb10864beb.png)

## Img 3
![Image](https://user-images.githubusercontent.com/85161724/207934592-87ca644b-8098-497c-9885-7694b0a4a1c5.png)

**Comment by tjerman** [comment]
I think this was fixed a while back; can you get someone to confirm if it's still broken?

**Comment by katrinDY** [comment]
Tested this and can confirm it's working as it should
