### ISSUE TITLE
Record list doesn't resize properly after the sidebar is pinned

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#674]
**Low priority**

## Current behaviour
![Image](https://user-images.githubusercontent.com/85161724/208061107-036b9059-0757-402a-9eda-0468332e7cab.gif)

## Expected behaviour
The record list should resize depending on the space that's left on the page. Only the table should be scrolled and not the whole page

**Comment by katrinDY** [comment]
For today: take a look at task and code, make a plan on how to handle it and start working on the task

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as intended. Since this is a fix there is no need for CL entry for it to be included in the dev.
Moving the ticket to Done.
