### ISSUE TITLE
Unselected fields in CItemPicker shown in Recordlist Configurator

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#675]
## Description of the bug

_When you have a record list with fields like name, email, etc. and those fields are populated, even if you unselect all of the fields from the field picker the data about the name, email, etc. will be displayed. Technically this is not a bug but just an improvement._

## Reproduction steps

1. Create a name space or use already existing one
2. Add a block, record list for example
3. Populate some of the fields for that module
4. Go in the edit block, and unselect the fields from the field picker
5. Press save and notice that the existing data is still there even that there are no fields selected in the field picker.

## Expected behavior

_I assume when there are no fields selected in the field picker, no data to be displayed on the block._

## Screenshots/Video

https://trello.com/1/cards/621f780441d5da7000c9403a/attachments/621f794c323afb04743f921c/download/edit_block_logic.webm

## Versions

Desktop Chrome: v98.0.4758.102 (Official Build) (64-bit)
Branch: 2022.3.x

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks as expected. @yonkov can you just include the CL entry?

**Comment by yonkov** [comment]
### Changelog
Added a module fields description in the Module List configurator that reads: "If no fields are selected, the default values would be shown.

**Comment by Bojan-Svirkov** [comment]
Added CL, @yonkov feel free to merge everything and once merged you can close this issue.
