### ISSUE TITLE
Client authorization removed message notification alignment

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#676]
When you revoke the access of the authorization clients the message/notification that is displayed below is not aligned properly as you can see from the screenshot. The text is not on the same line as the `X`.

![Image](https://user-images.githubusercontent.com/53232926/208079365-7ff53e70-b5e2-4f6e-8dbd-959d7a665a31.png)

**Comment by katrinDY** [comment]
Text message aligned on:
- [23.3](https://github.com/cortezaproject/corteza/commit/9f25111b1c9b3865c0db7e719dc0dbd8e08a0e08)
- [22.9](https://github.com/cortezaproject/corteza/pull/730/commits/54517d20ea460fadc3ce9ae6bb9eb4ab5f65a783)
