### ISSUE TITLE
Check if there are any characters that are filtered in .env

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#678]
## Description
Message from Andre:

_I had someone raise they had and issue using '[' in the env file, is this known to be a limitation? They were setting the webconsole credentials I believe using this string SomeStringWithA[ and found using SomeStringWithA! worked_

## Issue
Might be docker and its way of handling & passing values to the containerized system OR how those (correct) values are then incorrectly read in Corteza

**Comment by tjerman** [comment]
Couldn't manage to get any errors when using `[` in the password (inside and outside Docker).
Andre, could you please elaborate on what exactly the error was?

We don't do any processing on those strings so it could be an OS thing how they handle them?
If they quote the password, does it work (instead `abc[` you do `"abc["`)?

**Comment by tjerman** [comment]
As per Andre, we don't have a way of getting more info at the moment.
Closing the issue
