### ISSUE TITLE
Using Record and then ID in Join and Link datasources causes display issues

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#681]
## The issue

Join and Link steps require you to specify the two datasources to combine as well as the predicate for each (two fields/attributes based on which the combining would occur).

If modules a and b are joined via `ID` and `ref` fields; when defining a join using `a` (the `ID` field) as the local source and `b` (the `ref` field) as the foreign one it works fine.
When reversed, however, it doesn't work as expected (so using `b` (the `ref` field) as the local source and `a` (the `ID` field) as the foreign one)

## Screenshots

The following screenshots indicate the setup where the local and foreign data sources are reversed (the problematic one).

![Image](https://user-images.githubusercontent.com/85161724/208098676-aec9b0a2-b2be-48f7-9d10-d78b48943f05.png)

![Image](https://user-images.githubusercontent.com/85161724/208098687-32daa790-f48f-4439-b426-ed2eba858ef6.png)

![Image](https://user-images.githubusercontent.com/85161724/208098699-e4139498-44f0-423b-8fe7-61c42b7f37cd.png)

**Comment by tjerman** [comment]
The join step is broken on back-end; the link step is broken on front-end.
Will address both

**Comment by katrinDY** [comment]
Tested this with Tomaž and can confirm it's working as expected
