### ISSUE TITLE
Properly handle IDs for PGSQL

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#682]
## Description

Corteza uses `uint64` for the ID but PGSQL does not support unsigned integers so the maximum number it can save is `2^63-1` where the uint64 is `2^64-1`.

PGSQL driver knows how to convert `uint64` to `int64` before saving will start failing once the number passes `2^63` range.

## Solution

This should be fixed on the database driver side (`store/drivers/rdbms/pgsql`) and not in the service layer (ID should remain as `uint64`).
The most probable solution will require you to change the data type of ID and reference table columns (ref where to start `store/adapters/rdbms/drivers/postgres/dialect.go` and `store/adapters/rdbms/drivers/sqlserver`).

Utilise `numeric` data type (https://www.postgresql.org/docs/current/datatype-numeric.html) to solve this issue (check how I've done it for mssql).

This must be fixed on `2023.3.x`, `2022.9.x`.
This would optimally be addressed on `2022.3.x`.

## Potential issues

- how will we do the migration code if any at all

**Comment by KinyaElGrande** [comment]
## Reproduction steps

### Existing postgres database

Restart your server then check the datatype for tables with the `id` column, except for the `auth_sessions`, all other tables `id` column should have a `numeric` datatype.

### Fresh postgres database

For every table with an `id` column except the `auth_sessions`  table, the `id` column datatype should be `numeric`.

**Comment by Bojan-Svirkov** [comment]
Retested this and I can now confirm that everything work as expected. Moving the ticket to Docs & Changelogs and @KinyaElGrande when you have the time feel free to write up the changelog entry.

**Comment by KinyaElGrande** [comment]
## Change Log entry

### Fixed

**What was fixed**:  CortezaID datatype in PostgreSQL database.

**How was it fixed**:  Changed the datatype for CortezaID in the PostgreSQL database from bigint to numeric.

**Comment by Bojan-Svirkov** [comment]
CL entry added.

**Comment by skamensky** [comment]
Are there any plans for migration? If I were to do this manually, is this just altering the types for all id fields to numeric from bigint?
