### ISSUE TITLE
The record create interface is not consistent with the display

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#685]
**Low priority**

## Description
When I view the record via the "all records" view in the admin panel everything seems fine.

When I create a new record, I get a different view which makes it feel off.
In the version prior, both interfaces (view and create) were the same.

## Location
Compose/admin/modules/all records/add new record

![Image](https://user-images.githubusercontent.com/85161724/208120914-7ee174b2-461c-4301-9587-1b978e4a8589.png)

![Image](https://user-images.githubusercontent.com/85161724/208120920-768594d2-554e-4607-9814-40b8df464307.png)

**Comment by katrinDY** [comment]
Todo: check if this is still the case and if so discuss with Jože on what to do

**Comment by EmmyMay** [comment]
This looks to have been fixed to be consistent on both 2023.3 and 2022.9.

![Image](https://user-images.githubusercontent.com/31524469/223098133-b90af488-1cc7-4450-bdca-7a7ec9b1f472.png)



![Image](https://user-images.githubusercontent.com/31524469/223098156-1824cf97-f5e1-462d-9e52-1e952b2683fa.png)

**Comment by katrinDY** [comment]
For today: sync with Bojan to discuss task - what needs to be tested and be done

**Comment by Bojan-Svirkov** [comment]
Everything looks good, moving the ticket to **Done**.
