### ISSUE TITLE
Workflow resource validation with iterators when limit set to 0

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#695]
## Description
When the limit on the iterator is set to 0 it doesn't display any data. My assumption is that it should display all of the data so it could match the same logic as records per page on compose when the limit is set to 0 it displays all of the present data. All of the other limits work fine.

## Workflow
https://gist.github.com/katrinDY/0acc1d546fd5445c8962819ccfd2fd47

**Comment by tjerman** [comment]
## Changed

### What

workflow iterators to treat limit 0 parameter as no limit set

### Why

to make workflow iterators consistent with other searching/filtering interactions

### Refs

monorepo

- 2022.9.x `fc259ca62`
- 2023.3.x `cc24e622a`

**Comment by katrinDY** [comment]
Tested this on both branches and can confirm it works as expected. Moving to CL & Docs so this can be added to the CL

**Comment by Bojan-Svirkov** [comment]
Added CL
