### ISSUE TITLE
Enable joining and linking of aggregate datasources

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#700]
Aggregate datasources should be able to be linked and/or joined

**Comment by tjerman** [comment]
I've found the issue(s) and a few extra ones.
Giving the solutions some time in case I think of something better.

**Comment by tjerman** [comment]
@Bojan-Svirkov this also includes https://github.com/cortezaproject/corteza/issues/681

I've opted to firstly patch this issue out (it turned out it was simpler then firstly perceived) and I'll do a bunch of refactoring with those attribute related issues.

**Comment by katrinDY** [comment]
Tested this with Tomaž and can confirm it's working as expected
