### ISSUE TITLE
Add name to all column selector labels in reporter

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#702]
If you had a joined datasource and the column names were the same then you couldn't know from which datasource the column was. I extended the selector labels so that now you can see its name that has the information about the datasource it belongs to

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. The only part left now is the CL entry.

**Comment by Fajfa** [comment]
Changed

- What: The column selectors in reporter(prefilter, label/primary/secondary column) now all show the label and name of the column, they can also now be searched except for the presort. 

- Why: To make it easier to differentiate between the different fields that have the same label, for example after using a Join.

- How: Replaced the default bootstrap select with the vue-select component. That provides a more feature rich select implementation.
