### ISSUE TITLE
Reporter chart block overflowing if used in compose and block has title

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#703]
If you used a reporter chart in compose and the block had a title, the chart was overflowing the block

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. The only thing left now is the CL entry.

**Comment by Fajfa** [comment]
Fixed:
- What: If reporter chart was used inside a compose page block and the block had a title, the chart would overflow the block
- How: By using the same layout as on regular compose charts
