### ISSUE TITLE
Permissions modal title not correct on reporter edit if handle not defined

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#704]
Some permissions modals did not have the correct titles if the resource handle was not defined, mainly reporter

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. The only thing left now is the CL entry.

**Comment by Fajfa** [comment]
Fixed:
- What: Permissions modal title was sometimes incorrect if the resource didn't have a title/handle defined
- How: By making sure the resourceID will show in the permissions modal title if no other identifiable information exists
