### ISSUE TITLE
Extend reporter chart configurator so that its more similar to compose

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#705]
Added some configurations to reporter charts so they can be configured like compose.
Note some configurations are still missing, we should combine the two into the same configurator at a later stage.

Added:
- Rotate labels for x and y axis
- Always show tooltips checkbox
- Legend configuration
- Offset configuration

**Comment by Bojan-Svirkov** [comment]
Everything looks good just this needs to be aligned:

![image](https://user-images.githubusercontent.com/53232926/208896415-e018a1aa-189a-4e0a-8de7-5329a7dec1de.png)

**Comment by Bojan-Svirkov** [comment]
Now everything looks good, the only part left is the CL entry.

**Comment by Fajfa** [comment]
Added:
- What: Most missing configuration options that were in compose charts but not in reporter charts, e.g. Legend, Tooltip, Offset, label rotation for X and Y axis.
- Why: To provide the same set of features on both chart configurators
