### ISSUE TITLE
Sorting doesn't work in admin federation nodes

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#716]
When you try to sort by name, status or created, the sorting doesn't work and nothing happens.

**Comment by tjerman** [comment]
## Fixed

### What

missing support for filtering, sorting, and paging over federation nodes.

### Refs

2022.9 monorepo commit `22f49b031`

### Misc

https://user-images.githubusercontent.com/12545711/212267936-87ade1f5-d94d-4ed1-959c-e88be4a5a1e4.mov

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed.

**Comment by Bojan-Svirkov** [comment]
Added CL
