### ISSUE TITLE
Federation nodes in federations settings in compose are not shown as they should

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#717]
When you open federation settings in compose and if you have multiple nodes, the nodes misbehave if you zoom in or zoom out the page. See the video for better reference:

https://user-images.githubusercontent.com/53232926/209122732-0605675f-fd86-43cd-a2df-a3ea82b919f6.webm

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. @katrinDY now the only thing left is the CL entry.

**Comment by katrinDY** [comment]
CL

Fixed

What: A bootstrap class was removed

How: The bootstrap class `text-truncate` was removed from the `<b-list-group-item>`


Ref:
- 22.9 [efe382b](https://github.com/cortezaproject/corteza/commit/efe382b3d4782b2367a0f2b9ac196e23a875aa13)
- 23.3 [8b7f903](https://github.com/cortezaproject/corteza/commit/8b7f903378a867d193fb4a20a8a1fefe8d2db60e)

**Comment by Bojan-Svirkov** [comment]
Added both .9 and .3 CL
