### ISSUE TITLE
Can't zoom in uploaded file in record

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#718]
**Low priority**

## Steps to reproduce
1. Create a module with a field of type file
2. Click on `All records`
3. Add a new record
4. Upload a file
5. Save the record
6. Hover over the uploaded file and see the magnifying glass appear
7. Click on the file and see that nothing happens
7.1. Also can we add margin/padding on the right side of the file so it looks better?

## Video of issue
![Image](https://user-images.githubusercontent.com/85161724/209133581-b89823eb-7355-4089-9e3a-d7ac31e37796.gif)

## Why doesn't this work
The preview modal is only initialized on public pages so it will only work there

## TODO
- [x] move the attachment modal from public/pages/view, to namespace/view so the view can be used in both places

**Comment by katrinDY** [comment]
Where this should be tested:

Admin area:
- Module -> All record -> in the table of records click on the uploaded file
- Module -> All record -> in the table of records click on a record that has an uploaded file -> click on the uploaded file 
- Module -> All record -> in the table of records click on a record that has an uploaded file -> edit a record -> click on the uploaded file
- Edit page -> edit file block -> preview the uploaded file

Public area:
- In a public page -> in a File PB -> click on the uploaded file

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. @katrinDY , now the only thing left is the ChangeLog entry.

**Comment by katrinDY** [comment]
CL

Changed

What: The location of the attachment modal

Why: To enable previewing of attachments in private pages

How: The attachment modal was moved from Public/Pages/View to Namespace/View

Ref:
- 22.9 [ea1c1fa](https://github.com/cortezaproject/corteza/commit/ea1c1fa7889b3efb83e94127fcaad4ac44e56a2b)
- 23.3 [6ade044](https://github.com/cortezaproject/corteza/commit/6ade04484397285d541a2da1ff88e497c98717fb)

**Comment by Bojan-Svirkov** [comment]
Added both .9 and .3 CL
