### ISSUE TITLE
Cannot open record in a new tab

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#719]
## Issue

![Image](https://user-images.githubusercontent.com/85161724/209144454-c86dca85-5a2e-4ec4-9454-4e22677ac946.gif)

**Comment by Bojan-Svirkov** [comment]
@katrinDY I just tried to reproduce this on our QC instance and I wasn't able to. The function works as expected and records open up in new tabs. Can you also confirm this so we can close this issue?

**Comment by katrinDY** [comment]
Tested and can confirm this is working as expected
