### ISSUE TITLE
Creating a dummy automation button causes errors in the console

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#720]
## Errors
![Image](https://user-images.githubusercontent.com/85161724/209145991-3f5613ff-04e6-4c03-bd6e-4a7e062f20e4.png)

## Issue

![Image](https://user-images.githubusercontent.com/85161724/209146088-af514f83-1365-45b5-8505-d39b28d124d0.gif)

## Missing/broken translations

![Image](https://user-images.githubusercontent.com/85161724/209147121-7f140e6d-1a45-4f53-97aa-20d197aaf609.png)

**Comment by Fajfa** [comment]
Fixed: d79a4eefa

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now working as expected. Moving the card to **Done**.
