### ISSUE TITLE
Sorting doesn't work in admin Sensitivity Levels

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#722]
When you have multiple sensitivity levels and you try to sort them by the levels, they are not sorted and the list stays the same.

**Comment by tjerman** [comment]
I would consider ignoring this task as the UI for defining sensitivity levels is going to change anyway (no longer a table)

**Comment by tjerman** [comment]
Or rather ignore it all together.
The order of sensitivity levels is important as it indicates their hierarchy.
Allowing reordering via some arbitrary parameter could cause confusion.

**Comment by Bojan-Svirkov** [comment]
Since this doesn't look relevant anymore, I will close this issue.
