### ISSUE TITLE
Wrong password constraint number shown when changing password

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#723]
## Issue

![Image](https://user-images.githubusercontent.com/85161724/209169272-4f3e2926-5456-4165-8cb3-93311d3181dc.gif)

## Expected behaviour
The message should say `The passwords must be at least 10 characters long!` and not `The passwords must be at least 8 characters long!`

## Notes
After refreshing the page the correct number is shown
Also, we can hide the `Remove password` button if a password isn't set. Or we can leave this for another time.

**Comment by Fajfa** [comment]
Fixed: 6ed937278
