### ISSUE TITLE
Issue after creating a workflow in admin

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#725]
## Error

![Image](https://user-images.githubusercontent.com/85161724/209180340-feeb6f55-6a00-4ad7-a9f8-00cf616431d6.png)

## Issue

![Image](https://user-images.githubusercontent.com/85161724/209180700-bbc68666-6c3d-4b7d-84d2-404ad430f679.gif)

**Comment by Fajfa** [comment]
Fixed: 4918e35668e58b844715c31eec1f8dc262f69b83
