### ISSUE TITLE
Internal error when trying to change new password with old

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#728]
## Steps to reproduce
1. In any webapp click on `?` icon in the topbar
2. Click on `Change password`
3. Change you password successfully (nothing special was done here)
4. Try to change your new password with the previous
5. Get internal error (no server errors)

![Image](https://user-images.githubusercontent.com/85161724/209363237-cc7d448a-133f-498a-ac07-209a26679d1c.png)

## Notes
I tried to request a password change but got internal error again and server log this time

![Image](https://user-images.githubusercontent.com/85161724/209363237-cc7d448a-133f-498a-ac07-209a26679d1c.png)

![Image](https://user-images.githubusercontent.com/85161724/209363451-75155de6-65a5-4e42-97a5-2befb1f5d45b.png)

**Comment by tjerman** [comment]
iirc we started preventing resetting passwords to the current one.
Will check

**Comment by tjerman** [comment]
## Fixed

### What

uninformative `internal error` error message on the user profile change password interface

### How

properly handling and serving the error message

### Refs

monorepo
- 2022.9.x commit `82c70b366`
- 2023.3.x commit `73a29b6b9`

**Comment by tjerman** [comment]
![Image](https://user-images.githubusercontent.com/12545711/210550285-66e78ab0-9491-4ba8-bf97-61aacf77aba2.png)

**Comment by katrinDY** [comment]
This is tested and working as it should

**Comment by Bojan-Svirkov** [comment]
Added CL
