### ISSUE TITLE
Refresh page block improvements

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#731]
## TODO
- [x] add a manual refresh button so the user can choose when to refresh a page block

**Comment by tjerman** [comment]
Think that the backend tag is not needed here

**Comment by EmmyMay** [comment]
We have manual refresh already. But maybe we need to make it more prominent if it is being easily missed.

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/212346023-dbea5758-c0c0-4240-a794-5dd35e873859.png)

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/212348011-e0d2ae48-4c59-4db5-acfe-cd9d91c38195.png)

**Comment by EmmyMay** [comment]
# Changelog Entry

## Added

##  What was added
Manual Refresh option was added so that users can choose when to refresh a block.

## Why was it added?
To give users more control over refreshing when auto-refreshing is not needed.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. I will just wait for this to be merged so I can include the commit to the CL.
