### ISSUE TITLE
Add chart animation as a configuration option and prevent animation on chart refresh.

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#732]

**Comment by tjerman** [comment]
Think that backend tag is not needed here

**Comment by Bojan-Svirkov** [comment]
You still cannot enable the chart animation. When you disable the `Animation disabled` button and you press save, the toggle is back again enabled even though you disable it. Check the video for better reference.

[chart animation.webm](https://user-images.githubusercontent.com/53232926/214337135-f17fda0f-3861-4733-b15f-60b7a37de807.webm)

**Comment by Bojan-Svirkov** [comment]
Retested this and I can confirm that this finally looks and works as expected. The only thing left now is the CL entry.

**Comment by Fajfa** [comment]
Added

- What: A configuration option on charts to disable or enable animation
- Why: To allow users more chart configuration options

**Comment by Bojan-Svirkov** [comment]
CL added.
