### ISSUE TITLE
Pasting a copied block does not work. 

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.x

### Current Behavior

Block Pasting is not working. 

### Expected Behavior

When you paste a block it is not being pasted.

### Steps To Reproduce

In Compose, copy a block and try to paste it in page builder.

**Comment by katrinDY** [comment]
Found an issue:

Steps to reproduce:
1. Create a record list page block
2. Copy and paste the created page block
3. Change the title, description, translations of the copied page block
4. Save the change
5. Click on view page
6. Click on page builder
7. Click on view page
8. See that the title, description, translations of the copied page block have applied to the original page block

If you do the same thing the other way around - change the title, description, translations of the original page block, the changes will be applied to the copied page block

![Image](https://user-images.githubusercontent.com/85161724/210552060-63a45011-8454-4830-82f2-4f798f511192.gif)

**Comment by katrinDY** [comment]
After the latest changes title and description don't duplicate anymore. There's a new issue with translations. After adding a translation to the original page block -> saving -> view page -> page builder -> the title and description translations of the copied page block + the rest of the page blocks are removed


![Image](https://user-images.githubusercontent.com/85161724/210577086-78ec2664-4689-418c-985f-2138997714fe.gif)

**Comment by katrinDY** [comment]
Translations are no longer duplicated but the issue of title and description being removed after adding a translation in a language different from English is still present. Notice how after adding a translation to Hebrew, for example, this removes the title and description of all other page blocks.

![2](https://user-images.githubusercontent.com/85161724/210759206-1786bbde-cc9f-4091-a7b7-cbf4452c022f.gif)

**Comment by katrinDY** [comment]
An improvement/suggestion: after clicking on the copy page block button, unfocus the button and focus the whole page so you can directly paste the copied page block. Currently, I have to click somewhere else to unfocus the copy button which isn't that good, for me at least. If you are in the page builder and don't have any empty space between the page blocks it can be a bit awkward to "find" where to click in order to unfocus the copy button.

**Comment by katrinDY** [comment]
Tested this and can confirm that it's working as expected

**Comment by EmmyMay** [comment]
# Changelog Documentation

## Fixed

### What was Fixed?

**Issues with the copy paste feature** 
**Issues with focusing for pasting a block**


### How was it fixed?

**Resolved an issue where pasting was not working at all. Copied blocks can now be pasted.**
**Improved pasting and copying so that users don't have to click around to focus onto where they should paste a copied block**

**Comment by Bojan-Svirkov** [comment]
Added CL.
