### ISSUE TITLE
Duplicated Blocks title and desc issue when translated

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#743]
### Issue
 Translations are no longer duplicated but the issue of title and description being removed after adding a translation in a language different from English is still present. 
Notice how after adding a translation to Hebrew, for example, this removes the title and description of all other page blocks.

![2](https://user-images.githubusercontent.com/85161724/210759206-1786bbde-cc9f-4091-a7b7-cbf4452c022f.gif)

_Originally posted by @katrinDY in https://github.com/cortezaproject/corteza/issues/737#issuecomment-1372041458_

### Expected Behaviour

Duplicating a block and adding translations should not remove the title and description of other blocks

**Comment by katrinDY** [comment]
Tested this and can confirm it works as expected. All that's left to do is add CL

**Comment by EmmyMay** [comment]
# Changelog Documentation

## Fixed

### What was Fixed?

**Issues with Block title and Description when translations are included** 


### How was it fixed?

**Updating translations no longer affects other blocks with duplicate titles and description**
**Translation bugs when a block is duplicated has been resolved**

**Comment by Bojan-Svirkov** [comment]
Added CL
