### ISSUE TITLE
Map in geometry PB is overlapping toolbar buttons

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#745]
## Issue

![Image](https://user-images.githubusercontent.com/85161724/210829997-c5d70ea5-59af-4c2f-8799-746e508c35fb.png)

## Expected behavior
The map shouldn't appear on top of the buttons

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now is looking good. @katrinDY when you have the time just try to add the CL entry.

**Comment by katrinDY** [comment]
CL

Fixed

What: The map in the geometry page block was overlapping the toolbar buttons

How: The z-indx of the toolbar element was increased so the buttons appear in top of the map and not the other way around

Ref:
- 23.3 [ed097b6](https://github.com/cortezaproject/corteza/commit/ed097b6822e7959db619ff1cca1be3223514b620)

**Comment by Bojan-Svirkov** [comment]
Added CL
