### ISSUE TITLE
Record revision page block doesn't show any data when in page builder mode

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#747]
## Steps to reproduce
1. Pick a module (doesn't matter which)
2. Edit the module
3. Select the record revision tab
4. Enable record revisioning
5. Go to the record page of the same module
6. Edit a record
7. Add a record revision page block
8. Notice how in page builder mode no data is displayed
9. Switch to view mode and see the data displayed

![Image](https://user-images.githubusercontent.com/85161724/210834465-79cb0a56-9f14-4b21-8349-6c427a99a430.png)

## Expected behavior
Either the same data should be displayed as in view mode or some kind of text should be shown. Discuss with Jože

**Comment by yonkov** [comment]
## Changelog

Added an empty table with "No record revisions found" message in admin record template. Added the message in the public record page, when there are no revisions.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good.

**Comment by Bojan-Svirkov** [comment]
Added CL
