### ISSUE TITLE
Record revision datetime type not shown correctly

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#748]
*Needs confirmation*

## Steps to reproduce
1. Pick a module with a field of type datetime (CRM -> Contacts)
2. Edit the module
3. Select the record revision tab
4. Enable record revisioning
5. Go to the record page of the same module
7. Add a record revision page block
8. Notice the type of `Birthdate`

![Image](https://user-images.githubusercontent.com/85161724/210836846-c621a217-820d-4c78-9b64-8ad34e47d810.png)

**Comment by Bojan-Svirkov** [comment]
Tested this and can confirm that this works as intended and the only thing now left is the CL entry.

**Comment by kelanik8** [comment]
Changelog:

**What changed**
- fixed the record revision datetime type not showing correctly

**Why did it change**
- record list revision is not displaying the datetime type correctly, it display a the translation field and not the value of the datetime label

**How did it change**
- updated the type section translation on the record revision configurator to display the fields as camel case, which is the case for the datetime on the translation itself

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL entry
