### ISSUE TITLE
Exporting a WF without a handle results in having a name json.json

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#755]
When you have a WF without a handle and you try to export it, the exported WF is having a name json.json.

Should we change the exported WF to be taking the name of the WF instead of the handle?

**Comment by tjerman** [comment]
I would say we always use the name of the workflow in place of the handle (can also do handle -> name) and if none is present we can use a generic label or the ID.

**Comment by tjerman** [comment]
WF exporting is a pure FE task at the moment
