### ISSUE TITLE
IN operator not working on number multi value field

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#759]
## Description of the bug

_When you have a multi value number field and you want to filter with `contains` or `not contains` the filter doesn't return anything. (It is working fine for the other fields, it looks like the problem is only with the number field)_

## Reproduction steps

1. Create a multi value number field
2. Go on the public page and create couple multi value records
3. Try to filter out with the contains filter
4. Notice that no records are returned

## Expected behavior 

_You should be able to filter multi value number fields as you can with text or other fields._

## Video

https://user-images.githubusercontent.com/53232926/211555503-26db0e8d-be6e-4e79-8d1c-0b9550143935.webm

## Versions

Branch: 2023.3.x and 2022.9.x

**Comment by vicpatel** [comment]
Fixed with #776

**Comment by Bojan-Svirkov** [comment]
Just retested this and can confirm that this is now fixed. @vicpatel just when you can try to add the CL entry.

**Comment by vicpatel** [comment]
Fixed

What:
- Fixed filtering for multi-value number field with `contains` or `not contains` criteria.

How:
- By making sure to convert numbers into string format while building a query for the selected filter.

[7185611](https://github.com/cortezaproject/corteza/commit/7185611647d9960bcaf7153f5b5726f3f584fbfa)

**Comment by Bojan-Svirkov** [comment]
Added CL.
