### ISSUE TITLE
Sorting in reports with link steps doesn't work as expected

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#761]
When sorting a table which is showing a link step, the sort seems to order numbers based on text sorting rules, not on number sorting rules.

See the column `bb n1`; the values are numeric but the descending order was done using character order.

![Image](https://user-images.githubusercontent.com/12545711/211752013-8ef8f8e9-e365-4afb-92cf-abb120c30c76.png)

**Comment by tjerman** [comment]
@katrinDY this should be done in the next sprint because it's quite a big deal

**Comment by katrinDY** [comment]
For today: time-box to 1h to get familiar with DAL. Then spend 2 more hours trying to resolve issue. If you get stuck ping Tomaž.

**Comment by tjerman** [comment]
Found and resolved the issue; has to clean up the code a bit before submitting a PR.
Should be sorted by EOD

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as intended. Since this is a fix there is no need CL entry for it to be included in the dev.
Moving the ticket to **Done**.
