### ISSUE TITLE
Saving a report returns error 500 because its datasources are not saved

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#762]
## Description of the bug

_When you create a new report and you try to load and create a table, on the first save you are receiving error `Failed to run report: Request failed with status code 500`, but if you click save again, now the report is saved and everything works as expected.
This happens because you have to save report to save its datasources. Otherwise they wont work._

## Reproduction steps

1. Create a new report
2. Create a load datasource
3. Add a table block and configure it properly
4. Press save and notice the error
5. Press save again and see that the report is saved as it should

## Expected behavior 

_When creating a new report the error should not pop up when saving the report._

## Video

https://user-images.githubusercontent.com/53232926/211777951-b2136695-2395-4565-a42f-7b97dfe926a0.webm

## Versions

Branch: 2022.9.x & 2023.3.x

**Comment by Fajfa** [comment]
Datasources are now saved when pressing the save datasources button in the datasources modal.
The datasource configuration changes will also be reset if cancel button is clicked

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL has been also added.
