### ISSUE TITLE
Issue with record list query without selected fields

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#763]
It happens when there is no field selected to be displayed in the record list:

1. Add a record list for any module
2. Do not select any fields for the record list and try searching with the query.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. @Fajfa when you have the time just try to add the CL entry.

**Comment by Fajfa** [comment]
Fixed

-What: Searching a record list if it didnt have any fields selected in the configurator was not functional.

- How: By making sure a record list with default fields uses those instead of the selected ones to search from

**Comment by Bojan-Svirkov** [comment]
Added CL.
