### ISSUE TITLE
Unconfigured source in geometry field causing issues

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#766]
## Steps to reproduce
1. Create a geometry page block
2. Add a source event without selecting a module
3. See error in the console

![Image](https://user-images.githubusercontent.com/85161724/211815039-322c6431-b4df-499a-b249-25ff81abf5fc.gif)

## Expected behaviour
We shouldn't save unconfigured sources

### Requirements

- [x] Geometry field should be required for isValid check
- [x] Change order of inputs to Select, Geometry field, title, prefilter ....
- [x] Change Select module to Select
- [x] Module and Geometry field should be asterisked

**Comment by EmmyMay** [comment]
The issue has been updated with new requirements that should close the PR.

**Comment by katrinDY** [comment]
For today: resolve blocker on 23.3 and start working on this ticket. Submit for code review by EOD or tomorrow morning depending on when the blocker is resolved.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed.

**Comment by EmmyMay** [comment]
### Changelog Entry

**What Changed?**

The Geometry Block

**How did it change?**

- The way form fields are ordered in the 'Configured Sources' tab.
- The requirements for which the Geometry block is evaluated. Now you need to have selected a module and Geometry field.
- Required fields now have an asterisk for indication.
