### ISSUE TITLE
Related record not showing up on magnification

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Related information only shows if you press filter or sort

### Expected Behavior

Related information shows without users needing to interact further with the page

### Steps To Reproduce

See attached video

### Environment and versions

```markdown
`2023.3.0-dev.1`
```

### Anything else?

Maybe related to https://github.com/cortezaproject/corteza/issues/635

[Funding Attempt _ CRM _ Low Code.webm](https://user-images.githubusercontent.com/19151369/212548531-b658aefd-9ff7-49bf-91e7-2dd8e166e598.webm)

**Comment by skamensky** [comment]
Apprently this is not only on magnification. I'm showing a list of "cousin records" (records that share a parent with the current record), and the list is not showing on page load of a standard record page.

See here
[Lead _ CRM _ Low Code.webm](https://user-images.githubusercontent.com/19151369/212655401-b4834b67-dd4f-4bf7-9d41-c1654eadcbf5.webm)

**Comment by Fajfa** [comment]
This was fixed in 2023.3.0-dev.2
