### ISSUE TITLE
Date and Time record field issues

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#797]
Tests done on QC `2022.9.6-rc.1`

- [x] 1. When you have date only field, and you set the filter to be equal to the correct day, it is not showing any record. (it only shown for not equal and greater then)

- [x] 2. When you have time only and past values configured, it looks like the configuration is only taking the hour in its configuration, because even if you set minutes in the past it will say invalid form as long as you don't also change the hour too. (not sure if this is the expected behavior). Same goes for future time only, if you set minutes in the past but the hour is still the same, the time will work.

- [x] 3. When you have time only value, and you try to filter with a time filter, this is the error popping out `Could not load record list: pq: cannot cast type time with time zone to timestamp with time zone`

**Comment by Bojan-Svirkov** [comment]
@kelanik8  I tried testing 2nd, 3rd and 4th point and when I try to filter this is what I am getting:

for 2nd point:
<img width="1280" alt="2  date only" src="https://user-images.githubusercontent.com/53232926/217802390-5b135b9d-14fc-451b-9858-5b4b19faf8c0.png">

for 3rd and 4th point:

<img width="1278" alt="3  past time" src="https://user-images.githubusercontent.com/53232926/217802420-f0cc198a-8965-4cf3-9eb2-e0f3c1b20037.png">

Can you please take a look at this.

**Comment by Bojan-Svirkov** [comment]
Tested the above 3 points also with using different time zones and I can confirm that this now works flawlessly. @kelanik8 the only thing now left is the CL entry. 🎉

**Comment by kelanik8** [comment]
Changelog:

**What changed**
 - fixed the record list filter builder for `date` only and `time` only filter types

**Why did it change**
 - record list filter for field type `date` only and `time` only is not properly fetching the records based on the record list filter

**How did it change**
 - updated the record list filter builder with the correct query entry for `time` only and `date` only

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL entry
