### ISSUE TITLE
Additions to charts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#798]
## Description
A couple of chart features Lenny suggested

## Features
- [x] Save as image

```
  toolbox: {
    feature: {
      saveAsImage: {}
    }
  },
```

You can test it by adding it to https://echarts.apache.org/examples/en/editor.html?c=pie-simple, in the options.

---

- [x] Stacked line & bar chart
Same as line and bar chart, but with 1 option added to the series:

```
stack: 'Total',
```

https://echarts.apache.org/examples/en/editor.html?c=area-stack
line 44

---

- [x] Step line chart
Same as line chart, but with 1 option added to the series:

```
step: 'start',
```

https://echarts.apache.org/examples/en/editor.html?c=line-step
Line 33

---

- [x] Zoom on line chart

In a line or bar chart, using this piece in the options

```
  toolbox: {
    left: 'center',
    itemSize: 25,
    top: 55,
    feature: {
      dataZoom: {
        yAxisIndex: 'none'
      },
      restore: {}
    }
  },
```

https://echarts.apache.org/examples/en/editor.html?c=line-tooltip-touch
Line 32 until 42

---

- [x] Coxcomb chart
Same as a pie chart, but with only 1 option added to the series:

```
roseType: 'radius',
```

https://echarts.apache.org/examples/en/editor.html?c=pie-roseType
Line 40. If you remove it, the chart is a normal pie chart.

---

- [x] Ring Gauge chart
Gauge charts can be round, when you define the following angles in the series:

```
  startAngle: 90,
  endAngle: -270,
```

You can see it here: https://echarts.apache.org/examples/en/editor.html?c=gauge-ring

**Comment by Fajfa** [comment]
#1071
