### ISSUE TITLE
Not able to save module discovery config

### ISSUE THREAD

**Issue by vicpatel** [cortezaproject/corteza#802]
Not able to save module with discovery configuration, There is inconsistency with request data and module struct.

Fixed with [22.9](https://github.com/cortezaproject/corteza/commit/c4b4909d65bb76ac3ed3e876f199da4cd1f7755b), [23.3](https://github.com/cortezaproject/corteza/commit/c4b4909d65bb76ac3ed3e876f199da4cd1f7755b).

No CL is required as of now, It was broken due to sync b/w FE, and BE.

**Comment by vicpatel** [comment]
Ref Branch: `2022.3.x-fix-discovery`, Need to fix upgrade schema for migrated discovery settings.

**Comment by vicpatel** [comment]
Server changes are done.
On compose, It's not displaying as expected after saving discovery setting(on module save).

**Comment by Bojan-Svirkov** [comment]
@vicpatel when I try to start the server while on branch: `2022.3.x-fix-discovery`, I am getting this error and the server won't start

![image](https://user-images.githubusercontent.com/53232926/217079912-4ade458c-cec0-45b9-a166-d1ea6e3f6f41.png)

**Comment by vicpatel** [comment]
BranchName: `2022.9.x-fix-discovery`

**Comment by Bojan-Svirkov** [comment]
The server now starts, but the creation of modules is not possible even without any discovery settings:
![image](https://user-images.githubusercontent.com/53232926/217776236-4e2c38d9-0c91-4fc2-916e-915c7ab6802f.png)

**Comment by Bojan-Svirkov** [comment]
Tested this and can confirm that everything works fine now. I see that @vicpatel wrote that no CL is required here so I will just move the ticket straight to **Done**.

**Comment by vicpatel** [comment]
Fixed:

What:
- Fixed saving issue with module discovery settings
How:
- By Migrating discovery settings to support multi-language, and updated module discovery config struct to support multi lang result.

**Comment by vicpatel** [comment]
Merged 

2022.9 commit
- https://github.com/cortezaproject/corteza/commit/724804c493703a2dca897fa9bcc5227d69a117dd
- https://github.com/cortezaproject/corteza/commit/e020f7453a6b9c20fdd2c2c1c370ad3de2e857d2

 2023.3 commit
- https://github.com/cortezaproject/corteza/commit/ab283f89c38534838b183834b4b13893dadd302e
- https://github.com/cortezaproject/corteza/commit/3af167c1d60237986cf11da9d197ac526a349683

**Comment by Bojan-Svirkov** [comment]
Added CL, moving the card to **Done**.
