### ISSUE TITLE
Calendar block manual refresh inconsistency

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#809]
## Description of the bug

_When you have a calendar block with a manual refresh and the records are shown on the calendar when they are created (created_at), and you have couple records and when you delete one of the records and you refresh the calendar block, the record is still shown. The record will go away just if you reload the whole page._

## Reproduction steps

1. Create a calendar block with manual refresh that has records enabled in the event source
2. Create couple records and notice that they are shown on the record on the date that they were created (if that is the configuration in the event source)
3. Delete one of the records
4. Press on the manual refresh on the calendar block and notice that even though the record is deleted, it is still shown on the calendar block
5. Check the video for more context.

## Expected behavior 

_The calendar block should also refresh when triggered a manual refresh as in other page blocks._

## Video

https://user-images.githubusercontent.com/53232926/214026358-af714752-f91c-4d8c-a933-cb9a7d1652db.webm

## Version branch

Branch: 2023.3.x

**Comment by Bojan-Svirkov** [comment]
Retested this and confirming that this now works as expected. The only thing now left is the CL entry.

**Comment by EmmyMay** [comment]
# Changelog Entry

## Fixed

##  What was fixed
Calendar block manual refresh was not updating events.

How was it fixed?
Manual refresḣ now triggers update of events.
