### ISSUE TITLE
Error Handling Message In Workflows

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#810]
## About

We would like to improve error handling inside workflows by letting configurators access the context of the error message.
Currently, we can only define what path the WF should take in case of error but we don't really have any way to figure out what happened.

Inside of the catch branch, we'd like to define some variables that specify what the error was, what step it was on, ...

## How

Up to you.
I'd suggest the error handler provides a way for you to define into what variable the error message (and surrounding context is placed in) so the configurator has more freedom in defining error handling.

Other options would be to just define a (set of) variable(s) that hold the error message and the context.

## Ref forum post

https://forum.cortezaproject.org/t/error-handling-message-in-workflows/1219

**Comment by katrinDY** [comment]
Limit the amount of features you want to implement so this task only takes you max 2 days

**Comment by vicpatel** [comment]
Currently, we do have scope variable `error`, that contains the error message.
As an improvement we will let users specify into what variable the error is stored.

**Comment by tjerman** [comment]
This is then an addition, prefer to resolve actual issues over this for now

**Comment by vicpatel** [comment]
For FE, Add arguments on error-handler step for the `error` and `errorMessage`.

**Comment by vicpatel** [comment]
As per discussion, Updated PR with error, errorMessage, and error stepID.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.

Added CL:

```
Added:

{
      "what": [
        "support for error handling message inside workflows by letting configurators access the context of the error message."
      ],
      "why": [
        "to give user more freedom in defining error handling and to know where and on which step the error occurred."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1088"
      ]
    }
