### ISSUE TITLE
Add/Extend color picker that allows transparent option

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#811]
When you configure a metric block and you either configure the block to be shown either as a card or not you don't see much difference and the background is still there, it is white and it is not transparent as in the other page blocks. I guess if possible this should be revised.

Display as a card disabled.
![Image](https://user-images.githubusercontent.com/53232926/214091926-47d05811-ff00-427f-9a4b-eca18918e0af.png)

Display as a card enabled.
![Image](https://user-images.githubusercontent.com/53232926/214091927-4bd93d3f-f3e8-48be-9f12-13790c2f228b.png)

**Comment by katrinDY** [comment]
@Bojan-Svirkov, I don't think this is an issue. The Metric PB has a background color set to it so it looks like the card style isn't applied. Here's an example of two Metric PBs - one with a title and the other displaying a value. Notice how they look when a value is and isn't displayed. It's the same for both 22 and 23

Page builder mode:
![Image](https://user-images.githubusercontent.com/85161724/225682512-a9315068-d319-465e-bcd5-4858f4a5dc30.png)

Public page:
![Image](https://user-images.githubusercontent.com/85161724/225682513-a9c4088b-2336-4c9b-940f-06be8bdaf4c4.png)

**Comment by katrinDY** [comment]
Change of plan: I'll try to remove the background

**Comment by katrinDY** [comment]
For today: try to find a solution for this task

**Comment by katrinDY** [comment]
For today: add plan and start implementing it

**Comment by katrinDY** [comment]
Plan:
- [x] add a button to the metric configurator that sets the background color to transparent
- [x] create a custom color picker and add it to the metric configurator

**Comment by katrinDY** [comment]
For today: implement the rest of the functionality and submit for code review

**Comment by katrinDY** [comment]
FE added. Gonna need BE property for the transparent background prop

**Comment by katrinDY** [comment]
For today: submit task for code review after BE is added

**Comment by katrinDY** [comment]
Update: BE won't be needed. The transparent background option will be saved in the metric.options obj

**Comment by katrinDY** [comment]
todo: add plan of action

**Comment by katrinDY** [comment]
for today: add plan of action and start  working on this

**Comment by katrinDY** [comment]
Plan:
- [x] Find a library that's easy to use
- [x] Implement a reusable component
- [x] Apply it to all places where we use color-picker
- [x] Make sure the input is debounced
- [ ] Finishing touches

Add color picker to:
- [x] compose
- [x] admin
- [x] reporter

**Comment by katrinDY** [comment]
for today: start implementing reusable component

**Comment by katrinDY** [comment]
for today: speak to Jože about implementation and start adding the component

**Comment by katrinDY** [comment]
for today: continue working on this and resolve bg default issue

**Comment by katrinDY** [comment]
for today: discuss hex issue with Jože

**Comment by katrinDY** [comment]
for today: address comments on PR

**Comment by katrinDY** [comment]
for today: add finishing touches and submit for review

**Comment by katrinDY** [comment]
for today: address comments

**Comment by katrinDY** [comment]
for today: take a look into calendar color issue

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

Added CL:
```
"added": [
    {
      "what": [
        "option for transparent color in the color picker."
      ],
      "why": [
        "to give users more configuration options."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1211"
      ]
    }
