### ISSUE TITLE
Rework Envoy implementation for clarity, ease of maintenance, and stability

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#812]
Parts of the current implementation are a bit clumsy which impacts the performance as well as makes it difficult to maintain.

The next revision relies heavily on the old concept but utilizes codegen more as well as simplifies the entire flow to be easier to understand and maintain.

Rework overview:
  - Each component defines an `envoy` package (next to the `service` package).
  - Each component provides decoding/encoding logic for all formats for their own resources. The dep. management logic should be written in a way where it doesn't need to check if some resource can be handled by some `envoy` package.
  - Rework the `pkg/envoy` package to provide a single `Node` struct which wraps a `resource` with some metadata which is then used in the dep. graph (inside the `pkg/envoy`) which can then be offloaded to the registered encoders/decoders.
    - The package would provide some service (global version also) into which you register decoders (to get the `Nodes` from) and encoders (to consume `Nodes`).
    - The node might split a single Resource and a datasource into a separate concept for more clarity.

Notable changes:
  - New version utilizes more codegen since most of the logic is repetitive and can be deducted from the definition files.
  - New version simplifies dep. resolution and encoding process. Instead of offloading most of the work to the dep. graph (detecting cycles, calling functions with correct states and correct nodes, ...), the dep graph mostly provides a tool for those functions to optimally figure out what is related to what. This simplifies the state management (since most of it won't be needed) as well as encoding into files (since we can drop those wrapper structs).

Important points:
  - Special attention when getting to RBAC rules and resource translations (how will we handle those?)
  - Special attention when getting to Records - we should define a new aux resource to handle larger datasets (utilize file streams and disk caching).

**Comment by tjerman** [comment]
Good progress; will take a bit of a pause from the implementation.

Todo:

* Cleanup codegen logic/templates
* RBAC rules and resource translation
* Utilise SVC helper functions
* Port Record importing logic from prev version
* Expand test suite

Currently a bit stuck on how exactly we should handle RBAC rules (and resource translations -- same concept).
The two options:

* **A**: when fetching things from the DB, hold a record of the resources and then filter RBAC rules based on that one. This might be a bit trickier and it would need some extra logic to prevent duplicates
* **B**: throw all of the RBAC rules into a dep. graph, link up, prune all of the rules with missing deps (and some other logic). This one would probably be simpler and would do the trick (at least for now); my only concern is the number of nodes this would introduce.

**Comment by skamensky** [comment]
@tjerman ,

Does your solution use bulk DB insertion by any chance? I think that may also grant a large performance leap.

**Comment by tjerman** [comment]
It'll rely more on what we have in place as far as the store and DAL go so not directly. Improvements to better utilise insertion batching and such will be done on the _lower level_ (not with this set of commits)

**Comment by tjerman** [comment]
I've split this further

* https://github.com/cortezaproject/corteza/issues/867
* https://github.com/cortezaproject/corteza/issues/868
* https://github.com/cortezaproject/corteza/issues/869
* https://github.com/cortezaproject/corteza/issues/870
* https://github.com/cortezaproject/corteza/issues/871
* https://github.com/cortezaproject/corteza/issues/872
* https://github.com/cortezaproject/corteza/issues/873
* https://github.com/cortezaproject/corteza/issues/874

**Comment by tjerman** [comment]
Due to my unexpected absence, the plan changed a bit since a bunch of other work piled up.
The entire implementation will be primarily applied to 2023.3.x branch and partially backported to the 2022.9.x (the important parts).
The two versions will exist together (until the entire thing is switched up).

Tasks to merge the core logic:

* https://github.com/cortezaproject/corteza/issues/892

Initial rewrites:

* https://github.com/cortezaproject/corteza/issues/941
* https://github.com/cortezaproject/corteza/issues/943

Initial backports:

* https://github.com/cortezaproject/corteza/issues/942
* https://github.com/cortezaproject/corteza/issues/946

**Comment by katrinDY** [comment]
For today: finish the issues in the initial rewrites and fixing the broken tests

**Comment by tjerman** [comment]
Will backport & close this issue after the test fest passes

**Comment by tjerman** [comment]
We won't be backporting this.
