### ISSUE TITLE
Select field translations not show unless module is saved

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#815]
## Branch version
23.3

## Steps to reproduce
1. Create a select field
2. Add an option
3. Save the change from the configurator modal
4. Reopen the field
5. Click on the translation button
6. See that no translations are shown

## Video with reproduction steps

![Image](https://user-images.githubusercontent.com/85161724/214568048-4e0a716f-2c00-42d7-ac44-e7be113d8425.gif)

## Cause of the issue
The translations don't have a key so they're not saved on the BE

## Expected behaviour
Show the translations only if there are such (they're saved)

## Notes
I also noticed that the translations modal doesn't have a title

**Comment by Bojan-Svirkov** [comment]
Tested this and can confirm that this now works as expected. The only thing now left @kelanik8 is the CL entry.

**Comment by kelanik8** [comment]
Changelog:

**What changed**
- fixed the translation button on select field dropdown options entry to be disabled until when the module is saved with the new select dropdown option

**Why did it change**
 - Select/Dropwdown dropdown options can only be translated if the data is already saved
 
**How did it change**
 -  I updated the Select/dropdown configurator with a default initial state of the field options that are already saved, only options in the field options can be translated 

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
