### ISSUE TITLE
Can't use magnifying glass in page builder

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#816]
## Steps to reproduce
1. Add a PB that has the magnification option
2. Enable it
3. Go to page builder mode
4. Click on the magnification icon
5. Nothing happens

## Expected behaviour
Make blocks magnifiable in the builder

**Comment by katrinDY** [comment]
For today: change cursor and bg on hover, submit  PR in an hour

**Comment by katrinDY** [comment]
The previous goal of the task was to change the cursor but after speaking to Jože the new goal of the task is to make the mag. glass usable in the page builder.

What's to be done today is to make a plan on how the task will be handled and start implementing the code.

**Comment by katrinDY** [comment]
For today: sync with Emmy reg. block tabs implementation of Ids and start implementing needed changes. Should have a PR ready by the end of the day

**Comment by yonkov** [comment]
Update: I created a pr but Joze asked me to change the approach and make the magnify icon fully functional inside the builder instead of it redirecting to the public url.

**Comment by yonkov** [comment]
Update from 9:30 EET: I added the zoom functionality in the builder but now it interferes with the zooming on the public pages. I am working on a fix.

**Comment by katrinDY** [comment]
For today: timebox to 1h and if can't fix the issue sync with Emmy for help

**Comment by yonkov** [comment]
Update from 13:00 EET - Sent for qa.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. Moving the card to Done.
