### ISSUE TITLE
Buttons for zooming in and out map appear on top of the page block edit button

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#818]
## Branch version
23.3

## Issue

![Image](https://user-images.githubusercontent.com/85161724/214583099-61bd4a3c-e088-469d-992a-a6acf065f9c3.png)

## Expected behaviour
We should be able to see and use the edit button

**Comment by Bojan-Svirkov** [comment]
Retested this and now this looks good. The only thing left is the CL entry.

**Comment by kelanik8** [comment]
Changelog:

**What changed**
- Fix the overlapping between zoom button on the geometry page block with the page block edit group buttons

**Why did it change**
- To ensure the page block edit group button is clickable on geometry page blocks


**How did it change**
- Updated the styling option(z-index) for the page block edit to overlap the zoom edit buttons

**Comment by Bojan-Svirkov** [comment]
Added CL
