### ISSUE TITLE
Hide unnecessary configurations for pie and doughnut charts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#820]
## Description
These configs shouldn't be shown because they don't apply to pie and doughnut charts

## Configs
- [x] default value in dimensions
- [x] rotate label in dimensions
- [x] label in metrics

**Comment by katrinDY** [comment]
For today: take a look at the task and make a plan

**Comment by katrinDY** [comment]
For today: if you don;t have any other tasks, start working on this

**Comment by katrinDY** [comment]
For today: add plan to ticket and if time (depending on how TestFest goes) start working on it

**Comment by yonkov** [comment]
The fields that need to be edited are located at GenericChart.vue and ReportEdit.vue. I will look at it on Monday.

**Comment by yonkov** [comment]
Daily update: The task was executed correctly but the requirements shifted after a call with Joze:
1. Default value should be visible 
2. Rotate label functionality should be added for above chart types and be made visible.

**Comment by katrinDY** [comment]
For today: add written changes in comment above and re-submit code for review

**Comment by Bojan-Svirkov** [comment]
All good.

**Comment by Bojan-Svirkov** [comment]
Added CL
