### ISSUE TITLE
Post processing function not working for gauge chart

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#822]
## Steps to reproduce
1. Create a gauge chart or use an existing
2. Add `n/2` to the 'post processing function' field (n is the current value in the chart, not the chart legend!)
3. See that the values in the chart don't change

## Expected behaviour
The added expression should affect the value in the chart. If you go to a generic chart and add the same expression, the values will change.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. Also CL entry was added so moving the card to **Done**.
