### ISSUE TITLE
Discovery shows unexpected result with filters

### ISSUE THREAD

**Issue by vicpatel** [cortezaproject/corteza#824]
### Current Behavior

Trying to filter result by specific namesapce,
After selecting the name of the namespace from the left menu,
It is returning the result based on string search from filter's lable string.

### Expected Behavior

Response should be according to the selected filter from left side, It should just return result for selected namesapce.

**Comment by vicpatel** [comment]
Fixed:

What:
Fix discovery search result with namespace, module filters

How:
Fix aggregation filter(left side menu filter) matches, by adding minimum string match criteria(100%) to match exact string match for search results.

2023.3 commit# https://github.com/cortezaproject/corteza/commit/e2c374c106f13455811fce83bde2ed654e8e964a

**Comment by Bojan-Svirkov** [comment]
Added CL
