### ISSUE TITLE
Sidebar misbehaving in reporter

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#828]
## Version
23.3

## Issues
- [x] sidebar doesn't open on hover in reporter builder and view report
- [x] logo in reporter.list doesn't show unless you hover over it

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now looks good. The only thing now left is the CL entry @katrinDY

**Comment by katrinDY** [comment]
CL

Fixed:

What: Sidebar in the reporter webapp wasn’t opening on hover
How: Removed the disabledRoutes() watcher

Refs:
- 23.3 e3b1ec8022324003fa22b7be6803fdf89021c929

**Comment by Bojan-Svirkov** [comment]
Added CL.
