### ISSUE TITLE
When I try to set authentication role permissions, they et reset upon server restart

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2022.9.6

### Current Behavior

When modifying the "authenticated" role, your changes  only last until the next server restart, and then they get overwritten

### Expected Behavior

Changes should persist

### Steps To Reproduce

1. Go to system admin 
2. Go to corredor permissions
3. Change a value in the authenticated role permissions, save
4. Verify changes persist
5. Restart server
6. Go  back to corredor permissions
7. Verify changes we rolled back

**Comment by tjerman** [comment]
What do you mean by Corredor permissions -- automation scripts don't have any RBAC behind them.
Does this happen if you'd change any permission or just for the ones in question? What database are you running?

I tested this with workflows and it worked as expected:
![image](https://user-images.githubusercontent.com/12545711/216960524-91df8c9e-d9ac-48b0-ba6b-53a3c4af1532.png)

Could you send over some screenshots please?

**Comment by skamensky** [comment]
Sorry, I meant compose permissions.

> Does this happen if you'd change any permission or just for the ones in question? What database are you running?
This happens if I change any permissions. I'm running postgres.

You are changing system permissions. I'm changing compose permissions. Here's a video showcasing the issue.

[Admin Area.webm](https://user-images.githubusercontent.com/19151369/216988093-2d67fd80-50bd-4986-9d50-bbafa08638ae.webm)

Could this be the issue?
https://github.com/cortezaproject/corteza/blob/e3b1ec8022324003fa22b7be6803fdf89021c929/server/app/boot_levels.go#L255-L268

**Comment by tjerman** [comment]
It would seem the issue is caused by the provision step and it not being strict enough to omit already provisioned rules.
For now, you can set [`PROVISION_ALWAYS=false`](https://docs.cortezaproject.org/corteza-docs/2022.9/devops-guide/references/configuration/server.html#_provision_always) in your `.env` file to skip provisioning which should overcome this

**Comment by tjerman** [comment]
This should get resolved with `2022.9.7`

@Bojan-Svirkov I've added a check in the provision logic to skip base roles & RBAC rules if they were already provisioned. Monorepo commit `88204f772`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now resolved. Also CL entry has been added so moving the card to **Done**.

**Comment by skamensky** [comment]
Thank you guys, I appreciate it.
