### ISSUE TITLE
When I try to put record organizer on a record page I get an error

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2022.9.6

### Current Behavior

Receive error and forever loading

### Expected Behavior

Properly filter records

### Steps To Reproduce

1. Add record organizer to record page
2. User ${recordID} in prefilter conditions 

### Anything else?

![image](https://user-images.githubusercontent.com/19151369/216845641-bcb1337c-d5a5-46dd-bf8f-057fa7f012ec.png)

```javascript
vue.esm.js:1906 Error: Can not use ${record...} variable in non-record pages
    at a.expandFilter (RecordOrganizerBase.vue:338:17)
    at a.handler (RecordOrganizerBase.vue:237:49)
    at ot (vue.esm.js:1872:26)
    at e.$watch (vue.esm.js:4974:7)
    at br (vue.esm.js:4930:13)
    at yr (vue.esm.js:4912:7)
    at cr (vue.esm.js:4670:5)
    at e._init (vue.esm.js:5029:5)
    at new a (vue.esm.js:5177:12)
    at ln (vue.esm.js:3313:10)
```

![image](https://user-images.githubusercontent.com/19151369/216845750-ac1c207c-2eb7-448b-adcb-4077f628aef2.png)

**Comment by Fajfa** [comment]
Fixed
- What: Record organizer did not properly load when used on record pages while using ${recordID} in prefilter. If used on a record page, the values also now get properly prefilled.
- How: By properly fetching once the record object becomes available and providing the reference record so values can be prefilled.

Changed
- What: The record organizer now gets filtered based on the key field and key value.
- Why: To avoid putting the knowledge on how to set up the prefilter and make the record organizer work on the user.
- How: By generating a filter based on the key field and value and "AND-ing" it with the prefilter

**Comment by Fajfa** [comment]
@skamensky 
Was fixed and will be released with 2022.9.7

Please note that the error itself is not the issue here, it is intended so certain blocks don't need to wait for the record object to get loaded before displaying them. Other blocks are dependant on the record object so therefore they need to be fetched once the record object becomes available

**Comment by skamensky** [comment]
Thanks! Looking forward to the release :-D

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now resolved. CL entry has been also added. Moving the card to **Done**.
