### ISSUE TITLE
Relative value shown incorrectly for bar and line charts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#842]
## Version
_22.9.7_

## Steps to reproduce
1. Create a generic chart
2. Set module, dimension and metrics
3. View chart as pie
4. Select `Show relative value` checkbox
5. See the relative value displayed in the chart
6. Switch chart from pie to doughnut
7. See that the relative value is `{d%}` and not the actual value

![Image](https://user-images.githubusercontent.com/85161724/217080542-072090f4-a50e-4fc2-a8f3-1f753bdecab0.gif)

## Expected behaviour
Either show the actual value or hide it for bar and line charts

**Comment by Fajfa** [comment]
Since bar charts are not for showing relative data, we should prevent the relative tooltip on bar/line charts

**Comment by tjerman** [comment]
Spend max 3h to figure out how to fix this; have an estimation by tomorrow daily

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. Also the CL entry was added so moving the card to **Done**.
