### ISSUE TITLE
Integration gateway route not showing correct filters

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#848]
## Version
_22.9.6_

## Issue
![Image](https://user-images.githubusercontent.com/85161724/217257339-b1978c97-0205-49b2-a06e-3a7f012b55bc.gif)

## Expected behaviour
Show the correct filters for the selected method

**Comment by Fajfa** [comment]
Fixed:
- What: Integration gateway filter table was not properly refreshed in rare cases
- How: By adding a spinner to the integration gateway filter table, so that it is properly refreshed when fetched

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now resolved. Also CL entry has been added so moving the card to Done.
