### ISSUE TITLE
Wrong system permissions showed for selected roles after restarting server

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#850]
## Description
On system permission pages, if you've selected one or more roles, then dropped your DB and re-provisioned it (or switched version branches with a different DB), the selected role will still show selected (because it's in local storage) but it will show deny for all. This can mislead and potentially cause issues because you can still edit them

## How to reproduce
Go into your local storage and change an ID of a role to something that don't exist;
for example [{"mode":"edit","ID":"edit-323033808834217071","roleID":"323033808834217071","name":["Authenticated"]}]

![Image](https://user-images.githubusercontent.com/85161724/217577951-c0860f99-d6f5-48ae-869e-65db67c17ecc.png)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. The only thing now left is the CL entry.

**Comment by kelanik8** [comment]
Changelog

**What changed**
  - Fixed the issue of role with invalid ID stored in the localstorage from displaying of the permission pages
  
  
**Why did it change**
  - To prevent invalid roles from Displaying on the permissions pages
  
**How did it change**
  - Filtered out the invalid role IDs from the local storage 

@Bojan-Svirkov

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
