### ISSUE TITLE
Cannot use links in reminders

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#852]
## Description
There is no way to use the link of the reminder - when you create a reminder there’s an option to link it to a record, but that’s not exposed later on

## Ref to forum
https://forum.cortezaproject.org/t/how-can-i-modify-the-reminder-time-dropdown/1253/3?u=katrinyordanova

**Comment by skamensky** [comment]
Author of the form post here. I just want to add here that when the reminder pops up, there _is_ a link to the record originally related. However when you navigate to all reminders to view the list, there is no link there.

**Comment by yonkov** [comment]
The url can be constructed from the api's response - no need for backend work here 

![Image](https://user-images.githubusercontent.com/26258032/219412347-e85c0611-8afc-4514-9ebf-da13a70df136.png)

**Comment by katrinDY** [comment]
For today: address comments and re-submit for code review

**Comment by katrinDY** [comment]
For today: address comments and merge with other task for un-dismissing reminder

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL entry has been also added.
