### ISSUE TITLE
Can not undo the action of marking a reminder as complete

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#853]
## Ref to forum
https://forum.cortezaproject.org/t/how-can-i-modify-the-reminder-time-dropdown/1253/3

## Expected behavior
You should be able to undo the action of marking a reminder as complete

**Comment by katrinDY** [comment]
BE endpoint will be needed that will mark a reminder as undismissed. Then FE will be added

Note: I cannot use the updateReminder endpoint because it won't update the correct properties which are `dismissed_at` and `dismissed_by`

**Comment by katrinDY** [comment]
To be done today: discuss the BE with Vivek and the UI with Jože and update the ticket with the plan. Add checkboxes.

**Comment by yonkov** [comment]
We discussed with Joze and Vivek and reached the following conclusions:
1. We will add an option to undismiss a reminder by making the dismissed checkbox toggleable
2. Vivek will add an endpoint and ping me afterwards, no additional props will be added to db

**Comment by katrinDY** [comment]
For today: add necessary FE changes and submit for code review

**Comment by yonkov** [comment]
> For today: add necessary FE changes and submit for code review

Update: task submitted for code review.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL entry has been also added.
