### ISSUE TITLE
When you have a multi value date & time field, and you try to filter, you are getting error

### ISSUE THREAD

**Issue by vicpatel** [cortezaproject/corteza#857]
Error: `Could not load record list: unsupported IN operator on a single value field`. (same happens when you are also having just a date and just a time field)

**Comment by vicpatel** [comment]
Fixed:

What:
- Fixed record field issue with `contain/not contain` filter for multi value data time field.

How:
- By adding explicit type casting for date time values to cast into jsonb format while parsing the record filter query.

**Comment by katrinDY** [comment]
Tested and can confirm the error isn't present anymore
