### ISSUE TITLE
Record list filter not working when field name has hyphen in the field name

### ISSUE THREAD

**Issue by kelanik8** [cortezaproject/corteza#858]
Steps to recreate
1. Create a record field with a name that includes hyphen `-` e.g (`date-only`)
2. Try to filter with the created record field

![Image](https://user-images.githubusercontent.com/23015247/217806858-15d3bda5-ff3b-4bc7-8cfc-99853868d3f8.png)
![image](https://user-images.githubusercontent.com/23015247/217807110-04a7ed19-c81d-4fc5-bb1b-e5f56b2db1ff.png)
![Image](https://user-images.githubusercontent.com/23015247/217806766-47b9549f-910f-42ed-a1d9-c2a0d49e80d6.png)

**Comment by vicpatel** [comment]
Fixed:

What:
- Record list filter for field name with hyphen

How:
- While processing the record filters, added '-' (hyphen) to the allowed list.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. Also CL entry has been added.
