### ISSUE TITLE
Allow ability to toggle block border

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#859]
![Image](https://user-images.githubusercontent.com/15791641/217809513-b7ccbce1-22ad-4921-b1cf-442e2bc7caf1.png)

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/15791641/217810072-28517f9c-be0f-4816-a8ab-bb9d1e550639.png">

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. I also added a CL entry, so moving the card straight to **Done**.
