### ISSUE TITLE
Date selector flickering on specific page zoom

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#861]
This only happens on smaller screens and if the browser zoom is set to 90%.

- Create couple fields with dates selectors and once you reach the point where the date selector is almost at the end below on the page the page starts flickering and if you scroll up or down the flickering resolves. 

Here is a video for clearer view.

https://user-images.githubusercontent.com/53232926/217826257-6736216a-338a-4dad-923c-7b77000c07be.webm

Tested on 2022.9.x

**Comment by katrinDY** [comment]
@Bojan-Svirkov, can you, please, define smaller screens? Can't seem to reproduce this.

**Comment by Bojan-Svirkov** [comment]
@katrinDY my configuration is: 16" 2560x1600 resolution and the browser is set to 90% zoom. (It looks like I can't reproduce the issue on bigger screen too, but on this laptop size, the issue is present)

**Comment by katrinDY** [comment]
I am still not able to reproduce this. @Bojan-Svirkov, can we sync tomorrow/the day after?

**Comment by katrinDY** [comment]
Synced with Bojan and still couldn't reproduce the issue. I think this is an edge case for windows because the scrollbars are a lot bigger than those on mac, hence the flickering.

**Comment by katrinDY** [comment]
Note to self: sync with Jože because I"m not able to reproduce this

**Comment by katrinDY** [comment]
This is an edge case that's to do with dropdown target calculation. Research needs to be done on this. Not a hight priority for now.

**Comment by petergrlica** [comment]
Irrelevant
