### ISSUE TITLE
'STD' function not working correctly in charts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#864]
## Versions
_22.9.7-rc2 and 23.3_

## Notes
The issue is present in all types of charts

## Issue
![Image](https://user-images.githubusercontent.com/85161724/218080500-c2797974-233b-46fb-9017-a46aa6f91324.gif)

**Comment by katrinDY** [comment]
Note to self: move the ticket to 22.9.9 milestone; it's not a high priority
This worked for MySQL. Still broken because it's not registered as a handler
Todo: either remove this or make it work only for MySQL as it was before.

**Comment by tjerman** [comment]
Resolved.

## Fixed

### What

missing support for the STD aggregation function on MySQL databases.
The STD function was present in past versions.

### How

by adding an expression handler for the function and only allowing it for MySQL databases.

### Refs

2022.9.x monorepo `3ec7d19fa`

**Comment by Bojan-Svirkov** [comment]
Everything works as expected and CL was added. Moving the card to Done.
