### ISSUE TITLE
Make record search on MySQL databases case insensitive

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#866]
When using MySQL and JSON encoded record values, the search function is case sensitive (all credits here go to Brian from KBR).

The issue is caused by the way MySQL handles JSON encoded strings

> "Strings produced by converting JSON values have a character set of utf8mb4 and a collation of utf8mb4_bin", "Because utf8mb4_bin is a binary collation, comparison of JSON values is case-sensitive."

Below is an example that illustrates the issue:

```sql
select

-- raw data

[a.id](http://a.id/), a.values->>'$.Number[0]' case_number


-- charset/collation coming out of json functions

, charset(a.values->'$.Number[0]') json_charset

, collation(a.values->'$.Number[0]') json_collation


-- can we match using standard like? no.

, case when a.values->>'$.Number[0]' like lower('%ticket%') then 'Yes' else 'No' end normal_match


-- can we match using collate, cast, lower, or json_search? yes.

, case when a.values->>'$.Number[0]' like lower('%ticket%') collate utf8mb4_0900_ai_ci then 'Yes' else 'No' end collate_match

, case when cast(a.values->>'$.Number[0]' as char) like lower('%ticket%') then 'Yes' else 'No' end cast_match

, case when lower(a.values->>'$.Number[0]') like lower('%ticket%') then 'Yes' else 'No' end lower_match

, case when json_search(a.values->'$.Number', 'one', lower('%ticket%') collate utf8mb4_0900_ai_ci) is not null then 'Yes' else 'No' end json_search_match


from compose_record a

where a.values->'$.Number[0]' is not null;
```

Below is the output of the example:

![Image](https://user-images.githubusercontent.com/12545711/218394255-0c311abc-d2a9-4985-bbed-f26910d5173b.png)

## Todo

- [x] Pick a solution (consider benchmarking/researching which one would run faster)
- [x] Implement the fix

**Comment by katrinDY** [comment]
for today: sync with Tomaž and start working on task

**Comment by katrinDY** [comment]
for today: continue researching methods and work on benchmarking

**Comment by katrinDY** [comment]
for today: finish with benchmarking and implement best method
