### ISSUE TITLE
Enable geo location capture from Compose Webapp

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#875]
Extend the current geo module field to support users capturing their current location, either on demand or as a default value.
This feature is primarily designed to be used with mobile devices as the location is most accurate there.

## What to use

Use the [geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) provided by the browser.
Check if and how exceptions in regards to the API not supported, GPS not available, user denying location permissions, ...

You are free to use some NPM module but the standard API should be enough.

### Geometry field default current location

In the geometry module field configuration, add a new option for the "default value" checkbox which will take the user's current location and use it to prefill the input.

![Image](https://user-images.githubusercontent.com/12545711/217753658-48c31dd6-d2f3-4260-b3fd-3633a5489c63.png)

**Important concern**: When should the prefill value be captured? When opening the record page, before closing it? The concern here is if I'd have to capture locations on my mobile and I'd open the record page before hand, the location I'd want is the one when saving the record, not when opening it. If we want to capture it at the end, what if I was in a hurry and was planning on filling the rest out a bit later?

A potential soliton is to capture the location at the start then before saving, if the location changed from the previous one (we shouldn't use strict equality but rather a delta of x -- the user can walk around a bit but the location is still about the same), ask the user if they want to update the location. Additionally, you can capture some locations every n seconds and provide those as options to chose from.

**Note**: You are free to do some of your own research and propose a different UX for the current location prefill.

### Geometry field insert user location

When editing a record with a geometry field, provide a "use my current location" button which would use the geolocation API to get and update the field's value.

![Image](https://user-images.githubusercontent.com/12545711/217755335-3134d247-baa5-4d3a-905e-26b0500eaa6e.png)

## Steps

- [x] Research and determine how error/exception handling should be handled
- [x] Research how the prefill value option should behave
- [x] Implement the prefill value
- [x] Implement the button to insert the current location

**Comment by katrinDY** [comment]
For today: complete the second and third checkboxes

**Comment by katrinDY** [comment]
For today: sync with Katrin reg. handler blocker and submit task for code review

**Comment by tjerman** [comment]
For today:

- Finish PR review changes,
- Add the newly discussed feature on adding the same functionality on the map,
- Re-submit review.
- @KinyaElGrande write down the newly discussed feature (the map one) in the comment below.

**Comment by KinyaElGrande** [comment]
### Additional features

- `Prefill With Current Location` option which when enabled, both the latitude and longitude input fields are prefilled with the user's current location coordinates obtained.
- Implement current location feature on the map.
- Add an option to show/hide the `current location button`

**Comment by Bojan-Svirkov** [comment]
Everything looks fine so I am moving the ticket to Docs & changelogs.
Just a note: check if the tooltip translation was added tomorrow on the my location button on map

**Comment by Bojan-Svirkov** [comment]
I added the next CL for this ticket:
```
{
      "what": [
        "support for geo location capture.",
        "Ability to set current location while on a map was also added.",
        "An option to prefill the current location and to hide the current location button was added."
      ],
      "why": [
        "to improve the user experience and the location accuracy of the users.",
        "Now instead of manually entering their coordinates, they can just use the `find me` button and the coordinates will be updated."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/955/commits/1628845eccbbcaf8f939efdd1241e7dd147da8b4",
        "https://github.com/cortezaproject/corteza/pull/955/commits/de0f2ef3d103256a0ddff0fe03acd892e4ebce2f",
        "https://github.com/cortezaproject/corteza/pull/955/commits/6a01e35f06b848867a14b35b6e7649c0e358ba06",
        "https://github.com/cortezaproject/corteza/pull/955/commits/2e45899fad36d9495f8ff8625eb4929230e53604"
      ]
    }
