### ISSUE TITLE
Gauge chart metric functions not working as expected

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#879]
## Description of the bug

_When you configure a gauge chart to have a metric function, the functions are not displaying the correct data. For example when you select the `MIN` function it is actually giving you the `MAX` and so on._

## Reproduction steps

1. Have a module for example having fields like, name, surname and age
2. Create couple of record for each field
3. Create a gauge chart and configure it the field to be `Age` and after that try out the functions.
4. For example I have records with ages: 26, 20 and 32
5. and when I select SUM, it is giving 78 which is correct but when you select other functions the result is again always 78
6. So try selecting `Min`, and notice that the result is again 78, but this time needed to be 20, since that is the minimum age
7. try selecting `Max` and see that the result is again 78, but it needed to be 32, since that is the max age, and so on.

## Expected behavior 

_Selecting MIN, MAX, STD, AVG and all the other functions should actually give the correct result. Now the result is not correct and it is misleading._

## Screenshots

![Image](https://user-images.githubusercontent.com/53232926/219691403-a6df47c8-bbb4-48d5-ac95-161fc9a27fa2.png)

## Versions

Branch: 2022.9.x & 2023.3.x

**Comment by katrinDY** [comment]
Note to self: Tomaž wont have time for this one. Discuss with Bojan on who can take this over and how high of a priority it is

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. The only thing now left is the CL entry @Fajfa

**Comment by Fajfa** [comment]
Fixed:

-What
Gauge chart metric functions not showing correct results when report produced multiple dataframes

-How
Since the gauge only shows one value, the dimension field was set to deletedBy which produces at most one dataset.

**Comment by Bojan-Svirkov** [comment]
Added CL entry
