### ISSUE TITLE
Envoy/Finish up, cleanup, tests for records import/export

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#900]

**Comment by tjerman** [comment]
About a third done; will try to sort it out today, if not, it should be tomorrow.
I'm a little stuck so I might need another pair of brains here

**Comment by tjerman** [comment]
Need to checkup cross refs and self refs

**Comment by tjerman** [comment]
Need to checkup references to users

**Comment by katrinDY** [comment]
For today: clean up code and finish by EOD
