### ISSUE TITLE
Uploading .ico file results in not showing the picture on record list

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#904]
## Description of the bug

_When you have a record upload field in your record list page and you try to upload an icon with .ico configuration/extension, the icon is not shown. The other types like, png, svg are working the only problem looks like it is with .ico._

## Reproduction steps

1. Create a `File upload` field and configure it to be like single image and hide file name from the file upload configuration
2. After that try adding a record with uploading an .ico picture
3. After saving the record, notice that the file upload is blank, if you press on the record it is blank again, and if you press on edit record, then you can see the file uploaded with only the name of it

## Expected behavior 

_You should be able to upload an .ico file._

## Screenshots

![Image](https://user-images.githubusercontent.com/53232926/221901489-46123098-71f9-400b-9d3a-3b75eb5c1906.png)

![Image](https://user-images.githubusercontent.com/53232926/221901525-e1be808d-8b83-43c6-b77a-7563e3cbfcb4.png)

![Image](https://user-images.githubusercontent.com/53232926/221901556-e642dec8-cdb1-49df-bc13-e9ad6b52fc15.png)

## Version

Branch: 2022.9.8-rc.1 (Tested on QC)

**Comment by vicpatel** [comment]
Could we fallback to url if there is no previewUrl? 
If yes, then It will fix this problem, as there is not preview url for .ico type as of now.

**Comment by vicpatel** [comment]
Ref branch: `2023.3.x-fix-record-attachment-preview`

**Comment by vicpatel** [comment]
As per discussion, if the preview is empty, we will use the original link.

**Comment by vicpatel** [comment]
Fixes server by returning record attachment previewUrl(fallback to original if preview is empty).

**Comment by vicpatel** [comment]
Server to return original url if preview-url doesn't exist, but it preview is still not being displayed on record view page.

**Comment by vicpatel** [comment]
Fixed:

What:
Fixed preview for icon attachments(.ico)

How:
By adding support to decode ico file and saving preview for it

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Added:

{
      "what": [
        "support for uploading .ico files in record lists and file page blocks."
      ],
      "why": [
        "to give users the ability to upload icons."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1072/commits/ffd49d378375488706a4920e6ea164a8586d905d"
      ]
    }
