### ISSUE TITLE
File upload field throwing error when specific pictures are uploaded

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#905]
## Description of the bug

_When I try to upload some .jpg pictures I am getting errors as on the screenshot below.
The picture that I try to upload is this one:_

![Image](https://user-images.githubusercontent.com/53232926/221906571-5de0a766-b7f8-4c7e-bf3f-dff993c06f27.jpg)

## Reproduction steps

1. Create a file upload field
2. Try to upload the picture above or try uploading couple other pictures, preferably .jpg ones and probably a bit bigger ones
3. Notice that the picture it's not uploaded and you receive an error.

## Expected behavior 
_You should be able to upload the picture without any issues._

## Screenshots

![Image](https://user-images.githubusercontent.com/53232926/221906958-fbb6b791-bc39-4bc6-9e53-658eed6d34c0.png)

## Versions

Branch: 2022.9.8-rc.1

**Comment by katrinDY** [comment]
For today: try to upload image and see if issue will pop up. If not ping Bojan for assistance

**Comment by Bojan-Svirkov** [comment]
This is now resolved. Retested it again and now the upload works as it is supposed to. So moving the card straight to Done.
