### ISSUE TITLE
Error in workflow triggers section in admin if triggers aren't configured correctly

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#910]
## Version

_22.9.8-rc1_

## Steps to reproduce
1. In workflows, create a workflow
2. Add a trigger with resource: `Compose Module` and Event: `onManual`
3. Save the workflow without providing contraints. You should see this:

![Image](https://user-images.githubusercontent.com/85161724/222154003-37c9c36c-4e0f-484b-925e-82954e313b9f.png)

4. Go to admin and in automation -> workflow click on the same workflow
5. This error should appear in the console

![Image](https://user-images.githubusercontent.com/85161724/222154238-a5d7ab2b-24f3-429e-8fde-9f67d3c5a04a.png)

## Expected behaviour
The error shouldn't appear

**Comment by katrinDY** [comment]
One more thing to do: remove the functionality that adds the constraint automatically

**Comment by katrinDY** [comment]
For today: complete this task

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed.

**Comment by katrinDY** [comment]
CL for 22.9

Fixed:

what: Fix error when trying to fetch incorrectly configured workflow triggers in webapp Admin

how: A check was added to determine if a constant has a name. Also, the automatic addition of constraints after an event type was selected was removed 

commit: 7a9802a1c

**Comment by Bojan-Svirkov** [comment]
Added Cl entry.
