### ISSUE TITLE
Error on rec update when using revision feature with MySQL Backend

### ISSUE THREAD

**Issue by nabl13** [cortezaproject/corteza#911]
### Description

When using revisions i cannot update record anymore, its rasing error:

“Could not update record: failed to complete transaction: Error 1366: Incorrect decimal value: ‘updated’ for column ‘operation’ at row 1”

Table has been created just fine:

```
CREATE TABLE 'record_revisions_begleiter' (
 'id' bigint unsigned NOT NULL,
  'ts' datetime NOT NULL,
  'revision' decimal(10,0) NOT NULL,
  'operation' decimal(10,0) NOT NULL,
  'rel_resource' bigint unsigned NOT NULL,
  'rel_user' bigint unsigned NOT NULL,
  'delta' json NOT NULL,
  'comment' text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

```
record is beeing updated in background, but error is thrown because revision row in DB could not be created, it looks like insert order in code could be wrong. it seems to try to insert string "updated" into operation column which is beeing created as decimal

### Version
2022.9.7

### Steps to reproduce
With Docker installation using MySQL as a backend:
 - Activate revisions in module
 - try to update record in this module

### Expected behaviour

revision insert in MySQL table should work

**Comment by katrinDY** [comment]
Take a look at the task together. Mumbi to take a look at the issue and try to resolve it. Tomaž to assist if needed

**Comment by katrinDY** [comment]
For today: investigate and reproduce issue. Make a plan on how to handle this

**Comment by KinyaElGrande** [comment]
The issue is also present on Postgres and it arises during the creation of a dedicated record revision table, which orders the following fields incorrectly: `rel_resource`, `revision`, and `operation`.

**Comment by katrinDY** [comment]
For today: try to fix issue. Note down plan

**Comment by KinyaElGrande** [comment]
### My Plan

- Check on how dedicated record revision tables are created.
- Check the order of the columns in the table and correct the order of `rel_resource`, `revision`, and `operation` columns.
- Change the datatype for `operation` column.
- Re-test to confirm if the solution has worked.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected.


@KinyaElGrande When you can write the CL entry for this issue.

**Comment by KinyaElGrande** [comment]
### CL

```
Fixed:
{
      "what": [
        "record add or update error when dedicated record revisions table is  configured"
      ],
      "how": [
        "Rearranged the order of the rel_resource, revision, and operation columns when custom dedicated record revision table is configured and changed the operation column datatype to text"
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1020"
      ]
    }

**Comment by Bojan-Svirkov** [comment]
Added the CL.
