### ISSUE TITLE
FileBase improvements

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#914]
# I. Center image
![Image](https://user-images.githubusercontent.com/85161724/223094476-d3ba55ab-2714-4577-9bd3-aefc8dd8050d.png)

## Description

Image in top right corner does not fill the block and is anchored to the bottom right (without magnify feature it is anchored to the top right). 

## Notes

Center the image so it fills most of the block without reaching the borders. Don't stretch that image beyond its original intended area

# II. Can preview image in magnified glass modal

## Steps to reproduce
1. In FileBase click on image to open mag. glass modal
2. In the modal click on the image to preview it

## Expected behaviour
The user shouldn't be able to preview the attachment when it's opened in the mag. glass modal

## Suggestions
- Add option to disable download and preview
- If image preview is enabled, then, for visual consistency, it should resemble magnify modals and area

**Comment by kelanik8** [comment]
**Changelog:**

**What changed**
- Added new file configurator option to preview image in modal and option to download
- Images on the file base are centered by default

**Why did it change**
- To center images on the filebase
- New options on the file base for preview in magnified modal and option for download

**How did it change**
- Updated the file configurator with the new options

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL entry has been also added. Moving the card to Done
