### ISSUE TITLE
Unique constaint/Required Field /Validation not working on record bulk update

### ISSUE THREAD

**Issue by kelanik8** [cortezaproject/corteza#916]
1st Issue

- I created a unique constraint on one of the feilds created in the module
- I tried applying the bulk update to the module but the `valueErrors` field in the response seems to return a response for all the other fields in the module which doesn't have the unique constraint applied to it.
- The unique constraint has the `strict` value to be true, which means the form should error out when a unique value is entered, but it doesn't instead it returns the error in form of soft dedup
- The bulk update doesn't submit when a unique constraint and required, even after adding a new value and entering a value in a required field

2nd Issue

- I added a required value on one of the feilds created in the module
- I tried applying the bulk update to the the field hoping it errors out when I do not fill a field that is required but it doesn't it instead return the same response for soft dedup

3rd Issue
- Owned by not working due to BE

**Comment by tjerman** [comment]
Can't reproduce any of them, @kelanik8 is taking me through them a bit later

**Comment by katrinDY** [comment]
Issue was resolved
