### ISSUE TITLE
RecordListConfigurator Layout Change

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#918]
Update the styles and layout of the recordlist configurator's interface according to internally discussed designs.

**Comment by katrinDY** [comment]
For today: substitute the old layout with the new one

**Comment by katrinDY** [comment]
For today: continue layout for each section of the component

**Comment by katrinDY** [comment]
For today: finish with layout changes and discuss with Jože what's more to be done

**Comment by katrinDY** [comment]
For today: timebox 1h to fix last section of checkboxes. Speak to Jože about the next phase of the task

**Comment by EmmyMay** [comment]
For today: Finish up the current phase as discussed with Jože.

**Comment by katrinDY** [comment]
For today: complete the task

**Comment by tjerman** [comment]
Waiting for PR review from @Fajfa . Done if no additional change requests.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. The only part that's left now is the CL entry.
