### ISSUE TITLE
Calendar not shown on page builder when it is combined with tabs block

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#922]
## Description of the bug

_When you have a tabs block and you want to add a separate calendar block, the calendar block is not showing the whole calendar in the page builder view (you can check the screenshot below). When you save the page and then view the page the calendar is looking fine._

## Reproduction steps

1. Add a tabs block
2. Add a new calendar block
3. Notice that on page builder the calendar is not shown as a whole

## Expected behavior 

_The calendar should be shown whole and not cutted out._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/224339164-996a98c5-5596-4ade-b04b-5252211efe41.png)

## Version

Branch: 2023.3.x

**Comment by katrinDY** [comment]
For today: figure out what's causing the issue and try to fix it

**Comment by Bojan-Svirkov** [comment]
I retested this and I can confirm that this is no longer an issue. It got resolved along the way. Closing this ticket.

[4d7a9600-f8c7-4594-b8a7-7d07c471cf98.webm](https://github.com/cortezaproject/corteza/assets/53232926/a6ae2a1f-fb04-4649-ac1f-2ffaa7795128)
