### ISSUE TITLE
Calendar date picker not shown as a whole if you resize your tab or use the screen as split screen

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#923]
## Description of the bug

_When you use your screen as a split screen and you want to have two browsers open on the half of the page, the calendar date picker is cutted out and not shown as a whole._

## Reproduction steps

1. Create a module that will have a date and time field
2. Go to all records and click on add records
3. When you are adding the record, click on the date
4. When the calendar is opened, try to resize your browser or use it as a split screen and notice that the calendar is cutted out.

## Expected behavior 

_The calendar should be shown fully._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/224647689-cdbe75a4-4cfa-4621-8efd-6fe3ee4c8c16.png)

https://user-images.githubusercontent.com/53232926/224648108-c168ab18-31f2-43fe-b0c5-f96f6f6eea20.webm

## Version

20233-qc.cortezaproject.org

My screen is 16" (2560x1600)

**Comment by EmmyMay** [comment]
This issue also exists on Public pages with record lists. It isn't obvious because of the layout difference there.

**Comment by EmmyMay** [comment]
For today: Continue to find a fix for this issue

**Comment by katrinDY** [comment]
For today: investigate and make a plan on how to fix the issue

**Comment by katrinDY** [comment]
For today: continue investigating the cause of the issue and sync with Jože to discuss whether to continue work on this task or prioritize other tasks

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as intended. CL entry is not needed here since this is a fix for 2023.
