### ISSUE TITLE
Navigation block improvements

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#924]
## List of improvements
- [x] I. Context Menu falling off bottom of screen in Navigation block
- [x] II. Add transparent background option
- [x] III. No obvious difference between "Tabs" and "Pills" in Navigation Block
- [x] V. Do not refresh whole namespace on compose page click, do same as you navigate pages with sidebar
- [ ] V. Add option to "Open in Modal" to Navigation Block, where "Compose page" is selected
- [x] VI. Change position of "Navigation items +Add" to beneath the items in Navigation Block

## I. Context Menu falling off bottom of screen in Navigation block

![Image](https://user-images.githubusercontent.com/85161724/224700375-7962ff7d-05c4-4705-b6d7-878a4f003ce4.png)

### Expected behaviour
The list shouldn't fall off

---

###  Expected behaviour
When "Display Block as Card" is disabled, the background appears similarly to a card

![Image](https://user-images.githubusercontent.com/85161724/224702223-b55782fd-15c4-47ef-9ba2-76177e29890a.png)

---

###  Expected behaviour
Tabs should look and behave like the screenshot below (i.e. as they do in the "Change existing block"), except where transparent background is used. Tabs should have the same rounding on the corners as cards. 

![Image](https://user-images.githubusercontent.com/85161724/224706701-d64f8748-45ae-47b3-837a-7a55fa8d25df.png)

---

## V. Add option to "Open in Modal" to Navigation Block, where "Compose page" is selected

![Image](https://user-images.githubusercontent.com/85161724/224704302-27ec6dc9-6e78-418b-a5b1-32893e17a7a2.png)

---

## VI. Change position of "Navigation items +Add" to beneath the items in Navigation Block

![Image](https://user-images.githubusercontent.com/85161724/224704763-e641cfcf-9908-4f68-b4be-da426c9c1e9b.png)

## Notes
If only at the top , then user has to scroll up to add new item if list of Navigation items is long because "Navigation items +Add" scrolls off the screen.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. Since this is an improvement to a new feature no CL is required here. So moving the card straight to Done.
