### ISSUE TITLE
Add option to magnify any block

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#925]
Page block magnification was done just for specific blocks.
This will be expanded to all page blocks.

## Description
Given how maps need to regularly be inspected, this would be most useful

**Comment by katrinDY** [comment]
This option should be added to the rest of the page blocks that don't have it, not only to geometry block

**Comment by tjerman** [comment]
For today:

- write down the plan you made for this
- make a list of all the page blocks that need to be updated (update the original description, if you can't, write as a comment)

**Comment by Bojan-Svirkov** [comment]
The option to magnify any block is now present on every block we have. The only part missing now is the CL entry.

**Comment by Bojan-Svirkov** [comment]
Actually a CL entry is not needed here since this is an improvement of a new feature.  Moving the card to Done.
