### ISSUE TITLE
Preselect fields when exporting a record list

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#926]
![Image](https://user-images.githubusercontent.com/85161724/224712291-6821be0d-b944-4d32-a052-413996c0ba85.png)

## Expected behaviour
Show the fields of the record list table in the selected fields column in the exporter modal

**Comment by Bojan-Svirkov** [comment]
Retested and confirming that now everything works as expected. The only part left now is the CL entry.

**Comment by kelanik8** [comment]
**Changelog:**

**What changed**
- Configured fields on a record list table are preselected on the export modal

**Why did it change**
- To add default selected feilds for the export modal

**How did it change**
- Update the export modal to accept the record list fields as it's default preselected fields

@Bojan-Svirkov
