### ISSUE TITLE
Issue with multiple record list filter of multi value DateTime field

### ISSUE THREAD

**Issue by vicpatel** [cortezaproject/corteza#930]
DateTime field value didn't correctly format in the query for `IN` the operator. (~psql)

**Comment by vicpatel** [comment]
Working on fix for single value dateTime along with multivalue dateTime field.

**Comment by vicpatel** [comment]
Ref branch# `2022.9.x-fix-multi-date-filter`

**Comment by vicpatel** [comment]
The query issue is resolved, but result set is still empty looks like parsing of the result is failing for multi date with ISO format.

**Comment by tjerman** [comment]
The whole logic for filtering multi-value fields might need to be re-visited; specifically, a bit of the generated query is ```JSON_UNQUOTE(JSON_EXTRACT(`compose_record`.`values`, '$.dt[0]'))``` which would again work only over the first element (MySQL dialect output).

What we'll probably need to do is iterate the JSON, cast all values, and then query over that.

**Comment by katrinDY** [comment]
for today: assist with this task
