### ISSUE TITLE
Tweak DAL model handling & validation

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#932]
## Improve existing DAL attribute codec immutability (BE, FE)

After a codec is in place it's mutability is limited since we don't have any migration logic yet.
For example, a values codec can't be replaced by a column codec.

Currently, if there is a mismatch, we error out and that's that.

Server file ref: `store/adapters/rdbms/dal/connection.go`

- [x] On the back-end, allow the attribute codec to change if there are no records under that module (same as with field names and kinds).
- [ ] On the front-end, prevent the user from changing the codec in case the field was already created and there are records for the module.
- [ ] Consider improving the UI/UX to help prevent _mistakes_ like users saving the module before defining the codec.

## Allow models to lose attributes without modifying the database (BE)

Currently, there is a check in place which errors out in case there is an attribute mismatch (removing attributes).
DAL errors out because destructive operations are currently not supported.

Server file ref: `store/adapters/rdbms/dal/connection.go`

- [x] On the back-end, allow users to remove model attributes (module fields) without trying to alter the database

## Janky module issue reporting

Modules and DAL models are two separate bits. Whenever we perform an operation on the module which would pose issues on the model, that issue is noted in the model and then reported to the module.

Here are some issues I've found:

### When deleting a module field, I only see the issue after I refresh the page (BE, FE)

1. The module

![Image](https://user-images.githubusercontent.com/12545711/225039267-fa684e47-d1a7-4055-b573-adcf998bb086.png)

2. Field removed

![Image](https://user-images.githubusercontent.com/12545711/225039323-384c6b6c-2ae9-4b6b-a551-b20bfbc46635.png)

3. Saved

![Image](https://user-images.githubusercontent.com/12545711/225039386-07443673-7fe8-4a63-9e98-8a1d8a81614f.png)

4. Refreshed

![Image](https://user-images.githubusercontent.com/12545711/225039447-a4d01f11-a58c-4121-baed-7f4e35b11db7.png)

**Comment by tjerman** [comment]
This will most likely be sorted in the next sprint

**Comment by tjerman** [comment]
If you change the connection on an existing module you also get an error.



![Image](https://user-images.githubusercontent.com/12545711/232470065-355c9f48-e899-4c90-880a-9599e94be944.png)

I'm guessing we don't remove the old version

**Comment by tjerman** [comment]
Attribute modifications are now permitted; DB reflects changes only if the `DB_ALLOW_DESTRUCTIVE_SCHEMA_CHANGES` .env variable is set.

**Comment by katrinDY** [comment]
for today: start working on the FE

**Comment by katrinDY** [comment]
for today: start working on task

**Comment by tjerman** [comment]
While implementing the bits above it got clear that it'll make more sense to re-do DB altering logic instead of (just) fiddling around with validation.
Currently, DB modifications are too limited to support all of what module definitions can do. Changing up the validation would just be a bandage at this point (it'll also probably have to change when we re-do DDL).

I'll get in touch with a few devs tomorrow (Monday) to brainstorm our two options (mainly implicit and explicit modifications) and I'll make this my priority through this sprint.

**Comment by tjerman** [comment]
I'll get in touch with @petergrlica a bit later and I'll make a final decision & create tasks based on that.
The current options are to either automatically alter the database table (when the module changes), or to prompt a CTA for the user to request (partial) modifications.

**Comment by katrinDY** [comment]
for today: write specs

**Comment by tjerman** [comment]
Replaced with https://github.com/cortezaproject/corteza/issues/1200
