### ISSUE TITLE
Change the configuration of how we display date and time filters for past and future options

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#949]
## Description of the bug

_When you have date and time field and they are configured for future dates and time only or past date and time only, when you open the filter you cannot use the whole calendar since you are also limited with the past and future values on the filter too. This should not be the case with the filter, you should be able to filter by any date/entry you want to have. The same problem is with future and past times only fields. If you have past time only, and you try to put up a future time, you will be able to select a time but you cannot create the record and an error will pop up saying invalid field value._

## Reproduction steps

1. Create a future date only field for example
2. Create a record for it
3. Try using the filter, and let's say you want to filter with the between operator and you want to filter all the dates from 1st of Jan 2023 till the present day, but you cannot do that, since you cannot choose any date that is older than today. So that is the main issue.
4. Also the same with past time only or future time only, configure a past time only field for example
5. try to add a record with time in the future, notice that you will be able to add a time but you cannot save the record, since you will receive an error saying `invalid field value`.

## Expected behavior 

_You should be able to choose any date from the filter calendar regardless of your field configuration whether it is for future or past values only. And in regards to the time, if you select past time only, you should not be even allowed to select future times, as we have it on dates. So we should be consistent everywhere._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/225652093-22402383-f692-4427-914b-96c0ff93a811.png)

![Image](https://user-images.githubusercontent.com/53232926/225652273-547cecfe-e2c0-44e3-946f-e5d80d032bb8.png)

![Image](https://user-images.githubusercontent.com/53232926/225652317-8de78052-6450-42ab-a35e-6ec6533cbe3a.png)

## Version

Branch: 2023.3.x

**Comment by Bojan-Svirkov** [comment]
Everything looks good. @Fajfa can you just add a small CL entry here?

**Comment by Fajfa** [comment]
Fixed:
  - What: Future/past values not being selectable if DateTime field has future/past only values option applied.
  - How: By disabling the future/past only option on record list filter.

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
