### ISSUE TITLE
Geosearch support geometry field

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#954]
Implementation of an address search functionality in openstreet map field to get the GPS co-ordinates.

This is the prime candidate: https://github.com/fega/vue2-leaflet-geosearch
https://smeijer.github.io/leaflet-geosearch/

**Comment by Bojan-Svirkov** [comment]
Geosearch support is added. @kelanik8 Can you just add a CL entry here?

**Comment by kelanik8** [comment]
**Changelog:**

**What changed**
- Added support for geosearch on the geometry module field editor/viewer

**Why did it change**
- To add give users access to address search functionality when on the geometry module field editor/viewer

**How did it change**
- Updated the geometry module field editor/viewer components with open street geosearch plugin

**Comment by Bojan-Svirkov** [comment]
Added CL
