### ISSUE TITLE
Navigation block dropdown overflow

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#962]
## Description of the bug

_If you add a navigational block, and you use the add navigation item button, and you use the dropdown from the compose page, see that the dropdown is way wider than the actual selection._

## Reproduction steps

1. Add a navigational page block
2. Go in navigation tab of your block
3. Press on add navigation item
4. Select the type to be compose page
5. After that under the compose page dropdown make sure you have a record page there
6. Click on the dropdown and notice that the page shown is way wider than the dropdown box

## Expected behavior 

_The dropdown width should be same as the dropdown box._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/226868391-7e7a54d2-9081-4241-9c5b-38eb8e0521dd.png)

## Version

Branch: 2023.3.x-feat-navigation-block-improvements

**Comment by yonkov** [comment]
Daily update: turned out more difficult than I anticipated. After a sync with Joze I made the following plan:
1. Study Tolu's implementation of namespace sidebar dropdown
2. Make a plan how to accomplish a long word not to break down in the dropdown
3. Execute the task

**Comment by yonkov** [comment]
For today I will focus on this ticket and start implementing the above plan.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that now everything looks as it should. No need for CL entry here since this is a .3 fix. (fix for a new feature which is still not out)
