### ISSUE TITLE
Chart Configurator Layout Update

### ISSUE THREAD

**Issue by EmmyMay** [cortezaproject/corteza#965]
Improve the UI for the chart configurator based on internally discussed design details.

- [x] Understand configurator's current layout structure
- [x] Reorder the section structure based on design details
- [x] Check to see if previous layout is consistent with new one in terms of conditional layouts
- [x] Locale update

## Reorder the Section Structure based on Design Details
For this phase, UI elements (mostly) will be grouped together as per the design details.
Work in this part will be broken into:

<details>
<summary>Chart Builder's general info section</summary>

- [x]  Rearrange layout
- [x]  Replace components with their appropriate replacements

</details>
<details>

<summary> ReportEdit's generic content section</summary>

- [x]  Rearrange each section's layout
- [x] Recategorize each section
- [x]  Replace components with their appropriate replacements
- [x] Style each item correctly
- [x] Locale update

</details>

<details>
<summary>Generic Chart</summary>

- [x]  Rearrange each section's layout
- [x] Recategorize each section
- [x]  Replace components with their appropriate replacements
- [x] Style each item correctly
- [x] Locale update

</details>

<details>
<summary>Funnel Chart</summary>

- [x]  Rearrange each section's layout
- [x] Recategorize each section
- [x]  Replace components with their appropriate replacements
- [x] Style each item correctly
- [x] Locale update

</details>

<details>
<summary>Guage Chart</summary>

- [x]  Rearrange each section's layout
- [x] Recategorize each section
- [x]  Replace components with their appropriate replacements
- [x] Style each item correctly
- [x] Locale update

</details>

**Comment by katrinDY** [comment]
For today: focus on the first checkbox and make a plan of action

**Comment by katrinDY** [comment]
For today: make and write down plan. Start working on the first checkbox

**Comment by EmmyMay** [comment]
For today, I began implementing my plan of action. I updated the ticket to reflect that. A potential blocker I might have is @yonkov 's ticket. I don't know how much of an impact the merge would make.

**Comment by katrinDY** [comment]
For today: finish with ReportEdit's generic content section and Generic Chart sections

**Comment by katrinDY** [comment]
For today: start working on Generic Chart section and be halfway done with it

**Comment by katrinDY** [comment]
For today: address comments and resubmit code for review

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything looks as it should. No need for CL here since we will have a separate entry for new charts and their configurations.
