### ISSUE TITLE
When no modules are created NaN is displayed instead of 0

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#971]
## Description of the bug

_When there are no modules in the module list (in the admin panel), you get a NaN instead of 0 (or similar)._

## Reproduction steps

1. Create a new NS
2. Go to the admin panel
3. Go to modules

## Expected behavior 

_NaN should be replaced by a number or some other user-friendly label._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/227497658-9ad6c734-d7ae-4791-b923-eb96631b01d5.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Tomaz (Test Fest)

**Comment by Bojan-Svirkov** [comment]
Fixed
![image](https://user-images.githubusercontent.com/53232926/228508661-0ee9872b-e99f-4c00-a3c3-9b3f198daf64.png)

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
 {
      "what": [
        "when no resources are present, the `NaN items` was replaced with `0 items`."
      ],
      "why": [
        "to have consistency, since on every other place when there are no items, we display them as zero."
      ],
      "how": [
        "by updating the resource list configuration."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/999/commits/b7e2d598687dfd92adc2eb15ec9ed6aee7245e84"
      ]
    }

**Comment by katrinDY** [comment]
Merged
