### ISSUE TITLE
Record deletion from the three dots dropdown not possible on Firefox Mozilla

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#973]
## Description of the bug

_When you try to delete a record by clicking from the record list on the three dots and then pressing on the delete (trash can) button and then pressing on the red button doesn't work. When you press on the red button nothing happens._

## Reproduction steps

1. Open your record list in `Firefox`
2. Add a record
3. Now go on the record list and try to delete the record by clicking on the three dots on the right side of the record
4. Click on delete and press confirm (red button)
5. Notice that nothing happens

## Expected behavior 

_You should be able to delete a record without a problem._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/227504757-81f31a87-0c13-41c1-b524-f0b961050c14.mp4

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Atanas (Test Fest)
Browser: `This only happens of Mozilla Firefox, on other browsers it looks fine`

**Comment by yonkov** [comment]
For this one, the plan is to investigate what causes the issue by comparing how it works in Chrome and Firefox with a debugger. After finding out the culprit, steps will be taken to rewrite the current logic so that it works on Firefox too.

**Comment by katrinDY** [comment]
For today: figure out what's causing the issue and start implementing a solution

**Comment by katrinDY** [comment]
For today: spend 1 more hour to find a better approach for task

**Comment by katrinDY** [comment]
For today: try using nextTick and see if it'll work. Allocate 1h for this.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed and works as expected. Since this is a small specific fix there is no need for it to be included in the CL.
