### ISSUE TITLE
Add option to record and record list blocks to open record fields in modal on click

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#976]
## Note
This should be similar to record list option for opening records in modal

**Comment by Bojan-Svirkov** [comment]
If i open my record in a modal and then I want to open the record selector in a modal too or in a new tab, the functionality doesn't work, the record selector field is just opened in the same tab and the modal is closed. Here is a video of the behavior:



https://user-images.githubusercontent.com/53232926/228837101-00e99ac2-ce46-4b4c-9b53-37d86e906364.webm

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.
@kelanik8 Can you just write the CL entry ?

**Comment by Bojan-Svirkov** [comment]
I added this CL:

```
{
      "what": [
        "support for record and record list blocks to open record selector fields in modal on click."
      ],
      "why": [
        "to make viewing of records a bit more intuitive, since the user will remain on the record list page while opening a record selector pointing to another module."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/997/commits/041ed6be9b7b0fa6a60aba778027dd3fb2bc742a"
      ]
    }
