### ISSUE TITLE
Add option to record block to configure it to display another record based on a related field

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#978]

**Comment by Bojan-Svirkov** [comment]
While testing I noticed couple issues here:

- The fields are not selected on the record page, if you select they get deselected upon saving
- When you configure the reference field and press save, the page loads endlessly
- And when you open a reference record that has record selector that points to another module and record it looks like it is now showing the actual record.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. The only part left now is the CL entry.

**Comment by kelanik8** [comment]
**Changelog**:

**What changed**
  - Added new option to reference a record from a record selector field on the record block

**Why did it change**
  - To give user access to view a referenced record selector on the initial record page
  
**How did it change**
  - https://github.com/cortezaproject/corteza/pull/1065/commits/d5cb4660a7152651697804e2518a06ab047ab796

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
