### ISSUE TITLE
Add "http://" to all URLs input values across Corteza

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#979]
## Notes
- Add "http://" to all URLs input values right before they are used, if they don't include (https:// or http://).
- Do not change original value in input!
- If there is anything before the ://, leave it. (https://, http://, mailto://, irc://). If not, add "http://" 

### Plan:

- [x] Write a function / class method that checks if url starts with https and append it if it doesn't.
- [x] Investigate twitter feed block component and add the logic to it
- [x] investigate iframe page block component and add the logic to it
- [x] investigate navigation page block links and add the logic to it
- [x] investigate admin user inteface settings and add the logic to it

**Comment by yonkov** [comment]
A consideration would be how to detect all url input fields across corteza. This should probably be created as a mixin that is being called upon demand.

**Comment by katrinDY** [comment]
todo: discuss implementation with Jože and add plan of action

**Comment by katrinDY** [comment]
for today: write down discussed with Jože and start working on it

**Comment by yonkov** [comment]
After discussion with Joze: the places that need to be investigated are: 
navigation, tweeter feed, admin user inteface settings and probably topbar links, as well as  iframe)

**Comment by katrinDY** [comment]
for today: add necessary functionality to compose and admin

**Comment by katrinDY** [comment]
for today: complete the last two checkboxes and open PR by EOD

**Comment by katrinDY** [comment]
for  today: complete task

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:
```
Added:
{
      "what": [
        "http prefixes to all URL input values across {PRODUCT_NAME} if it is not provided by the user."
      ],
      "why": [
        "to make it easier for users to define URLs with leaving out the http:// part."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1188"
      ]
    }
