### ISSUE TITLE
Namespace short name cannot end with dashes, underscores and dots

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#980]
## Description of the bug

_We say that the short name of a namespace `Should be at least 2 characters long and start with a letter. Can contain only letters, numbers, dashes, underscores and dots.`
But, it cannot also not end with dashes, underscores and dots._

## Reproduction steps

1.	Go to the manage namespaces page
2.	Click on a namespace to edit it
3.	Change the short URL and add an _, ., or - at the end.

## Expected behavior 

_The message should state it cannot start and end with dashes, underscores and dots._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/227509128-e475e57d-7d6c-49ea-9cdb-4182b347eea6.png)

## Version

Branch: 2023.3.0-dev.5.1 
Reporter: Lenny (Test fest)
Browser: Firefox

**Comment by katrinDY** [comment]
@Bojan-Svirkov: This change was also added in:

Admin
- automation wfs
- system: authClients, connections, queues, sens lvls, roles, templates, users
- ui settings (in links)

Compose
- chart
- module
- page

Reporter
- create/edit report

Wfs
- configurator

Please, check if the text is the same everywhere.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything is good.
Also CL was added:

```
{
      "what": [
        "description of handle/namespace slug."
      ],
      "why": [
        "to have consistency across our system and to be more user friendly."
      ],
      "how": [
        "by updating the description of our slugs."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/993/commits/b94b3a7b07f9d83768b0a8dedc49c6bfaf984970"
      ]
    }
