### ISSUE TITLE
Error:  font file not found, please ensure that the correct AVATAR_INITIALS_FONT_PATH is set

### ISSUE THREAD

**Issue by KinyaElGrande** [cortezaproject/corteza#983]
## Issue

![Image](https://user-images.githubusercontent.com/32476094/227933997-f8755f83-81c5-49f9-9882-aa79587f56bd.png)

## When does the issue occur
- after enabling profile settings in system settings and trying to add/edit a user

## TODO
- [x] fix bug
- [x] improve error message

**Comment by katrinDY** [comment]
For today: finish up with the implementation and submit a PR by half of the day

**Comment by Bojan-Svirkov** [comment]
@petergrlica Test locally with a custom build docker image

**Comment by katrinDY** [comment]
For today: test this in a container and submit to QC if all is fine, else submit for code review

**Comment by katrinDY** [comment]
For today: merge task
