### ISSUE TITLE
Hidden blocks can become invisible forever

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#985]
## Description of the bug

_When you remove or delete a block within the Tabs configuration, it does not return to the layout, but it will stay hidden. If you subsequently remove the entire tab block, those blocks are still on the page, but invisible forever._

## Reproduction steps

1.	Create a couple of page blocks. It does not matter which ones.
2.	Create a Tab block.
3.	Add the page blocks created before to tabs under the “Tabs” tab 🙂
4.	Optionally, hit save and close (to see that they work)
5.	In the Tabs configuration, empty one tab by clicking on the X.
6.	For another tab, select a different page block
7.	For the last tab, hit the delete button
Those block will not return to the page layout. And if you would delete the Tab block, they will not come back either.

## Expected behavior 

_Whenever a page block is not forming part of the Tabs block anymore, it must return to the page layout._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/227889758-cea33815-b485-487f-8905-9251cc201719.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Lenny (Test fest)
Browser: Firefox

**Comment by katrinDY** [comment]
for today: make a plan of action and start implementing it

**Comment by katrinDY** [comment]
for today: continue working on task. Add plan of action

**Comment by EmmyMay** [comment]
Plan of Action

Have it so that when a block is untabbed, we determine its occurrence across the page and decide if it should be rendered on the page

**Comment by KinyaElGrande** [comment]
for today: address review comments.

**Comment by katrinDY** [comment]
for today: continue to address review comments

**Comment by katrinDY** [comment]
for today: sync with Jože to discuss plan of action

**Comment by katrinDY** [comment]
for today: add finishing touch and submit to QC

**Comment by katrinDY** [comment]
Blocks are no longer hidden. Just one more thing to address

![Image](https://github.com/cortezaproject/corteza/assets/85161724/fe170891-e0b0-4260-a9b4-1bfaf68b6cbc)

_Error_

![Image](https://github.com/cortezaproject/corteza/assets/85161724/e2cdc8ba-d104-478d-b45a-541b26c21f73)

**Comment by katrinDY** [comment]
Tested and can confirm everything works as it should
