### ISSUE TITLE
Tabs in the tab block not following the defined order

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#987]
## Description of the bug

_Tabs in the tab block are not shown in the defined order._

## Reproduction steps

1.	Create a number of page block on a page
2.	Create a tab block and add those page blocks
3.	Give them labels that make it easy to see if the order is maintained (for example, 1,2, 9, 10, 11, A, B, C, 100, F)
4.	Hit save and close
Now you’ll see that the order is not maintained

## Expected behavior 

_The order of the tabs when the block is saved must be equal to the order the tabs are configured in._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/227891724-690f0824-6cf9-422c-8319-9712afd202d7.png)

![Image](https://user-images.githubusercontent.com/53232926/227891747-c2cadab6-efed-4528-bfbd-78b2fdaf6b33.png)

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Lenny (Test fest)
Browser: Firefox

**Comment by katrinDY** [comment]
For today: investigate issue and make a plan

**Comment by EmmyMay** [comment]
This appears to have been fixed on the latest copy of 2023.3 base.

**Comment by katrinDY** [comment]
For today: Check with Jože if this is working as it should
