### ISSUE TITLE
Drag and drop expression sorting in workflows

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#995]
The user should be able to sort the added expressions in the expression step in workflows.

When there are multiple variables that need to include additional variable, the quickest way to do it
is to add another expression step before the one, so the workflow eventually starts to grow in size.

The user should be able to sort the existing expressions for a more intuitive and faster workflow implementation.

![Image](https://user-images.githubusercontent.com/4668490/228191528-94476a86-4dce-4729-9e8e-ed6b2705f2d6.png)

**Comment by katrinDY** [comment]
For today: make plan on how to resolve the issue

**Comment by KinyaElGrande** [comment]
### Plan

1. Update the existing FE expressions logic with `b-table-simple` and `vue-draggable` to achieve the drag-and-drop sort functionality.
2. Create a new expressions sort API endpoint on the BE that updates the position of the expressions.

**Comment by katrinDY** [comment]
For today: finish with FE and start implementing BE

**Comment by katrinDY** [comment]
For today: add finishing touches to FE and start working on BE

**Comment by katrinDY** [comment]
For today: figure out how to update list on FE and send it to BE

**Comment by katrinDY** [comment]
For today: fix same table in Function cmp where this is referenced and open a PR int he next 1h

**Comment by katrinDY** [comment]
For today: add finishing touches and re-submit for review in an hour

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. No need for CL since this is a small thing which will go under general improvements entry.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Added:
{
      "what": [
        "drag-and-drop expression sorting in workflows expression step."
      ],
      "why": [
        "to allow the user the ability to sort the existing expressions for a more intuitive and faster workflow implementation."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1081/commits/7d7155d68e72b74575c976e9e46b508364bf8534"
      ]
    }
