### ISSUE TITLE
Can't change the preferred language

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#996]
## Description of the bug

_You cannot change the preferred language. If you select another language and hit save, the chosen language resets to the default one (English) and not the one you just selected and saved._

## Reproduction steps

1. Open your profile settings
2. Under preferred languages, select another language from the dropdown
3. Press save
4. Notice that the chosen language is not saved

## Expected behavior 

_You should be able to change your app language according to your preference._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/228196057-48a9287a-4f52-40f9-9550-aa8b8a2802ef.webm

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Mariya (Test fest)
Browser: Chrome

**Comment by tjerman** [comment]
Looks like this only happens on containerized deployments :/

**Comment by katrinDY** [comment]
For today: try to fix the issue

**Comment by tjerman** [comment]
The issue is caused by the profile image generator's font file issue. It'll be fixed by that and @KinyaElGrande is already working on that/has it sorted.

**Comment by tjerman** [comment]
Moving it back; will re-check when that code is dev released

**Comment by katrinDY** [comment]
For today: check if this is still broken

**Comment by KinyaElGrande** [comment]
The issue is already fixed.
However, an update for fixing error handling for missing font file when generating user avatar initial in auth profile has been added in order to inform the user why their update was not persisted.

Ref: https://github.com/cortezaproject/corteza/pull/1089

**Comment by katrinDY** [comment]
For today: checkout comments on PR and address them

**Comment by katrinDY** [comment]
For today: sync with Tomaž on this and submit to QC

**Comment by Bojan-Svirkov** [comment]
I am still able to reproduce this issue.

**Comment by katrinDY** [comment]
todo: sync with @Bojan-Svirkov or @katrinDY to reproduce this and try to fix this if needed

**Comment by KinyaElGrande** [comment]
I have tested the fix with a different user agent string: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0`, and it appears to be working as expected.

**Comment by katrinDY** [comment]
For today: rebuild qc container and test fix. If it works fine, ping Peter else work on solution

**Comment by KinyaElGrande** [comment]
**update**: Rebuilt the QC container and it appears to be functioning as expected within the container.

**Comment by katrinDY** [comment]
for today: sync with Bojan to test fix
