### ISSUE TITLE
Auto scroll NS list

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#998]
## Description of the bug

_When you want to click on the top namespace from the list of namespaces from the sidebar, the list auto scrolls which makes it difficult for you to select the preferred NS._

## Reproduction steps

1. Open compose
2. Make sure that you have multiple namespaces so that the list will be longer (you can test this on QC)
3. Open the namespaces list from the sidebar
4. Go down and after that try to select the top NS and once you hover over it notice that the list starts scrolling automatically

## Expected behavior 

_When you open the list and you go through the items, the list should not auto scroll._

## Screenshot/Video

https://user-images.githubusercontent.com/53232926/228215544-398da3b2-c845-4938-8c6d-6746c0d8cf46.webm

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Bojan (Test fest)
Browser: Chrome

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. No need for Cl entry since this is a fix for 2023.3

**Comment by katrinDY** [comment]
For today: fix broken test
